### DISCUSSION TITLE
How to attach trait to some non-standard workloads

### DISCUSSION THREAD

**Discussion by Jeffwan** [kubevela/kubevela#1718] [General]
I am recently looking OAM & KubeVela documentation. Seem it's easy to 

1. Register workload type using crd which is managed by other operators. There's a FaaS example [here](https://www.bookstack.cn/read/kubevela-0.1-en/6c98bd51efb286f4.md).
2. Register trait. 

My question is how to make these two work together? if it's possible to attach trait to some crd objects?  

for example, it's hard to create a KEDA trait for a deployment managed by some operators.

**Comment by wonderflow** [comment]
We have provide some [patch capability in trait](https://kubevela.io/docs/platform-engineers/cue/patch-trait).

So if the workload type is non-standard, if the workload itself keeps extension, then we can use the `patch trait` to patch on the workload.

**Reply by Jeffwan** [reply]
Hi @wonderflow 

Thanks for your reply. I think `patch capability` solves problem for one kind of trait but not all the problems. As I understand, there will be two different catagories. 

Category 1: trait template belongs to existing native kubernetes resources.  Label, Annotation, resource traits all fit under this category and `patch` works.

Category 2: trait template is a separate CRD. for example, we will need to create a KEDA scaledobjects. In that case, how can we know the `ScaledObjectRef` if we use a workload backed by custom resource?

**Reply by wonderflow** [reply]
1. The trait ScaledObjectRef will be automatically inject the GVK and name by regsiter the `workloadRefPath`
```
  apiVersion: core.oam.dev/v1alpha2
  kind: TraitDefinition
  metadata:
    name: keda
  spec:
    workloadRefPath: spec.ScaledObjectRef
    definitionRef:
      name: manualscalertraits.core.oam.dev
```

2. The custom workload can register it's child resources to let the trait know, in this case, KubeVela won't automatically inject.

```
apiVersion: core.oam.dev/v1alpha2
kind: WorkloadDefinition
metadata:
   name: mydb.standard.oam.dev
spec:
  definitionRef:
     name: mydb.standard.oam.dev
  childResourceKinds:
     - apiVersion: apps/v1
       kind: Deployment
     - apiVersion: v1
       kind: Service      
```
