### DISCUSSION TITLE
Create a string of an array of string in CUE

### DISCUSSION THREAD

**Discussion by alexis-wefight** [kubevela/kubevela#1854] [Q&A]
Hi,

I want to automate the creation of the following YAML configuration using CUE:

```yaml
objects:  |
      array:
        - |
          objectName: read
          objectType: secret
          objectVersion: ""
        - |
          objectName: read-write
          objectType: secret        
          objectVersion: ""         
        - |
          objectName: test-secret-store
          objectType: secret       
          objectVersion: ""         
```

The `objects` field is a String (I already tried to create it with an array, but it must be a String value). I would like to generate it like the following, but to convert it to YAML string at the end:

```cue
objects: {
  array: [
      for k,v in parameter.secrets {
          objectName: v              
          objectType: "secret"
          objectVersion: ""
      }
   ]
}
```

What would the best way to do it?

Thank you!
