### DISCUSSION TITLE
Pass information from component into trait in the case of Terraform configurations

### DISCUSSION THREAD

**Discussion by neinkeinkaffee** [kubevela/kubevela#2006] [Q&A]
Hello,

I have a `ComponentDefinition` and a `TraitDefinition` that both output a Terraform configuration. The component is supposed to create an S3 bucket, while the trait is supposed to create an IAM policy and role with read access to the bucket. In order for this to work, the trait needs to know about the name of the bucket that the component it's attached to creates. I'm wondering what a good way to access that information from within the trait could be. Right now I'm just passing in the same parameter twice, to the component and the trait (see my `ApplicationDefinition` below), but I suppose there must be a better way?

This is my `ApplicationDefinition`:
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: some-application-with-trait
spec:
  components:
    - name: s3-output-port
      type: output-port
      properties:
        port_name: podcasts
      traits:
        - type: access-policy
          properties:
            port_name: podcasts
```

The `ComponentDefinition` looks like this:
```
apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  name: output-port
  annotations:
    definition.oam.dev/description: Terraform configuration for s3 output port
    type: terraform
spec:
  workload:
    definition:
      apiVersion: terraform.core.oam.dev/v1beta1
      kind: Configuration
  schematic:
    terraform:
      configuration: |
        module "s3_bucket" {
          source = "http://my-nginx/s3.zip"

          port_name = var.port_name
        }

        output "port_bucket_name" {
          value = module.s3_bucket.bucket_name
        }

        variable "port_name" {
              description = "S3 bucket name"
              type = string
        }

```

And the `TraitDefinition` like this:
```
apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  name: access-policy
spec:
  schematic:
    cue:
      template: |
        import "encoding/yaml"

        parameter: {
            port_name: string
        }

        outputs: port_access: {
            apiVersion: "terraform.core.oam.dev/v1beta1"
            kind:       "Configuration"
            spec: {
              yaml.Unmarshal(hclyaml)
              variable:
                output_port: parameter.port_name
            }
        }

        hclyaml: """
          hcl: |
            module "output_port_read_access" {
              source = "http://my-nginx/iam.zip"

              output_port = var.output_port
            }

            variable "output_port" {
              type = string
            }
        """
```
