### DISCUSSION TITLE
Can I implement multiple steps in one workflowstep

### DISCUSSION THREAD

**Discussion by chwetion** [kubevela/kubevela#2511] [Q&A] [answered]
**Except**: I hope to use workflow to achieve the blue-green upgrade process, and write it in a workflowstepdefinition.

in my k8s, I changed the controllermanager implementation to still be able to pause deployment after the upgrade is complete, so blue-green step is: 

* write rollingupdate field and apply new deployment
* when new version rs created, add paused filed in deployment

In other words, I need to execute an apply first(update and add rollingupdate filed), then wait for a condition(new version rs created), and execute apply again(add paused)

I saw op.#Steps on the official website

cue template as follow:

```cuelang
import "vela/op"

parameter: {
  componentName: string
}


load: op.#Load & {}

componentUpgrade: op.#Steps & {
  apply: op.#ApplyComponent & {
    value: load.value[parameter.componentName]
    patch: {
      // +patchStrategy=retainKey
      workload: {
        spec: strategy: rollingUpdate: {
          maxSurge: "100%"
          maxUnavailable: 0
        }
        // +patchStrategy=retainKey
        metadata: annotations: "harmonycloud.cn/upgrade": "canary"
      }
    }
  } @step(1)

  workload: apply.value

  wait: op.#ConditionalWait & {
    continue: workload.status.updatedReplicas == 2 && 
      workload.status.observedGeneration == workload.metadata.generation &&
      workload.metadata.annotations["harmonycloud.cn/upgrade"] == "canary"
  } @step(2)

  apply: op.#ApplyComponent & {
    value: load.value[parameter.componentName]
    patch: {
      workload: {
        spec: {
          // +patchStrategy=retainKey
          strategy: rollingUpdate: {
            maxSurge: "100%"
            maxUnavailable: 0
          }
          // +patchStrategy=retainKey
          paused: true
        }
        // +patchStrategy=retainKey
        metadata: annotations: "harmonycloud.cn/upgrade": "canary"
      }
    }
  } @step(3)
}
```

but when i use it to update application, the first apply did not happen, it is still in the wait state.

```yaml
status:
  workflow:
    appRevision: testapp-v2:a5d4cfa004f6f54a
    contextBackend:
      apiVersion: v1
      kind: ConfigMap
      name: workflow-testapp-context
      uid: b50ba315-8a0c-49c7-9dc1-9f059bcff72a
    mode: StepByStep
    steps:
    - id: tiwkpmxt7i
      name: upgrade
      phase: running
      reason: Wait
      type: hc.blue-green-upgrade
    suspend: false
    terminated: false
```

Is there any way to help me achieve it?

**appendix**

componentdefinition cue template as follow:

```
#Container: {
    name: string
    image: string
    imagePullPolicy: "Always" | "Never" | *"IfNotPresent"
    ports ?: [...{
        port: int
        protocol: *"TCP" | "UDP"
    }]
    exec ?: {
        command ?: [...string]
        args ?: [...string]
    }
}

parameter: {
    initContainers: [...#Container]
    containers: [...#Container]
}

output: {
    apiVersion: "apps/v1"
    kind:       "Deployment"
    metadata: {
        name: context.name
    }
    spec: {
        selector: matchLabels: {
            "app": context.name
        }
        template: {
            metadata: labels: {
                "app": context.name
            }
            spec: {
                if parameter.initContainers != _|_ {
                    initContainers: [
                        for container in parameter.initContainers {
                            name: container.name
                            image: container.image
                            if container.imagePullPolicy != _|_ {
                                imagePullPolicy: container.imagePullPolicy
                            }
                            ports: [
                                if container.ports != _|_ {
                                    for port in container.ports {
                                        containerPort: port.port
                                        protocol: port.protocol
                                    }
                                }
                            ]
                            if container.exec != _|_ {
                                if container.exec.command != _|_ {
                                    command: container.exec.command
                                }
                                if container.exec.args != _|_ {
                                    args: container.exec.args
                                }
                            }
                        }
                    ]
                }
                if parameter.containers != _|_ {
                    containers: [
                        for container in parameter.containers {
                            name: container.name
                            image: container.image
                            if container.imagePullPolicy != _|_ {
                                imagePullPolicy: container.imagePullPolicy
                            }
                            ports: [
                                if container.ports != _|_ {
                                    for port in container.ports {
                                        containerPort: port.port
                                        protocol: port.protocol
                                    }
                                }
                            ]
                            if container.exec != _|_ {
                                if container.exec.command != _|_ {
                                    command: container.exec.command
                                }
                                if container.exec.args != _|_ {
                                    args: container.exec.args
                                }
                            }
                        }
                    ]
                }
            }
        }
    }
}
```

application.yaml as follow:

```yaml
# raw app
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: testapp
spec:
  components:
  - type: hc.deployment
    name: testapp
    properties:
      initContainers:
      - name: busybox
        image: 10.1.11.15:8443/onlineshop/busybox:1.30
        exec:
          command:
          - echo
          args:
          - "hello world"
      containers:
      - name: nginx
        image: 10.1.11.15:8443/library/nginx:latest
        ports:
        - port: 80
          protocol: TCP
      - name: tomcat
        image: 10.1.11.15:8443/onlineshop/tomcat:v8.0-hc
        ports:
        - port: 8080
          protocol: TCP
    traits:
    - type: hc.manualscaler
      properties:
        replicas: 2
    - type: hc.resources
      properties:
        containerName: tomcat
        requests:
          cpu: 100m
          memory: 512Mi
        limits:
          cpu: '1'
          memory: 512Mi
    - type: hc.resources
      properties:
        containerName: nginx
        requests:
          cpu: 200m
          memory: 512Mi
        limits:
          cpu: '2'
          memory: 512Mi
---
# new version app
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: testapp
spec:
  components:
  - type: hc.deployment
    name: testapp
    properties:
      initContainers:
      - name: busybox
        image: 10.1.11.15:8443/onlineshop/busybox:1.30
        exec:
          command:
          - echo
          args:
          - "hello world v2"
      containers:
      - name: nginx
        image: 10.1.11.15:8443/library/nginx:latest
        ports:
        - port: 80
          protocol: TCP
      - name: tomcat
        image: 10.1.11.15:8443/onlineshop/tomcat:v8.0-hc
        ports:
        - port: 8080
          protocol: TCP
    traits:
    - type: hc.manualscaler
      properties:
        replicas: 2
    - type: hc.resources
      properties:
        containerName: tomcat
        requests:
          cpu: 100m
          memory: 512Mi
        limits:
          cpu: '1'
          memory: 512Mi
    - type: hc.resources
      properties:
        containerName: nginx
        requests:
          cpu: 200m
          memory: 512Mi
        limits:
          cpu: '2'
          memory: 512Mi
  workflow:
    steps:
    - name: upgrade
      type: hc.blue-green-upgrade
      properties:
        componentName: testapp
        cwsdebug: true
```
