### DISCUSSION TITLE
Traits not attached into simple Application

### DISCUSSION THREAD

**Discussion by MingZhang-YBPS** [kubevela/kubevela#2842] [Q&A]
Hi guys
I am trying to create a simple Kubevela application below, a simple trait is attached into such application 
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
   name: app-delivering-chart
spec:
   components:
     - name: terraform-controller
       type: helm
       properties:
          repoType: git
          url: https://github.com/oam-dev/terraform-controller
          chart: ./chart
          timeout: 300s
          git:
            branch: master
       traits:
       - properties:
           replicas: 2
         type: scaler
```
However, the traits "replicas" not works, it is still "1",  you can check out the deployment 
![image](https://user-images.githubusercontent.com/74715700/143996690-c4f183f6-54c5-4b68-bec3-ede2e9fb233b.png)

Is there anything wrong?
