### DISCUSSION TITLE
How to reference a rendered component | 如何引用一个渲染过的component

### DISCUSSION THREAD

**Discussion by muma378** [kubevela/kubevela#2897] [Q&A]
I want to make a  demo on dispatching applications with OCM, which defined a `WorkflowStepDefinition`: 

```
apiVersion: core.oam.dev/v1beta1
kind: WorkflowStepDefinition
metadata:
  name: dispatch-traits
  namespace: vela-system
spec:
  schematic:
    cue:
      template: |
        import ("vela/op")

        app: op.#Steps & {
          load: op.#Load & {
            component: parameter.component
          } @step(1)

          apply: op.#Apply & {
            value: {
                apiVersion: "work.open-cluster-management.io/v1"
                kind: "ManifestWork"
                metadata: {
                   namespace: parameter.cluster
                   name: parameter.component + "-traits"
                }
                spec: {
                    workload: manifests: [
                        load.value[parameter.component]
                        ]
                }
            }
          }@step(2)
        }

        parameter: {
          component: string
          cluster: string
        }
```

but when I apply a `Application` as follow:
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: workflow-rollout-demo
  namespace: default
spec:
  components:
    - name: nginx-server
      externalRevision: nginx-server-v1
      type: webservice
      properties:
        image: nginx:1.20.0
        port: 80
      traits:
        - type: rollout
          properties:
            targetRevision: nginx-server-v1
            targetSize: 2
            rolloutBatches:
              - replicas: 1
              - replicas: 1

  workflow:
    steps:
      - name: dispatchRollout
        type: dispatch-traits
        properties:
          component: nginx-server
          cluster: cluster2
```

It reports an error on referecing the component：
```
    mode: StepByStep
    steps:
    - id: txhvgglggi
      message: 'step app: step apply: run step(provider=kube,do=apply): cannot apply
        manifest, name: "nginx-server-traits" apiVersion: "work.open-cluster-management.io/v1"
        kind: "ManifestWork": cannot create object: ManifestWork.work.open-cluster-management.io
        "nginx-server-traits" is invalid: [spec.workload.manifests[0].apiVersion:
        Required value: must not be empty, spec.workload.manifests[0].kind: Required
        value: must not be empty]'
      name: dispatchRollout
      phase: failed
      reason: Execute
      type: dispatch-traits
    suspend: false
    terminated: false
```

I am new to CUE and kube-vela, not sure what happened when loading components. As the [OCM Doc](https://open-cluster-management.io/concepts/manifestwork/) says, I shold supply the manifest of raw resource(deployment, service, etc.) rendered from component. Is there any idea on what field I should use or how to tracking the problem? Any help is appreciated.

BTW, I didn't find any documentation on debuging X-definition locally. If I wrote a X-definition, do I have any methods to render an application which uses the definition with the CLI cue/vela?

**Comment by FogDong** [comment]
Hi, muma!

> As the OCM Doc says, I shold supply the manifest of raw resource(deployment, service, etc.) rendered from component.

The `op.#Load` you use will return a map, in which the key is the component name, and value is the component struct.

But if you want to get the raw manifest of the component rendered, you can use `op.#RenderComponent`.
We can get the manifest in this way:

```cue
// use load first to get the component struct
load: op.#Load & {
    component: parameter.component
}
// render the component to get the manifests
render: op.#RenderComponent & {
    value: load.value[component]
}
```

Now we get `render`. In render, the component manifest is inside of `output`, you can use `render.output` to get it.
The trait manifests is inside of `outputs`, the `outputs` is a map, you can use `render.outputs.[trait-name]` to get it.

> BTW, I didn't find any documentation on debuging X-definition locally.

You can use [dry run](https://kubevela.io/docs/platform-engineers/debug/dry-run) for local debugging, but we can't dry-run workflow step definition locally now, we'll support it in the near future.

**Reply by muma378** [reply]
Hi @FogDong , very thanks for your help! I followed your advice but vela reports a new error:

```  
    mode: StepByStep
    steps:
    - id: txhvgglggi
      message: |-
        step render: _|_ // undefined field "#RenderComponent"
        (bottom kind)
      name: dispatchRollout
      phase: failed
      reason: Execute
      type: dispatch-traits
    suspend: false
    terminated: false
```

I guess it is because the `vela/op` module dose not contain the operator `RenderComponent`. I checked the code and found that  `RenderComponent` is newly added in the release 1.2 and my version is 1.1.7.  ：(

So···is there any ways to make it work in the old version?
