### DISCUSSION TITLE
自定义运维特征不生效求助

### DISCUSSION THREAD

**Discussion by fanzhenyu95** [kubevela/kubevela#3473] [Q&A] [answered]
参考官方文档中的CUE语言-交付完整模块中的内容创建自定义组件，试验比较顺利，然后，想着再学习一自定义运维特征，于是将 StatefulSet 的 volumeClaimTemplates 定义和挂载卷的定义都作为运维特征 patch 到 StatefulSet 的定义中。但是，试验一直不成功，特来向大家求助。

（1）首先，自定义组件，将官方文档-CUE语言-交付完整模块的示例去除了volumeClaimTemplates 和卷挂载的部分，一切正常：
```
"test-stateful": {
        annotations: {}
        attributes: workload: definition: {
                apiVersion: "apps/v1"
                kind:       "StatefulSet"
        }
        description: "StatefulSet component."
        labels: {}
        type: "component"
}

template: {
        output: {
                apiVersion: "apps/v1"
                kind:       "StatefulSet"
                metadata: name: context.name
                spec: {
                        selector: matchLabels: app: context.name
                        minReadySeconds: 10
                        replicas:        parameter.replicas
                        serviceName:     context.name
                        template: {
                                metadata: labels: app: context.name
                                spec: {
                                        containers: [{
                                                name: "nginx"
                                                ports: [{
                                                        name:          "web"
                                                        containerPort: 80
                                                }]
                                                image: parameter.image
                                        }]
                                        terminationGracePeriodSeconds: 10
                                }
                        }
                }
        }
        outputs: web: {
                apiVersion: "v1"
                kind:       "Service"
                metadata: {
                        name: context.name
                        labels: app: context.name
                }
                spec: {
                        clusterIP: "None"
                        ports: [{
                                name: "web"
                                port: 80
                        }]
                        selector: app: context.name
                }
        }
        parameter: {
                image: string
                replicas: int
        }
}
```

（2）自定义运维特征将volumeClaimTemplates 和卷挂载的部分作为运维特征，定义如下：
```
storageclass: {
    type: "trait"
    annotations: {}
    labels: {}
    description: "Add storageclass on K8s pod for your workload which follows the pod spec in path 'spec.template'."
    attributes: {
	    appliesToWorkloads: ["*"]
    }
}
template: {

    volumeClaimTemplatesList: *[
        for v in parameter.volumeClaimTemplates {
            {
                metadata: name: v.name
                spec: {
                    accessModes: ["ReadWriteOnce"]
                    resources: requests: storage: v.requests
                    storageClassName: v.storageClassName
                }
            }
        },
    ] | []

    volumeClaimTemplateVolumeMountsList: *[
        for v in parameter.volumeClaimTemplates {
            {
                name:      v.name
                mountPath: v.mountPath
            }
        },
    ] | []

    patch: {
        spec: {
            template: spec: {
                    containers: [...{
                    // +patchKey=name
                    volumeMounts: volumeClaimTemplateVolumeMountsList
                }]
            }
            // +patchKey=name
            volumeClaimTemplates: volumeClaimTemplatesList
        }
    }

    parameter: {
        volumeClaimTemplates?: [...{
            name:    string
            requests:    string
            storageClassName:    string
            mountPath:    string
        }]
    }
}
```
（3）格式校验成功：
```
$ vela def vet storageclass.cue 
Validation succeed.
```

（4）安装运维特征成功：
```
$ vela def apply storageclass.cue 
TraitDefinition storageclass created in namespace vela-system.
```

（5）定义应用trait-demo.yaml 
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: website
spec:
  components:
    - name: custom-component
      type: test-stateful
      properties:
        image: nginx:latest
        replicas: 1
  traits:
    - type: storageclass
      properties:
        volumeClaimTemplates:
          - name: test
            requests: 10Gi
            storageClassName: cbs
            mountPath: /usr/share/nginx/html
```

（6）试运行验证：
```
vela dry-run -f trait-demo.yaml 
---
# Application(website) -- Component(custom-component) 
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations: {}
  labels:
    app.oam.dev/appRevision: ""
    app.oam.dev/component: custom-component
    app.oam.dev/name: website
    app.oam.dev/namespace: default
    app.oam.dev/resourceType: WORKLOAD
    workload.oam.dev/type: test-stateful
  name: custom-component
  namespace: default
spec:
  minReadySeconds: 10
  replicas: 1
  selector:
    matchLabels:
      app: custom-component
  serviceName: custom-component
  template:
    metadata:
      labels:
        app: custom-component
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        ports:
        - containerPort: 80
          name: web
      terminationGracePeriodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: custom-component
    app.oam.dev/appRevision: ""
    app.oam.dev/component: custom-component
    app.oam.dev/name: website
    app.oam.dev/namespace: default
    app.oam.dev/resourceType: TRAIT
    trait.oam.dev/resource: web
    trait.oam.dev/type: AuxiliaryWorkload
  name: custom-component
  namespace: default
spec:
  clusterIP: None
  ports:
  - name: web
    port: 80
  selector:
    app: custom-component

---
```
从输出的内容来看，运维特征根本没有起作用，这是什么原因呢？命令执行没有报错，core组件也没有error日志，完全没有头绪，请大佬们指导，谢谢！

**Comment by wonderflow** [comment, marked as answer]
The application format is wrong, but vela dry-run CLI didn't report for that, I think this is an issue:

For this discussion, you can fix it by changing the format:

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: website
spec:
  components:
    - name: custom-component
      type: test-stateful
      properties:
        image: nginx:latest
        replicas: 1
      traits:
        - type: storageclass
          properties:
            volumeClaimTemplates:
              - name: test
                requests: 10Gi
                storageClassName: cbs
                mountPath: /usr/share/nginx/html
```
