### DISCUSSION TITLE
trait patch volumes位置不对

### DISCUSSION THREAD

**Discussion by achanceofsunshine** [kubevela/kubevela#3693] [Q&A] [answered]
app.yaml文件内容如下：
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: test-11111
spec:
  components:
    - name: edgex-redis
      type: uis-webservice
      properties:
        replicas: 1
        image: swr:6666/opcs/nginx:v1
        ports:
         - port: 6379
           expose: true
        exposeType: ClusterIP
        env:
          - name: EDGEX_SECURITY_SECRET_STORE
            value: "false"
          - name: edgex_registry
            value: consul://edgex-core-consul:8500
          - name: Registry_Host
            value: edgex-core-consul
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 5
          periodSeconds: 15
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 5
          periodSeconds: 15
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        - name: hostpath-1
          mountPath: /appdata/edgex/db-data
        - mountPath: /block/volumes/mount
          name: block-vol-1
        - mountPath: /share/volumes/mount
          name: share-vol-1
        hostname: edgex-nginx
        tolerations:
        - effect: NoExecute
          key: openpalette.clusternode/reserved
          operator: Exists
        - effect: NoSchedule
          key: GPU
          operator: Equal
          value: "True"
        annotations:
          uis: as
        labels:
          uis: as
      traits:
        - type: uis-com-rule
          properties:
            maxReplicas: 1
            cpu:
              request: "0"
              limit: "1"
            memory:
              request: "50Mi"
              limit: "500Mi"
            accelerators:
              requests:
                nvidia.com/gpu: "1"
              limits:
                nvidia.com/gpu: "1"
            storage:
              - type: block
                name: block-vol-1
                size: 100Gi
                diskIO: extra_high
              - type: share 
                name: share-vol-1
                size: 10Gi
        - type: uis-volume-rule
          properties:
            storage:
              - type: block
                name: block-vol-1
                size: 100Gi
                diskIO: extra_high
              - type: share 
                name: share-vol-1
                size: 10Gi

```
component模板文件如下所示：
```
apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  annotations:
    definition.oam.dev/description: uis-webservice was composed by deployment and service
  name: uis-webservice
spec:
  schematic:
    cue:
      template: |
        output: {
        	apiVersion: "uis.tcf.io/v1alpha1"
        	kind:       "ComponentWork"
        	metadata: {
        		name: context.name
        		labels: "app.oam.dev/name": context.name
        	}
        	spec: workload: manifests: [
        		{
        			apiVersion: "v1"
        			kind:       "Service"
        			metadata: name: context.name
        			spec: {
        				selector: app: context.name
        				if parameter["ports"] != _|_ {
        					ports: [
        						for v in parameter.ports {
        							protocol:   v.protocol
        							port:       v.port
        							targetPort: v.port
        						},
        					]
        				}
        				type: parameter.exposeType
        			}
        		},
        		{
        			apiVersion: "apps/v1"
        			kind:       "Deployment"
        			metadata: {
        				name: context.name
        				labels: {
        					if parameter.labels != _|_ {
        						parameter.labels
        					}
        					"app.oam.dev/component": context.name
        					"app.oam.dev/revision":  context.revision
        				}
        				if parameter.annotations != _|_ {
        					annotations: parameter.annotations
        				}
        			}
        			spec: {
        				replicas: parameter.replicas
        				selector: matchLabels: app: context.name
        				template: {
        					metadata: labels: app: context.name
        					spec: {
        						schedulerName: "uis-scheduler"
        						containers: [
        							{
        								name:  context.name
        								image: parameter.image
        								if parameter["env"] != _|_ {
        									env: parameter.env
        								}
        								if parameter["ports"] != _|_ {
        									ports: [
        										for v in parameter.ports {
        											containerPort: v.port
        										},
        									]
        								}
        								if parameter["readinessProbe"] != _|_ {
        									readinessProbe: parameter.readinessProbe
        								}
        								if parameter["livenessProbe"] != _|_ {
        									livenessProbe: parameter.livenessProbe
        								}
        								if parameter["volumeMounts"] != _|_ {
        									volumeMounts: parameter.volumeMounts
        								}
        								if parameter["cpu"] != _|_ {
        									resources: {
        										limits: cpu:   parameter.cpu
        										requests: cpu: parameter.cpu
        									}
        								}

        								if parameter["memory"] != _|_ {
        									resources: {
        										limits: memory:   parameter.memory
        										requests: memory: parameter.memory
        									}
        								}

        								if parameter["gpu"] != _|_ {
        									resources: {
        										limits:   parameter.gpu
        										requests: parameter.gpu
        									}
        								}
        							},
        						]
        						if parameter["hostname"] != _|_ {
        							hostname: parameter.hostname
        						}
        						if parameter["tolerations"] != _|_ {
        							tolerations: parameter.tolerations
        						}
        					}
        				}
        			}
        		},
        	]
        }
        outputs: {}
        parameter: {
        	labels?: [string]:      string
        	annotations?: [string]: string
        	ports?: [...{
        		port:     int
        		expose:   *false | bool
        		protocol: *"TCP" | "UDP" | "SCTP"
        	}]
        	image:    string
        	replicas: *1 | int
        	env?: [...{
        		name:   string
        		value?: string
        	}]
        	readinessProbe?: #HealthProbe
        	livenessProbe?:  #HealthProbe
        	volumeMounts?: [...{
        		name:      string
        		mountPath: string
        	}]
        	hostname?: string
        	cpu?:      string
        	mem?:      string
        	gpu?: [string]: string
        	exposeType: *"ClusterIP" | "NodePort" | "LoadBalancer" | "ExternalName"
        	tolerations?: [...{
        		effect:   string
        		key:      string
        		operator: string
        		value?:   string
        	}]
        }
        #HealthProbe: {
        	tcpSocket: port: int
        	initialDelaySeconds: int
        	periodSeconds:       int
        	successThreshold:    int
        	failureThreshold:    int
        }
  workload:
    definition:
      apiVersion: uis.tcf.io/v1alpha1
      kind: ComponentWork
```
trait模板文件内容如下所示：
```
apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  annotations:
    definition.oam.dev/description: ""
  name: uis-com-rule
spec:
  appliesToWorkloads:
    - uis-webserver
  podDisruptive: false
  schematic:
    cue:
      template: |
        patch: spec: {
        	cncfRule: {
        		resourcesQos:           "BE"
        		resourcesPriorityClass: "appPriority-1"
        		appArch:                "x86"
        		tenant:                 "shanghai-show"
        		appPkg:                 "container"
        		appType:                "online"
        		appPriority:            "low"
        		appLatency:             "low"
        		maxReplicas:            parameter.maxReplicas
        		if parameter.componentLabels != _|_ {
        			affinity: componentLabel: parameter.componentLabels
        		}
        		if parameter.clusterSelector != _|_ {
        			affinity: clusterSelector: labelSelector: parameter.clusterSelector
        		}
        		if parameter.componentSelector != _|_ {
        			affinity: componentSelector: labelSelector: parameter.componentSelector
        		}
        		cpu:    parameter.cpu
        		memory: parameter.memory
        		if parameter.accelerators != _|_ {
        			if parameter.accelerators.requests != _|_ {
        				accelerators: requests: parameter.accelerators.requests
        			}
        			if parameter.accelerators.limits != _|_ {
        				accelerators: limits: parameter.accelerators.limits
        			}
        		}
        		if parameter.storage != _|_ {
        			storage: parameter.storage
        		}
        	}
        	if parameter.storage != _|_ {
        		workload: {
        			// +patchKey=metadata.name
        			manifests: [
        				for v in parameter.storage {
        					if v.type == "share" {
        						apiVersion: "v1"
        						kind:       "PersistentVolumeClaim"
        						metadata: name: v.name
        						spec: {
        							accessModes: ["ReadWriteMany"]
        							volumeMode: "Filesystem"
        							resources: requests: storage: v.size
        							storageClassName: ""
        						}
        					}
        					if v.type == "block" {
        						apiVersion: "v1"
        						kind:       "PersistentVolumeClaim"
        						metadata: name: v.name
        						spec: {
        							accessModes: ["ReadWriteOnce"]
        							volumeMode: "Filesystem"
        							resources: requests: storage: v.size
        							storageClassName: ""
        						}
        					}
        				},
        			]
        		}
        	}
        }
        parameter: {
        	maxReplicas: *1 | int
        	componentLabels?: [string]: string
        	clusterSelector?: {
        		matchLabels?: [string]: string
        		matchExpressions?: [...{
        			key: string
        			values: [...string]
        			operator: string
        		}]
        	}
        	componentSelector?: {
        		matchLabels?: [string]: string
        		matchExpressions?: [...{
        			key: string
        			values: [...string]
        			operator: string
        		}]
        	}
        	cpu:    #cpu
        	memory: #memory
        	accelerators?: {
        		requests?: [string]: string
        		limits?: [string]:   string
        	}
        	storage?: [...{
        		name: string
        		// +usage=Specify volume type, options: "hostPath","block","share"
        		type: "hostPath" | "block" | "share"
        		if type == "hostPath" {
        			path: string
        		}
        		if type == "block" {
        			size:   string
        			diskIO: "extra_high" | "high" | "ordinary"
        		}
        		if type == "share" {
        			size: string
        		}
        	}]

        }
        #cpu: {
        	request: string
        	limit:   string
        }
        #memory: {
        	request: string
        	limit:   string
        }
```
期望产生的CR文件如下所示：
```
apiVersion: uis.tcf.io/v1alpha1
kind: ComponentWork
metadata:
  annotations: {}
  labels:
    app.oam.dev/appRevision: ""
    app.oam.dev/component: edgex-redis
    app.oam.dev/name: shanghai-show
    app.oam.dev/namespace: default
    app.oam.dev/resourceType: WORKLOAD
    workload.oam.dev/type: uis-webservice
  name: edgex-redis
  namespace: default
spec:
  cncfRule:
    accelerators:
      limits:
        nvidia.com/gpu: "1"
      requests:
        nvidia.com/gpu: "1"
    appArch: x86
    appLatency: low
    appPkg: container
    appPriority: low
    appType: online
    cpu:
      limit: "1"
      request: "0"
    maxReplicas: 1
    memory:
      limit: 500Mi
      request: 50Mi
    resourcesPriorityClass: appPriority-1
    resourcesQos: BE
    storage:
    - diskIO: extra_high
      name: block-vol-1
      size: 100Gi
      type: block
    - name: share-vol-1
      size: 10Gi
      type: share
    tenant: shanghai-show
  workload:
    manifests:
    - apiVersion: v1
      kind: Service
      metadata:
        name: zhan-test
      spec:
        ports:
        - port: 6379
          protocol: TCP
          targetPort: 6379
        selector:
          app: edgex-redis
        type: ClusterIP
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        annotations:
          uis: as
        labels:
          app.oam.dev/component: edgex-redis
          app.oam.dev/revision: KUBEVELA_COMPONENT_REVISION_PLACEHOLDER
          uis: as
        name: edgex-redis
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: edgex-redis
        template:
          metadata:
            labels:
              app: edgex-redis
          spec:
            containers:
            - env:
              - name: EDGEX_SECURITY_SECRET_STORE
                value: "false"
              - name: edgex_registry
                value: consul://edgex-core-consul:8500
              image: swr:6666/opcs/nginx:v1
              livenessProbe:
                failureThreshold: 3
                initialDelaySeconds: 5
                periodSeconds: 15
                successThreshold: 1
                tcpSocket:
                  port: 6379
              name: edgex-redis
              ports:
              - containerPort: 6379
              readinessProbe:
                failureThreshold: 3
                initialDelaySeconds: 5
                periodSeconds: 15
                successThreshold: 1
                tcpSocket:
                  port: 6379
              volumeMounts:
              - mountPath: /appdata/edgex/db-data
                name: hostpath-1
              - mountPath: /block/volumes/mount
                name: block-vol-1
              - mountPath: /share/volumes/mount
                name: share-vol-1
            hostname: edgex-nginx
            schedulerName: uis-scheduler
            tolerations:
            - effect: NoExecute
              key: openpalette.clusternode/reserved
              operator: Exists
            - effect: NoSchedule
              key: GPU
              operator: Equal
              value: "True"
            volumes:
            - name: share-vol-1
              persistentVolumeClaim:
                claimName: share-vol-1
			- name: block-vol-1
              persistentVolumeClaim:
                claimName: block-vol-1
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: block-vol-1
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        storageClassName: ""
        volumeMode: Filesystem
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: share-vol-1
      spec:
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: 10Gi
        storageClassName: ""
        volumeMode: Filesystem
```
而实际上产生的ＣＲ如下所示
```
apiVersion: uis.tcf.io/v1alpha1
kind: ComponentWork
metadata:
  annotations: {}
  labels:
    app.oam.dev/appRevision: ""
    app.oam.dev/component: edgex-redis
    app.oam.dev/name: shanghai-show
    app.oam.dev/namespace: default
    app.oam.dev/resourceType: WORKLOAD
    workload.oam.dev/type: uis-webservice
  name: edgex-redis
  namespace: default
spec:
  cncfRule:
    accelerators:
      limits:
        nvidia.com/gpu: "1"
      requests:
        nvidia.com/gpu: "1"
    appArch: x86
    appLatency: low
    appPkg: container
    appPriority: low
    appType: online
    cpu:
      limit: "1"
      request: "0"
    maxReplicas: 1
    memory:
      limit: 500Mi
      request: 50Mi
    resourcesPriorityClass: appPriority-1
    resourcesQos: BE
    storage:
    - diskIO: extra_high
      name: block-vol-1
      size: 100Gi
      type: block
    - name: share-vol-1
      size: 10Gi
      type: share
    tenant: shanghai-show
  workload:
    manifests:
    - apiVersion: v1
      kind: Service
      metadata:
        name: zhan-test
      spec:
        ports:
        - port: 6379
          protocol: TCP
          targetPort: 6379
        selector:
          app: edgex-redis
        type: ClusterIP
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        annotations:
          uis: as
        labels:
          app.oam.dev/component: edgex-redis
          app.oam.dev/revision: KUBEVELA_COMPONENT_REVISION_PLACEHOLDER
          uis: as
        name: edgex-redis
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: edgex-redis
        template:
          metadata:
            labels:
              app: edgex-redis
          spec:
            containers:
            - env:
              - name: EDGEX_SECURITY_SECRET_STORE
                value: "false"
              - name: edgex_registry
                value: consul://edgex-core-consul:8500
              image: swr:6666/opcs/nginx:v1
              livenessProbe:
                failureThreshold: 3
                initialDelaySeconds: 5
                periodSeconds: 15
                successThreshold: 1
                tcpSocket:
                  port: 6379
              name: edgex-redis
              ports:
              - containerPort: 6379
              readinessProbe:
                failureThreshold: 3
                initialDelaySeconds: 5
                periodSeconds: 15
                successThreshold: 1
                tcpSocket:
                  port: 6379
              volumeMounts:
              - mountPath: /appdata/edgex/db-data
                name: hostpath-1
              - mountPath: /block/volumes/mount
                name: block-vol-1
              - mountPath: /share/volumes/mount
                name: share-vol-1
            hostname: edgex-nginx
            schedulerName: uis-scheduler
            tolerations:
            - effect: NoExecute
              key: openpalette.clusternode/reserved
              operator: Exists
            - effect: NoSchedule
              key: GPU
              operator: Equal
              value: "True"
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: block-vol-1
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        storageClassName: ""
        volumeMode: Filesystem
	template:
          spec:
            volumes:
            - name: block-vol-1
              persistentVolumeClaim:
                claimName: block-vol-1
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: share-vol-1
      spec:
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: 10Gi
        storageClassName: ""
        volumeMode: Filesystem
	template:
          spec:
            volumes:
            - name: share-vol-1
              persistentVolumeClaim:
                claimName: share-vol-1
```
问题：我希望ｖｏｌｕｍｅｓ的位置在spec.workload.manifests.deployment下面而不是在ｐｖｃ下面
