### DISCUSSION TITLE
自定义补丁型运维特征patchKey不生效

### DISCUSSION THREAD

**Discussion by fanzhenyu95** [kubevela/kubevela#3696] [Q&A] [answered]
参考官方文档定义增加 Pod 环境变量的运维特征：https://kubevela.net/zh/docs/platform-engineers/traits/patch-trait#%E5%A2%9E%E5%8A%A0-pod-%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F

当webservice组件env属性的key和自定义增加 Pod 环境变量的trait中key同名但是值不同时会报错，具体如下：

自定义运维特征的 `CUE` 模板 `env.cue`：
```
apiVersion: core.oam.dev/v1beta1
kind: Application
env: {
  type: "trait"
  annotations: {}
  description: "add env info"
  attributes: {
    podDisruptive: true
    appliesToWorkloads: ["*"]
  }
}
template: {
  patch: {
      spec: template: spec: {
          // +patchKey=name
          containers: [{
              name: context.name
              // +patchKey=name
              env: [
                  for k, v in parameter.env {
                      name:  k
                      value: v
                  },
              ]
          }]
      }
  }

  parameter: {
      env: [string]: string
  }
}
```

安装：
```
vela def apply env.cue
```

定义测试应用`env.yaml`，webservice组件的env属性中有key为token的环境变量，自定义trait中也有key为token的环境变量，但是值不同：
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: test-demo
  namespace: dev
spec:
  components:
    - name: express-server
      type: webservice
      properties:
        image: crccheck/hello-world
        port: 8000
        env:
          - name: token
            value: token123
      traits:
        - type: env
          properties:
            env:
              token: token456
```

本地运行测试`vela dry-run -f env.yaml`，报错：
```
Error: generate OAM objects: cannot generate AppConfig and Components: evaluate base template component=express-server app=test-demo: failed to have the workload/trait unstructured: cue: marshal error: spec.template.spec.containers.0.env.0.value: from source
```

看起来像是patchKey不生效，麻烦各位大佬解答一下，谢谢！
