### DISCUSSION TITLE
Manually Applying Policies for Custom Deploy Workflow

### DISCUSSION THREAD

**Discussion by kferrone** [kubevela/kubevela#4646] [Ideas]
The workflow steps are not as versatile as hoped. I ultimately want to create my own Deploy workflow where I can pick and choose which components are applied and what polices are applied to them before getting deployed. 

Long story short, I prefer telling a HelmRelease what cluster to push into versus sending the HelmRelease to that cluster, ie flux on one cluster vs all clusters. 

I view the polices as what defines the differences between resources in one environment to the next. The [override policy](https://github.com/kubevela/kubevela/blob/master/references/docgen/def-doc/policy/override.eg.md)and the [replicator policy](https://github.com/kubevela/kubevela/blob/master/references/docgen/def-doc/policy/replication.eg.md) make a lot of sense. As long as you set the name of something with a trait during deployment, it's possible to have a bunch of items in the same ns each with a unique suffix. With the replicator, as long as every component needs replicating, it's fine. 

I thought a custom deploy could be achieved with `op.#ApplyComponent` and some other magic in cue with `vela/op`. However, there is no way to apply any of the polices manually without the deploy step. Applying more traits to components in a custom workflow step is also not possible. 

I feel it would be great to have a new `vela/op` function like `op.#ApplyPolicies` which can give me more granular control over a custom deployment. 

Maybe, the `apply-component` step type could simply include policy and component selector
```yaml
- type: apply-component 
  properties:
    policies: ["foo","bar"]
    selector: ["my-component"]
```

I imagine if this were possible, the policy definitions would need to state what their scope is. What I understand so far is custom policy definitions just run all the time and only the built in policies are chosen on the deploy step.

**Comment by Somefive** [comment]
```yaml
- type: deploy
  properties:
    policies: ["foo","bar"]
    selector: ["my-component"]
```
Is this step equally acceptable?

There is a long way from `apply-component` to `deploy` workflow step. In general, we intend to extend more internally capabilities on the `deploy` step but leave limited extensibility for `apply-component` as well.

The `selector` used in the shown `apply-component` is actually embedded in `override` policy which can be leveraged by `deploy` workflow step. Like

```yaml
policies:
- type: override
  name: select-comp
  properties:
    selector: ["my-component"]
workflow:
  steps:
  - type: deploy
    name: deploy
    properties:
      policies: ["foo", "bar", "select-comp"]
```

FYI, some details for `deploy` vs `apply-component`:

The initial intention for `deploy` is to make multi-cluster deployment easier. So at first we try to re-use `apply-component` in `deploy2env` (the legacy version of `deploy`). This reuse is built on CUELang but later we found although it is highly extensible (just like what you want), but it is too complex for users to understand and make customization. Here is the legacy implementation. https://github.com/kubevela/kubevela/blob/release-1.2/pkg/stdlib/pkgs/multicluster.cue

Then we found the CUELang composed workflow step is also hard to maintain. (Difficult to locate bugs and errors.) Besides, there are features that are hard to implement based on pure CUELang (such as dependency between components & healthCheck). Therefore, in KubeVela v1.4, we switch the implementation of `deploy` from CUELang to internal GoLang, which is less extensible and open but more robust and easy to use.

So if possible, we prefer to leave your feature requests to `deploy` step. But the design of `selector` field in `deploy` step, I'm afraid is not very easy to accept. (Easy to implement) Some of the community members prefer leaving the `deploy` step to be clean but AFAIS specifying `selector` in `deploy` can simplify the usage.
