### DISCUSSION TITLE
Set traits in an appfile

### DISCUSSION THREAD

**Discussion by Tranceh2** [kubevela/kubevela#4703] [Q&A]
Hello. I am trying to implement the use of appfile/kubevela in conjunction with Argocd and I reached the following issue #4342 
But when I try to apply the proposed solution, through the traitDefinition indicated in the issue, which is the following:
```yaml
apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  annotations:
    definition.oam.dev/description: "Specify annotations to mark all resources to be ignored by ArgoCD"
  name: argocd
spec:
  schematic:
    cue:
      template: |
        patch: {
          metadata: annotations: {
            "argocd.argoproj.io/compare-options": "IgnoreExtraneous"
            "argocd.argoproj.io/sync-options": "Prune=false"
          }
        }
        patchOutputs: {
          for k, v in context.outputs {
            "\(k)": {
              metadata: annotations: {
                "argocd.argoproj.io/compare-options": "IgnoreExtraneous"
                "argocd.argoproj.io/sync-options":    "Prune=false"
              }
            }
          }
        }

```
to an appfile, following the documentation at [Learning Appfile](https://kubevela.io/docs/developers/learn-appfile), it does not work. The appfile that I am using to test is written as follows:
```yaml
name: demo
services:
  testsvc:
    type: webservice
    image: crccheck/hello-world
    port: 8000
    argocd:
      name: argocd
```
the only way in which it works is by applying it directly in an application type manifest:
```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: demo
spec:
  components:
  - name: testsvc
    properties:
      image: crccheck/hello-world
      port: 8000
    type: webservice
    traits:
      - type: argocd
        properties:
          name: argocd
```

I really appreciate the help and apologize if I missed something in the documentation. And sorry because my english is bad

**Comment by wonderflow** [comment]
Thanks for raising this, I'll try investigate it.

**Reply by wonderflow** [reply]
I did the same steps as you described but my appfile runs well, you can use vela export for test first:

```
✗ vela export -f appfile.yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  creationTimestamp: null
  name: demo
spec:
  components:
  - name: testsvc
    properties:
      image: crccheck/hello-world
      port: 8000
    traits:
    - properties:
        name: argocd
      type: argocd
    type: webservice
status: {}
```

It will convert the appfile to application object, they're actually the same.

Then I deployed the appfile like below:

```
$ vela up -f appfile.yaml
Parsing vela application file ...
Load Template ...
parsing application components
Applying application ...
Checking if app has been deployed...
App has not been deployed, creating a new deployment...
✅ App has been deployed 🚀🚀🚀
    Port forward: vela port-forward demo
             SSH: vela exec demo
         Logging: vela logs demo
      App status: vela status demo
        Endpoint: vela status demo --endpoint
```

```
vela status demo
About:

  Name:      	demo
  Namespace: 	default
  Created at:	2022-09-09 13:35:11 +0800 CST
  Status:    	running

Workflow:

  mode: DAG
  finished: true
  Suspend: false
  Terminated: false
  Steps
  - id: 8xs7cnogii
    name: testsvc
    type: apply-component
    phase: succeeded
    message:

Services:

  - Name: testsvc
    Cluster: local  Namespace: default
    Type: webservice
    Healthy Ready:1/1
    Traits:
      ✅ argocd
```

The annoation also injected:

<detail>

```
kubectl get deploy testsvc -o yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.oam.dev/last-applied-configuration: '{"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"argocd.argoproj.io/compare-options":"IgnoreExtraneous","argocd.argoproj.io/sync-options":"Prune=false","oam.dev/kubevela-version":"v1.5.4"},"labels":{"app.oam.dev/app-revision-hash":"215dc8467199ac8","app.oam.dev/appRevision":"demo-v1","app.oam.dev/cluster":"","app.oam.dev/component":"testsvc","app.oam.dev/name":"demo","app.oam.dev/namespace":"default","app.oam.dev/resourceType":"WORKLOAD","app.oam.dev/revision":"testsvc-v1","oam.dev/render-hash":"8fdf44efed56928b","workload.oam.dev/type":"webservice"},"name":"testsvc","namespace":"default"},"spec":{"selector":{"matchLabels":{"app.oam.dev/component":"testsvc"}},"template":{"metadata":{"labels":{"app.oam.dev/component":"testsvc","app.oam.dev/name":"demo"}},"spec":{"containers":[{"image":"crccheck/hello-world","name":"testsvc","ports":[{"containerPort":8000}]}]}}}}'
    app.oam.dev/last-applied-time: "2022-09-09T05:35:11Z"
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
    deployment.kubernetes.io/revision: "1"
    oam.dev/kubevela-version: v1.5.4
  creationTimestamp: "2022-09-09T05:35:11Z"
  generation: 1
  labels:
    app.oam.dev/app-revision-hash: 215dc8467199ac8
    app.oam.dev/appRevision: demo-v1
    app.oam.dev/cluster: ""
    app.oam.dev/component: testsvc
    app.oam.dev/name: demo
    app.oam.dev/namespace: default
    app.oam.dev/resourceType: WORKLOAD
    app.oam.dev/revision: testsvc-v1
    oam.dev/render-hash: 8fdf44efed56928b
    workload.oam.dev/type: webservice
  name: testsvc
  namespace: default
  resourceVersion: "2090"
  uid: ddb5e4a2-77e2-4802-9b09-975379dcafd8
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.oam.dev/component: testsvc
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.oam.dev/component: testsvc
        app.oam.dev/name: demo
    spec:
      containers:
      - image: crccheck/hello-world
        imagePullPolicy: Always
        name: testsvc
        ports:
        - containerPort: 8000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-09-09T05:35:22Z"
    lastUpdateTime: "2022-09-09T05:35:22Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-09-09T05:35:11Z"
    lastUpdateTime: "2022-09-09T05:35:22Z"
    message: ReplicaSet "testsvc-7f8b9ccdb7" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
```

</detail>

**Reply by Tranceh2** [reply]
I am using the "vela export" command in the same way to verify before if the appfile is correct.
```shell
❯ cat vela.yaml 
name: demo
services:
  testsvc:
    type: webservice
    image: crccheck/hello-world
    port: 8000
    argocd:
      name: "argocd"

❯ vela export -f vela.yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  creationTimestamp: null
  name: demo
spec:
  components:
  - name: testsvc
    properties:
      argocd:
        name: argocd
      image: crccheck/hello-world
      port: 8000
    type: webservice
status: {}
```
And I am also verifying that the "trait" exists in the cluster

```shell
❯ vela traits
NAME                            APPLIES-TO                                                  
NAME                            APPLIES-TO                                                      DESCRIPTION                                                 
affinity                        [deployments.apps statefulsets.apps daemonsets.apps             Affinity specifies affinity and toleration K8s pod for your 
                                jobs.batch]                                                     workload which follows the pod spec in path 'spec.template'.
annotations                     [*]                                                             Add annotations on your workload. if it generates pod, add  
                                                                                                same annotations for generated pods.                        
argocd                          []                                                              Specify annotations to mark all resources to be ignored by  
                                                                                                ArgoCD                                                      
argocd-patch                    [*]                                                             Specify annotations to mark all resources to be ignored by  
                                                                                                ArgoCD                                                      
command                         [deployments.apps statefulsets.apps daemonsets.apps             Add command on K8s pod for your workload which follows the  
                                jobs.batch]                                                     pod spec in path 'spec.template'                            
configmap                       [*]                                                             Create/Attach configmaps on K8s pod for your workload which 
                                                                                                follows the pod spec in path 'spec.template'. This          
                                                                                                definition is DEPRECATED, please specify configmap in       
                                                                                                'storage' instead.                                          
container-image                 [deployments.apps statefulsets.apps daemonsets.apps             Set the image of the container.                             
                                jobs.batch]                                                                                                                 
cpuscaler                       [deployments.apps statefulsets.apps]                            Automatically scale the component based on CPU usage.       
env                             [deployments.apps statefulsets.apps daemonsets.apps             Add env on K8s pod for your workload which follows the pod  
                                jobs.batch]                                                     spec in path 'spec.template'                                
expose                          [deployments.apps statefulsets.apps]                            Expose port to enable web traffic for your component.       
gateway                         [deployments.apps statefulsets.apps]                            Enable public web traffic for the component, the ingress API
                                                                                                matches K8s v1.20+.                                         
hostalias                       [deployments.apps statefulsets.apps daemonsets.apps             Add host aliases on K8s pod for your workload which follows 
                                jobs.batch]                                                     the pod spec in path 'spec.template'.                       
import-grafana-dashboard        []                                                              Import dashboards to Grafana                                
ingress                         []                                                              Enable public web traffic for the component.                
ingress-1-20                    []                                                              Enable public web traffic for the component, the ingress API
                                                                                                matches K8s v1.20+.                                         
init-container                  [deployments.apps statefulsets.apps daemonsets.apps             add an init container and use shared volume with pod        
                                jobs.batch]                                                                                                                 
json-merge-patch                [*]                                                             Patch the output following Json Merge Patch strategy,       
                                                                                                following RFC 7396.                                         
json-patch                      [*]                                                             Patch the output following Json Patch strategy, following   
                                                                                                RFC 6902.                                                   
labels                          [*]                                                             Add labels on your workload. if it generates pod, add same  
                                                                                                label for generated pods.                                   
lifecycle                       [deployments.apps statefulsets.apps daemonsets.apps             Add lifecycle hooks for every container of K8s pod for your 
                                jobs.batch]                                                     workload which follows the pod spec in path 'spec.template'.
nocalhost                       [deployments.apps statefulsets.apps daemonsets.apps             nocalhost develop configuration.                            
                                jobs.batch]                                                                                                                 
node-affinity                   [*]                                                             affinity specify node affinity and toleration on K8s pod for
                                                                                                your workload which follows the pod spec in path            
                                                                                                'spec.template'.                                            
patch                           [*]                                                             Patch the output directly.                                  
pure-ingress                    [*]                                                             Enable public web traffic for the component without creating
                                                                                                a Service.                                                  
pvc                             [deployments.apps]                                              Create a Persistent Volume Claim and mount the PVC as volume
                                                                                                to the  first container in the pod. This definition is      
                                                                                                DEPRECATED, please specify pvc in 'storage' instead.        
register-grafana-datasource     []                                                              Add a datasource to Grafana                                 
resource                        [deployments.apps statefulsets.apps daemonsets.apps             Add resource requests and limits on K8s pod for your        
                                jobs.batch]                                                     workload which follows the pod spec in path 'spec.template.'
scaler                          [deployments.apps statefulsets.apps]                            Manually scale K8s pod for your workload which follows the  
                                                                                                pod spec in path 'spec.template'.                           
service-account                 [deployments.apps statefulsets.apps daemonsets.apps             Specify serviceAccount for your workload which follows the  
                                jobs.batch]                                                     pod spec in path 'spec.template'.                           
service-binding                 [deployments.apps statefulsets.apps daemonsets.apps             Binding secrets of cloud resources to component env. This   
                                jobs.batch]                                                     definition is DEPRECATED, please use 'storage' instead.     
sidecar                         [deployments.apps statefulsets.apps daemonsets.apps             Inject a sidecar container to K8s pod for your workload     
                                jobs.batch]                                                     which follows the pod spec in path 'spec.template'.         
storage                         [deployments.apps statefulsets.apps daemonsets.apps             Add storages on K8s pod for your workload which follows the 
                                jobs.batch]                                                     pod spec in path 'spec.template'.                           
volumes                         [deployments.apps]                                              Add volumes on K8s pod for your workload which follows the  
                                                                                                pod spec in path 'spec.template'. This definition is        
                                                                                                DEPRECATED, please use 'storage' instead.                   
```
Other information that could be useful is that I am deploying "vela" through "helm" (with Argocd) in its version "vela-minimal" 1.5.4 and using the following values
```yaml
multicluster:
  enabled: false
admissionWebhooks:
  autoGenWorkloadDefinition: true
```

A moment ago I tried with the "vela-core" version and activating the multicluster option, but I have the same problem. I am performing these tests on K0S clusters of 1 single node in version 1.24.4+k0s.0. I don't know if I'm doing something wrong

Thanks for the help
