### DISCUSSION TITLE
Difference between dry-run and export

### DISCUSSION THREAD

**Discussion by Niksko** [kubevela/kubevela#5100] [Q&A] [answered]
Hi, I'm wondering what the difference is between `vela dry-run` and `vela export`. Is one preferred over the other? In particular, which would you recommend for a CMP in ArgoCD? This document seems to use `vela export`, but it's almost two years old: https://www.cncf.io/blog/2020/12/22/argocd-kubevela-gitops-with-developer-centric-experience/

**Comment by wonderflow** [comment, marked as answer]
Hi @Niksko , It's a good question. There're two kinds of yaml in vela one is called appfile and the other is called application.

appfile is like:

```
name: testapp

services:
  frontend: # 1st service

    image: oamdev/testapp:v1
    build:
      docker:
        file: Dockerfile
        context: .

    cmd: ["node", "server.js"]
    port: 8080

    route: # trait
      domain: example.com
      rules:
        - path: /testapp
          rewriteTarget: /

  backend: # 2nd service
    type: task # workload type
    image: perl 
    cmd: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
```

https://kubevela.net/docs/developers/learn-appfile#prerequisites

Another one is application.yaml

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: first-vela-app
spec:
  components:
    - name: express-server
      type: webservice
      properties:
        image: oamdev/hello-world
        ports:
         - port: 8000
           expose: true
      traits:
        - type: scaler
          properties:
            replicas: 1
  policies:
    - name: target-default
      type: topology
      properties:
        # The cluster with name local is installed the KubeVela.
        clusters: ["local"]
        namespace: "default"
    - name: target-prod
      type: topology
      properties:
        clusters: ["local"]
        # This namespace must be created before deploying.
        namespace: "prod"
    - name: deploy-ha
      type: override
      properties:
        components:
          - type: webservice
            traits:
              - type: scaler
                properties:
                  replicas: 2
```

https://kubevela.net/docs/quick-start

`vela dry-run` works for application.yaml while `vela export` works for appfile. Now, most of the applications used in kubevela are represent in application.yaml.
