### DISCUSSION TITLE
Add the ability to select an environment from the CLI during dry-run

### DISCUSSION THREAD

**Discussion by Niksko** [kubevela/kubevela#5184] [Ideas] [answered]
We're trying to build a method of application delivery where KubeVela templates are rendered ahead of time e.g. by ArgoCD and then applied to the cluster as raw Kubernetes YAML.

What's currently blocking us is that the concept of an environment in KubeVela seems to be a server-side concept, and there is no way of selecting an environment client side e.g. during a dry run. What we would like is to be able to run `vela dry-run --environment dev -f my-app.yaml` and have this render the application as if it was going to be deployed to an environment called `dev`. This would allow developers to configure overlays and other environment specific differences e.g. replicas or different hostnames.

Is there any existing way to accomplish this? If not, would you be open to a feature contribution to add this?

**Comment by wonderflow** [comment, marked as answer]
Hi, @Niksko , this is a good idea! Environment is an existing concept in vela CLI, it currently only represent namespace to deploy.

We have something similar that leverages policy for configure overlay parameters, but I'm not sure if this satisfied for you.

For example, we have an application like below:

```my-app.yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: first-vela-app
spec:
  components:
    - name: express-server
      type: webservice
      properties:
        image: oamdev/hello-world
        ports:
         - port: 8000
           expose: true
      traits:
        - type: scaler
          properties:
            replicas: 1
  policies:
    - name: env-default
      type: topology
      properties:
        clusters: ["local"]
        namespace: "default"
    - name: env-prod
      type: topology
      properties:
        clusters: ["local"]
        namespace: "prod"
    - name: deploy-ha
      type: override
      properties:
        components:
          - type: webservice
            traits:
              - type: scaler
                properties:
                  replicas: 2
```

We can support commands like:

```
vela dry-run --policy env-prod,deploy-ha -f my-app.yaml
```

Then we can render yaml results which specify the deploy target and also override configurations.

This relates the issue https://github.com/kubevela/kubevela/issues/4410

In this case, **workflow steps** won't be supported in client-side dry-run as it's a server-side feature. \cc @cezhang @Somefive 

BTW, we're very open for contributions! @Niksko

**Reply by Niksko** [reply]
Great, thanks so much @wonderflow, I think that's along the lines of what we're looking for. I think we'd really like something like the following:

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: first-vela-app
spec:
  components:
    - name: express-server
      type: webservice
      properties:
        image: oamdev/hello-world
        ports:
         - port: 8000
           expose: true
      traits:
        - type: scaler
          properties:
            replicas: 1
  policies:
    - name: env-default
      type: topology
      properties:
        clusters: ["local"]
        namespace: "default"
    - name: env-prod
      type: topology
      properties:
        clusters: ["local"]
        namespace: "prod"
    - name: deploy-ha
      type: override
      properties:
        components:
          - type: webservice
            traits:
              - type: scaler
                properties:
                  replicas: 2
    # This would be new, not sure if it complies with the OAM spec
    - name: default
      type: deployment-target
      properties:
        policies:
        - env-default
    - name: prod
      type: deployment-target
      properties:
        policies:
        - env-prod
        - deploy-ha
```

And then we could select the deployment target with something like `vela dry-run --target default -f my-app.yaml`. Essentially, bundling together different policies for a particular environment.

We'll wait for that feature to release in 1.7, it would be a good start.

Also, it feels like we might be able to accomplish our use case using addons, does that sound feasible?

**Reply by wonderflow** [reply]
Why do you need to add the new section?

```
   # This would be new, not sure if it complies with the OAM spec
    - name: default
      type: deployment-target
      properties:
        policies:
        - env-default
    - name: prod
      type: deployment-target
      properties:
        policies:
        - env-prod
        - deploy-ha
```

Actually, this is not needed in the solution:

If you want to render the default envrionment, just:

```
vela dry-run --policy default -f my-app.yaml
```

For prod envrionement:
```
vela dry-run --policy env-prod,deploy-ha -f my-app.yaml
```

The bundling works when you specify the policies in the command.

Are you meaning that you want the name more straightforward?

>  it feels like we might be able to accomplish our use case using addons, does that sound feasible?

 Really glad to hear that!

**Reply by Somefive** [reply]
There is a proposed way to handle the case, after discussed with @wonderflow . @Niksko you can review this design.

In this design, your application is split into multiple files.
```bash
my-app/
|- app.yaml
|- env-default.yaml
|- env-prod.yaml
```

```yaml
# my-app/app.yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: first-vela-app
spec:
  components:
    - name: express-server
      type: webservice
      properties:
        image: oamdev/hello-world
        ports:
         - port: 8000
           expose: true
      traits:
        - type: scaler
          properties:
            replicas: 1
```

```yaml
# my-app/env-default.yaml
apiVersion: core.oam.dev/v1alpha1
kind: Policy
metadata:
  name: env-default
type: topology
properties:
  clusters: ["local"]
  namespace: "default"
```

```yaml
# my-app/env-prod.yaml
apiVersion: core.oam.dev/v1alpha1
kind: Policy
metadata:
  name: env-prod
type: topology
properties:
  clusters: ["local"]
  namespace: "prody"
---
apiVersion: core.oam.dev/v1alpha1
kind: Policy
metadata:
  name: ha
type: override
properties:
  components:
  - type: webservice
    traits:
    - type: scaler
      properties:
        replicas: 2
```

- If you need to render the resources for `env-default`, run `vela dry-run -f my-app/app.yaml my-app/env-default.yaml`.
- If you need to render the resources for `env-prod`, run `vela dry-run -f my-app/app.yaml my-app/env-prod.yaml`.

How do you think of it?

/cc @cezhang Maybe this design could help you to review the implementation of #4815.

Reference:
- https://kubevela.net/docs/end-user/components/ref-objects#distribute-reference-objects-with-different-configuration

**Reply by Niksko** [reply]
@cezhang @wonderflow @Somefive that's exactly the sort of design we're looking for, that would be fantastic if it were implemented as part of #4815. As I said, also happy to contribute ourselves if necessary.

**Reply by wonderflow** [reply]
Great, the final design will follow @Somefive listed here. It'll be Included in v1.7 release. \cc @cezhang

**Reply by cezhang** [reply]
Hi, I re-implement this feature. Please check this out .

Take the  above```my-app``` for example:
```
vela dry-run -f app.yaml -p env-default.yaml 

---
# Application(first-vela-app with topology env-default) -- Component(express-server)
---

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app.oam.dev/appRevision: ""
    app.oam.dev/component: express-server
    app.oam.dev/name: first-vela-app
    app.oam.dev/namespace: default
    app.oam.dev/resourceType: WORKLOAD
    workload.oam.dev/type: webservice
  name: express-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.oam.dev/component: express-server
  template:
    metadata:
      labels:
        app.oam.dev/component: express-server
        app.oam.dev/name: first-vela-app
    spec:
      containers:
      - image: oamdev/hello-world
        name: express-server
        ports:
        - containerPort: 8000
          name: port-8000
          protocol: TCP

---
## From the auxiliary workload
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app.oam.dev/appRevision: ""
    app.oam.dev/component: express-server
    app.oam.dev/name: first-vela-app
    app.oam.dev/namespace: default
    app.oam.dev/resourceType: TRAIT
    trait.oam.dev/resource: webserviceExpose
    trait.oam.dev/type: AuxiliaryWorkload
  name: express-server
  namespace: default
spec:
  ports:
  - name: port-8000
    port: 8000
    targetPort: 8000
  selector:
    app.oam.dev/component: express-server
  type: ClusterIP

---
```

```
vela dry-run -f app.yaml -p env-prod.yaml 

---
# Application(first-vela-app with topology env-prod) -- Component(express-server)
---

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app.oam.dev/appRevision: ""
    app.oam.dev/component: express-server
    app.oam.dev/name: first-vela-app
    app.oam.dev/namespace: default
    app.oam.dev/resourceType: WORKLOAD
    workload.oam.dev/type: webservice
  name: express-server
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app.oam.dev/component: express-server
  template:
    metadata:
      labels:
        app.oam.dev/component: express-server
        app.oam.dev/name: first-vela-app
    spec:
      containers:
      - image: oamdev/hello-world
        name: express-server
        ports:
        - containerPort: 8000
          name: port-8000
          protocol: TCP

---
## From the auxiliary workload
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app.oam.dev/appRevision: ""
    app.oam.dev/component: express-server
    app.oam.dev/name: first-vela-app
    app.oam.dev/namespace: default
    app.oam.dev/resourceType: TRAIT
    trait.oam.dev/resource: webserviceExpose
    trait.oam.dev/type: AuxiliaryWorkload
  name: express-server
  namespace: default
spec:
  ports:
  - name: port-8000
    port: 8000
    targetPort: 8000
  selector:
    app.oam.dev/component: express-server
  type: ClusterIP

---

```

```
vela dry-run -f app.yaml  

---
# Application(default) -- Component(express-server)
---

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app.oam.dev/appRevision: ""
    app.oam.dev/component: express-server
    app.oam.dev/name: first-vela-app
    app.oam.dev/namespace: default
    app.oam.dev/resourceType: WORKLOAD
    workload.oam.dev/type: webservice
  name: express-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.oam.dev/component: express-server
  template:
    metadata:
      labels:
        app.oam.dev/component: express-server
        app.oam.dev/name: first-vela-app
    spec:
      containers:
      - image: oamdev/hello-world
        name: express-server
        ports:
        - containerPort: 8000
          name: port-8000
          protocol: TCP

---
## From the auxiliary workload
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app.oam.dev/appRevision: ""
    app.oam.dev/component: express-server
    app.oam.dev/name: first-vela-app
    app.oam.dev/namespace: default
    app.oam.dev/resourceType: TRAIT
    trait.oam.dev/resource: webserviceExpose
    trait.oam.dev/type: AuxiliaryWorkload
  name: express-server
  namespace: default
spec:
  ports:
  - name: port-8000
    port: 8000
    targetPort: 8000
  selector:
    app.oam.dev/component: express-server
  type: ClusterIP

---
```

As the example of ```workflow reference```(https://kubevela.net/docs/end-user/components/ref-objects#distribute-reference-objects-with-different-configuration) 
```
apiVersion: core.oam.dev/v1alpha1
kind: Policy
metadata:
  name: env-prod
type: topology
properties:
  clusters: ["local"]
  namespace: "prod"
---
apiVersion: core.oam.dev/v1alpha1
kind: Policy
metadata:
  name: ha
type: override
properties:
  components:
  - type: webservice
    traits:
    - type: scaler
      properties:
        replicas: 2
---
apiVersion: core.oam.dev/v1alpha1
kind: Workflow
metadata:
  name: deploy-demo
  namespace: default
steps:
  - type: deploy
    name: deploy-prod
    properties:
      policies: ["ha", "env-prod"]

for above pre-defined:

# first-app.yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: first-vela-app
spec:
  components:
    - name: express-server
      type: webservice
      properties:
        image: oamdev/hello-world
        ports:
         - port: 8000
           expose: true
      traits:
        - type: scaler
          properties:
            replicas: 1
  workflow:
    ref: deploy-demo
```

```
vela dry-run -f first-app.yaml,  will produce

---
# Application(first-vela-app with topology env-prod) -- Component(express-server)
---

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app.oam.dev/appRevision: ""
    app.oam.dev/component: express-server
    app.oam.dev/name: first-vela-app
    app.oam.dev/namespace: default
    app.oam.dev/resourceType: WORKLOAD
    workload.oam.dev/type: webservice
  name: express-server
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app.oam.dev/component: express-server
  template:
    metadata:
      labels:
        app.oam.dev/component: express-server
        app.oam.dev/name: first-vela-app
    spec:
      containers:
      - image: oamdev/hello-world
        name: express-server
        ports:
        - containerPort: 8000
          name: port-8000
          protocol: TCP

---
## From the auxiliary workload
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app.oam.dev/appRevision: ""
    app.oam.dev/component: express-server
    app.oam.dev/name: first-vela-app
    app.oam.dev/namespace: default
    app.oam.dev/resourceType: TRAIT
    trait.oam.dev/resource: webserviceExpose
    trait.oam.dev/type: AuxiliaryWorkload
  name: express-server
  namespace: default
spec:
  ports:
  - name: port-8000
    port: 8000
    targetPort: 8000
  selector:
    app.oam.dev/component: express-server
  type: ClusterIP
```
