### DISCUSSION TITLE
create-config 的template是什么东西呢

### DISCUSSION THREAD

**Discussion by 13567436138** [kubevela/kubevela#5685] [Q&A]
```
kind: Application
apiVersion: core.oam.dev/v1beta1
metadata:
  name: create-config
spec:
  components: 
    - type: webservice
      name: nginx
      properties:
        image: nginx
        imagePullPolicy: IfNotPresent
      traits:
        - type: expose
          properties:
            port: [80]
  workflow:
    steps:
      - name: Prepare Prometheus
        type: step-group
        subSteps:
        - name: write-config
          type: create-config
          properties:
            name: test
            template: prometheus-server
            config: 
              key1: value1
              key2: 2
              key3: true
              key4: 
                key5: value5
```
