### DISCUSSION TITLE
WorkloadRef kind is not supported

### DISCUSSION THREAD

**Discussion by AsherBoone** [kubevela/kubevela#5825] [Q&A]
`# kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}`

kubevela version:

```CLI Version: 1.8.0-beta.3
Core Version: 1.8.0-beta.3
GitRevision: git-8fabbbf2
GolangVersion: go1.19.7
```

Canary yaml:
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: canary-demo
  annotations:
    app.oam.dev/publishVersion: v1
spec:
  components:
  - name: canary-demo
    type: helm
    properties:
      repoType: "helm"
      url: "https://wangyikewxgm.github.io/my-charts/"
      chart: "canary-demo"
      version: "1.0.0"
    traits:
    - type: kruise-rollout
      properties:
        canary:
          # The first batch of Canary releases 20% Pods, and 20% traffic imported to the new version, require manual confirmation before subsequent releases are completed
          steps:
          - weight: 20
          # The second batch of Canary releases 90% Pods, and 90% traffic imported to the new version.
          - weight: 90
          trafficRoutings:
          - type: ingress
```

error info:

```
Applying an application in vela K8s object format...
I0410 17:09:35.029928 4137927 apply.go:121] "patching object" name="canary-demo" resource="core.oam.dev/v1beta1, Kind=Application"
✅ App has been deployed 🚀🚀🚀
    Port forward: vela port-forward canary-demo
             SSH: vela exec canary-demo
         Logging: vela logs canary-demo
      App status: vela status canary-demo
        Endpoint: vela status canary-demo --endpoint
Application /canary-demo applied.
# vela status canary-demo
About:

  Name:         canary-demo
  Namespace:    default
  Created at:   2023-04-10 15:40:51 +0800 CST
  Status:       workflowFailed

Workflow:

  mode: DAG-DAG
  finished: true
  Suspend: false
  Terminated: true
  Steps
  - id: 5uxj5uaruk
    name: canary-demo
    type: apply-component
    phase: failed
    message: run step(provider=oam,do=component-apply): Dispatch: pre-dispatch dryrun failed: Found 1 errors. [(cannot create object: admission webhook "vrollout.kb.io" denied the request: Spec.ObjectRef.WorkloadRef: Invalid value: v1alpha1.WorkloadRef{APIVersion:"helm.toolkit.fluxcd.io/v2beta1", Kind:"HelmRelease", Name:"canary-demo"}: WorkloadRef kind is not supported)]
```

error:
    message: run step(provider=oam,do=component-apply): Dispatch: pre-dispatch dryrun failed: Found 1 errors. [(cannot create object: admission webhook "vrollout.kb.io" denied the request: Spec.ObjectRef.WorkloadRef: Invalid value: v1alpha1.WorkloadRef{APIVersion:"helm.toolkit.fluxcd.io/v2beta1", Kind:"HelmRelease", Name:"canary-demo"}: WorkloadRef kind is not supported)]

I have encountered this error, please help me
