### DISCUSSION TITLE
How to distrubute the manifest in git repo to managedCluster by fluxcd

### DISCUSSION THREAD

**Discussion by USER0308** [kubevela/kubevela#5850] [Q&A]
Hello all:
  I have a hub cluster and a joined and healthy managedCluster. And I have installed kubevela controller and enabled the fluxcd addon on my k8s cluster successfully. Everything was normal.

  And I am trying to distribute some manifest in git repository by fluxcd.
  This is my application.yaml:
```
kind: Application
metadata:
  name: public-git-https
  namespace: default
spec:
  components:
  - name: public-git-https
    properties:
      git:
        branch: master
      path: ./deploy
      pullInterval: 1m
      repoType: git
      secretRef: git-ca-cert
      url: https://10.50.208.30:32151/root/k8s-raw-yaml.git
    type: kustomize
```

The yaml manifests in git repo is raw k8s resource, like this:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-dev
  namespace: default
spec:
  selector:
    matchLabels:
      app: dev
  template:
    metadata:
      labels:
        app: dev
    spec:
      containers:
      - image: nginx:1.23.3
        name: nginx
```

After running `vela up -f ./application.yaml`, kube vela controller created the application successfully. And fluxcd controller pulled the code successfully. An nginx pod was running in default namespace successfully.(I know that if no cluster specified, resource will deploy on `local` cluster)

So my question is "How to make this nginx pod running on my managedCluster".
I have tried to add the policies and workflow in application.yaml to specify the managedCluster and namespace, and it didn't work.

I have also tried to change the k8s raw deploymant yaml into an application.yaml like this:

**Comment by USER0308** [comment]
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: app-from-git
  namespace: default
spec:
   workflow:
     steps:
       - name: workflow-git
         type: deploy
         properties:
           policies: ["deploy-git"]
   policies:
     - name: deploy-git
       type: topology
       properties:
         clusters: ["new-cluster"]
         namespace: kube-vela-app-ns
  components:
    - name: create-app-https
      type: k8s-objects
      properties:
        objects:
          - apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: app-create
            spec:
              selector:
                matchLabels:
                  app: app-create
              template:
                metadata:
                  labels:
                    app: app-create
                spec:
                  containers:
                  - image: nginx:1.23.3
                    name: nginx
```
This worked and created two application in local cluster and nginx pod ran in managedCluster.
But I don't want to hard code the deploy infos(policies, workflow) in git repo yaml, since I could deploy this component in different clusters and namespaces dynamicly. 

Is there any way to make it come true? Thanks for your opinions ^_^

**Comment by Somefive** [comment]
```yaml
kind: Application
metadata:
  name: public-git-https
  namespace: default
spec:
  components:
  - name: public-git-https
    properties:
      git:
        branch: master
      path: ./deploy
      pullInterval: 1m
      repoType: git
      secretRef: git-ca-cert
      url: https://10.50.208.30:32151/root/k8s-raw-yaml.git
    type: kustomize
   policies:
     - name: deploy-git
       type: topology
       properties:
         clusters: ["new-cluster"]
         namespace: kube-vela-app-ns
```

You mean this does not work? Is there any error reported for this application?

Something to notice:
1. If you enable "fluxcd" addon before you join your managed cluster, you need to enable it again to get it work in managed cluster as well.
2. If "fluxcd" is not deployed on your managed cluster, the kustomize resource will not be able to be delivered to managed cluster.
3. If "fluxcd" is installed on your managed cluster, and the application successfully delivered the kustomize resource, you should be able to get a kustomize object in your managed cluster. The fluxcd controller will take responsibility to process that kustomize object and create your deployment.

FYI, if you do not want to include too much deploy infos in your application, you can leave it out in the external Policy and Workflow. Though it does not work completely as you mentioned, it could give you some idea for how to design and manage your manifest. See http://kubevela.net/docs/end-user/components/ref-objects for more details.
