### DISCUSSION TITLE
How to restart an "application" within kube vela

### DISCUSSION THREAD

**Discussion by USER0308** [kubevela/kubevela#5851] [Q&A]
I have created an application with `vela up -f application.yaml`.

Application.yaml like this:
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    app.oam.dev/publishVersion: redeploy-app-v1
    oam.dev/kubevela-version: v1.7.6
  name: redeploy-app
  namespace: test-vela
spec:
  components:
  - name: redeploy-app
    properties:
      objects:
      - apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: redeploy-app
        spec:
          selector:
            matchLabels:
              app: redeploy-app
          template:
            metadata:
              labels:
                app: redeploy-app
                version: v1
            spec:
              containers:
              - image: xxx:latest
                name: xxx
    type: k8s-objects
  policies:
  - name: redeploy-app
    properties:
      clusters:
      - new-cluster
      namespace: ns2
    type: topology
```

And the pod was running successfully in namespace `ns2` of managedCluster `new-cluster`.
Considering the pod was something wrong(hang on or something else) and needed to be deleted and recreated, how to do this with kube vela?

And I have tried to run `vela workflow restart redeploy-app -n test-vela`, it shows restart successfully. But the pod was not recreated. And I read the kube vela source code and found out that it just update the application's status and set status.workflow to nil.

So, I have tried to update application's status to runningWorkflow and set .Status.Workflow = nil within code and it didn't work, also.
```
app, err := appClient.CoreV1beta1().Applications(namespace).Get(context.TODO(), name, metav1.GetOptions{})
app.Status.Phase = "runningWorkflow"
app.Status.Workflow = nil
```
It updated the application's status again but the pod was not recreate.

Event though I use -s to specify the workflow step name, it didn't recreate. And the kube vela source code shows that it will deal with failed step only.

I have also tried to use the latest revision to re-deploy the application. And the pod didn't re-create again.

So are there any methods to delete and recreate the pod by kube-vela?
More over, what if there are two pods in different namespaces in managedCluster, are there any ways to delete the specify one?
