### DISCUSSION TITLE
关于内置资源和自定义组件的最佳实践讨论

### DISCUSSION THREAD

**Discussion by kissycn** [kubevela/kubevela#5931] [Show and tell]
最近在封装OpenKruise这个应用时在对一些公共字段定义的一些困惑，还要从KubeVela的内置资源定义说起。
以内置组件`Webservice` 为例，他内置了：`labels`、`annotations`、`cmd`、`env` ... 这些常见的内置资源定义。
但是，在内置运维特征列表 也内置了： `Labels `、`Annotations`、`Cmd`、`Env`  ...

从上述的资源定义和使用的产生效果来说：`Webservice` 定义的资源和内置运维特征列表有很多资源时重复的，例如我定义一个Webservice我想要添加`annotations`，那么这个`annotations`可以定义在`Webservice` 里边也可以定义在`trait`里边。

那么用户在使用的时候难免会困惑，所有想跟大家探讨几个问题：
1、应该优先以哪个为准，社区建议的最佳实践是什么？
2、我在编写一些自定义组件是不是就定义该组件`特有`部分就行了，已经存在了的像： `Labels `、`Annotations`、`Cmd`、`Env`  这些资源定义我是否可以不用定义，而直接使用这些内置运维特征就行了，例如以：`openkruise` 的`CloneSet `为例：

下面是CloneSet 原始资源定义的yaml：
```yaml
apiVersion: apps.kruise.io/v1alpha1
kind: CloneSet
metadata:
  labels:
    app: sample
  name: sample-data
spec:
  replicas: 5
  #minReadySeconds: 10
  updateStrategy:
    type: InPlaceIfPossible
    inPlaceUpdateStrategy:
      gracePeriodSeconds: 10
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          volumeMounts:
            - name: data-vol
              mountPath: /usr/share/nginx/html
```
接下来我需要完成对CloneSet 的组件定义
在`CloneSet` 组件定义中一些常见的`labels`、`annotations`、`cmd`等我就直接复用内置运维特征列表的资源定义，而不用单独再去一定一次。
所以如下CloneSet的定义我不添加任何资源描述参数：

```cue
output: {
	type: "CloneSet"
	properties: {
		objects: [
			{
				// This creates a plain old Kubernetes namespace
				apiVersion: "apps.kruise.io/v1alpha1"
				kind:       "CloneSet"
				// We can use the parameter defined in parameter.cue like this.
				metadata: name: parameter.myparam
			},
		]
	}
}
```
对于特有`CloneSet`的`updateStrategy`的资源定义我在单独定义一份`traits`组件，这用通过组合的方式实现整体`CloneSet`的定义。
```cue
"update-strategy": {
	alias: ""
	annotations: {}
	attributes: {
		appliesToWorkloads: []
		conflictsWith: []
		definitionRef:   ""
		podDisruptive:   false
		workloadRefPath: ""
	}
	description: "kruise update strategy trait."
	labels: {}
	type: "trait"
}

template: {
	parameter: {
		//  +usage=用户指定重建升级还是原地升级，可选参数如下：
		// 	ReCreate: 控制器会删除旧 Pod 和它的 PVC，然后用新版本重新创建出来。
		//	InPlaceIfPossible: 控制器会优先尝试原地升级 Pod，如果不行再采用重建升级。具体参考下方阅读文档。
		//	InPlaceOnly: 控制器只允许采用原地升级。因此，用户只能修改上一条中的限制字段，如果尝试修改其他字段会被 Kruise 拒绝。
		podUpdatePolicy: *"InPlaceIfPossible" | "ReCreate" | "InPlaceOnly"
		// +usage=用户如果配置了 gracePeriodSeconds 这个字段，控制器在原地升级的过程中会先把 Pod status 改为 not-ready，然后等一段时间（gracePeriodSeconds），最后再去修改 Pod spec 中的镜像版本。
		// 这样，就为 endpoints-controller 这些控制器留出了充足的时间来将 Pod 从 endpoints 端点列表中去除。
		gracePeriodSeconds?: int
	}

	patch: {}
	outputs: strategy: {
		updateStrategy: {
			type: "RollingUpdate"
			rollingUpdate: {
				podUpdatePolicy: parameter.podUpdatePolicy
			}
			if parameter.gracePeriodSeconds != _|_ {
				inPlaceUpdateStrategy: {
					gracePeriodSeconds: parameter.gracePeriodSeconds
				}
			}
		}
	}
}

```
最后组合的Application效果：
```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: cloneset-app
spec:
  components:
    - name: cloneset-server
      type: CloneSet
   traits:
    - type: container-image
          properties:
            containers:
              - containerName: sidecar-nginx
                image: nginx-1.20
        - type: annotations
          properties:
            "description": "web application"
        - type: labels
          properties:
            "release": "stable"
        - type: update-strategy
        	properties:
        		podUpdatePolicy: InPlaceIfPossible
        		gracePeriodSeconds: 20
  policies:
    - name: target-default
      type: topology
      properties:
        # local 集群即 Kubevela 所在的集群
        clusters: ["local"]
        namespace: "default"
    - name: target-prod
      type: topology
      properties:
        clusters: ["local"]
        # 此命名空间需要在应用部署前完成创建
        namespace: "prod"
    - name: deploy-ha
      type: override
      properties:
        components:
          - type: webservice
            traits:
              - type: scaler
                properties:
                  replicas: 2
  workflow:
    steps:
      - name: deploy2default
        type: deploy
        properties:
          policies: ["target-default"]
      - name: manual-approval
        type: suspend
      - name: deploy2prod
        type: deploy
        properties:
          policies: ["target-prod", "deploy-ha"]
```
