### DISCUSSION TITLE
Filter out generated manifest before sending out for remote deployment

### DISCUSSION THREAD

**Discussion by nitagarwal** [kubevela/kubevela#6010] [Q&A] [answered]
We have a core-dev cluster which installs the Kubevela and Crossplane.
This core cluster is responsible for doing remote deployments to multiple cluster(For ex: dev-services, prod-services)

The application manifest is written in OAM and  has both service and crossplane components. So, the generated manifest has both K8s and Crossplane manifests. 

We would like to use core-dev cluster for deploying the crossplane resources to AWS accounts. And filter out the crossplane manifests before sending out to services cluster. Otherwise crossplane is not installed there and it will trigger a bunch of failures there. 

Is there a way I can achieve this?  

We evaluate the approach of separating out application into service / infrastructure. But it will be a confusing experience and we would like to abstract our customers from what is being generated as K8s manifest vs cross plane manifest.

**Comment by Somefive** [comment, marked as answer]
Yes. You can declare your service and crossplane components in your application and use "override" policy with "topology" policy to select which component should be delivered to the cluster. For example,

```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: example
spec:
  components:
  - name: services
    ...
  - name: crossplane
    ...
  policies:
  - type: topology
    name: core-dev-cluster
    properties:
      clusters: ["core-dev"]
  - type: override
    name: core-dev-override
    properties:
      selector: ["crossplane"]
  - type: topology
    name: service-cluster
    properties:
      clusters: ["services"]
  - type: override
    name: service-override
    properties:
      selector: ["services"]
  workflow:
    steps:
    - type: deploy
      name: deploy-crossplane
      properties:
        policies: ["core-dev-cluster", "core-dev-override"]
    - type: deploy
      name: deploy-services
      properties:
        policies: ["service-cluster", "service-override"]
```
