### DISCUSSION TITLE
patch workflow not worked

### DISCUSSION THREAD

**Discussion by 11061134** [kubevela/kubevela#6089] [Q&A] [answered]
workflow:
```cue
import (
	"vela/op"
)

"update-hotupgrade-annotation": {
	type: "workflow-step"
	annotations: {}
	labels: {}
	description: "Read ex hot upgrade annotation from old version cloneset for your workflow steps"
}
template: {
	output: {
		load: op.#Load & {}
		app:  op.#ApplyComonent & {
			value: load.value[parameter.name]

			patch: {
				workload: {
					// +patchStrategy=retainKeys
					spec: template: metadata: annotations: {

						"hotupgrade-work-annotations": "c1"
					}
				}

			}
		}

	}

	parameter: {
		// +usage=Specify the name of the secret
		name: string
		// +usage=Specify the namespace of the secret
		namespace?: string
	}
}
``` 
application:
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: hotupgrade-test1
spec:
  components:
    - name: hotupgrade-test1
      properties:
        terminationGracePeriodSeconds: 1000
        containers:
          - image: busybox:latest
            name: hotupgrade-test
      type: cloneset
      traits:
      - properties:
            replicas: 1
        type: replicas
      - properties:
          nodeSelector:
          - key: test
            operator: In
            values:
            - test
        type: scheduling


  workflow:
    steps:
      - name: update-hotupgrade-annotation
        type: update-hotupgrade-annotation
        properties:
          name: hotupgrade-test1
      - name: apply-application
        type: apply-application
```

**Comment by Somefive** [comment, marked as answer]
1. ApplyComonent  -> ApplyComponent
2. WorkflowStepDefinition does not need "output".
3. apply-application step is not needed

Example app:
```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: hotupgrade-test1
spec:
  components:
    - name: hotupgrade-test1
      properties:
        image: busybox:latest
      type: webservice
      traits:
        - properties:
            replicas: 1
          type: scaler
  workflow:
    steps:
      - name: update-hotupgrade-annotation
        type: update-hotupgrade-annotation
        properties:
          name: hotupgrade-test1
```
Example WorkflowStepDefinition
```cue
import (
	"vela/op"
)

"update-hotupgrade-annotation": {
	type: "workflow-step"
	annotations: {}
	labels: {}
	description: "Read ex hot upgrade annotation from old version cloneset for your workflow steps"
}
template: {
		load: op.#Load & {}
		app:  op.#ApplyComponent & {
			value: load.value[parameter.name]

			patch: {
				workload: {
					// +patchStrategy=retainKeys
					spec: template: metadata: annotations: {
						"hotupgrade-work-annotations": "c1"
					}
				}

			}
		}

	parameter: {
		// +usage=Specify the name of the secret
		name: string
		// +usage=Specify the namespace of the secret
		namespace?: string
	}
}
```
