### DISCUSSION TITLE
Can the read-object workflow-step correctly read and decode secrets of type Opaque?

### DISCUSSION THREAD

**Discussion by imzhangsiwei** [kubevela/kubevela#6230] [Q&A]
When using kubevela to apply Terraform cloud resources, the returned values are saved in the secret specified by writeConnectionSecretToRef. 
My question is: when using the read-object step in a workflow to read the values from this secret, can outputs and inputs properly decode secrets of type Opaque?
The following YAML is an example of applying two cloud resources. The second resource needs to retrieve the returned value id from the first resource, which is saved in a secret.

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: xxxx
spec:
  components:
    - name: abc 
      type: alibaba-abc
      properties:
        is_internal: true
        providerRef:
          name: abc-provider
          namespace: default
        writeConnectionSecretToRef:
          name: output-abc
    - name: hello
      type: alibaba-zzzz
      properties:
        providerRef:
          name: abc-provider
          namespace: default
        writeConnectionSecretToRef:
          name: output-zzz
  workflow:
    steps:
      - name: deploy-abc
        type: apply-component
        properties:
          component: abc
      - name: read-output-abc
        type: read-object
        dependsOn:
          - deploy-abc
        outputs:
          - name: id-of-output-abc
            valueFrom: output.value.data.id
        properties:
          apiVersion: v1
          kind: Secret
          name: output-abc
          cluster: local
      - name: deploy-hello
        type: apply-component
        dependsOn:
          - read-output-abc
        properties:
          component: hello
        inputs:
          - from: id-of-output-abc
            parameterKey: properties.id
```
