### DISCUSSION TITLE
Override application template from configmap

### DISCUSSION THREAD

**Discussion by geowalrus4gh** [kubevela/kubevela#6298] [General]
I have a workflow as below. In the worflow it creates an application using apply-app step. Given step loads the application template from the configMap. How to overide/patch any values in the template with that of new one in the step ?

```
apiVersion: core.oam.dev/v1alpha1
kind: WorkflowRun
metadata:
  name: apply-applications
  namespace: default
  annotations:
    workflowrun.oam.dev/debug: "true"
spec:
  workflowSpec:
    steps:
      - name: apply-app1
        type: apply-app
        properties:
          ref:
            name: my-app
            key: application
            type: configMap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-app
  namespace: default
data:
  application: |
    apiVersion: core.oam.dev/v1beta1
    kind: Application
    metadata:
      name: webservice-app2
    spec:
      components:
        - name: express-server2
          type: webservice
          properties:
            image: crccheck/hello-world
            ports:
              - port: 8000
        
```
