### DISCUSSION TITLE
Apply a trait parameters on all defined images

### DISCUSSION THREAD

**Discussion by nelsg** [kubevela/kubevela#6478] [General]
From this example: https://kubevela.io/docs/platform-engineers/cue/patch-strategy/#patchkey
Is there a way to apply defined environments variables to all defined images ?

I use this application definition (I developped my own webservice with multiple images):

````yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: webservice-app
spec:
  components:
    - name: express-server
      type: webservice
      properties:
        images:
        - name: crccheck/hello-world
        - name: crccheck/hello-world2
      traits:
        - type: myenv
          properties:
            env:
              NEW: new
````

But environment variables are only applyed on first image
