### DISCUSSION TITLE
Application 更新未同步到 Deployment

### DISCUSSION THREAD

**Discussion by runkecheng** [kubevela/kubevela#6683] [Q&A]
## 问题描述
我正在尝试将一些之前通过自定义资源管理的 Deployment 和 Service 迁移到 OAM Application。我编写了一个 adopt template，将集群中现存的 Deployment 和 Service 转换为 OAM Application。我自定义了一个 component，其中包含一些参数，用于控制 Deployment 等资源。

当我首次应用转换后的 OAM Application 时，参数能够正确传递到 Deployment。但是，在 OAM Application 创建之后，对其进行任何更新操作，都无法将更改传递给 Deployment。尽管 Deployment 上存在相关的 oam label，但 revision 始终保持在 v1。

## 疑问
- 我的用法是否存在错误？
- 如何才能使 OAM Application 的更新能够同步到 Deployment？

以下是我转换出的 Application：
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  creationTimestamp: null
  labels:
    app: foo
    group: ft
    version: base
    app.oam.dev/adopt: native
  name: foo-base
  namespace: sqb
spec:
  components:
  - name: foo-base
    properties:
...
      deployment:
        ...
        replicas: 1
        resource:
          limits:
            cpu: 0.5
            memory: 512
          requests:
            cpu: 0.1
            memory: 128
...
      service:
        ports:
        - port: 80
          protocol: http
          targetPort: 8080
    type: stateless
  policies:
  - name: topology-local
    properties:
      clusters:
      - local
    type: topology
  - name: take-over
    properties:
      rules:
      - selector:
          componentNames:
          - foo-base
    type: take-over
  - name: garbage-collect
    properties:
      rules:
      - selector:
          resourceTypes:
          - Deployment
          - Service
        strategy: never
    type: garbage-collect
   - name: apply-once
      properties:
        rules:
        - selector:
            resourceTypes:
            - Deployment
            - Service
    type: apply-once
  workflow:
    steps:
    - name: deploy
      subSteps:
      - name: xxx-vpc-k8s
        properties:
          policies:
          - topology-local
        type: deploy
      type: step-group
```
