### DISCUSSION TITLE
[KubeVela 用户体验月][Example] zhouzhengxi

### DISCUSSION THREAD

**Discussion by zzxwill** [kubevela/kubevela#816] [Show and tell]
# 1. 完成 1 个 workload/trait 扩展开发
完成一个 Trait 开发，请见 PR https://github.com/oam-dev/catalog/pull/65，具体说明和使用方法，请参加 README.md。

# 2. 完成 3 个 Appfile
### vela.yaml
```
name: _app-name_

services:
  _service-name_:
    # If `build` section exists, this field will be used as the name to build image. Otherwise, KubeVela will try to pull the image with given name directly.
    image: oamdev/testapp:v1

    build:
      docker:
        file: _Dockerfile_path_ # relative path is supported, e.g. "./Dockerfile"
        context: _build_context_path_ # relative path is supported, e.g. "."

      push:
        local: kind # optionally push to local KinD cluster instead of remote registry

    type: webservice (default) | worker | task

    # detailed configurations of workload
    ... properties of the specified workload  ...

    _trait_1_:
      # properties of trait 1

    _trait_2_:
      # properties of trait 2

    ... more traits and their properties ...

  _another_service_name_: # more services can be defined
    ...
```

### 部署和管理应用
通过 `vela up` 启动，通过 xxx 命令和工具，检查应用状态，如下：

```
xxxxxxx

```

通过 xxx 命令和工具，检查 trait xxx 状态，发现 xxx。

```
xxxxxxx

```

## 3) 该 Appfile 实现 xx 功能

# 3. 反馈
- xxx 使用很方便
...

- xxx 相关文档不清晰
...

建议 xxx

- 不知道怎么执行/查看 xxx
xxx 

建议 xxx
