### DISCUSSION TITLE
Data-binding from cloud resource to business workloads in Appfile.

### DISCUSSION THREAD

**Discussion by zzxwill** [kubevela/kubevela#874] [Show and tell]
By discussion with Ryan and Wonderflow, here is another sample mechanism for data-binding from **cloud resource** to business workloads in Appfile.

## Assumptions
Here are some assumptions.

- Cloud resources are deployed by Terraform
With this assumption, cloud resource can be easily output to config (`vela config` object) and Secret.

```
✗ terraform output
DB_HOST = "rm-2zew32nd4coz64o01.mysql.rds.aliyuncs.com"
DB_PASSWORD = "xxxxxxx"
db_name = "poc"
db_port = "3306"
db_user_name = "oam"
oss_bucket_address = "vela-website.oss-cn-beijing.aliyuncs.com"
```
- Cloud resource data are consumed by `env` (`spec.tamplate.containers[i].env`)

- Keys in config/Secret can match the keys required by `spec.tamplate.containers[i].env`

As in cloud resource WorkloadDefinition, it's easy to change the output keys, so the output keys can be changed to the same to those of application.

RDS WorkloadDefinition:
```
apiVersion: core.oam.dev/v1alpha2
kind: WorkloadDefinition
metadata:
  name: aliyun-rds
spec:
  extension:
    template: |
      output: {
      	{
      		module: {
      			rds: {
      				source:           "terraform-alicloud-modules/rds/alicloud"
      				engine:           parameter.engine
      			}
      		}
      		output: {
      			DB_HOST: {
                            value: "${module.rds.this_db_instance_connection_string}"
                         }
                         DB_USER: {
                             value: "${module.rds.this_db_database_account}"
                         }
```

Application environment requirement:
```
from flask import Flask
from flask import render_template
import os
import sys


application = Flask(__name__)

host = os.getenv("DB_HOST")
user = os.getenv("DB_USER")
```

## Data binding

In this Appfile, each cloud resource `sample-db` and `sample-oss` will respectively create a config besides on `terraform out` with config name `sample-db` and `sample-oss`, which will result in creation of Secret `sample-db` and `sample-oss`.

```
name: hello

services:
  express-server:
    type: deployment
    image: zzxwill/database-flask-web-application:v0.2
    ports: 80
    configRef: 
      - name: "sample-db"
        keys: 
          - "db_name"
          - "db_host" 
      - name: "sample-oss"
        keys: 
          - "bucket_name"

  sample-db:
    type: aliyun-rds
    engine: "MySQL"
    engine_version: "8.0"
    instance_type: "rds.mysql.c1.large"
    instance_name: "poc"
    account_name: "oam"
    password: "Xyfe83jfewGGf"

  sample-oss:
    type: aliyun-oss
    bucket: "oam-website"
```

In business WorkloadDefinition, add a field `configRef` to ask for cloud resource config requirements and for each resource, which keys are needed.

```
parameter: {
	// +usage=Referred config
	configRef?: [...{
		// +usage=Referred config name, ie, cloud resource name
		name: string
		// +usage=Key from KubeVela config
		keys: [...string]
	}]
```

In this Appfile, business workload `express-server` asks for output from `sample-db` and `sample-oss` with specified keys listed.

```
name: hello

services:
  express-server:
    type: deployment
    image: zzxwill/database-flask-web-application:v0.2
    ports: 80
    configRef: 
      - name: "sample-db"
        keys: 
          - "DB_NAME"
          - "DB_HOST" 
      - name: "sample-oss"
        keys: 
          - "bucket_name"

  sample-db:
    type: aliyun-rds
    engine: "MySQL"
    engine_version: "8.0"
    instance_type: "rds.mysql.c1.large"
    instance_name: "poc"
    account_name: "oam"
    password: "Xyfe83jfewGGf"

  sample-oss:
    type: aliyun-oss
    bucket: "oam-website"
```

In the business WorkloadDefnition, cue will assemble the required `env`. (issue [two nested loops output doesn't meet expectation](https://github.com/cuelang/cue/discussions))
```
output: {
	apiVersion: "apps/v1"
	kind:       "Deployment"
	spec: {

			spec: {
				containers: [{
					
					if parameter["env"] != _|_ {
						envValue
					}
					if parameter["configRef"] != _|_ {
						envValueFrom
					}
					if parameter["env"] != _|_ && parameter["configRef"] != _|_ {
						envValue | envValueFrom
					}
				}]
		}
		}
	}
}

envValue: {
	if parameter["env"] != _|_ {
		env:
		[ for e in parameter.env {
			name:  e.name
			value: e.value
		}]
	}
}

envValueFrom: {
	if parameter["configRef"] != _|_ {
		env:
		[ for c in parameter.configRef {
			[ for k in c.keys {
				name: k
				valueFrom: {
					secretKeyRef: {
						name: c.name
						key:  k
					}
				}
			},
			]
		}]
	}
}

parameter: {

	// +usage=Referred config
	configRef?: [...{
		// +usage=Referred config name, ie, cloud resource name
		name: string
		// +usage=Key from KubeVela config
		keys: [...string]
	}]
}
```

## Pros and Cons
Pros:
- KubeVela core won't change
Only need to apply cloud resources and generate config/secret from the output.

Cons:
- Heavily depend on three assumptions
- Only focus on data from Cloud resource.

/cc @ryanzhang-oss @wonderflow
