### ISSUE TITLE
[Feature] Consider built-in components w/o template module - so we can reference a workload as template

### ISSUE THREAD

**Issue by resouer** [kubevela/kubevela#1100]
**Is your feature request related to a problem? Please describe.**

This is a way that `Rollout` can work with raw workload instance, it will be helpful to demos and onboarding users. 

**Describe the solution you'd like**

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
    rollout.kubevela.io: true # the flag
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```

Then it will begin to rollout with immutable instances!

**What happened**

Because we have several built-in `ComponentDefinition`, let's say:

```yaml
apiVersion: core.oam.dev/v1alpha3
kind: ComponentDefinition
metadata:
  name: built-in-deployment # reserved name
spec:
  workload:
    definition:
      apiVersion: apps/v1
      kind: Deployment
    characteristics:
      replicable: true
      podspecable: true
      revisionable: true # means it will be revisioned
  schematic: {} # empty means it will reference a raw resource as template, no component package needed
```

And, we also have a adaptor (webhook?). It will convert (create, update, delete) any Deployment with `rollout.kubevela.io: true` to an `Application` with built-in `ComponentDefinition`, e.g.

```yaml
apiVersion: core.oam.dev/v1alpha2
kind: Application
metadata:
  name: nginx-deployment
spec:
  components:
    - name: nginx-deployment
      type: built-in-deployment
      settings:
        metadata: # name and `rollout` label should be removed
          labels:
            app: nginx
        spec:
          replicas: 3
          selector:
            matchLabels:
              app: nginx
          template:
            metadata:
              labels:
                app: nginx
            spec:
              containers:
              - name: nginx
                image: nginx:1.14.2
                ports:
                - containerPort: 80
```

Then `Application` controller should be able to render such `module: {}` app. The reason I want to reuse `ComponentDefinition` is it can still be used to control the behavior of the workload.

And when user attach a `Rollout` to it:

```yaml
apiVersion: core.oam.dev/v1alpha1
kind: RolloutTrait # we really need to rename it to Rollout ...
metadata:
  name: canary
spec:
  application: nginx-deployment # name of the application
  ... # cool rollout spec
```
The hook will add rollout strategy to referenced application:

```yaml
apiVersion: core.oam.dev/v1alpha2
kind: Application
metadata:
  name: nginx-deployment
spec:
  components:
    - name: nginx-deployment
      type: vela-deployment 
      ...
  rollout:
     ... # cool rollout spec
```

After this,  it should be able to rollout following defined strategy.

/cc @wonderflow @ryanzhang-oss not sure if this works and any better idea.

**Describe alternatives you've considered**

**Additional context**

**Comment by charles-woshicai** [comment]
So it will require a `WebhookMutation` to convert `raw workload` like `deployment` with specific label to `Application` when APIServer receving a request?

**Comment by wonderflow** [comment]
@charles-woshicai We don't need a webhook. We can use to tool to convert.

```
kubectl vela convert --deployment=nginx-deployment
```

Then we automatically generate the Application:

```
apiVersion: core.oam.dev/v1alpha2
kind: Application
metadata:
  name: nginx-deployment
spec:
  components:
    - name: nginx-deployment
      type: built-in-deployment
      settings:
        metadata: # name and `rollout` label should be removed
          labels:
            app: nginx
        spec:
          replicas: 3
          selector:
            matchLabels:
              app: nginx
          template:
            metadata:
              labels:
                app: nginx
            spec:
              containers:
              - name: nginx
                image: nginx:1.14.2
                ports:
                - containerPort: 80
```

And we can add trait for it and patch to the orignal Deployment.
