### ISSUE TITLE
[Feature]support import third-party package for WorkloadDefinition

### ISSUE THREAD

**Issue by Ghostbaby** [kubevela/kubevela#1195]
**Describe the bug**
If a third-party package is imported into the cue template, the program will report an error:
```shell
 package "k8s.io/api/core/v1" not found (and 1 more errors)
```

**To Reproduce**
```go
package kube

import (
	"k8s.io/api/core/v1"
)

output: {
	"apiVersion": "apps/v1"
	"kind":       "Deployment"
	"metadata": {
		"name":      parameter.name
		"namespace": parameter.namespace
	}
	"spec": {
		"replicas": parameter.replicas
		"selector":
			"matchLabels":
				"app": parameter.name
		"template": {
			"metadata": {
				"annotations": {
					"log-injector/format": "json"
				}
				"labels": {
					"app":     parameter.name
					"version": parameter.version
				}
			}
			"spec": {
				if parameter.containers != _|_ {
					"containers": [
						for _, v in parameter.containers {
							v
						},
					]
				}
				if parameter.initContainers != _|_ {
					"initContainers": [
						for _, v in parameter.initContainers {
							v
						},
					]
				}
				if parameter.nodeSelector != _|_ {
					"nodeSelector": {
						for k, v in parameter.nodeSelector {
							k: v
						}
					}
				}
				if parameter.tolerations != _|_ {
					tolerations: [
						for k, v in parameter.tolerations {
							effect:   "NoSchedule"
							key:      k
							operator: "Equal"
							value:    v
						}]
				}
				if parameter.volumes != _|_ {
					"volumes": [
						for _, v in parameter.volumes {
							if v.type != _|_ && v.type == "pvc" {
								{
									"name": v.name
									"persistentVolumeClaim": {
										"claimName": v.name
									}
								}
							}
							if v.type != _|_ && v.type == "hostPath" {
								{
									"hostPath": {
										"path": v.path
										"type": ""
									}
									"name": v.name
								}
							}
							if v.type != _|_ && v.type == "configmap" && v.key != "" && v.path != "" && v.subName != "" {
								{
									"configMap": {
										"defaultMode": 420
										"items": [
											{
												"key":  v.key
												"mode": 511
												"path": v.path
											},
										]
										"name": v.subName
									}
									"name": v.name
								}
							}
							if v.type != _|_ && v.type == "configmap" {
								{
									"configMap": {
										"defaultMode": 420
										"name":        v.subName
									}
									"name": v.name
								}
							}
						},
					]
				}
			}
		}
	}
}

parameter: {
	containers: [...v1.#Container]
	initContainers: [...v1.#Container]
	replicas:  *3 | int
	name:      *"ghostbaby" | string
	namespace: *"default" | string
	version:   *"v1" | string
	tolerations?: [string]:  string
	nodeSelector?: [string]: string
	volumes?: [...#volumes]
}

#volumes: {
	type:     "pvc" | "configmap" | "secret" | "hostPath" | "ephemeral"
	name:     string
	chown?:   *777 | int
	key?:     string
	path?:    string
	subName?: string
}

parameter: {
	replicas: 4
	name:     "shein-test"
	version:  "v1"
	tolerations: {
		"a": "b"
	}
	nodeSelector: {
		"c": "d"
	}
	volumes: [
		{
			type:    "configmap"
			name:    "test"
			key:     "abc"
			path:    "def"
			subName: "123"
		},
	]
	containers: [
		{
			name:  "ghostbaby-containers"
			image: "nginx:1.9.1"
			env: [{
				name:  "iamfirstenv"
				value: "test"
			}]
			resources: {
				requests: {
					cpu:              "500m"
					ephemeralStorage: "100Mi"
					memory:           "512Mi"
				}
			}
			volumeMounts: [
				{
					name:      "test"
					mountPath: "/log/test2"
				},
			]
		},
	]
	initContainers: [
		{
			name:  "ghostbaby-init-containers"
			image: "nginx:1.9.1"
			env: [{
				name:  "iaminit"
				value: "test"
			}]
			resources: {
				requests: {
					cpu:              "500m"
					ephemeralStorage: "100Mi"
					memory:           "512Mi"
				}
			}
			volumeMounts: [
				{
					name:      "test"
					mountPath: "/log/test2"
				},
			]
		},
	]
}

```
**Expected behavior**

**Screenshots**

**Cluster information**

**Additional context**

**Comment by wonderflow** [comment]
```
apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
metadata:
  annotations:
    definition.oam.dev/description: "Configures replicas for your service."
  name: scaler
  namespace: {{.Values.systemDefinitionNamespace}}
spec:
  appliesToWorkloads:
    - webservice
    - worker
  definitionRef:
    name: manualscalertraits.core.oam.dev
  workloadRefPath: spec.workloadRef
  schematic:
    cue:
      imports:
      - name: a.cue
        url: "https://xxxx.a.cue"
      template: |
        outputs: scaler: {
        	apiVersion: "core.oam.dev/v1alpha2"
        	kind:       "ManualScalerTrait"
        	spec: {
        		replicaCount: parameter.replicas
        	}
        }
        parameter: {
        	//+short=r
        	//+usage=Replicas of the workload
        	replicas: *1 | int
        }
        
```
