### ISSUE TITLE
[Feature]  Best practices for middleware products using in Vela

### ISSUE THREAD

**Issue by LeoLiuYan** [kubevela/kubevela#1199]
**Is your feature request related to a problem? Please describe.**

As the title said,   what's the best practices for middleware products like `es`, `mq`, `kafka` and so on when we used in vela?
Should we delivery those middleware products as a component or another application?  As we know,  middleware products general shared by multiple stateless application.

**Describe the solution you'd like**
Some discussions or docs. 

**Describe alternatives you've considered**

**Additional context**

**Comment by shikanon** [comment]
I think the middleware or db can be used as a general traits statement by other components, they can come from cloud or self-build.

**Comment by mosesyou** [comment]
> I think the middleware or db can be used as a general traits statement by other components, they can come from cloud or self-build.

In another situation, we hope it can create a new middleware for the application. And we can define that how to create a new middleware.

**Comment by shikanon** [comment]
> > I think the middleware or db can be used as a general traits statement by other components, they can come from cloud or self-build.
> 
> In another situation, we hope it can create a new middleware for the application. And we can define that how to create a new middleware.

If you want to create a new application, you can think of it as part of micro-services, this like app A to depends on app B. The middleware mean it is a public services which is in charge of the infrastructure team.

**Comment by wonderflow** [comment]
We suggest the middleware products which will be shared by different applications be deployed in a standalone application.

**Comment by LeoLiuYan** [comment]
The middleware products delivery as a  standalone application may be fine.

Some ideas come out of #1128:

1. The middleware application should have multiple output. Think that app1 and app2 share same rds, and they have different username and password.

```yaml
apiVersion: core.oam.dev/v1alpha2
kind: Application
metadata:
  name: producer
  labels:
    role: producer
spec:
  components:
    - name: mydb
      type: rds
      settings:
        region: "us-east-1"
        version: "1.9.0"
        outputSecrets:
          // Should have multiple output. 
          - name: output1
            db: test1
            username: test1
          - name: output2
            db: test2
            username: test2
```

2. The stateless application may include a component which type is `middlewareClaim`. 

```yaml
apiVersion: core.oam.dev/v1alpha2
kind: Application
metadata:
  name: consumer-1
  labels:
    role: consumer
spec:
  components:
    - name: myweb
      type: webserver
      settings:
        image: "nginx"
        secretRef: database.output1  // Ref to `database` component
    - name: database
      type: middlewareClaim  // New type
      claimRef: producer.outputSecrets
     

apiVersion: core.oam.dev/v1alpha2
kind: Application
metadata:
  name: consumer-2
  labels:
    role: consumer
spec:
  components:
    - name: myweb
      type: webserver
      settings:
        image: "nginx"
        secretRef: database.outpu2  // Ref to `database` component
    - name: database
      type: middlewareClaim  // New type
      claimRef: producer.outputSecrets
```
