### ISSUE TITLE
How to make multipe components (web-services) share an ingress instance?

### ISSUE THREAD

**Issue by ghostbody** [kubevela/kubevela#1378]
Suppose I have multiple web-service components, and many of them need a route trait to expose the ports.

```yaml
name: my-web-app

services:
  web-service1:
    type: webservice
    image: oamdev/testapp1:v1
    cmd: ["node", "server.js"]
    port: 8080
    cpu: "0.1"
    route:
      domain: example.com
      issuer: tls
      rules:
        - path: /web-service1
          rewriteTarget: /

  web-service2:
    type: webservice
    image: oamdev/testapp2:v1
    cmd: ["node", "server.js"]
    port: 8080
    cpu: "0.1"
    route:
      domain: example.com
      issuer: tls
      rules:
        - path: /web-service2
          rewriteTarget: /

```

It seems like kubevela will create as many ingress instance as services. How can I acheive one ingress instance which is shared by all these components?
