### ISSUE TITLE
validating expand resources in webhook by dry-run in kube apiserver

### ISSUE THREAD

**Issue by cnbailian** [kubevela/kubevela#1688]
**Describe the bug**
The error message is unsharp when TraitDefinition template is wrong

**Expected behavior**
Displayed in application events

**Additional context**
TraitDefinition.yaml
```yaml
apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  annotations:
    definition.oam.dev/description: "TraitDefinition"
  name: wrong
spec:
  appliesToWorkloads:
    - worker
  podDisruptive: false
  schematic:
    cue:
      template: |
        // trait template can have multiple outputs in one trait
        outputs: service: {
        	apiVersion: "v1"
        	kind:       "Service"
        	metadata:
        		name: context.name
        	spec: {
        		selector: {
        			"app.oam.dev/component": context.name
        		}
        		port: [
        			for k, v in parameter.http {
        				port:       v
        				targetPort: v
        			},
        		]
        	}
        }

        parameter: {
        	// +usage=Specify the mapping relationship between the http path and the workload port
        	http: [string]: int
        }


```
`ports` => `port`

Application.yaml
```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: nginx
spec:
  components:
    - name: nginx
      type: worker
      properties:
        image: "nginx"
      traits:
        - type: wrong
          properties:
            domain: basic.example.com
            http:
              "/": 80

```
