### ISSUE TITLE
[Feature] Add Application Version

### ISSUE THREAD

**Issue by kinsolee** [kubevela/kubevela#1786]
**Is your feature request related to a problem? Please describe.**

Now kubevela uses incremental number to name application version, e.g, v1, v2,v3. But it is irrelevant to application's version (releasing new version of the application, usually with a new release tag and image tag). It's just snapshots or deployment history of the application. 

There is no way to know which application version a revision is related to. When it comes to traffic management or rollout, it's hard to tell which release version of the application is running on the component with a revision named like 'v123', and the platform users are not sure which revision to choose.

We need a way to differentiate version and revision. I think different versions of application can exist at the same time, but different revisions of the same version of an application don't. If we use Kubevela to build an application management platform, platform users care more about the application version rather than revision, so there should be a way to list/show and set the application version (might be shown on UI).

Dependent components of an application like mysql, redis should be deployed according to application version or be singleton to the application, it depends on the user's decision. I am not sure if the introduction of `Workflow` can solve this.

**Describe the solution you'd like**

There should be an `ApplicationVersion` crd describing a specific version of an application. Just like `ApplicationRevision`, it stores the definitions, components and application objects, but they are of the last revision.

```yaml
apiVersion: core.oam.dev/v1beta1
kind: ApplicationVersion
metadata:
  name: hello-world-v1-0-1
  namespace: default
  labels:
    app.oam.dev/name: hello-world
    app.oam.dev/version: v1.0.1
spec:
  application: xxx
  components: xxx
  componentDefinitions: xxx
  traitDefinitions: xxx
```

User can declare version of the application at the annotations of Application:
```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: hello-world
  namespace: default
  annotations:
     app.oam.dev/version: v1.0.1
spec:
  components:
    - name: express-server
      type: webservice
```
When version name is declared by user, `application_controller` is responsible for syncing the latest revision of `ApplicationVersion`.
The name of ApplicationRevision should include the name of ApplicationVersion:
```yaml
metadata:
  name: hello-world-v1-0-1-1
kind: ApplicationRevision
  spec:
    ...
```

`ApplicationVersion` can be referenced by `AppRollout` or `AppDeployment`:
```yaml
apiVersion: core.oam.dev/v1beta1
kind: AppRollout
metadata:
  name: rolling-example
spec:
  sourceAppVersionName: hello-world-v1.0.1
  targetAppVersionName: hello-world-v1.0.2
  ...
```
```yaml
apiVersion: core.oam.dev/v1beta1
kind: AppDeployment
metadata:
  name: first-vela-app-deployment
spec:
  appRevisions:
    - versionName: hello-world-v1.0.1
      placement:
        - distribution:
            replicas: 2
    - versionName: hello-world-v1.0.2
      placement:
        - distribution:
            replicas: 1
```
@BinaryHB0916
