### ISSUE TITLE
Bug for vela dry-run when the components not in the vela-system namespace

### ISSUE THREAD

**Issue by shikanon** [kubevela/kubevela#1795]
**Describe the bug**

I create a components for the default namespace and  use for dry-run it raise error ` workloaddefinitions.core.oam.dev "xxx" not found`. And when I change it to the `vela-system` namespace, It can run well.

**To Reproduce**

1. create a cumstom components
2. apply it to the default namespace
3. the error occurred

![image](https://user-images.githubusercontent.com/7250620/121987095-5b132000-cdca-11eb-8eb2-90e44757f967.png)

**Expected behavior**

It run for `default` namespace not `vela-system` if the name not set namespace.

**Screenshots**

![image](https://user-images.githubusercontent.com/7250620/121986967-2010ec80-cdca-11eb-9ac5-8b41aee48e99.png)

**Cluster information**

```bash
$ vela version
Version: refs/tags/v1.0.5
GitRevision: git-53b49ac
GolangVersion: go1.14.15
```

**Additional context**

**Comment by shikanon** [comment]
the application yaml:
```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: abtestdata
  namespace: cs
spec:
  components:
    - name: abtestdata-component
      type: micro-service
      properties:
        image: xxxx
      traits:
      - type: ingressgateway
        properties:
          gateway: "internal-gateway"
          hosts: ["xxxxx"]
          exportport: 8000
```

**Comment by wonderflow** [comment]
Yes, by default, vela dry-run will find definition from vela-system, but I think we should find both the specified namespace and `vela-system`. So if user not specify namespace, we should search both `default` and `vela-system`

**Comment by shikanon** [comment]
@wonderflow I think the components whether affect the creation of application. When we create a application, we can not set the components namespace (or it can ?). If like this, can we delete namespace for the components CRD?

**Comment by wonderflow** [comment]
yes, in dry-run , the namespace of componentDefinition should be ignored.

**Comment by shikanon** [comment]
@wonderflow And if only not use in `dry-run`, how to dealing the different namespace of `componentDefinition`  in the `Application` in the vela-core? 
For example, I have a `componentDefinition`  in namespace of `test1` and namespace of `test2`. The `Application` how to set to use  specified namespace.

**Comment by wonderflow** [comment]
The `Application` should use the definition in the same namespace.

**Comment by shikanon** [comment]
@wonderflow yes, and when Application follow the component namespace, the application and component is coupled together if not use in the `vela-system`. In this way he loses the concept of being an application. I think the component should like the CRD,  it is a resource and not include the namespace scope.

**Comment by wonderflow** [comment]
@shikanon Why not use the `vela-system`?

**Comment by shikanon** [comment]
@wonderflow Because the `vela-system` not for the default if we not set namespace for namespace, people will feel troubled for it. Besides we have component with namespace scope, and the componet definition also have namespace. Do this like set all CRD for namespace scope and some common CRD for special namespace.

**Comment by wonderflow** [comment]
Here's the reason why we change the CRD scope: https://github.com/oam-dev/kubevela/issues/918

If component-def don't have namespace, then the application shouldn't have namespace, then they can match.

**Comment by shikanon** [comment]
@wonderflow  Yes, we should have system level definition and user level definition in application and component but not component definition. Is need to make the component definition to the normal user? maybe is not. We can control normal users to prohibit to publish and update components definition on RBAC. They are only use the application combine of components and traits. The components and traits of user created is namespace-scoped and the components definition is system level. And custom component definition can be more like CRD abstraction.
we can set the yaml like this:
```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: jupyterhub
  namespace: test
spec:
  components:
    - name: jupyterhub-component
      type: testcomponent
      properties:
        image: jupyterhub/jupyterhub-demo:1.4
```
that will create a Application `jupyterhub` and a components `jupyterhub-component` in the namespace `test`, but the component type of `testcomponent` can be a system level object.
