### ISSUE TITLE
[Feature] Add support for a trait to patch to any outputs defined before it and not just the output defined by the corresponding component.

### ISSUE THREAD

**Issue by YourTechBud** [kubevela/kubevela#1851]
**Is your feature request related to a problem? Please describe.**
Currently, traits can patch the workload of the corresponding components only. It is not possible for traits to patch workloads of other traits. This tends to make a trait overly complex when its targeting a fairly complex resource. For e.g. in Istio, a `DestinationRule` is responsible for several related activities like loadbalancing and circuit breaking. However, I would like to expose these as two separate traits. So now I'm in a scenario where a two traits are attempting to work on a single resource which isn't the one described by the corresponding component.

**Describe the solution you'd like**

There should be a field in a CUE part of the trait which indicated which resource is it trying to patch. So a trait can patch the resource defined by the component or any other `outputs` which were defined before it.

**Describe alternatives you've considered**

The only way to solve this right now is to make a separate component for `DestinationRule` all together and attach traits to that instead which doesn't really sound like a good idea.

**Additional context**

**Comment by wonderflow** [comment]
Can you give some yaml example about this case?

**Comment by YourTechBud** [comment]
Lets take the example of deploying a normal workload in a service mesh like Istio. Ideally the workload component need to be changed if the service was deployed in a service mesh or not. Its just a k8s deployment after all. 

The OAM Application may look something like this:

```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: sample-service
spec:
  components:
    - name: myapp
      type: webservice
      properties:
        image: myregistry.io/projectid/sample-service
        port: 8000
      traits:
        - type: readiness-probes
          properties:
            http:
              path: /health
              port: 8090
              interval: 20s
        # These are the traits of concern
        - type: service-mesh
          properties:
            enabled: true
        - type: mesh-routes
          properties:
            routes:
               - name: "api-routes"
                 match:
                   - uri:
                       prefix: "/v1/api"
        - type: loadbalancing-policy
          properties:
            policy: ROUND_ROBIN
        - type: circuit-breaking
          properties:
            maxConnections: 100
            connectTimeout: 30ms
            tcpKeepalive:
              time: 7200s
              interval: 75s
```

```yaml
# This resource is created by the service mesh trait
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: reviews-route
spec:
  hosts:
  - myapp
  http:
  - name: "api-routes"                 # This route is generated from the mesh-routes trait
    match:
    - uri:
        prefix: "/v1/api"
    route:
    - destination:
        host: myapp

# The resource is defined via the service mesh trait
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: my app
spec:
  host: myapp
  trafficPolicy:
    loadBalancer:                          #This part is generated from the loadbalancing trait
      simple: ROUND_ROBIN
    connectionPool:                        #This part is generated from the circuit breaking trait
      tcp:
        maxConnections: 100
        connectTimeout: 30ms
        tcpKeepalive:
          time: 7200s
          interval: 75s
    
```
I understand that the service mesh trait can be a separate component all together. But even in that case, a single component would have to define multiple outputs and the trait will still need to patch a resource present in the output

**Comment by wonderflow** [comment]
Yes, it makes sense.

By default, our patch trait only patches to workload which is output in CUE.

```
apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  name: patch
spec:
  schematic:
    cue:
      template: |
        patch: {spec: template: metadata: labels: app: context.name}
```

And we should support the cases like:

```
apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  name: patch
spec:
  schematic:
    cue:
      template: |
        patch: outputs: <resourceName> :{spec: template: metadata: labels: app: context.name}
```

The keyword should be `patch` and inside word `outputs` and then the `resourceName` defined in other outputs resources.

Would you like to send a PR ? @YourTechBud
