### ISSUE TITLE
The quick start does not work for kind node version 1.21.1

### ISSUE THREAD

**Issue by dongwangdw** [kubevela/kubevela#1927]
I followed the quick start from here https://kubevela.io/docs/install, with kind version 0.11.0, kind node version 1.21.1.

And I followed the book to deploy vela-app.yaml.
Then the app keeps pending:
```
NAME             COMPONENT        TYPE         PHASE            HEALTHY   STATUS   AGE
first-vela-app   express-server   webservice   healthChecking                      4h5m
```

I get error log from kubevela-vela-core:
```
"Failed to aggregate status" err=app=first-vela-app, comp=express-server, trait=ingress, check health error: get template context: failed to get obj express-server with gvk networking.k8s.io/v1beta1, Kind=Ingress : ingresses.networking.k8s.io "express-server" not found
```
I get the log from nginx controller:
```
"failed to process webhook request" err="rejecting admission review because the request does not contain an Ingress resource but networking.k8s.io/v1, Kind=Ingress with name express-server in namespace default"
```

Did I miss anyting? Please help.

**Comment by wonderflow** [comment]
What is your K8s version, is it v1.21?

I think it's because the ingress API is changed. 

You can apply this ingress trait https://raw.githubusercontent.com/oam-dev/kubevela/master/charts/vela-core/templates/defwithtemplate/ingress-1-20.yaml

It's name is `ingress-1-20` to distinguish with `ingress`. And you can change the application like this:

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: first-vela-app
spec:
  components:
    - name: express-server
      type: webservice
      properties:
        image: crccheck/hello-world
        port: 8000
      traits:
        - type: ingress-1-20
          properties:
            domain: testsvc.example.com
            http:
              "/": 8000
```
