### ISSUE TITLE
The upgrade action failed after only domain of application trait Ingress was modified

### ISSUE THREAD

**Issue by jingliming** [kubevela/kubevela#2004]
**Describe the bug**
The upgrade action failed after only domain of application trait Ingress is modified

**To Reproduce**

1. The YAML files of Component/Trait I used.
webservice/ingress
2. The YAML file of Application I applied.
``` yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    app.oam.dev/rolling-components: express-server
    app.oam.dev/rollout-template: "true"
  labels:
    name: "stes"
  name: first-vela-app
  namespace: xishuaipro-test
spec:
  components:
  - name: express-server
    type: webservice
    properties:
      image: crccheck/hello-world
      port: 8000
    traits:
    - type: ingress
      properties:
        domain: testchange13.example.com
        http:
          /: 8000
```
3. Other operations I have done.
3.1 modify the domain of ingress trait
3.2 create an approllout for new apprev
4.1 The original Deployment has been deleted
4.2 The new Deployment has not been created
4.3 Approllout is always in the batchInRolling state

**Expected behavior**

1. The original Deployment could be deleted
2. The new Deployment could be created
3. Approllout is in the batchReady state
4. The new Ingress domain takes effect

**Screenshots**

![image](https://user-images.githubusercontent.com/9865050/127804606-08fdba42-6527-44ca-a7af-4599cd52168d.png)

**KubeVela Version**

oamdev/vela-core:v1.1.0-alpha.5

**Cluster information**

Describe your kubernetes cluster information.
- Kubernetes Version [v1.18.8-aliyun.1]

**Additional context**
