### ISSUE TITLE
CR from a HelmRelease component will be orphaned when the Initializer is being deleted

### ISSUE THREAD

**Issue by zzxwill** [kubevela/kubevela#2067]
**Describe the bug**

**To Reproduce**

1. Apply the Initializer.
```
apiVersion: v1
kind: Namespace
metadata:
  name: observability
spec: { }

---
apiVersion: core.oam.dev/v1beta1
kind: Initializer
metadata:
  name: grafana
  namespace: observability
spec:
  appTemplate:
    spec:
      components:
        # install grafana datasource registration chart
        - name: grafana-datasource-registration-release
          properties:
            apiVersion: helm.toolkit.fluxcd.io/v2beta1
            kind: HelmRelease
            metadata:
              name: grafana-datasource-registration-release
              namespace: observability
            spec:
              chart:
                spec:
                  chart: ./chart
                  interval: 1m
                  sourceRef:
                    kind: GitRepository
                    name: grafana-datasource-registration-repo
                    namespace: observability
              interval: 5m
              values:
                replicaCount: 1
          type: raw
        - name: grafana-datasource-registration-repo
          properties:
            apiVersion: source.toolkit.fluxcd.io/v1beta1
            kind: GitRepository
            metadata:
              name: grafana-datasource-registration-repo
              namespace: observability
            spec:
              interval: 5m
              ref:
                branch: master
              url: https://github.com/zzxwill/grafana-datasource-registration
          type: raw
```

2. When all resources get ready, apply a CR.

```
apiVersion: grafana.extension.oam.dev/v1alpha1
kind: DatasourceRegistration
metadata:
  name: poc
  namespace: observability
spec:
  grafana:
    service: grafana
    namespace: observability
    credentialSecret: grafana
    credentialSecretNamespace: observability
  datasource:
    name: loki-poc
    service: loki
    namespace: observability
    type: loki
    access: proxy
```

3. Delete the initializer

`DatasourceRegistration` is orphaned. And it, with a finializer, could be deleted as the backend chart is deleted.

**Expected behavior**

DatasourceRegistration is deleted

**Screenshots**

**KubeVela Version**

**Cluster information**

**Additional context**
