### ISSUE TITLE
skipRevisionAffect filed of TraitDefinition is not effect

### ISSUE THREAD

**Issue by chwetion** [kubevela/kubevela#2155]
**Describe the bug**
skipRevisionAffect filed of TraitDefinition is not effect

**To Reproduce**
a simple example create nginx deployment, use trait patch an env value
Definition files as follow:
```
apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  name: nginx
spec:
  workload:
    definition:
      apiVersion: apps/v1
      kind: Deployment
  schematic:
    cue:
      template: |
        parameter: {}
        output: {
            apiVersion: "apps/v1"
            kind:       "Deployment"
            spec: {
                selector: matchLabels: {
                    "app": context.name
                }
                template: {
                    metadata: labels: {
                        "app": context.name
                    }
                    spec: {
                        containers: [{
                            name: "nginx"
                            image: "nginx"
                        }]
                    }
                }
            }
        }
---
apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  name: nginx-env
spec:
  appliesToWorkloads:
  - deployments.apps
  skipRevisionAffect: true
  schematic:
    cue:
      template: |
        parameter: {
            env: string
        }
        patch: {
            spec: template: spec: {
                // +patchKey=name
                containers: [{
                    name: "nginx"
                    // +patchKey=name
                    env: [{
                        name: "test"
                        value: parameter.env
                    }]
                }]
            }
        }
```
app yaml as follow:
```
# first deploy
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: revision-test
spec:
  components:
  - type: nginx
    name: nginx
    properties: {}
    traits:
    - type: nginx-env
      properties:
        env: debug-v1
---
# upgrade version to v2 (or use kubectl edit app revision-test)
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: revision-test
spec:
  components:
  - type: nginx
    name: nginx
    properties: {}
    traits:
    - type: nginx-env
      properties:
        env: debug-v2
    - type: rollout
      properties:
        targetSize: 1
        rolloutBatches:
        - replicas: 1
---
# upgrade version to v3 (or use kubectl edit app revision-test)
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: revision-test
spec:
  components:
  - type: nginx
    name: nginx
    properties: {}
    traits:
    - type: nginx-env
      properties:
        env: debug-v3
    - type: rollout
      properties:
        targetSize: 1
        rolloutBatches:
        - replicas: 1
```
it will generate controllerrevision as follow:
```
NAME       CONTROLLER                               REVISION   AGE
nginx-v1   application.core.oam.dev/revision-test   1          21m
nginx-v2   application.core.oam.dev/revision-test   2          21m
nginx-v3   application.core.oam.dev/revision-test   3          21m
```
rollout application to v2, yaml as follow:
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: revision-test
spec:
  components:
  - type: nginx
    name: nginx
    properties: {}
    traits:
    - type: nginx-env
      properties:
        env: nginx-v3
    - type: rollout
      properties:
        targetRevision: nginx-v2
        targetSize: 1
        rolloutBatches:
        - replicas: 1
```

**Expected behavior**
only change the trait with skipRevisionAffect field should not generate controllerrevision, at least it should not be rolled back when the application is rolled back

**KubeVela Version**
```
[root@vela revision]# helm list -n vela-system
NAME    	NAMESPACE  	REVISION	UPDATED                                	STATUS  	CHART          	APP VERSION
kubevela	vela-system	1       	2021-08-24 06:42:25.162278935 -0400 EDT	deployed	vela-core-1.1.0	1.1.0
```

**Cluster information**
```
[root@vela revision]# kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.15", GitCommit:"73dd5c840662bb066a146d0871216333181f4b64", GitTreeState:"clean", BuildDate:"2021-01-13T13:14:05Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.18) exceeds the supported minor version skew of +/-1
```

**Additional context**
request: some trait features that are not related to the business should not be changed with the upgrade/rollback of the application, such as scheduling traits or ipam

BTW: During my upgrade process, if I quickly apply three upgrades yaml file, it will cause rollout resource hang, and the deployment will lose ownerReferences filed, I will submit a new issue.
