### ISSUE TITLE
[Feature] Rollout the application as a whole 

### ISSUE THREAD

**Issue by chwetion** [kubevela/kubevela#2168]
**Is your feature request related to a problem? Please describe.**
Kubevela exposes the application as a whole to front-end users. This should also be a whole when app rollout. The "rollout trait" only performs rollback operations for "component" rendered by kubevela, which cannot solve "a whole rollout" requirements of the application.

Scenario: There is an application with only one component, which contains the traits of configuration files, ingress, hpa, and schedule.

Requirement 1: The configuration file has been changed, so this upgrade changes the image field in the component and the trait of the configuration file. Obviously, while rolling back, we need to roll back the trait of the configuration file, or application will occur error with wrong configuration file.

example: v1->v2 and v2->v1, configuration trait should rollback.
```
# v1 app
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: java-application
spec:
  components:
  - type: hc.deployment
    name: app1
    properties:
      containers:
      - name: app1
        image: javaapp:v1
        ports:
        - port: 80
          protocol: TCP
    traits:
    - type: configuration
      properties:
        path: /cfg/application.yml
        data: |
          key1: value1
          key2: value2
    - type: ingress
      properties:
        domain: example.com
    - type: hpa
      properties:
        ...
    - type: schedule
      properties:
        ...
# v2 app
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: java-application
spec:
  components:
  - type: hc.deployment
    name: app1
    properties:
      containers:
      - name: app1
        image: javaapp:v2
        ports:
        - port: 80
          protocol: TCP
    traits:
    - type: configuration
      properties:
        path: /cfg/application.yml
        data: |
          key1: value1
          key3: value3
    - type: ingress
      properties:
        domain: example.com
    - type: hpa
      properties:
        ...
    - type: schedule
      properties:
        ...
```

Requirement 2: On the basis of the realized requirement 1, We hope that traits that are not related to the business will not be rolled back, such as schedule, ipam, etc. For example, after a upgrade, We have changed the app affinity. We don’t want to roll back schedule trait at the same time we roll back the app.

example: v1->v2 and v2->v1,  configuration trait should rollback, schedule trait should not rollback.
```
# v1 app
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: java-application
spec:
  components:
  - type: hc.deployment
    name: app1
    properties:
      containers:
      - name: app1
        image: javaapp:v1
        ports:
        - port: 80
          protocol: TCP
    traits:
    - type: configuration
      properties:
        path: /cfg/application.yml
        data: |
          key1: value1
          key2: value2
    - type: ingress
      properties:
        domain: example.com
    - type: hpa
      properties:
        ...
    - type: schedule
      properties:
        ...
# v2 app
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: java-application
spec:
  components:
  - type: hc.deployment
    name: app1
    properties:
      containers:
      - name: app1
        image: javaapp:v2
        ports:
        - port: 80
          protocol: TCP
    traits:
    - type: configuration
      properties:
        path: /cfg/application.yml
        data: |
          key1: value1
          key3: value3
    - type: ingress
      properties:
        domain: example.com
    - type: hpa
      properties:
        ...
    - type: schedule
      properties:
        ... (has change)
```

**Describe the solution you'd like**
Like the ApplicationDeployment mentioned in https://github.com/oam-dev/kubevela/blob/master/design/vela-core/rollout-design.md, it can solve this feature. Communicated with the community developers offline and know that this upgrade method will be deprecated. Hope to keep this upgrade method and use it as a trait.

To solve the requirement 2, also need to consider the trait with `skipRevisionAffect` added to the app in the v1->v2 version. For example, the v1 app does not contain the schedule trait, and then the trait is added to complete the scheduling requirements. At this time, because the `skipRevisionAffect` field exists, no new revision will be generated. After the app is upgraded, to roll back from v2->v1, the existing traits with the `skipRevisionAffect` field in v2 should be merged into v1.

example: v1->v2 and v2->v1, schedule trait should be merge on v1
```
# v1 app
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: java-application
spec:
  components:
  - type: hc.deployment
    name: app1
    properties:
      containers:
      - name: app1
        image: javaapp:v1
        ports:
        - port: 80
          protocol: TCP
    traits:
    - type: configuration
      properties:
        path: /cfg/application.yml
        data: |
          key1: value1
          key2: value2
    - type: ingress
      properties:
        domain: example.com
    - type: hpa
      properties:
        ...
# v2 app
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: java-application
spec:
  components:
  - type: hc.deployment
    name: app1
    properties:
      containers:
      - name: app1
        image: javaapp:v2
        ports:
        - port: 80
          protocol: TCP
    traits:
    - type: configuration
      properties:
        path: /cfg/application.yml
        data: |
          key1: value1
          key3: value3
    - type: ingress
      properties:
        domain: example.com
    - type: hpa
      properties:
        ...
    - type: schedule
      properties:
        ...
```
