### ISSUE TITLE
[Bug] Multiple workload versions exist when deploying old applications using Rollout

### ISSUE THREAD

**Issue by jingliming** [kubevela/kubevela#2476]
**Describe the bug**
Multiple workload versions exist when I deployed old applications using Rollout, and only the latest workload version is available after I deployed it again.

**To Reproduce**
1. Deploy the application with AppRollout in 1.1.0-alpha5
2. Upgrade KubeVela to 1.1.5
3. Deploy the application with Rollout in 1.1.5

**Yaml may be used**
1. component defination
``` yaml
# Code generated by KubeVela templates. DO NOT EDIT.
apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  name: stateless-component
  namespace: vela-system
  annotations:
    definition.oam.dev/description: "Describes long-running, scalable, containerized services that have a stable network endpoint to receive external network traffic from customers."
spec:
  workload:
    definition:
      apiVersion: apps/v1
      kind: Deployment
  schematic:
    cue:
      template: |
        output: {
          apiVersion: "apps/v1"
          kind:       "Deployment"
          spec: {
            selector: matchLabels: {
              "app.oam.dev/component": context.name
              if parameter.addRevisionLabel {
                "app.oam.dev/appRevision": context.appRevision
              }
            }

            template: {
              metadata: labels: {
                "app.oam.dev/component": context.name
                if parameter.addRevisionLabel {
                  "app.oam.dev/appRevision": context.appRevision
                }
              }

              spec: {
                containers: [{
                  name:  context.name
                  image: parameter.image
                  ports: [{
                    containerPort: parameter.port
                  }]

                  if parameter["cmd"] != _|_ {
                    command: parameter.cmd
                  }

                  if parameter["args"] != _|_ {
                    args: parameter.args
                  }

                  if parameter["env"] != _|_ {
                    env: parameter.env
                  }

                  if context["config"] != _|_ {
                    env: context.config
                  }

                  if parameter["cpu"] != _|_ {
                    resources: {
                      limits:
                        cpu: parameter.cpu.limits
                      requests:
                        cpu: parameter.cpu.requests
                    }
                  }

                  if parameter["memory"] != _|_ {
                    resources: {
                      limits:
                        memory: parameter.memory.limits
                      requests:
                        memory: parameter.memory.requests
                    }
                  }

                  if parameter["volumes"] != _|_ {
                    volumeMounts: [ for v in parameter.volumes {
                      {
                        mountPath: v.mountPath
                        name:      v.name
                      }}]
                  }

                  if parameter["livenessProbe"] != _|_ {
                    livenessProbe: parameter.livenessProbe
                  }

                  if parameter["readinessProbe"] != _|_ {
                    readinessProbe: parameter.readinessProbe
                  }

                }]
                
              if parameter["imagePullSecrets"] != _|_ {
                imagePullSecrets: parameter.imagePullSecrets
              }

              if parameter["volumes"] != _|_ {
                volumes: [ for v in parameter.volumes {
                  {
                    name: v.name
                    if v.type == "pvc" {
                      persistentVolumeClaim: {
                        claimName: v.claimName
                      }
                    }
                    if v.type == "configMap" {
                      configMap: {
                        defaultMode: v.defaultMode
                        name:        v.cmName
                        if v.items != _|_ {
                          items: v.items
                        }
                      }
                    }
                    if v.type == "secret" {
                      secret: {
                        defaultMode: v.defaultMode
                        secretName:  v.secretName
                        if v.items != _|_ {
                          items: v.items
                        }
                      }
                    }
                    if v.type == "emptyDir" {
                      emptyDir: {
                        medium: v.medium
                      }
                    }
                  }}]
              }
            }
          }
        }
        }
        parameter: {
          // +usage=Which image would you like to use for your service
          // +short=i
          image: string

          // +usage=Which image pull secret would you like to use for your deploymet
          imagePullSecrets: [...{
            name: string
          }]

          // +usage=Which port do you want customer traffic sent to
          // +short=p
          port: *80 | int

          // +ignore
          // +usage=If addRevisionLabel is true, the appRevision label will be added to the underlying pods
          addRevisionLabel: *false | bool

          // +usage=Commands to run in the container
          cmd?: [...string]

          args?: [...string]

          // +usage=Define arguments by using environment variables
          env?: [...{
            // +usage=Environment variable name
            name: string
            // +usage=The value of the environment variable
            value?: string
            // +usage=Specifies a source the value of this var should come from
            valueFrom?: {
              // +usage=Selects a key of a secret in the pod's namespace
              secretKeyRef: {
                // +usage=The name of the secret in the pod's namespace to select from
                name: string
                // +usage=The key of the secret to select from. Must be a valid secret key
                key: string
              }
            }
          }]

          // +usage=Number of CPU units for the service, like `0.5` (0.5 CPU core), `1` (1 CPU core)
          cpu?: #Cpu

          // +usage=Specifies the attributes of the memory resource required for the container.
          memory?: #Memory

          // +usage=Declare volumes and volumeMounts
          volumes?: [...{
            name:      string
            mountPath: string
            // +usage=Specify volume type, options: "pvc","configMap","secret","emptyDir"
            type: "pvc" | "configMap" | "secret" | "emptyDir"
            if type == "pvc" {
              claimName: string
            }
            if type == "configMap" {
              defaultMode: *420 | int
              cmName:      string
              items?: [...{
                key:  string
                path: string
                mode: *511 | int
              }]
            }
            if type == "secret" {
              defaultMode: *420 | int
              secretName:  string
              items?: [...{
                key:  string
                path: string
                mode: *511 | int
              }]
            }
            if type == "emptyDir" {
              medium: *"" | "Memory"
            }
          }]

          // +usage=Instructions for assessing whether the container is alive.
          livenessProbe?: #HealthProbe

          // +usage=Instructions for assessing whether the container is in a suitable state to serve traffic.
          readinessProbe?: #HealthProbe
        }

        #Cpu: {
          limits:   string
          requests: string
        }

        #Memory: {
          limits:   string
          requests: string
        }

        #HealthProbe: {

          // +usage=Instructions for assessing container health by executing a command. Either this attribute or the httpGet attribute or the tcpSocket attribute MUST be specified. This attribute is mutually exclusive with both the httpGet attribute and the tcpSocket attribute.
          exec?: {
            // +usage=A command to be executed inside the container to assess its health. Each space delimited token of the command is a separate array element. Commands exiting 0 are considered to be successful probes, whilst all other exit codes are considered failures.
            command: [...string]
          }

          // +usage=Instructions for assessing container health by executing an HTTP GET request. Either this attribute or the exec attribute or the tcpSocket attribute MUST be specified. This attribute is mutually exclusive with both the exec attribute and the tcpSocket attribute.
          httpGet?: {
            // +usage=The endpoint, relative to the port, to which the HTTP GET request should be directed.
            path: string
            // +usage=The TCP socket within the container to which the HTTP GET request should be directed.
            port: int
            scheme: string
            httpHeaders?: [...{
              name:  string
              value: string
            }]
          }

          // +usage=Instructions for assessing container health by probing a TCP socket. Either this attribute or the exec attribute or the httpGet attribute MUST be specified. This attribute is mutually exclusive with both the exec attribute and the httpGet attribute.
          tcpSocket?: {
            // +usage=The TCP socket within the container that should be probed to assess container health.
            port: int
          }

          // +usage=Number of seconds after the container is started before the first probe is initiated.
          initialDelaySeconds: *0 | int

          // +usage=How often, in seconds, to execute the probe.
          periodSeconds: *10 | int

          // +usage=Number of seconds after which the probe times out.
          timeoutSeconds: *1 | int

          // +usage=Minimum consecutive successes for the probe to be considered successful after having failed.
          successThreshold: *1 | int

          // +usage=Number of consecutive failures required to determine the container is not alive (liveness probe) or not ready (readiness probe).
          failureThreshold: *3 | int
        }

```
2. trait defination
``` yaml
# Code generated by KubeVela templates. DO NOT EDIT.
apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  annotations:
    definition.oam.dev/description: "Enable public web traffic for the component."
  name: bizworks-ingress
  namespace: vela-system
spec:
  status:
    customStatus: |-
      let igs = context.outputs.ingress.status.loadBalancer.ingress
      if igs == _|_ {
        message: "No loadBalancer found, visiting by using 'vela port-forward " + context.appName + " --route'\n"
      }
      if len(igs) > 0 {
        if igs[0].ip != _|_ {
          message: "Visiting URL: " + context.outputs.ingress.spec.rules[0].host + ", IP: " + igs[0].ip
        }
        if igs[0].ip == _|_ {
          message: "Visiting URL: " + context.outputs.ingress.spec.rules[0].host
        }
      }
    healthPolicy: |
      isHealth: len(context.outputs.service.spec.clusterIP) > 0
  appliesToWorkloads:
    - deployments.apps
  podDisruptive: false
  schematic:
    cue:
      template: |
        // trait template can have multiple outputs in one trait
        outputs: service: {
        	apiVersion: "v1"
        	kind:       "Service"
        	metadata:
        		name: parameter.ingressName
        	spec: {
        		selector: {
        			"app.oam.dev/component": context.name
        		}
        		ports: [
        			for k, v in parameter.http {
        				port:       v
                        protocol:   "TCP"
        				targetPort: parameter.targetPort
        			},
        		]
        	}
        }
        
        outputs: ingress: {
        	apiVersion: "networking.k8s.io/v1beta1"
        	kind:       "Ingress"
        	metadata:
        		name: parameter.serviceName
        	spec: {
        		rules: [{
        			host: parameter.domain
        			http: {
        				paths: [
        					for k, v in parameter.http {
        						path: k
        						backend: {
        							serviceName: parameter.serviceName
        							servicePort: v
        						}
        					},
        				]
        			}
        		}]
        	}
        }
        
        parameter: {
          // +usage=Specify the domain you want to expose
          domain: string

          // +usage=Specify the mapping relationship between the http path and the workload port
          http: [string]: int
          
          // +usage=Specify the service targetPort
          targetPort: int

          // +usage=Specify the ingress name
          ingressName: string
   
          // +usage=Specify the service name
          serviceName: string
        }
```
3. application
``` yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    oam.dev/kubevela-version: v1.1.5
  name: application01
  namespace: cn1-ty01
spec:
  components:
  - name: application01
    properties:
      cpu:
        limits: "1"
        requests: "0.5"
      env:
      - name: TZ
        value: Asia/Shanghai
      - name: bwa_logs_catalina
        value: stdout
      - name: bwa_logs_catalina_tags
        value: topic=bizworks-logging-trace,tenantId=103573587971,clusterCode=6ce8544f056a46eba893fb4de4efc16f
      - name: x-bw-app_id
        value: application01
      - name: x-bw-app_version
        value: 1.0.1
      - name: x-bw-env_id
        value: cn1.ty01
      - name: x-bw-tenant_id
        value: "103573587971"
      - name: x-bw-project_id
        value: cn1
      - name: x-bw-endpoint
        value: application01.sdm.bizworks.cn
      - name: createAt
        value: "1634134866172"
      image: bizworks-alpha-registry.cn-beijing.cr.aliyuncs.com/bizworks/cn1-application01:1.0.1-20211013221953
      imagePullSecrets:
      - name: cn1-ty01-image-pull-secret
      memory:
        limits: 1024Mi
        requests: 512Mi
      port: 80
    traits:
    - properties:
        domain: application01.sdm.bizworks.cn
        http:
          /: 80
        ingressName: application01
        serviceName: application01
        targetPort: 8080
      type: bizworks-ingress
    - properties:
        bizworks.aliyun.com/cluster-code: 6ce8544f056a46eba893fb4de4efc16f
        bizworks.aliyun.com/tenant-id: "103573587971"
      type: labels
    - properties:
        rolloutBatches:
        - replicas: 1
        targetSize: 1
      type: rollout
    type: stateless-component
```

**Expected behavior**
workload could upgrade to the new version

**Screenshots**
![image](https://user-images.githubusercontent.com/9865050/137244933-1cf8384e-5bba-4a17-937a-de6eb7709b16.png)

**KubeVela Version**
1.1.0-alpha5
1.1.5

**Cluster information**
v1.18.8-aliyun.1

**Additional context**
