### ISSUE TITLE
[Feature] Multiple Port Exposure Support

### ISSUE THREAD

**Issue by kertkukk** [kubevela/kubevela#2501]
Web Services should support multiple port exposure:

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: first-vela-app
spec:
  components:
    - name: express-server
      type: webservice
      properties:
        image: crccheck/hello-world
        ports:
          - name: http-main
            protocol: TCP
            port: 8000
          - name: http-secondary
            protocol: TCP
            port: 8080
````

**Comment by FogDong** [comment]
Support multiple ports in this PR #2664 
But I guess we don't need to specify the name in ports🤔.

**Comment by martivo** [comment]
> Support multiple ports in this PR #2664 But I guess we don't need to specify the name in portsthinking.

I would recommend to leave the possibility to name ports. A list+dictionary approach would also be more future proof - in case some other fields need to be defined. For example there is also a "protocol" field - for a webservice it is TCP today, but it might also change to SCTP for some cases.

These names can also be used in services.

From kubernetes manual about port naming in pods https://kubernetes.io/docs/concepts/services-networking/service/  
> Port definitions in Pods have names, and you can reference these names in the targetPort attribute of a Service. This works even if there is a mixture of Pods in the Service using a single configured name, with the same network protocol available via different port numbers. This offers a lot of flexibility for deploying and evolving your Services. For example, you can change the port numbers that Pods expose in the next version of your backend software, without breaking clients.

It also enables to implement traits that detect certain ports by the name. For example if I name the port "http-prometheus" then an annotation could be added by a trait to add the pods to prometheus scraping.

In case of services when someone would like to implement a service mesh, it is vital the the Service objects ports are named. It could be useful to already name the ports in the pods, so the names can be inherited by services - again when we are using traits to expose the pods in a service we would not have to name them at the service level.
https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/

Also if we want to define more than one port in a Service then the name parameter is mandatory.
>When using multiple ports for a Service, you must give all of your ports names so that these are unambiguous.
 https://kubernetes.io/docs/concepts/services-networking/service/#multi-port-services

I would recommend to use the following parameter
```
ports: [...{
            name: *"http" | string
            number: int
            protocol: *"TCP" | "SCTP" | "UDP"
          }]
```
So the yaml for application could be:
```
ports:
         - number: 8000
           name: http-web
         - number: 8080
           name: http-monitoring
```
Or in case I don't have a complicated setup then just:
```
ports:
         - number: 8000
```

**Comment by FogDong** [comment]
Hi @martivo !
Thanks for your advice and I think we can leave the `name` optional like below:

```yaml
ports: [...{
            name?: string
            port: int
            protocol: *"TCP" | "SCTP" | "UDP"
          }]
```
