### ISSUE TITLE
[Bug]Dependencies between application components

### ISSUE THREAD

**Issue by zengzezheng** [kubevela/kubevela#2508]
**I  use dependencies between application components . used `depondsOn`  It didn't work. **

**my kube-vela version is  1.1.5 . my application yaml is :**

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: limingtest2
  namespace: tenant-paas-test-liming
  labels:
    ns: tenant-paas-test-liming
spec:
  components:
  - name: limingtest-mysql
    type: webservice
    properties:
      env:
      - name: MYSQL_ROOT_PASSWORD
        value: root
      image: mysql:5.7aaaa
      port: 3306
      cpu: 1000m
      memory: 500M
    traits:
    - type: ingress
      properties:
        http:
          /hloi: 13666
        domain: com.zdww1
    - type: scaler
      properties:
        replicas: 1
    - type: cpuscaler
      properties:
        cpuUtil: 70
        min: 1
        max: 3
    - type: pvc
      properties:
        claimName: aaa
        accessModes:
        - ReadWriteOnce
        storageClassName: nfs-dynamic-sc
        resources:
          requests:
            storage: 1Gi
        volumesToMount:
        - mountPath: /aaa
          name: aaa
    - type: pvc
      properties:
        claimName: bbb
        accessModes:
        - ReadWriteOnce
        storageClassName: nfs-dynamic-sc
        resources:
          requests:
            storage: 1Gi
        volumesToMount:
        - mountPath: /bbb
          name: bbb
  - name: limingtest-frontend-web
    type: webservice
    properties:
      image: ip:9999/kubernetes/kubewanwei-web-nginx:0909
      port: 80
      cpu: 500m
      memory: 500M
    traits:
    - type: ingress
      properties:
        http:
          /front: 80
        domain: liming.test.com
    - type: scaler
      properties:
        replicas: 1
    - type: cpuscaler
      properties:
        cpuUtil: 70
        min: 1
        max: 3
  - name: limingtest-redis-secret
    type: raw
    properties:
      apiVersion: v1
      kind: Secret
      metadata:
        name: limingtest-redis-secret
        namespace: tenant-paas-test-liming
      type: generic
      data:
        sss: ZGRk
        fff: ZGRk
  - name: limingtest-redis
    type: webservice
    properties:
      image: redis
      port: 6379
      cpu: 200m
      memory: 500M
    dependsOn:
    - limingtest-redis-secret
    - limingtest-mysql
    traits:
    - type: innerservice
      properties:
        http:
          /: 6379
    - type: scaler
      properties:
        replicas: 1
    - type: cpuscaler
      properties:
        cpuUtil: 70
        min: 1
        max: 3
    - type: service-binding
      properties:
        envMappings:
          sss:
            secret: limingtest-redis-secret
          fff:
            secret: limingtest-redis-secret
  - name: limingtest-sql
    type: webservice
    properties:
      image: sql
      port: 22
      cpu: 200m
      memory: 500M
    traits:
    - type: innerservice
      properties:
        http:
          /: 22
    - type: scaler
      properties:
        replicas: 1
    - type: cpuscaler
      properties:
        cpuUtil: 70
        min: 1
        max: 3
  policies:
  - name: health-policy
    type: health
    properties:
      probeTimeout: 10
      probeInterval: 10
```

Actual start-up situation:

![image](https://user-images.githubusercontent.com/72589839/137684810-802d1107-a4ca-4adc-a9c8-a63b4a2af8ae.png)

The correct situation should be 
 `limingtest-mysql`  Failed to start successfully , `limingtest-redis`It should not be able to start successfully.
