### ISSUE TITLE
Kubevela v1.1.x loose integration with ArgoCD

### ISSUE THREAD

**Issue by alexisbel1** [kubevela/kubevela#2608]
**Describe the bug**
I recently updated Kubevela  from v1.0.7 to v1.1.7 and I saw that workload deployed using Components are now "Controlled" by `ResourceTracker` (previously controlled by `ApplicationContext` in v1.0.7):
 
In v1.0.7:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: medvik-back
  namespace: medvik
  ownerReferences:
    - apiVersion: core.oam.dev/v1alpha2
      kind: ApplicationContext
      name: medvik
      uid: 9e513c85-ca8d-4e12-b690-f181b534cbbf
      controller: true
      blockOwnerDeletion: true
```
In v1.1.7:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: medvik-back
  namespace: medvik
  ownerReferences:
    - apiVersion: core.oam.dev/v1beta1
      kind: ResourceTracker
      name: medvik-v5-medvik
      uid: 0d6e6f93-31dd-42ad-a64d-95ce5ae951d2
      controller: true
      blockOwnerDeletion: true
```
The problem is that the `ResourceTracker` is not controlled by `ApplicationContext` `Application` or other any CRD managed by Kubevela, and so we lose the link between `Pods` and the `Application` we defined as the end user.

It is particularly annoying when using GitOps tools like ArgoCD to visualize pods:

ArgoCD UI with kubevela 1.0.7:

![argocd-kubevela1 0 7](https://user-images.githubusercontent.com/25341574/139925934-c39fb104-a558-4766-b7aa-f54df6a65efc.png)

ArgoCD UI with kubevela 1.1.7:

![arogcd-kubevela-1 1 7](https://user-images.githubusercontent.com/25341574/139925964-4ab2d12e-95c1-44ee-970a-19d3f652a9f3.png)

**To Reproduce**

Check `ownerReferences` in `ResourceTracker` and you'll see there is no Kubevela CRD attached.

**Expected behavior**

 `metadata.ownerReferences` in `ResourceTracker` CRD should be populated with a Kubevela CRD to keep the link between Kubevela `Application`  and generated resources (`Deployement`, `Pod`, `Ingress` ...)

**KubeVela Version**
v1.1.7

**Cluster information**
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"881d4a5a3c0f4036c714cfb601b377c4c72de543", GitTreeState:"clean", BuildDate:"2021-10-21T05:13:01Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```
