### ISSUE TITLE
When an application uses `depends-on-app` to install the other one, `apply-application` has to be used to install itself

### ISSUE THREAD

**Issue by zzxwill** [kubevela/kubevela#2737]
**Describe the bug**

In the application below, application `terraform` uses `depends-on-app` to install `fluxcd`, `apply-application` has to be used to install itself. If workflow step `apply-application` isn't set, the application itself won't get deployed.
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    addons.oam.dev/description: "Terraform Controller is a Kubernetes Controller for Terraform."
  name: terraform
  namespace: vela-system
spec:
  workflow:
    steps:
      - name: checking-depends-on
        type: depends-on-app
        properties:
          name: fluxcd
          namespace: vela-system
      - type: apply-application
  components:
    - name: terraform-controller
      type: helm
      properties:
        repoType: helm
        url: https://charts.kubevela.net/addons
        chart: terraform-controller
        version: 0.2.5
```

**To Reproduce**

**Expected behavior**

Without explicitly setting workflow step `apply-application`, after the dependent application becomes running, the application itself should be deployed immediately. 

**Screenshots**

**KubeVela Version**

**Cluster information**

**Additional context**
