### ISSUE TITLE
Incomplete value  in interpolation

### ISSUE THREAD

**Issue by kgonyon** [kubevela/kubevela#2775]
**Describe the bug**
Getting error when applying component definition to cluster for valid cue template.

```'cannot store capability ff-workflow in ConfigMap: failed to generate OpenAPI v3 JSON schema for capability ff-workflow: openapi: #parameter.steps.task.name: incomplete value ''name'' in interpolation'```

**To Reproduce**
``` yaml
# Code generated by KubeVela templates. DO NOT EDIT. Please edit the original cue file.
apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  annotations:
    definition.oam.dev/description: Creates a CI workflow template to be triggered by events
  name: ff-workflow
spec:
  schematic:
    cue:
      template: |
        parameter: steps: [...#Step]
        output: {
          tasks: [
            for index, step in parameter.steps {
              step.task
            }
          ]
        }
        #Step: {
          name: string
          task: {
            "name": "\(name)-task"
          }
        }
  workload:
    definition:
      apiVersion: argoproj.io/v1alpha1
      kind: WorkflowTemplate
```
1. kubectl apply the above yaml.

**Expected behavior**
Component should apply fine

**KubeVela Version**
Kubevela version 1.1.10 installed through Helm chart.

**Cluster information**
Kubernetes 1.21

**Additional context**
If you set a default value for #Step.name then it works fine, but this is not desired in all cases. Also if you use the variable outside of string interpolation it works fine, however if you do `name + "-task"` instead you get the below error instead.

```'cannot store capability ff-workflow in ConfigMap: failed to generate OpenAPI v3 JSON schema for capability ff-workflow: openapi: #parameter.steps.task.name: incomplete error'```

If you run `vela dry-run -f <somedef> -d ff-workflow.yaml` it works fine.
