### ISSUE TITLE
Improvements on the mechanism applying components in order

### ISSUE THREAD

**Issue by zzxwill** [kubevela/kubevela#2805]
Somehow, the application of add-on observability is assembled as below:

```
spec:
  components:
  - name: resources-loki
    properties:
      chart: loki-stack
      releaseName: loki
      repoType: helm
      targetNamespace: vela-system
      url: https://charts.kubevela.net/addons
      version: 2.4.1
    traits:
    - properties:
        access: proxy
        credentialSecret: grafana
        credentialSecretNamespace: observability
        grafanaServiceName: grafana
        grafanaServiceNamespace: observability
        name: loki
        namespace: observability
        service: loki
        type: loki
      type: register-grafana-datasource
    type: helm
  - name: resources-grafana-registration
    properties:
      chart: ./chart
      git:
        branch: master
      repoType: git
      targetNamespace: vela-system
      url: https://github.com/oam-dev/grafana-registration
      values:
        replicaCount: 1
    type: helm
```

When applying the application, it hit an issue:

```
  workflow:
    appRevision: addon-observability-v2:b0abb3e854e650ff
    contextBackend:
      apiVersion: v1
      kind: ConfigMap
      name: workflow-addon-observability-context
      uid: bbf53e3c-d83d-4dbf-9261-2946973dc9cb
    finished: false
    mode: StepByStep
    startTime: "2021-11-25T08:07:18Z"
    steps:
    - firstExecuteTime: "2021-11-25T08:07:19Z"
      id: en5tfejyoi
      lastExecuteTime: "2021-11-25T08:13:36Z"
      message: 'step apply: step components: step resources-loki: run step(provider=oam,do=component-apply):
        DispatchTraits: cannot apply manifest, name: "resources-loki-register-grafana-datasource-749fc8b44b"
        apiVersion: "grafana.extension.oam.dev/v1alpha1" kind: "DatasourceRegistration":
        cannot get object: no matches for kind "DatasourceRegistration" in version
        "grafana.extension.oam.dev/v1alpha1"'
```

The trait `register-grafana-datasource` from the first component depends on the second component. But it failed and the controller has no chance to install the second one. Then it is a dead-lock state.

Here are two proposals:
- We keep the in-order applying components mechanism. But the controller can process to the next component applying even if procedure one failed.
- We return back to the disorder applying mechanism.
