### ISSUE TITLE
rollout controller panic when user remove rolloutBatches during a rollout 

### ISSUE THREAD

**Issue by basuotian** [kubevela/kubevela#3002]
**Describe the bug**

1. apply a rollout
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: rollout-trait-test
spec:
  components:
    - name: express-server
      type: webservice
      # 设置组件版本为 express-server-v1
      externalRevision: express-server-v1
      properties:
        image: stefanprodan/podinfo:4.0.3
      traits:
        - type: rollout
          # 缺省设置 targetRevision 直接指向最新的组件版本也就是 express-server-v1
          properties:
            # 设置部署5个副本
            targetSize: 5
            # 分两批发布，上一批次副本全部就绪之后部署下一批次
            rolloutBatches:
              - replicas: 2
              - replicas: 3
```
2. edit application, remove `rolloutBatches` field, like
```
traits:
- type: rollout
  # 缺省设置 targetRevision 直接指向最新的组件版本也就是 express-server-v1
  properties:
    # 设置部署5个副本
    targetSize: 5
    # 分两批发布，上一批次副本全部就绪之后部署下一批次
```
3. then rollout controller panic
```
panic: runtime error: index out of range [1] with length 0

goroutine 293 [running]:
github.com/oam-dev/kubevela/pkg/controller/common/rollout.(*Controller).gatherAllWebhooks(...)
       	/.../kubevela/pkg/controller/common/rollout/rollout_plan_controller.go:259
github.com/oam-dev/kubevela/pkg/controller/common/rollout.(*Controller).initializeOneBatch(0x0, {0x2375a28, 0xc000b6d230})

```

in pkg/controller/common/rollout/rollout_plan_controller.go:259
```
currentBatch := s.rolloutSpec.RolloutBatches[s.rolloutStatus.CurrentBatch]
```

perhaps vela should prevent user removing `rolloutBatches` during a rollout?
