### ISSUE TITLE
[Bug]  在已经存在的App的Component上更新traits  底层workload未同步

### ISSUE THREAD

**Issue by wxuedong** [kubevela/kubevela#3088]
K8s version 1.16
Kubevela version 1.1.8
首先创建一个新的App
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: first-vela-app
spec:
  components:
    - name: bcs-k8s-java-demo-service
      type: argo-rollout
      properties:
        image: xx/bcs-k8s-java-demo-service:1.0.0-e27b046
        port: 8000
      traits:
        - type: "annotations"
          properties:
              app: "bcs-k8s-java-demo-service"
```

其次在此基础上新加一些新的traits
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: first-vela-app
spec:
  components:
    - name: bcs-k8s-java-demo-service
      type: argo-rollout
      properties:
        image: xx/bcs-k8s-java-demo-service:1.0.0-e27b046
        port: 8000
      traits:
        - type: "annotations"
          properties:
              app: "bcs-k8s-java-demo-service"
        - type: "skywalking"
          properties:
             env: "test"
```

App 更新成功 ，但是traits的skywalking 能力并没有体现出来，本质上skywalking patch一些新的属性到argo-rollout的实现中，既然App 更新成功 argo-rollout 这个组件定义也应该同步
