### ISSUE TITLE
[Feature] Support custom CUE providers

### ISSUE THREAD

**Issue by phantomnat** [kubevela/kubevela#3206]
**Is your feature request related to a problem? Please describe.**

I do have a requirement to implement internal logics in Kube Vela and execute that via workflow.
After scan through the codes, I think it would be great if we can provide a way to load custom CUE providers since a lot of workflow steps were implemented in Golang.

**Describe the solution you'd like**

Have a way to load a custom providers and then use in the workflow.

`my-action.cue`

```yaml
import (
  "some/custom"
)

"my-action": {
    type: "workflow-step"
}

template: {
  func1: custom.#MyFunction1 & {}

  func2: custom.#MyFunction2 & {}  
}
```

`application.yaml`

```yaml
  workflow:
    steps:
      - name: my-action
        type: my-action
```

**Describe alternatives you've considered**

- Fork this project, create custom providers and then deploy a custom build. 
- Provide http server for internal logic and using `op.HTTP*` step to call the endpoints.

**Additional context**
