### ISSUE TITLE
[Bug] TraitDefinition updating triggers Application and Pod updating

### ISSUE THREAD

**Issue by dengqian** [kubevela/kubevela#3252]
**Describe the bug**
last issue: https://github.com/oam-dev/kubevela/issues/3168  was not completedly solved,  I update my vela-core version to v1.2.3, and update trait definition the same way in https://github.com/oam-dev/kubevela/issues/3168 , and pods updated about ten minute after updating the trait definition. My application was like below, 
```
NAME                  COMPONENT             TYPE         PHASE             HEALTHY   STATUS      AGE
cdn-live-tao          cdn-live-tao          cloneset     runningWorkflow   false     Ready:0/1   3h4m
```
the diff before and after the updating of trait definition was :
```
$ diff new.yaml curr.yaml
12c12
<   resourceVersion: "17434075"
---
>   resourceVersion: "17436868"
300c300
<       lastExecuteTime: "2022-02-14T12:45:07Z"
---
>       lastExecuteTime: "2022-02-14T12:55:07Z"

```
about ten minute after updating the trait definition, pod updating triggered:
```
$ kg pods -n ppe-wlh-cn3690
NAME                      READY   STATUS    RESTARTS   AGE
cdn-live-tao-mmlrf        2/3     Running   0          15m
```

application status:
```
    conditions:
    - lastTransitionTime: "2022-02-14T09:51:28Z"
      reason: Available
      status: "True"
      type: Parsed
    - lastTransitionTime: "2022-02-14T09:51:28Z"
      reason: Available
      status: "True"
      type: Revision
    - lastTransitionTime: "2022-02-14T09:51:28Z"
      reason: Available
      status: "True"
      type: Policy
    - lastTransitionTime: "2022-02-14T09:51:28Z"
      reason: Available
      status: "True"
      type: Render
    latestRevision:
      name: cdn-live-tao-v1
      revision: 1
      revisionHash: 4d53131497eb192d
    observedGeneration: 1
```

And I found this updating was not applied to all applications. I have no idea what kind of application will be affected, and what will not
