### ISSUE TITLE
Variable `region` in an Application is eaten by Terraform Controller execution job

### ISSUE THREAD

**Issue by zzxwill** [kubevela/kubevela#3384]
**Describe the bug**

so...I am running into an interesting problem. I applied the component for emr as below:

```
apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  annotations:
    definition.oam.dev/description: Terraform module which creates EMR
      on AWS
  creationTimestamp: null
  labels:
    type: terraform
  name: aws-emr
  namespace: vela-system
spec:
  schematic:
    terraform:
      configuration: https://github.com/cloudposse/terraform-aws-emr-cluster.git
      providerRef:
        name: aws
        namespace: default
      type: remote
  workload:
    definition:
      apiVersion: terraform.core.oam.dev/v1beta1
      kind: Configuration
status: {}
```

[2:49](https://cloud-native.slack.com/archives/D034HFTAGKW/p1646333369121969)
but somehow when I apply the application, eventhough I provide region  as a property to the yaml, it doesnt seem to find it when the tf applies. I feel somehow we are loosing region  in the marshalling from the configuration. A sample here:
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: anoop-emr
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  components:
    - name: anoop-emr-tf-component
      type: aws-emr
      properties:
        name: "anoop-emr-tf-component"
        region: "us-east-1"
        vpc_id: "xxxx"
        subnet_id: "xxxxxx"
        applications:
          - "Spark"
        core_instance_group_instance_type: "m4.large"
        core_instance_group_ebs_size: 1
        master_instance_group_instance_type: "m4.large"
        master_instance_group_ebs_size: 1
        writeConnectionSecretToRef:
          name: anoop-emr-details
          namespace: default
  workflow:
    steps:
      - name: create-emr
        type: apply-component
        properties:
          component: anoop-emr-tf-component
```

```
 Services:
    Healthy:  false
    Message:  │ Error: No value for required variable
│
│   on variables.tf line 199:
│  199: variable "region" {
│
│ The root module input variable "region" is not set, and has no default
│ value. Use a -var or -var-file command line argument to provide a value for
│ this variable.
[2:54](https://cloud-native.slack.com/archives/D034HFTAGKW/p1646333648729089)
I will try to debug further, but if you see anything thats obviously wrong, do let me know
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**KubeVela Version**

**Cluster information**

**Additional context**
