### ISSUE TITLE
[Feature] Workflow need support new step type to  batch apply a lot of components parallelly or in order

### ISSUE THREAD

**Issue by zq200618** [kubevela/kubevela#3460]
**Request description**
For example, I have 6 components in a OAM application，the first and second one need apply before the last four components and wait user to confirm after it apply success.  If I use the workflow to apply it, the workflow have so much 7 steps, and the workflow will be much more complex when the components increase in future. As a requirements, I need workflow is as this:
![lQDPDhtCjx7_ldnNArnNB-6wHWBFHtTv6joCPbk8LECyAA_2030_697](https://user-images.githubusercontent.com/101779235/159426615-657472d6-2b0f-4171-94af-7ea9baf90234.jpg)

**Currently**
Now the official workflow step could apply two components in a workflow step，but it could not apply two components to different targets in a step, at the same time, it could not support get the each component deploy status.

**New solutions**
A new step type is needed which could apply a lot of components parallelly or in order. User could add common apply steps such as apply-component, deploy2env as sub-steps to it. When it is applying,  we can get each sub-step deploy status.  
Yaml example:
![lQDPDhs-m8SDwMfM280BsbAxfFJ_xnRhYQI3QDt1wEAA_433_219](https://user-images.githubusercontent.com/101779235/158753994-8d2d4a62-0a4d-4551-8e5f-1507c1e0b98b.jpg)

**Solution details**
(1) Create apply-step-group step type to op.cue and oam.cue. it should support all kinds of appliable workflow step types.
(2) Create custom stepGroupTaskRunner implements from TaskRunner, which contain a property name is subStepTaskRunners. When application step is generated, stepGroupTaskRunner will be created if step type is apply-step-group.
(3) Custom group apply handler will be created in apply provider to handler the apply-step-group step to apply. The handler will run each stepGroupTaskRunners to apply components.
(4) Do not change the main process schedule frame, sub-Step schedule method is the same as the deploy2env step type.

**Comment by fourierr** [comment]
+1

**Comment by barnettZQG** [comment]
@zq200618 @fourierr  #3223 In this PR, provide a new workflow step type `deploy`, that can batch deploy all components or a part of the components selected across by override policy.

You can set multiple steps of the `deploy` type.

**Comment by wonderflow** [comment]
I propose the solution can be like this:

```
workflow:
  steps:
  - type: parent-step
     properties:
       ...
     steps:
     - type: sub-step1
        properties:
           ...
```

The substeps are also an official field in the parent step named `steps`.

**Comment by leejanee** [comment]
Yeap, this proposal is great.
@zq200618 I add some background information:

**Comment by fourierr** [comment]
> After talked with @zjq123456 in community meeting. We found that this is really good scenario for deploy application into clusters in high availability mod. We can use sub-steps to deploy on component to different clusters in parallel.
> 
> I propose the solution can be like this:
> 
> ```
> workflow:
>   steps:
>   - type: group
>     name: my-parent-step
>     properties:
>        ...
>     subSteps:
>      - type: deploy
>        name: deploy-comp-1
>        properties:
>            ...
> ```
> 
> The substeps are also an official field in the parent step named `steps`.
> 
> By default, the outer (parent) steps are executed by step by step, the sub-steps are executed parallel.
> 
> The sub step status must be synced into the workflow status:
> 
> ```
> status:
>   workflow:
>     steps:
>     - type: group
>       name: my-parent-step
>       message: ...
>       subSteps:
>       - type:  sub-step1
>         name: deploy-comp-1
>         message: ...
> ```
> 
> ping @leejanee @Somefive , please share your ideas.

This solution is great and very satisfied for the scenario

**Comment by Somefive** [comment]
> After talked with @zjq123456 in community meeting. We found that this is really good scenario for deploy application into clusters in high availability mod. We can use sub-steps to deploy on component to different clusters in parallel.
> 
> I propose the solution can be like this:
> 
> ```
> workflow:
>   steps:
>   - type: group
>     name: my-parent-step
>     properties:
>        ...
>     subSteps:
>      - type: deploy
>        name: deploy-comp-1
>        properties:
>            ...
> ```
> 
> The substeps are also an official field in the parent step named `steps`.
> 
> By default, the outer (parent) steps are executed by step by step, the sub-steps are executed parallel.
> 
> The sub step status must be synced into the workflow status:
> 
> ```
> status:
>   workflow:
>     steps:
>     - type: group
>       name: my-parent-step
>       message: ...
>       subSteps:
>       - type:  sub-step1
>         name: deploy-comp-1
>         message: ...
> ```
> 
> ping @leejanee @Somefive , please share your ideas.

I think if `subSteps` is designed at the same level with `properties`, then we do not need workflow step `type` and `properties` in this special step. `type`/`properties` should be exclusive with `subSteps`.

```
workflow:
  steps:
  - name: my-parent-step
    subSteps:
     - type: deploy
       name: deploy-comp-1
       properties:
           ...
```

Otherwise, we should put `subSteps` in properties to keep consistency, like 
```
workflow:
  steps:
  - type: group
    name: my-parent-step
    properties:
        subSteps:
        - type: deploy
          name: deploy-comp-1
          properties:
          ...
```

**Comment by wonderflow** [comment]
yes +1 for the new spec, this will be more clear:

```
workflow:
  steps:
  - name: my-parent-step
    subSteps:
     - type: deploy
       name: deploy-comp-1
       properties:
           ...
```

The subSteps and steps should be  exclusive fields with each other.

**Comment by Somefive** [comment]
FYI, compared to add subSteps to KubeVela workflow, an alternative solution is to develop a `multi-deploy` workflow step which is more light-weight but not so powerful as the subSteps design.
```yaml
workflow:
  steps:
    - name: deploy-step1
      type: multi-deploy
      properties:
        deploy-component1:
          policies: ["override-select-component1", "topology-c1n1", "topology-c2n1"]
        deploy-component2:
          policies: ["override-select-component2", "topology-c1n2", "topology-c2n2"]       
```
or 
```yaml
workflow:
  steps:
    - name: deploy-step1
      type: multi-deploy
      properties:
        parallel: true    
        groups:
          - name: deploy-component1
            policies: ["override-select-component1", "topology-c1n1", "topology-c2n1"]
          - name: deploy-component2
            policies: ["override-select-component2", "topology-c1n2", "topology-c2n2"]       
```

In this solution, the key is to write a `multi-deploy.cue` WorkflowStepDefinition like `deploy.cue`. There's no need to modify controller code, except that controller need to recognize the policies inside this workflow step which can be extended in function `LoadExternalPoliciesForWorkflow` in pkg/workflow/step/dependency.go.

**Comment by zq200618** [comment]
>

**Comment by wonderflow** [comment]
@zq200618 why closing this issue? I think this is meaningful.

**Comment by wonderflow** [comment]
> FYI, compared to add subSteps to KubeVela workflow, an alternative solution is to develop a `multi-deploy` workflow step which is more light-weight but not so powerful as the subSteps design.
> 
> ```yaml
> workflow:
>   steps:
>     - name: deploy-step1
>       type: multi-deploy
>       properties:
>         deploy-component1:
>           policies: ["override-select-component1", "topology-c1n1", "topology-c2n1"]
>         deploy-component2:
>           policies: ["override-select-component2", "topology-c1n2", "topology-c2n2"]       
> ```
> 
> or
> 
> ```yaml
> workflow:
>   steps:
>     - name: deploy-step1
>       type: multi-deploy
>       properties:
>         parallel: true    
>         groups:
>           - name: deploy-component1
>             policies: ["override-select-component1", "topology-c1n1", "topology-c2n1"]
>           - name: deploy-component2
>             policies: ["override-select-component2", "topology-c1n2", "topology-c2n2"]       
> ```
> 
> In this solution, the key is to write a `multi-deploy.cue` WorkflowStepDefinition like `deploy.cue`. There's no need to modify controller code, except that controller need to recognize the policies inside this workflow step which can be extended in function `LoadExternalPoliciesForWorkflow` in pkg/workflow/step/dependency.go.

@zq200618 if this proposal is adopted, hope you can also contribute to the upstream, this is good scenario.

**Comment by zq200618** [comment]
Sorry. i reopen it now. close is a fault operation

**Comment by zq200618** [comment]
Combine everyone points，I suggestion it is as bellow
```
workflow:
  steps:
    - name: step-group1
      type: step-group
      subSteps:
        - name: deploy1 
          type: deploy
          ......
```
Name and type is mandatory for all workflow step, properties and subSteps is optional according to the step type. 
For example:
Suspend step type don't have properties and subSteps
Deploy step type only have properties
Step-group step type only have subSteps

We can just support each subStep running in parallel now
I hope the step and sub-step could define clearly,  so user could get the step and sub-step execute status clearly.

**Comment by wonderflow** [comment]
@zq200618 will the `multi-deploy` more suitable and easy to implement for your case?

**Comment by zq200618** [comment]
@wonderflow  Because we need to get each components deploy process information, so maybe multi-deploy may not match my case. 
If use substep solution, a component will be set to a substep,  then I could get component deploy process information according to the substep status as you suggestion two days ago :
```
status: running
workflow:
  steps:
  - type: group
    name: my-parent-step
    message: ...
    subSteps:
    - type:  sub-step1
      name: deploy-comp-1
      message: ...
```
Meanwhile, substep solution is not so much powerful,  We could review it then make decision after I submit the PR.
