### ISSUE TITLE
Application 添加 spec.policies: [] 更新后，会删除所有应用组件的工作负载

### ISSUE THREAD

**Issue by ranger-huang** [kubevela/kubevela#3489]
**Describe the bug**

第一种情况
在首次 create 无spec.policies字段的 Application，组件 workload(如 Deployment/HelmRelease 等 ）按预期运行健康；

接着编辑 添加`spec.policies: []` 再次提交更新，Application 状态维持 `status.latestRevision.name: webapp-v1`, `status.workflow.appRevision: webapp-v1:e3b4736b7436ca17` ，

组件workload ( Deployment/HelmRelease ) 被 ***全部删除掉*** 。

第二种情况，同样出现类似问题。
首次 create 带有 spec.policies字段的Application，组件workload按预期运行； 删除 spec.policies 字段更新Application 后， 组件workload对应的资源，也被 全部删除掉。

**To Reproduce**

1.1 首次创建 application webapp
```shell 
kubectl apply -f webapp.yaml
application.core.oam.dev/webapp created
```

```yaml 
# webapp.app.yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: webapp
spec:
  components:
    - name: webapp-service
      type: webservice
      properties:
        image: nginx:1.20
    - name: webapp-cache
      properties:
        chart: redis
        pullInterval: 2m
        repoType: helm
        url: https://charts.bitnami.com/bitnami
        version: 14.8.2
        values:
          architecture: standalone
          auth:
            enabled: false
            sentinel: false
          master:
            persistence:
              enabled: false
      type: helm
  workflow:
    steps:
      - name: depends-app
        type: apply-application
```

1.2 创建结果的资源对象
```shell
$> kubectl get applicationcontext,applicationrevision,resourcetracker,deployment,helmrelease -l app.oam.dev/name=webapp

NAME                                         AGE
applicationrevision.core.oam.dev/webapp-v1   75s

NAME                                                      TYPE                 APP      APP-NS       APP-GEN
resourcetracker.core.oam.dev/webapp-comp-rev-testing-mw   component-revision   webapp   testing-mw   0
resourcetracker.core.oam.dev/webapp-v1-testing-mw         versioned            webapp   testing-mw   1

NAME                             READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/webapp-service   1/1     1            1           75s

NAME                                              READY   STATUS                             AGE
helmrelease.helm.toolkit.fluxcd.io/webapp-cache   True    Release reconciliation succeeded   73s
```

2.1 添加 spec.policies 后更新应用
```shell 
$> kubectl apply -f update-webapp.app.yaml
application.core.oam.dev/webapp configured
```

```yaml 
# update-webapp.app.yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: webapp
spec:
  components:
    - name: webapp-service
      type: webservice
      properties:
        image: nginx:1.20
    - name: webapp-cache
      properties:
        chart: redis
        pullInterval: 2m
        repoType: helm
        url: https://charts.bitnami.com/bitnami
        version: 14.8.2
        values:
          architecture: standalone
          auth:
            enabled: false
            sentinel: false
          master:
            persistence:
              enabled: false
              annotations:
                test.val: "v3"
      type: helm
  # --- Additional ---
  policies: [] 
  # --- Additional ---
  workflow:
    steps:
      - name: depends-app
        type: apply-application
```

2.2 更新应用后的资源对象
```shell
$> kubectl get applicationcontext,applicationrevision,resourcetracker,deployment,helmrelease -l app.oam.dev/name=webapp
NAME                                         AGE
applicationrevision.core.oam.dev/webapp-v1   4m39s

NAME                                                      TYPE                 APP      APP-NS       APP-GEN
resourcetracker.core.oam.dev/webapp-comp-rev-testing-mw   component-revision   webapp   testing-mw   0


$> kubectl get resourcetracker.core.oam.dev/webapp-comp-rev-testing-mw -oyaml
apiVersion: core.oam.dev/v1beta1
kind: ResourceTracker
metadata:
  creationTimestamp: "2022-03-22T02:59:48Z"
  finalizers:
  - resourcetracker.core.oam.dev/finalizer
  generation: 4
  labels:
    app.oam.dev/appRevision: webapp-v1
    app.oam.dev/name: webapp
    app.oam.dev/namespace: testing-mw
    app.oam.dev/uid: 81774c81-f3d5-4bc3-857e-7d3f52183ecb
  managedFields:
  # ...
  name: webapp-comp-rev-testing-mw
  resourceVersion: "20666142822"
  selfLink: /apis/core.oam.dev/v1beta1/resourcetrackers/webapp-comp-rev-testing-mw
  uid: 99c219f9-88bd-4063-b614-bfcc65f870fe
spec:
  applicationGeneration: 0
  type: component-revision
```

2.3  更新应用后的异常
- `deployment.apps/webapp-service`  ,  `helmrelease.helm.toolkit.fluxcd.io/webapp-cache` 被删除；
- Application 状态维持 `status.latestRevision.name: webapp-v1`, `status.workflow.appRevision: webapp-v1:e3b4736b7436ca17` 。
- workflow 没有执行， 两个应用组件没有重新部署。

**Expected behavior**

Application webapp内的应用组件，
- 在没有改变组件情况下 `deployment.apps/webapp-service`  ,  `helmrelease.helm.toolkit.fluxcd.io/webapp-cache`  不会被强行删除； 
- 改变helm组件values配置不会删除重建，helmrelease只做patch update。

**Screenshots**

**KubeVela Version**

- Vela-Core Version 1.2.1 、1.2.5  （ 大于1.1.3都出现同样的问题 ）  

**Cluster information**

- Kubernetes Version 1.19.0

**Additional context**
