### ISSUE TITLE
[Feature] Install the CRD before install the addon.

### ISSUE THREAD

**Issue by barnettZQG** [kubevela/kubevela#3566]
**Is your feature request related to a problem? Please describe.**

About the CRD of the addon, we have two obstacles:

1. There is a definition that depends on one CRD. it will create failure if CRD is not installed.

such as:
```
apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  name: helm
  namespace: vela-system
  annotations:
    definition.oam.dev/description: "helm release is a group of K8s resources from either git repository or helm repo"
spec:
  workload:
    definition:
      apiVersion: "source.toolkit.fluxcd.io/v1beta1"
      kind:       "HelmRelease"
...
```
When we install the flux addon, it will fail. because the CRD is not installed success before creating this component definition.
```
Error: cannot create object: admission webhook "mutating.core.oam-dev.v1beta1.componentdefinitions" denied the request: no matches for kind "HelmRelease" in version "source.toolkit.fluxcd.io/v1beta1"
```

2. For an addon that is deployed to runtime cluster, we must install it to the hub cluster. because we need to install the CRD. 

**Describe the solution you'd like**

1. parse all CRD in the addon. 
2. install the CRD to the hub cluster before installing the application of the addon.
