### ISSUE TITLE
[Feature]about webservice cue templete

### ISSUE THREAD

**Issue by shikingram** [kubevela/kubevela#3813]
We encountered some scenarios when using custom X-Definition, In some cases we need to use configuration properties of extended resources, E.g:
```
 resources:
      limits:
        cpu: 500m
        memory: 1Gi
        tencent.com/vcuda-memory: "24"
      requests:
        cpu: 100m
        memory: 512Mi
        tencent.com/vcuda-memory: "24"

```
The current template does not support such a setting method, we can modify it as follows
```
  if parameter.limits != _|_ {
    resources: {
      limits : {
	for k,v in parameter.limits {
	  "\(k)": v
	}
      }
    }
  }

  if parameter.requests != _|_ {
    resources: {
      requests : {
	for k,v in parameter.requests {
	  "\(k)": v
	}
      }
    }
  }
```
In this way, we can configure resource properties more flexibly

The above are just suggestions
