### ISSUE TITLE
[Feature] Add `SourceToImage` workflow step in KubeVela 

### ISSUE THREAD

**Issue by FogDong** [kubevela/kubevela#3817]
**Is your feature request related to a problem? Please describe.**

KubeVela now has the strong capability in CD but lacks in CI, we can first add `s2i` (sourceToImage) workflow step to start.

**Describe the solution you'd like**

We can refer to:
1. kaniko: https://github.com/GoogleContainerTools/kaniko
2. s2i: https://github.com/openshift/source-to-image
3. buildkit: https://github.com/moby/buildkit

**Describe alternatives you've considered**

**Additional context**

**Comment by StevenLeiZhang** [comment]
Why not Kaniko?

**Comment by FogDong** [comment]
> Why not Kaniko?

I referenced Kaniko in the first solution.

**Comment by YourTechBud** [comment]
This would be great!

**Comment by wonderflow** [comment]
refer to #3817

**Comment by FogDong** [comment]
Supported in #5199 

You can use this like:

```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: build-push-image
  namespace: default
spec:
  components:
  - name: my-web
    type: webservice
    properties:
      image: fogdong/simple-web-demo:v1
      ports:
        - port: 80
          expose: true
  workflow:
    steps:
    - name: create-git-secret
      type: export2secret
      properties:
        secretName: git-secret
        data:
          token: <git token>
    - name: create-image-secret
      type: export2secret
      properties:
        secretName: image-secret
        kind: docker-registry
        dockerRegistry:
          username: <docker username>
          password: <docker password>
    - name: build-push
      type: build-push-image
      properties:
        # use your kaniko executor image like below, if not set, it will use default image oamdev/kaniko-executor:v1.9.1
        # kanikoExecutor: gcr.io/kaniko-project/executor:latest
        # you can use context with git and branch or directly specify the context, please refer to https://github.com/GoogleContainerTools/kaniko#kaniko-build-contexts
        context:
          git: git://github.com/FogDong/simple-web-demo
          branch: main
        image: fogdong/simple-web-demo:v1
        # specify your dockerfile, if not set, it will use default dockerfile ./Dockerfile
        # dockerfile: ./Dockerfile
        credentials:
          image:
            name: image-secret
        # buildArgs:
        #   - key="value"
        # platform: linux/arm
    - name: apply-comp
      type: apply-component
      properties:
        component: my-web
```
