### ISSUE TITLE
[Feature] Can traits take effect independently of workflow?

### ISSUE THREAD

**Issue by fourierr** [kubevela/kubevela#3818]
# Can traits take effect independently of workflow?
### The scenario is as follows: 
Two components are serially dispatched to the cluster through two worflowsteps and running normally;
Then the application is modified and deployed again with some errors and the first component is dispatched incorrectly, the user wants to modify the replicas of the second component through the scaler.
However, the scaler modification of the second component cannot be completed because of an error in the first workflowstep

```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: fourierapp03
  namespace: fourier
spec:
  components:
    - name: fourierapp03-fouriercomponent-01
      type: webservice
      properties:
        image: busybox:latest
        imagePullPolicy: IfNotPresent
        cmd: [ "sleep", "10000" ]
        cpu: "0.1"
        mem: "100Mi"
    - name: fourierapp03-fouriercomponent-02
      type: webservice
      properties:
        image: busybox:latest
        imagePullPolicy: IfNotPresent
        cmd: [ "sleep", "10000" ]
        cpu: "0.1"
        mem: "100Mi"
  policies:
    - name: fourierapp03-topology-01
      type: topology
      properties:
        clusters: [ "kind01" ]
        namespace: fourier01
    - name: fourierapp03-topology-02
      type: topology
      properties:
        clusters: [ "kind02" ]
        namespace: fourier02
    - name: fourierapp03-override-01
        type: override
        properties:
          components:
            - name: fourierapp03-fouriercomponent-01
    - name: fourierapp03-override-02
        type: override
        properties:
          components:
            - name: fourierapp03-fouriercomponent-02
  workflow:
    steps:
      - type: deploy
        name: fourierapp03-deploy-01
        properties:
          policies: [ "fourierapp03-topology-01", "fourierapp03-override-01" ]
      - type: deploy
        name: fourierapp03-deploy-02
        properties:
          policies: [ "fourierapp03-topology-02","fourierapp03-override-02" ]

```

**Comment by FogDong** [comment]
That's because the workflow will not be executed if the first step is failed.
I guess if we can use `substeps` in this case, and wrap the two steps in one step, then the second step can deploy no matter the first step is failed or not.

**Comment by fourierr** [comment]
@FogDong Yes, if the user uses substeps, it can cover this issue, but the orchestration of the workflow is exposed to the user, who may not use substeps. We will first continue to clarify this problem within our team, and then we will give a detailed proposal about this issue.

**Comment by wonderflow** [comment]
In this case, we can update the workflow to reverse the steps.

**Comment by FogDong** [comment]
> @FogDong Yes, if the user uses substeps, it can cover this issue, but the orchestration of the workflow is exposed to the user, who may not use substeps. We will first continue to clarify this problem within our team, and then we will give a detailed proposal about this issue.

I think the point of this case is that our workflow is running in `StepByStep` mode.
And in this case, we don't want the latter step to have some dependency on the former one, so if we can set the workflow mode to `DAG`, we can solve the case.

**Comment by wonderflow** [comment]
This could be a good scenario for #3399

**Comment by fourierr** [comment]
@wonderflow @FogDong I think modifying replicas is just a simple `operation` And make it as easy as possible for users to use these `operations`. There are many `operations` like this, replicas, env, domian, etc. Under the above case, users must update their workflow to achieve the purpose of modifying replicas, which undoubtedly increases the burden of users.

**Comment by oeular** [comment]
If traits can take effect independently, it will bring much more efficiency to application operation, and make the complexity of application controller lower , and even more,  the architecture may be much more extensible.

**Comment by wonderflow** [comment]
>  traits can take effect independently

@fourierr @oeular Do you have any idea about how this could work?

**Comment by fourierr** [comment]
> > traits can take effect independently
> 
> @fourierr @oeular Do you have any idea about how this could work?


We think it can be implemented via a new policy type.
The purpose is to make the update to component properties or traits can take effect directly under any circumstances and without changing the workflow, it seems to a optional and independent dispatcher at the component level, and we will post a detailed plan about this proposal in the comment later.

**Comment by leejanee** [comment]
I recommend that support new trait types: `placeholder`,It work after rendering and before apply the `resource`.
For example as bellow
```
placeholder: {
   replicas: *3 | int
}

output: {
    ...
    spec: replicas: placeholder.replicas
}
```

**Comment by StevenLeiZhang** [comment]
> > @FogDong Yes, if the user uses substeps, it can cover this issue, but the orchestration of the workflow is exposed to the user, who may not use substeps. We will first continue to clarify this problem within our team, and then we will give a detailed proposal about this issue.
> 
> I think the point of this case is that our workflow is running in `StepByStep` mode. And in this case, we don't want the latter step to have some dependency on the former one, so if we can set the workflow mode to `DAG`, we can solve the case.

Maybe, we need enhance `workflow`, allow user to describe the followed action.

```
steps:
   - name: s1
     action:
       fail: skip / suspend /exit
       finish: continue
   - name: s2
```

**Comment by FogDong** [comment]
This issue can be closed since we have support `if` and `mode` in workflow.

We can now use:
```yaml
mode: 
   steps: DAG
```

or:
```yaml
steps:
   - name: mystep
      if: always
      ...
```
