### ISSUE TITLE
[Feature] workflow support  get application status for notification after `apply-application` 

### ISSUE THREAD

**Issue by rainwolf01** [kubevela/kubevela#3825]
**Is your feature request related to a problem? Please describe.**

no

In my CD workflow:
- use  `apply-application`, I want to know application status for notification
  - if application health, send notification success message
  - if some error or application unhealthy within a certain time , send notification  failed message. 

**Describe the solution you'd like**

no

**Describe alternatives you've considered**

no

**Additional context**

no

**Comment by FogDong** [comment]
Although we can make some special policies like `error-notification` to send notifications every time the workflow fails, but this solution lacks flexibility.

I think it's better if we extend our `dependsOn` to support more expressions like:

```yaml
workflow:
  steps:
      - name: A
         type: deploy
      - name: B
         type: notification
         dependsOn:
             - A.error
```

The `<step>.error` can be a special built-in expression that we'll reckon it as the failure ot the step.

We can also support some more like cue expression in `workflow context`:
```yaml
workflow:
  steps:
      - name: A
         type: deploy
      - name: B
         type: notification
         dependsOn:
             // default valid if it's true
             - A.output.status
             // or
             // - A.output.status == ready
```

WDYT? /cc @wonderflow @Somefive @leejanee

**Comment by wonderflow** [comment]
good idea @FogDong

**Comment by FogDong** [comment]
After discussing with @leejanee and @yangsoon , we noticed that `dependsOn` is not a good way to specify error state, because if the state in `dependsOn` is not satisfied, we'll wait for it until it's ready, which is kinda confused in this case.

Instead, we can add `onFailed` in workflow steps like below:
```yaml
workflow:
  // if the workflow status is suspended (due to failure after retries), then the notification will be sent.
  onFailed:
      - name: notification
         type: notification
  steps:
      - name: A
         type: deploy
         // If step A's phase is failed, then the notification will be sent.
         onFailed: 
             - name: notification
                type: notification
```

For the case @rainwolf01  mentioned：
* if some error or application unhealthy within a certain time , send notification failed message
We can add field like `retries` or `timeout` in workflow step, and if the time is reached, the step's phase should be failed.

Also, we still need a `if condition` in workflow, and if the condition is not satisfied, the step should be skipped.
For example:

```yaml
steps:
  - name: a
     phase: succeeded
  - name: b
     if: a.output.unhealthy == true
     phase: skipped
```

**Comment by wonderflow** [comment]
I propose onFailed => onFailure, and like this design.

To the `if condition` design, I'm a bit confused on your example.

**Comment by FogDong** [comment]
> Why not "webhook-notification". @rainwolf01 seems just need one notification of the deployment result

The point of this issue is to send `notification` if the former step is failed.

It's kinda like the situation you commented on the #3818 and we can discuss here.

I think it's clear to add action in workflow like you described:
```yaml
steps:
   - name: s1
     action:
       fail: skip / suspend /exit
       finish: continue
   - name: s2
```

But still, it may lack some extendability.

**Comment by FogDong** [comment]
After discussion with the team offline, we think that the `onFailure` in the workflow may be too complicated for users.
Instead, we can add a policy like:

```yaml
polices:
  - type: hook
     properties:
         phase: ["onFailure", "onGarbageCollectFinish", ...]
         notification: ....
         webhook: .....
```

**Comment by wonderflow** [comment]
@FogDong  Will the `if` keyword be able to get and check CRD exists? My scenario is to check whether a CRD exists in workflow and judge if the next step should deploy a helm chart for that CRD with Controller.

**Comment by FogDong** [comment]
> @FogDong Will the `if` keyword be able to get and check CRD exists? My scenario is to check whether a CRD exists in workflow and judge if the next step should deploy a helm chart for that CRD with Controller.

That's too complicated if we let `if` to check the CRD in the cluster, I think it's better to write a workflow step do check it.

**Comment by wonderflow** [comment]
@FogDong We have this scenario, how could the yaml like if you use a workflow step for this need?

**Comment by FogDong** [comment]
> @FogDong We have this scenario, how could the yaml like if you use a workflow step for this need?

You can use `#op.Read` to check if the CRD exists in the definition.

**Comment by wonderflow** [comment]
> You can use `#op.Read` to check if the CRD exists in the definition.

In this case, anyone build a new addon MUST learn how to write a definition in CUE, this is un-acceptable.

You can learn this use case in https://github.com/kubevela/kubevela/issues/3891

**Comment by FogDong** [comment]
> > You can use `#op.Read` to check if the CRD exists in the definition.
> 
> In this case, anyone build a new addon MUST learn how to write a definition in CUE, this is un-acceptable.
> 
> You can learn this use case in #3891

We can write a workflow step called `checkCRD` or `checkResource`, and users can use it like:

```yaml
steps:
  - name: checkCRD
     type: checkResource
     properties:
         resources:
               - kind: CustomResourceDefinition
                  name: Application
```

**Comment by wonderflow** [comment]
```
steps:
  - name: crdcheck
     type: resource-check
     properties:
         resources:
         - applications.core.oam.dev
   - name: deploy-helm
      if: crdcheck.output.exist==true
      type: deploy
      properties:
         ...
```

This would be better for me.

**Comment by barnettZQG** [comment]
> After discussion with the team offline, we think that the `onFailure` in the workflow may be too complicated for users. Instead, we can add a policy like:
> 
> ```yaml
> polices:
>   - type: hook
>      properties:
>          phase: ["onFailure", "onGarbageCollectFinish", ...]
>          notification: ....
>          webhook: .....
> ```

why do we need to create a hook policy?  In general, systems without pipeline capability will provide some fixed hook capability, the pipeline(workflow) should be more flexible, and users can accomplish similar things.

For example:
```
steps:
  - type: deploy
    name: deployapp
 - type: notification
    properties:
       sub-steps:
          - name: onFailure
             if: steps.deployapp. phase == failure
          - name: onSuccess
             if: steps.deployapp. phase == success
```

**Comment by FogDong** [comment]
> For example:

We'll also support `if` in the near future. The `hook` policy is to handle the failure of the workflow, what you said is to handle the failure of the step.

**Comment by wonderflow** [comment]
```
polices:
  - type: webhook
     properties:
         events: ["onFailure", "onGarbageCollectFinish", ...]
         notification: ....
         webhook: .....
```

**Comment by wonderflow** [comment]
I have another proposal:

```
steps:
  - type: deploy
    name: deployapp
 - type: notification
    if: always
    properties:
       notification: 
           ... events.failure
       webhook: .....
```

**Comment by FogDong** [comment]
> I have another proposal, we should support if always condition, and pass the context as arguments.
> 
> ```
> steps:
>   - type: deploy
>     name: deployapp
>  - type: notification
>     if: always
>     properties:
>        notification: 
>            ... context.events
>        webhook: .....
> ```

We can use `inputs` & `outputs` to pass the parameters like:

```yaml
steps:
 - type: deploy
   name: deployapp
   outputs:
       name: events
       valueFrom: output.event
 - name: notificationA
   if: always
   type: notification
   inputs:
      - from: events
         parameterKey: message.text
   properties:
       slack:
           url:
              value: <url>
```
