### ISSUE TITLE
[Feature] Extend apply-once policy to allow the specified path configuration to drift

### ISSUE THREAD

**Issue by fourierr** [kubevela/kubevela#3840]
## Extend apply-once policy to allow the specified path configuration to drift

**Is your feature request related to a problem? Please describe.**
One component contains both the scaler and the cpuscaler(hpa) trait. The initial replicas are set by the scaler, and the deployment is scaled by the hpa. However, now that hpa adjusts the replicas of the deployment, the scaler will also change the replicas of the deployment back.

**Describe the solution you'd like**
After an offline discussion with @Somefive ,  We have got a general idea: Solve this issue with that extend apply-once policy to allow the specified field configuration to drift.

##### Firstly, extend ApplyOncePolicySpec, DispatchOption and `ResourceTracker.ManagedResource`
- ApplyOncePolicySpec as follows.
```shell
// ApplyOncePolicySpec defines the spec of preventing configuration drift
type ApplyOncePolicySpec struct {
	Enable    bool                 `json:"enable"`
	Component []ApplyOnceComponent `json:"component"`
}
// ApplyOnceComponent defines the component allow configuration drift
type ApplyOnceComponent struct {
	Name     string              `json:"name"`
	Resource []ApplyOnceResource `json:"resource"`
}
// ApplyOnceResource defines the resource and path allow configuration drift
type ApplyOnceResource struct {
	Type string   `json:"type"`
	Path []string `json:"path"`
}
```

- DispatchOption as follows.
```shell
// MetaOnlyPartOption record only meta part in resourcetracker, which disables the configuration-drift-prevention
type MetaOnlyPartOption struct {
	ApplyOnceComponent []v1alpha1.ApplyOnceComponent
}

// ApplyToDispatchConfig apply change to dispatch config
func (option MetaOnlyPartOption) ApplyToDispatchConfig(cfg *dispatchConfig) {
	cfg.applyOnceComponent = option.ApplyOnceComponent
}
```

- `ResourceTracker.ManagedResource` as follows.
```shell
// ManagedResource define the resource to be managed by ResourceTracker
type ManagedResource struct {
	common.ClusterObjectReference `json:",inline"`
	common.OAMObjectReference     `json:",inline"`
	// +kubebuilder:pruning:PreserveUnknownFields
	Data *runtime.RawExtension `json:"raw,omitempty"`
	// Deleted marks the resource to be deleted
	Deleted bool `json:"deleted,omitempty"`
	// ApplyOncePath marks the path allows configuration drift
	ApplyOncePath []string `json:"applyOncePath"`
}
```

##### Secondly, record ApplyOncePath in ResourceTracker's ManagedResource
When the user dispatch the application, record the ApplyOncePath to the ManagedResource while recording the k8s resource through AddManagedResource.
In this way, when the `StateKeep` is executed, the ResourceTracker can obtain the ApplyOncePath and then allow the specified fields of the specified resources to be configured drift.

##### Thirdly, query the applyOncePath and reApply
When executing StateKeep, resourceKeeper first queries the specific resource in the cluster, and gets the value corresponding to ApplyOncePath.
then sets the value to `resourceKeeper.managedResource.Data`, and then continues to execute reApply.

##### Finally, an example of application with apply-once policy 
the configuration drift of the specified path of the specific k8s resource under the specific component is allowed. 
And an example of application with apply-once policy is as follows.
```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: fourierapp03
  namespace: fourier
spec:
  components:
    - name: fourierapp03-fouriercomponent-01
      type: webservice
      properties:
        image: busybox:latest
        imagePullPolicy: IfNotPresent
        cmd: [ "sleep", "10000" ]
        cpu: "0.1"
        mem: "100Mi"
      traits:
        - type: scaler
          properties:
            replicas: 1
  policies:
    - name: fourierapp03-topology-01
      type: topology
      properties:
        clusters: [ "local" ]
        namespace: fourier01
    - name: fourierapp03-topology-02
      type: topology
      properties:
        clusters: [ "local" ]
        namespace: fourier02
    - name: apply-once
      type: apply-once
      properties:
        enable: true
        component:
          - name: fourierapp03-fouriercomponent-01
            resource:
              - type: Deployment
                path: [ "spec.replicas","spec.template.spec.containers[0].image" ]
  workflow:
    steps:
      - type: deploy
        name: fourierapp03-deploy-01
        properties:
          policies: [ "fourierapp03-topology-01" ]
      - type: deploy
        name: fourierapp03-deploy-02
        properties:
          policies: [ "fourierapp03-topology-02" ]
```

**Describe the situation you'd expected**
![img_1](https://user-images.githubusercontent.com/35767528/167428191-6cec4842-4e1e-494c-9326-df01821a2b95.png)

**Additional context**
For the boundary case, we can allow the given component and the component's given resource to be configured drift.

```yaml
    - name: apply-once-01
      type: apply-once
      properties:
        enable: true
        component:
          - name: fourierapp03-fouriercomponent-01
            resource:
              - type: Deployment
                path: [ "*" ]
```

**Comment by wonderflow** [comment]
The proposal generally LGTM, how do you prepare to implement this partially statekeeper feature?

**Comment by fourierr** [comment]
> The proposal generally LGTM, how do you prepare to implement this partially statekeeper feature?

Keep the logic of the original statekeeper is first, and add a reassignment operation on resourceKeeper.Managerdresource.data.
The detailed operation is that 
- Firstly resourceKeeper queries the specific resource in corresponding cluster,
- Secondly, get the value corresponding to ApplyOncePath from the resource, 
- Thirdly, then sets the value to resourceKeeper.managedResource.Data, a
- Finally, continues to statekeep for executing reApply.

**Comment by wonderflow** [comment]
BTW, we should add a diff mechanism for the advanced apply-once policy, to avoid the following case:

1. one has an application and define apply-once polciy

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: fourierapp03
  namespace: fourier
spec:
  components:
    - name: fourierapp03-fouriercomponent-01
      type: webservice
      properties:
        image: busybox:latest
        imagePullPolicy: IfNotPresent
        cmd: [ "sleep", "10000" ]
        cpu: "0.1"
        mem: "100Mi"
      traits:
        - type: scaler
          properties:
            replicas: 1
  policies:
    - name: apply-once
      type: apply-once
      properties:
        enable: true
        component:
          - name: fourierapp03-fouriercomponent-01
            resource:
              - type: Deployment
                path: [ "spec.replicas","spec.template.spec.containers[0].image" ]
```

2. this user modify the replica of deployment directly

3. next time, the user deploy the application with new image version but didn't align the replica with the real production instace.

What will happen to it? Will it override the replica and change back to the orignal one?

To avoid this case, we need a diff and need manuel approve from user.
