### ISSUE TITLE
[Feature] Create a Template and Instance CRD for allowing Kubevela to template the Application object itself

### ISSUE THREAD

**Issue by YourTechBud** [kubevela/kubevela#3869]
**Is your feature request related to a problem? Please describe.**
The component and trait system kubevela suggests is great, but an application manifest can turn out to be very large and complex since everything is in a single file. Many developers might not have the necessary skills to even use the right components and pass the write arguments to it.

I suggest we make another CRD called "ApplicationTemplate". This will contain a cue template to render an application itself. We can use this "ApplicationTemplate" Directly in the "Application" resource or create a new crd.

This will greatly simplify developet experience and devops teams can not create different "ApplicationTemplates" for each use case they have while developers have to provide just a few parameters to create an Application from it.

**Describe the solution you'd like**
Already did above

**Describe alternatives you've considered**
Use helm to template out the "Application" object. But i was hoping to avoid helm altogether if possible.

**Additional context**

**Comment by wonderflow** [comment]
Good suggestion, this is in our roadmap. Welcome for detail design including following questions:

1. how would the ApplicationTemplate crd looks like?
2. what will the rending mechanism work? it should works in CUE align our current mechanism.
3. how could the current Application be exported as an ApplicationTemplate?
4.  and many more related considerations are welcome to discuss.

**Comment by barnettZQG** [comment]
The ApplicationTemplate is like the addon, we could base the ApplicationTemplate to define some SaaS or typical applications. So, CRD maybe is not the best shape.

**Comment by YourTechBud** [comment]
> Welcome for detail design
I'll put my thoughts down shortly.

> The ApplicationTemplate is like the addon, we could base the ApplicationTemplate to define some SaaS or typical applications. So, CRD maybe is not the best shape.

I was suggesting that we use a CRD for two reasons
- each "ApplicationTemplate" will most likely have a few input variables to template based on and can change. Kubevela operator will most likely have to keep a hot cache of all these templates in memory.
- A deployable manifest should be able to refer to this template at run time whenever the 'kubectl apply` command is invoked. I think it will be easier to manage this if the template and the instance object are applied (and hence managed) in a similar way, i.e. by the oeprator

**Comment by zhiyuone** [comment]
Is it possible to reference other components in component, to implement the ApplicationTemplate?

**Comment by YourTechBud** [comment]
> Is it possible to reference other components in component, to implement the ApplicationTemplate?

Thats a good idea. But wouldn't that make things a bit too convoluted? The end-goal I had in mind was to make an "Application" reproducible with the smallest set of inputs. Also, since components are designed to be byte sized anyways, referencing other components wouldn't really help in reducing verbosity. This is just my opinion.

**Comment by zhiyuone** [comment]
I'm not sure, but my experience with helm sub chart is very good. In helm, you can directly reference other charts as sub-charts, and you can configure all charts with just one values file.
Indeed, this is too complicated for vela.

**Comment by wonderflow** [comment]
As we already have the addon system, the application template feature will be more like the addon ( https://github.com/kubevela/catalog/tree/master/addons ). 

1. Written in CUE, have parameters and all kinds of templating&validating features leveraged with CUE.
2. Leverage OCI Infrastructure and align with Helm Charts format.

\cc @wangyikewxgm

**Comment by YourTechBud** [comment]
Hi, wanted to share how I went about implementing this for my project:

I first tried implementing my template as an addon but couldn't use it since:
1. The goal of addons seems to be to create new components definitions and not augment existing `Applications`
2. It's seems overengineered for the use case I was trying to solve for.

This is how I actually went about it:
1. Created two CRDs `AppTemplate` and `App`.
2. `AppTemplate` has the exact same spec has a normal Kubevela `Application`.
3. `App` has the same spec has a Kubevela `Application` as well. The only difference is a `appRef` field at the root level which refers to a `AppTemplate` resource.

I'm using a `AppTemplate` to define the base version of my application. It doesn't actually create a Kubevela `Application`. Example:

```yaml
apiVersion: example.com/v1alpha1
kind: AppTemplate
metadata:
  name: python-app
spec:
  components:
    - name: backend
      type: webservice
      properties:
        ports:
          - port: 11000
            expose: true
        cpu: "0.5"
        memory: "512Mi"
      traits:
        - type: cpuscaler
          properties:
            min: 1
            max: 10
            cpuUtil: 60
```

Then I create an application by:

```yaml
apiVersion: example.com/v1alpha1
kind: App
metadata:
  name: service-a
spec:
  appRef: python-app
  components:
    - name: backend
      type: webservice
      properties:
        image: myrepo/myimage:latest
      traits:
       - type: cpuscaler
          properties:
            cpuUtil: 80
```
Upon creating the above resource the controller spits out the following kubevela `Application` after recursively merging all component and trait properties defined in the `App` with the ones in `AppTemplate`

```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: service-a
spec:
  components:
    - name: backend
      type: webservice
      properties: myrepo/myimage:latest
        image: 
        ports:
          - port: 11000
            expose: true
        cpu: "0.5"
        memory: "512Mi"
      traits:
        - type: cpuscaler
          properties:
            min: 1
            max: 10
            cpuUtil: 80
```

Advantages:
1. Developers don't really have to copy paste length kubevela `Application` resources anymore. They can simply refer to a `AppTemplate` and override the properties they want. They can even add new components or traits if needed.

Disadvantages:
1. No mechanism to remove a component / trait defined in the `AppTemplate`
