### ISSUE TITLE
ApplicationRevision.spec.referredObjects  array should have exactly one sub-item

### ISSUE THREAD

**Issue by justxi1** [kubevela/kubevela#3874]
**Describe the bug**
get error when apply application
```txt
SchemaError(dev.oam.core.v1beta1.ApplicationRevision.spec.referredObjects): array should have exactly one sub-item） 
```
**To Reproduce**

yaml 
```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: cluster-app
spec:
  components:
    - name: simple-test
      type: webservice
      properties:
        image: nginx
```
I uninstall the kubevela v1.1.11 and reinstall kubevela v1.3.4 
I have execute command to clear CRD before reinstall 
```bash
kubectl get crd |grep oam | awk '{print $1}' | xargs kubectl delete crd
```
**Expected behavior**
**Screenshots**
![image](https://user-images.githubusercontent.com/39458411/168021971-d20d3588-221d-4a52-b286-92bb2dd74d19.png)

**KubeVela Version**

CLI Version: v1.3.4
Core Version: 1.3.4
GitRevision: git-d748096
GolangVersion: go1.17.9

**Cluster information**

kubernet v1.19.2

**Additional context**
