### ISSUE TITLE
no such cluster when join cluster with engine ocm 

### ISSUE THREAD

**Issue by justxi1** [kubevela/kubevela#3904]
**Describe the bug**

vela cluster join with engine ocm. when apply application which with polic topology, I get error 【no such cluster】 

**To Reproduce**

```shell
vela cluster join -n cluster-138 --engine=ocm --in-cluster-boostrap ./config-138
```
```yaml 
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: cluster-app-cluster
  namespace: gaozj
spec:
  components:
    - name: simple-test
      type: webservice
      properties:
        image: nginx:latest
    - name: simple-test-2
      type: webservice
      properties:
        image: nginx:latest
  policies:
    - name: topology-hangzhou-clusters
      type: topology
      properties:
        clusters: ["cluster-138","local"]
```

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/39458411/168550370-fe087269-5093-48aa-85f7-c54de16e0e4c.png)
![image](https://user-images.githubusercontent.com/39458411/168550442-37cd04a1-f232-419a-bc6e-ee67f421119b.png)

**KubeVela Version**
vela v1.3.4

**Cluster information**

Kubernetes Version  1.19.2
ocm 0.2.0

**Additional context**
