### ISSUE TITLE
field "name" not allowed in closed struct in the deploy-cloud-resurce step

### ISSUE THREAD

**Issue by barnettZQG** [kubevela/kubevela#3908]
**Describe the bug**

Error status:
```
steps:
    - firstExecuteTime: "2022-05-16T09:29:18Z"
      id: 7nid8gspnw
      lastExecuteTime: "2022-05-16T09:30:11Z"
      message: 'step app: step deploy: step mysql-rds: step update: run step(provider=kube,do=apply):
        cue: marshal error: app.deploy."mysql-rds".update.value.metadata: field "name"
        not allowed in closed struct'
      name: default-cloud-resource
      phase: failed
      reason: Execute
      type: deploy-cloud-resource
```

workflow:

```
workflow:
    steps:
    - name: default-cloud-resource
      properties:
        env: default
        policy: env-bindings-default
      type: deploy-cloud-resource
    - name: default
      properties:
        policies:
        - default
      type: deploy
```

This application has two components(alibab-rds, webservice).

**To Reproduce**

1. create and deploy an application with both cloud service component and webservice component.
2. use the deploy-cloud-resource workflow step.

**KubeVela Version**

master
