### ISSUE TITLE
[Bug](addon): `context` not available in trait's outputs section

### ISSUE THREAD

**Issue by cnfatal** [kubevela/kubevela#3917]
**Describe the bug**
 
Example trait:

```yaml
"argo-rollouts": {
    type: "trait"
    annotations: {}
    labels: {}
    description: "Bundle component."
    attributes: {
        appliesToWorkloads: ["*"]
    }
}
template: {
    outputs: rollouts: {
        apiVersion: "argoproj.io/v1alpha1"
        kind:       "Rollout"
        metadata: {
            name:      context.output.metadata.name
            namespace: context.output.metadata.namespace
        }
        spec: {
            workloadRef: {
                apiVersion: context.output.apiVersion
                kind:       context.output.kind
                name:       context.output.metadata.name
            }
        }
    }
    parameter: {}
}

```

Error on application:
```log
workflow:
    appRevision: nginx-v1:89f7b133aef46d4d
    contextBackend:
      name: workflow-nginx-context
      uid: 8ee17db4-7ca9-445c-b89d-42683464e6e5
    finished: false
    message: The workflow suspends automatically because the failed times of steps
      have reached the limit
    mode: DAG
    startTime: "2022-05-17T07:29:22Z"
    steps:
    - firstExecuteTime: "2022-05-17T07:29:23Z"
      id: oaekr8oajc
      lastExecuteTime: "2022-05-17T07:30:15Z"
      message: 'step apply: run step(provider=oam,do=component-apply): GenerateComponentManifest:
        evaluate trait=rollouts template for component=nginx app=nginx: failed to
        have the workload/trait unstructured: metadata.name: reference "context" not
        found (and 4 more errors)'
      name: nginx
      phase: failed
      reason: Execute
      type: apply-component
```

**To Reproduce**

```sh
vela def apply argo-rollouts.cue
kubectl apply -f tmp/demo-app.yaml 
```
Sample application:

```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: nginx
  namespace: default
spec:
  components:
    - name: nginx
      type: webservice
      properties:
        image: docker.io/library/nginx
        name: nginx
      traits:
        - type: argo-rollouts
```

**Expected behavior**

context can be used at outputs section.

**Screenshots**
 
**KubeVela Version**

release-1.3

**Cluster information**
 
**Additional context**
