### ISSUE TITLE
trait env 新增环境变量工作流执行失败

### ISSUE THREAD

**Issue by yonget** [kubevela/kubevela#3978]
**Describe the bug**
在应用中使用默认env trait，添加不存在的key会导致工作流失败。
**To Reproduce**

1. 使用的trait
```
env: {
	type: "trait"
	annotations: {}
	labels: {
		"ui-hidden": "true"
	}
	description: "Add env on K8s pod for your workload which follows the pod spec in path 'spec.template'"
	attributes: appliesToWorkloads: ["*"]
}
template: {
	#PatchParams: {
		// +usage=Specify the name of the target container, if not set, use the component name
		containerName: *"" | string
		// +usage=Specify if replacing the whole environment settings for the container
		replace: *false | bool
		// +usage=Specify the  environment variables to merge, if key already existing, override its value
		env: [string]: string
		// +usage=Specify which existing environment variables to unset
		unset: *[] | [...string]
	}
	PatchContainer: {
		_params: #PatchParams
		name:    _params.containerName
		_delKeys: {for k in _params.unset {"\(k)": ""}}
		_baseContainers: context.output.spec.template.spec.containers
		_matchContainers_: [ for _container_ in _baseContainers if _container_.name == name {_container_}]
		_baseContainer: *_|_ | {...}
		if len(_matchContainers_) == 0 {
			err: "container \(name) not found"
		}
		if len(_matchContainers_) > 0 {
			_baseContainer: _matchContainers_[0]
			_baseEnv:       _baseContainer.env
			if _baseEnv == _|_ {
				// +patchStrategy=replace
				env: [ for k, v in _params.env if _delKeys[k] == _|_ {
					name:  k
					value: v
				}]
			}
			if _baseEnv != _|_ {
				_baseEnvMap: {for envVar in _baseEnv {"\(envVar.name)": envVar}}
				// +patchStrategy=replace
				env: [ for envVar in _baseEnv if _delKeys[envVar.name] == _|_ && !_params.replace {
					name: envVar.name
					if _params.env[envVar.name] != _|_ {
						value: _params.env[envVar.name]
					}
					if _params.env[envVar.name] == _|_ {
						if envVar.value != _|_ {
							value: envVar.value
						}
						if envVar.valueFrom != _|_ {
							valueFrom: envVar.valueFrom
						}
					}
				}] + [ for k, v in _params.env if _delKeys[k] == _|_ && (_params.replace || _baseEnvMap[k] == _|_) {
					v
				}]
			}
		}
	}
	patch: spec: template: spec: {
		if parameter.containers == _|_ {
			// +patchKey=name
			containers: [{
				PatchContainer & {_params: {
					if parameter.containerName == "" {
						containerName: context.name
					}
					if parameter.containerName != "" {
						containerName: parameter.containerName
					}
					replace: parameter.replace
					env:     parameter.env
					unset:   parameter.unset
				}}
			}]
		}
		if parameter.containers != _|_ {
			// +patchKey=name
			containers: [ for c in parameter.containers {
				if c.containerName == "" {
					err: "containerName must be set for containers"
				}
				if c.containerName != "" {
					PatchContainer & {_params: c}
				}
			}]
		}
	}

	parameter: *#PatchParams | close({
		// +usage=Specify the environment variables for multiple containers
		containers: [...#PatchParams]
	})

	errs: [ for c in patch.spec.template.spec.containers if c.err != _|_ {c.err}]
}
```
2. 部署的Application
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: env-patch
spec:
  components:
    - name: express-server
      properties:
        cmd:
          - node
          - server.js
        image: oamdev/testapp:v1
        cpu: "0.2"
        memory: 256Mi
        port: 8080
        env:
          - name: myenv1
            value: myvalue1
          - name: myenv2
            value: myvalue2
          - name: myenv3
            value: myvalue3
      traits:
        - type: env
          properties:
            env:
              myenv2: patch2
              myenv4: myvalue4
              myenv5: myvalue5
            unset:
              - myenv3
      type:
        webservice
```
3. 部署应用
`vela up -f env-patch.yaml -n default`
`vela status env-patch -n default`
7. error
```bash
About:

  Name:         env-patch                    
  Namespace:    default                      
  Created at:   2022-05-25 13:56:15 +0800 CST
  Status:       workflowSuspending           

Workflow:

  mode: DAG
  finished: false
  Suspend: true
  Terminated: false
  Steps
  - id:gorwlhdedx
    name:express-server
    type:apply-component
    phase:failed 
    message:step apply: run step(provider=oam,do=component-apply): Dispatch: Found 1 errors. [(cannot calculate patch by computing a three way diff: list element types are not identical: [[map[name:myenv1 value:myvalue1] map[name:myenv2 value:myvalue2] map[name:myenv3 value:myvalue3]] [map[name:myenv1 value:myvalue1] map[name:myenv2 value:patch2] myvalue4 myvalue5]])]

Services:
```
**Expected behavior**
期望工作流apply成功

**Screenshots**

<img width="589" alt="image" src="https://user-images.githubusercontent.com/16254612/170198007-a9c6561f-8abc-4252-acb0-0ea76ca3bb9e.png">
推测是env.cue 第58行代码引起的bug

**KubeVela Version**

```bash
CLI Version: v1.3.5
Core Version: 1.3.5
GitRevision: git-cbed2b5
GolangVersion: go1.17.10
```
**Cluster information**

```bash
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5+k3s2", GitCommit:"724ef700bab896ff252a75e2be996d5f4ff1b842", GitTreeState:"clean", BuildDate:"2021-10-05T19:59:14Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```
**Additional context**
