### ISSUE TITLE
trait env两个以上的env会触发error

### ISSUE THREAD

**Issue by yonget** [kubevela/kubevela#3979]
**Describe the bug**

在application添加两个以上type为env的trait，部署不成功
**To Reproduce**

- trait env yaml
```
env: {
	type: "trait"
	annotations: {}
	labels: {
		"ui-hidden": "true"
	}
	description: "Add env on K8s pod for your workload which follows the pod spec in path 'spec.template'"
	attributes: appliesToWorkloads: ["*"]
}
template: {
	#PatchParams: {
		// +usage=Specify the name of the target container, if not set, use the component name
		containerName: *"" | string
		// +usage=Specify if replacing the whole environment settings for the container
		replace: *false | bool
		// +usage=Specify the  environment variables to merge, if key already existing, override its value
		env: [string]: string
		// +usage=Specify which existing environment variables to unset
		unset: *[] | [...string]
	}
	PatchContainer: {
		_params: #PatchParams
		name:    _params.containerName
		_delKeys: {for k in _params.unset {"\(k)": ""}}
		_baseContainers: context.output.spec.template.spec.containers
		_matchContainers_: [ for _container_ in _baseContainers if _container_.name == name {_container_}]
		_baseContainer: *_|_ | {...}
		if len(_matchContainers_) == 0 {
			err: "container \(name) not found"
		}
		if len(_matchContainers_) > 0 {
			_baseContainer: _matchContainers_[0]
			_baseEnv:       _baseContainer.env
			if _baseEnv == _|_ {
				// +patchStrategy=replace
				env: [ for k, v in _params.env if _delKeys[k] == _|_ {
					name:  k
					value: v
				}]
			}
			if _baseEnv != _|_ {
				_baseEnvMap: {for envVar in _baseEnv {"\(envVar.name)": envVar}}
				// +patchStrategy=replace
				env: [ for envVar in _baseEnv if _delKeys[envVar.name] == _|_ && !_params.replace {
					name: envVar.name
					if _params.env[envVar.name] != _|_ {
						value: _params.env[envVar.name]
					}
					if _params.env[envVar.name] == _|_ {
						if envVar.value != _|_ {
							value: envVar.value
						}
						if envVar.valueFrom != _|_ {
							valueFrom: envVar.valueFrom
						}
					}
				}] + [ for k, v in _params.env if _delKeys[k] == _|_ && (_params.replace || _baseEnvMap[k] == _|_) {
					v
				}]
			}
		}
	}
	patch: spec: template: spec: {
		if parameter.containers == _|_ {
			// +patchKey=name
			containers: [{
				PatchContainer & {_params: {
					if parameter.containerName == "" {
						containerName: context.name
					}
					if parameter.containerName != "" {
						containerName: parameter.containerName
					}
					replace: parameter.replace
					env:     parameter.env
					unset:   parameter.unset
				}}
			}]
		}
		if parameter.containers != _|_ {
			// +patchKey=name
			containers: [ for c in parameter.containers {
				if c.containerName == "" {
					err: "containerName must be set for containers"
				}
				if c.containerName != "" {
					PatchContainer & {_params: c}
				}
			}]
		}
	}

	parameter: *#PatchParams | close({
		// +usage=Specify the environment variables for multiple containers
		containers: [...#PatchParams]
	})

	errs: [ for c in patch.spec.template.spec.containers if c.err != _|_ {c.err}]
}
```
- applicatoin yaml
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: env-patch
spec:
  components:
    - name: express-server
      properties:
        cmd:
          - node
          - server.js
        image: oamdev/testapp:v1
        cpu: "0.2"
        memory: 256Mi
        port: 8080
        env:
          - name: myenv1
            value: myvalue1
          - name: myenv2
            value: myvalue2
          - name: myenv3
            value: myvalue3
      traits:
        - type: env
          properties:
            env:
              myenv1: myvalue-trait-patched1
        - type: env
          properties:
            env:
              myenv2: myvalue-trait-patched2
        - type: env
          properties:
            env:
              myenv3: myvalue-trait-patched3

      type:
        webservice
```
`vela up -f env-patch.yaml -n default`
- error
```bash
Applying an application in vela K8s object format...
I0525 14:54:14.438588    6748 apply.go:107] "patching object" name="env-patch" resource="core.oam.dev/v1beta1, Kind=Application"
error: cannot patch object: admission webhook "validating.core.oam.dev.v1beta1.applications" denied the request: field "schematic": Invalid value error encountered, cannot evaluate trait "env": invalid template of trait env after merge with parameter and context: patch.spec.template.spec.containers.0._baseContainer._baseEnvMap.myenv1.value: from source (and 1 more errors). 
```
**Expected behavior**

期望application apply 成功
**Screenshots**

**KubeVela Version**

```bash
CLI Version: v1.3.5
Core Version: 1.3.5
GitRevision: git-cbed2b5
GolangVersion: go1.17.10
```
**Cluster information**

```bash
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5+k3s2", GitCommit:"724ef700bab896ff252a75e2be996d5f4ff1b842", GitTreeState:"clean", BuildDate:"2021-10-05T19:59:14Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```
**Additional context**

**Comment by wonderflow** [comment]
apply the same trait more than once is not supported, why don't use as below:

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: env-patch
spec:
  components:
    - name: express-server
      properties:
        cmd:
          - node
          - server.js
        image: oamdev/testapp:v1
        cpu: "0.2"
        memory: 256Mi
        port: 8080
        env:
          - name: myenv1
            value: myvalue1
          - name: myenv2
            value: myvalue2
          - name: myenv3
            value: myvalue3
      traits:
        - type: env
          properties:
            env:
              myenv1: myvalue-trait-patched1
              myenv2: myvalue-trait-patched2
              myenv3: myvalue-trait-patched3
      type:
        webservice
```

**Comment by yonget** [comment]
有些场景可能需要这样使用，比如自定义三种trait：日志采集  jvm监控  skywalking注入的开关。三个自定义trait都有可能需要修改env。

**Comment by wonderflow** [comment]
自定义trait换个名字是可以patch env的

**Comment by yonget** [comment]
我复制了env.cue的源码到env1.cue env2.cue并重新命名trait type为env1和env2，然后使用下面的env-patch.yaml部署
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: env-patch
spec:
  components:
    - name: express-server
      properties:
        cmd:
          - node
          - server.js
        image: oamdev/testapp:v1
        port: 8080
        env:
          - name: myenv1
            value: myvalue1
          - name: myenv2
            value: myvalue2
      traits:
        - type: env
          properties:
            env:
              myenv1: myvalue-trait-patched
        - type: env1
          properties:
            env:
              myenv2: myvalue-trait-patched2
        - type: env2
          properties:
            env:
              myenv3: myvalue-trait-patched3
      type: webservice
```
`vela up -f env-patch.yaml -n default`
output:
```
Applying an application in vela K8s object format...
I0525 17:46:52.441709   27792 apply.go:107] "creating object" name="env-patch" resource="core.oam.dev/v1beta1, Kind=Application"
error: cannot create object: admission webhook "validating.core.oam.dev.v1beta1.applications" denied the request: field "schematic": Invalid value error encountered, cannot evaluate trait "env2": invalid template of trait env2 after merge with parameter and context: patch.spec.template.spec.containers.0._baseContainer._baseEnvMap.myenv1.value: from source (and 1 more errors). 
```

**Comment by Somefive** [comment]
Should be fixed in https://github.com/kubevela/kubevela/pull/4207 .
I tried the application below
```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: env-patch
spec:
  components:
    - name: express-server
      properties:
        cmd:
          - node
          - server.js
        image: oamdev/testapp:v1
        cpu: "0.2"
        memory: 256Mi
        port: 8080
        env:
          - name: myenv1
            value: myvalue1
          - name: myenv2
            value: myvalue2
          - name: myenv3
            value: myvalue3
      traits:
        - type: env
          properties:
            env:
              myenv1: myvalue-trait-patched1
        - type: env
          properties:
            env:
              myenv2: myvalue-trait-patched2
        - type: env
          properties:
            env:
              myenv3: myvalue-trait-patched3

      type:
        webservice
```
It works in v1.5.0-alpha.2.

Feel free to reopen it if there is any further bug / feature requests.
