### ISSUE TITLE
[Feature] support apply Traits with Helm Component

### ISSUE THREAD

**Issue by wonderflow** [kubevela/kubevela#4024]
### Discussed in https://github.com/kubevela/kubevela/discussions/3918

<div type='discussions-op-text'>

<sup>Originally posted by **MaharaJothi** May 17, 2022</sup>
Hi

I want to apply a helm package using `Helm Component` and deploy ingress service for the same via `Trait`.

## Issue Description:
I'm installing a helm package using `Helm` component which doesn't expose its service.  So in order to access it, after installing the package, I tried to expose using Ingress controller by `Trait` as below:

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: ksqldb
  namespace: ksqldb
spec:
  components:
    - name: ksqldb
      type: helm
      properties:
        chart: ksqldb
        version: 0.1.0
      traits:
        - type: ingress
          properties:
            domain: ${ksqldomain}
            http:
              "/": 8088
```

Upon applying this YAML, the application shows `runningWorkFlow` and doesnt apply Helm chart but only the trait.
While describing the application, I don't see any error either.

However, without the trait, am able to deploy the helm package successfully.
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: ksqldb
  namespace: ksqldb
spec:
  components:
    - name: ksqldb
      type: helm
      properties:
        chart: ksqldb
        version: 0.1.0
```

Does KubeVela support applying Trait for a Helm Component?
Thanks in advance.</div>
