### ISSUE TITLE
[Feature] Parallel deploy step in Golang

### ISSUE THREAD

**Issue by phantomnat** [kubevela/kubevela#4035]
**Is your feature request related to a problem? Please describe.**

In an Application, we deploy around 20 clusters with a combination of parallel like 2 -> 4 -> 4 and so on with a custom parallel deploy step. 

<details>
<summary>parallel-deploy.cue</summary>

```cue
import (
	"vela/op"
)

"parallel-deploy": {
	type: "workflow-step"
	annotations: {}
	labels: {}
	description: "Deploy components with policies."
}
template: {
	deploy: op.#Steps & {
        for idx, _policies in parameter.multiPolicies {
            "\(idx)": op.#Steps & {
                load: op.#Load @step(1)

                _components: [ for k, v in load.value {v}]
                policiesInOrder: op.#LoadPoliciesInOrder & {
                    input: _policies
                } @step(2)

                _outputPolicies: policiesInOrder.output
                deployPolicies: op.#HandleDeployPolicies & {
                    inputs: {
                        components: _components
                        policies:   _outputPolicies
                    }
                } @step(3)

                _decisions:         deployPolicies.outputs.decisions
                _patchedComponents: deployPolicies.outputs.components
                _deploy:            op.#Steps & {
                    for decision in _decisions {
                        for key, comp in _patchedComponents {
                            "\(decision.cluster)-\(decision.namespace)-\(key)": op.#ApplyComponent & {
                                value: comp
                                waitHealthy: parameter.wait

                                if decision.cluster != _|_ {
                                    cluster: decision.cluster
                                }
                                if decision.namespace != _|_ {
                                    namespace: decision.namespace
                                }
                            }
                        }
                    }
                } @step(4)
            }
        }
	}
	parameter: {
        wait: *false | bool
		multiPolicies?: [...multiPolicy]
	}

    multiPolicy: [...string]
}
```
</details>

<details>
<summary>example workflows</summary>

```yaml
  workflow:
    steps:
    - name: deploy-hk-canary
      properties:
        wait: false
        multiPolicies:
        - [topology-hk-2i, "component-hk-2i", "canary-10-percent"]
        - [topology-hk-2j, "component-hk-2j", "canary-10-percent"]
      type: parallel-deploy

    - name: wait-hk-canary
      properties:
        wait: true
        multiPolicies:
        - [topology-hk-2i, "component-hk-2i", "canary-10-percent"]
        - [topology-hk-2j, "component-hk-2j", "canary-10-percent"]
      type: parallel-deploy
```
</details>

**Describe the solution you'd like**

As the project moved `deploy` workflow step from cue to Golang.

Can I add the `waitHealty` in `deploy`?

**Describe alternatives you've considered**

**Additional context**
