### ISSUE TITLE
Fail to delete applications due lack of dependency between components when using terraform

### ISSUE THREAD

**Issue by alisson276** [kubevela/kubevela#4045]
**Describe the bug**

When deleting a bunch of components in the same application using the terraform addon, the controller decides to delete them in order of creation, however, depending of the provider (in my case is Azure) it requires some order (delete all resources under a resource group and after this deleting the resource group itself).

**To Reproduce**

1. Configure the terraform and terraform-azure addons
```
vela addon install terraform
vela addon install terraform-azure
vela provider add terraform-azure --ARM_CLIENT_ID $ARM_CLIENT_ID --ARM_CLIENT_SECRET $ARM_CLIENT_SECRET --ARM_SUBSCRIPTION_ID $ARM_SUBSCRIPTION_ID --ARM_TENANT_ID $ARM_TENANT_ID --name azure -n vela-system
```
2. Create a Virtual Machine ComponentDefinition
```
apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  annotations:
    definition.oam.dev/description: Terraform configuration for Azure Cloud Virtual Machine object
  labels:
    type: terraform
  name: azure-virtual-machine
  namespace: vela-system
spec:
  workload:
    definition:
      apiVersion: terraform.core.oam.dev/v1beta1
      kind: Configuration
    type: configurations.terraform.core.oam.dev
  schematic:
    terraform:
      configuration: |
        provider "azurerm" {
          features {}
        }

        data "azurerm_subnet" "vnet" {
          name                 = var.subnet_name
          virtual_network_name = var.vnet_name
          resource_group_name  = var.subnet_rg_name
        }

        module "server" {
          source              = "Azure/compute/azurerm"
          resource_group_name = var.resource_group
          nb_instances        = var.instance_count
          vm_os_simple        = var.os
          public_ip_dns       = [var.hostname]
          vnet_subnet_id      = data.azurerm_subnet.vnet.id
          location            = var.location
          vm_hostname         = var.hostname
          vm_size             = var.vm_size
          ssh_key             = ""
          ssh_key_values      = [var.ssh_key]
        }

        variable "resource_group" {
          description = "Resource group name"
          type = string
          default = "example"
        }

        variable "subnet_name" {
          description = "Subnet Name"
          type = string
        }

        variable "vnet_name" {
          description = "Virtual Network Name"
          type = string
        }

        variable "subnet_rg_name" {
          description = "Resource group of the Subnet"
          type = string
        }

        variable "instance_count" {
          description = "Specify the number of vm instances."
          type        = number
          default     = 1
        }

        variable "hostname" {
          description = "VM instance name"
          type = string
          default = "linux-server"
        }

        variable "location" {
          description = "Azure Location"
          type = string
          default = "westeurope"
        }

        variable "os" {
          description = "Specify UbuntuServer, WindowsServer, RHEL, openSUSE-Leap, CentOS, Debian, CoreOS or SLES"
          type = string
          default = "UbuntuServer"
        }

        variable "vm_size" {
          description = "VM size"
          type = string
          default = "Standard_B1s"
        }
        
        variable "ssh_key" {
          description = "SSH Public Key"
          type = string
        }

        output "vm_public_name" {
          value = module.server.public_ip_dns_name
        }

        output "vm_public_ip" {
          value = module.server.public_ip_address
        }
      deleteResource: true
      providerRef:
        name: azure
        namespace: default
```
3. Edit the current azure-subnet (the current one doesn't work)
```
kubectl patch componentDefinitions azure-subnet -n vela-system --type merge -p '{"spec":{"schematic":{"terraform": {"configuration": "https://github.com/alisson276/terraform-modules.git"}}}}'
```
4. Create a file called first-vm.yaml:
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: vm-1
spec:
  components:
    - name: example-rg
      type: azure-resource-group
      properties:
        location: westeurope
        name: example1
        writeConnectionSecretToRef:
          name: example-rg
    - name: example-virtual-network
      type: azure-subnet
      properties:
        vnet_name: vnet-1
        create_network: true
        resource_group_name: example1
        subnet_prefixes:
          - 10.0.0.0/24
        subnet_names:
          - subnet-1
        writeConnectionSecretToRef:
          name: example-vnet
    - name: vm-1-1
      type: azure-virtual-machine
      properties:
        instance_count: 1
        subnet_name: subnet-1
        vnet_name: vnet-1
        subnet_rg_name: example1
        resource_group: example
        hostname: kubevela
        writeConnectionSecretToRef:
          name: vm1-conn
```
5. Apply it:
```
vela up -f first-vm.yaml
```
6. Wait untill all resource are healthy
7. vela delete vm-1

**Expected behavior**

As you can see in the components, the second component is a subnet under example1 resource group (the first component). The problem is: the virtual machine is in another resource group (example) and it has a NIC associate to it, which is linked to the subnet. So if you try to delete the first component created first, the resource group, it fails, because the vnet (the second resource) is under it and can't be deleted because the third resource (the vm) wasn't destroyed yet.

The idea is to have a way to refer it as `depends_on` (saying that the vm depends on the vnet and the vnet depends on the resource group) or simply delete them in the reverse order that they were created.

**Screenshots**

**KubeVela Version**

CLI Version: master
Core Version: 1.3.6
GitRevision: git-c8264b8c
GolangVersion: go1.18.2

**Cluster information**

Kubernetes version: 1.22.9

**Additional context**

**Comment by zzxwill** [comment]
@alisson276 Thanks for reporting this issue.
Did the application `vm-1` fail to delete?
When deleting the application, three jobs will be created to delete each of the comments. Of course, as you said, two of them will fail, but they will retry later until there is no dependency.

As you mentioned the order to ensure the deletion for the dependent components, @FogDong implemented the mechanism to reversely delete resources per the depend_on flag, which will be soon released in v1.4.0.

**Comment by FogDong** [comment]
It is fixed in #4063 , you can check to docs here to check if it meets your requirements: https://github.com/kubevela/kubevela/blob/master/docs/examples/app-with-policy/gc-policy/reverse-dependency.md

**Comment by alisson276** [comment]
@zzxwill, it's applied serially as far as I see, because all there was just one job running and other ones were pending. The problem is the first one got stuck, because the resource group never gets deleted. I needed to deleted the virtual machine through the Azure Portal then the resource group could be deleted, but the next jobs never was completed, because I deleted the virtual machine manually.

@FogDong , which version is this available? 1.4?

**Comment by FogDong** [comment]
> @zzxwill, it's applied serially as far as I see, because all there was just one job running and other ones were pending. The problem is the first one got stuck, because the resource group never gets deleted. I needed to deleted the virtual machine through the Azure Portal then the resource group could be deleted, but the next jobs never was completed, because I deleted the virtual machine manually.
> 
> @FogDong , which version is this available? 1.4 only?

Yes, this feature will be released in v1.4 and it is not released yet, you can use the master branch to give it a try.

**Comment by wonderflow** [comment]
It's released just now. https://github.com/kubevela/kubevela/releases/tag/v1.4.0

**Comment by zzxwill** [comment]
> @zzxwill, it's applied serially as far as I see, because all there was just one job running and other ones were pending. The problem is the first one got stuck, because the resource group never gets deleted. I needed to deleted the virtual machine through the Azure Portal then the resource group could be deleted, but the next jobs never was completed, because I deleted the virtual machine manually.

@FogDong In theory, these should be three jobs running to delete the resource respectively. Was the components deleted one by one?

**Comment by FogDong** [comment]
> nt is a subnet under example1 resource group (the first component). The problem is: the virtual machine is in another resource group (example) and it has a NIC associate to it, which is linked to the subnet. So if you try to delete the first component created first, the resource group, it fails, because the vnet (the second resource) is under it and can't be deleted because the third resource (the vm) wasn't destroyed yet.
> 
> The idea is to have a way to refer it as `depends_on` (saying that the vm depends on the vnet and the vnet depends on the resource group) or simply delete them in the reverse order t

If you specify components with `dependsOn` in Application like:

```
A dependsOn _
B dependsOn _
C dependsOn A, B
D dependsOn C
E dependsOn C, D
```

the order of creation is:  A, B -> C -> D -> E

the order of gc (with the gc dependency policy specified) is: E -> D -> C -> A, B

**Comment by alisson276** [comment]
I tested the dependsOn changing the order of the components and it worked.
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: vm-1
spec:
  components:
    - name: vm-1-1
      type: azure-virtual-machine
      properties:
        instance_count: 2
        subnet_name: subnet-1
        vnet_name: vnet-1
        subnet_rg_name: example1
        resource_group: example
        hostname: kubevela
        providerRef:
          name: azure-personal
        writeConnectionSecretToRef:
          name: vm1-conn
      dependsOn:
        - example-virtual-network
    - name: example-virtual-network
      type: azure-subnet
      properties:
        vnet_name: vnet-1
        create_network: true
        resource_group_name: example1
        subnet_prefixes:
          - 10.0.0.0/24
        subnet_names:
          - subnet-1
        providerRef:
          name: azure-personal
        writeConnectionSecretToRef:
          name: example-vnet
      dependsOn:
        - example-rg
    - name: example-rg
      type: azure-resource-group
      properties:
        location: westeurope
        name: example1
        providerRef:
          name: azure-personal
        writeConnectionSecretToRef:
          name: example-rg
```

Now the deletion is running parallel, don't know what happen before on my setup that only one was running at a time. But you can consider it closed.

**Comment by FogDong** [comment]
> https://github.com/kubevela/kubevela/blob/master/docs/examples/app-with-policy/gc-policy/reverse-dependency.md

Hi, please add gc policy in your application like:

```yaml
  policies:
    - name: gc-dependency
      type: garbage-collect
      properties:
        order: dependency
```

Docs here: https://github.com/kubevela/kubevela/blob/master/docs/examples/app-with-policy/gc-policy/reverse-dependency.md
