### ISSUE TITLE
[Feature] Support more expressions in if

### ISSUE THREAD

**Issue by FogDong** [kubevela/kubevela#4087]
**Is your feature request related to a problem? Please describe.**

Right now we support `if` in the workflow step, we can support more expressions in if like:

```yaml
workflow:
  steps:
      - name: A
         type: A
      - name: B
         type: B
         if: A.status.phase == failed && A.status.reason == timeout
```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
