### ISSUE TITLE
[Feature] add a `note.cue` file in the addon

### ISSUE THREAD

**Issue by fourierr** [kubevela/kubevela#4114]
**Is your feature request related to a problem? Please describe.**

- As we discussed in https://github.com/kubevela/kubevela/pull/4108
- Hardcode for every add-on is a disaster. e.g
https://github.com/kubevela/kubevela/blob/05b45fa52cb1727cc8b9f1148126b19dd21841a3/references/cli/addon.go#L203

**Describe the solution you'd like**
- Refer to helm and align with helm chart Note.txt https://helm.sh/docs/chart_template_guide/notes_files/
- we want to add a 'note' field in the `addon's metadata.yaml`, e.g
```yaml
name: pyroscope
version: 0.17.1
description: Pyroscope is an open source platform, consisting of server and agent. It allows the user to collect, store, and query the profiling data in a CPU and disk efficient way.
url: https://github.com/pyroscope-io/pyroscope
icon: https://raw.githubusercontent.com/pyroscope-io/pyroscope/main/webapp/images/favicon.ico

tags:
  - profiling tool

deployTo:
  control_plane: true

dependencies:
  - name: fluxcd

needNamespace:
  - pyroscope-system

invisible: false

note:
 - Thank you for installing parameter["image.repository"].
 - The image is parameter["image.repository"].
 - To learn more about the pyroscope, try:
 - first-msg
 - second-msg
```
- The `parameter["image.repository"]` and `parameter["image.repository"]` will get the value from resource's parameter.cue. e.g
```cue
parameter: {
	// +usage=Specify the image hub of velaux, eg. "acr.kubevela.net"
	repo?: string
	// +usage=Specify the database type, current support KubeAPI(default) and MongoDB.
	dbType: *"kubeapi" | "mongodb"
	// +usage=Specify the database name, for the kubeapi db type, it represents namespace.
	database?: string
	// +usage=Specify the MongoDB URL. it only enabled where DB type is MongoDB.
	dbURL?: string
	// +usage=Specify the domain, if set, ingress will be created if the gateway driver is nginx.
	domain?: string
	// +usage=Specify the gateway type.
	gatewayDriver: *"nginx" | "traefik"
	// +usage=Specify the serviceAccountName for apiserver
	serviceAccountName: *"kubevela-vela-core" | string
	// +usage=Specify the service type.
	serviceType: *"ClusterIP" | "NodePort" | "LoadBalancer" | "ExternalName"
	// +usage=Specify the names of imagePullSecret for private image registry, eg. "{a,b,c}"
	imagePullSecrets?: [...string]
	// +usage=Specify whether to enable the dex
	dex: *"false" | "true"
}
```

**Additional context**
ping @wonderflow  @barnettZQG @wangyikewxgm
