### ISSUE TITLE
[Feature]how to impl it one application delivery difference cluster and notify diff msg

### ISSUE THREAD

**Issue by rainwolf01** [kubevela/kubevela#4158]
**Is your feature request related to a problem? Please describe.**

same application:
- deploy `dev`  notify dev deploy ok   
- deploy `test`  notify test deploy ok

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: foo-app
  namespace: examples
spec:
  components:
    - name: nginx
      type: webservice
      properties:
        image: nginx:1.20
  policies:
    - name: topology-dev
      type: topology
      properties:
        clusters: ["local"]
        namespace: dev
    - name: topology-test
      type: topology
      properties:
        clusters: ["local"]
        namespace: test
    - name: override-hadev
      type: override
      properties:
        components:
        - type: webservice
          properties:
          traits:
          - type: scaler
            properties:
              replicas: 1
    - name: override-hatest
      type: override
      properties:
        components:
        - type: webservice
          properties:
          traits:
          - type: scaler
            properties:
              replicas: 2
  workflow:
    steps:
      - type: deploy
        name: deploy-dev
        properties:
          policies: ["topology-dev", "override-hadev"]
      - type: deploy
        name: deploy-test
        properties:
          policies: ["topology-test", "override-hatest"]
      - name: dingtalk-deploy-dev
        type: notification
        properties:
          dingding:
            url:
              secretRef:
                name: secret-dingtalk
                key: url
            message:
              msgtype: markdown
              markdown:
                title: "deploy success"
                text: "deploy success, env=dev,service=foo-app"  ## if use workflow ref, need get component name or application name "foo-app"
        if: env == dev #### need if dev
      - name: dingtalk-deploy-test
        type: notification
        properties:
          dingding:
            url:
              secretRef:
                name: secret-dingtalk
                key: url
            message:
              msgtype: markdown
              markdown:
                title: "deploy success"
                text: "deploy success, env=test,service=foo-app" ## if use workflow ref, need get component name or application name "foo-app"
        if: env == test #### need if test

```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by barnettZQG** [comment]
@rainwolf01 you could configure the workflow like:

```
workflow:
    steps:
     - type: deploy
        name: deploy-dev
        properties:
          policies: ["topology-dev", "override-hadev"]
      - name: dingtalk-deploy-dev
        type: notification
        properties:
          ...
      - type: deploy
        name: deploy-test
        properties:
          policies: ["topology-test", "override-hatest"]
      - name: dingtalk-deploy-test
        type: notification
        properties:
           ....
```
