### ISSUE TITLE
[Feature] Updating the data field of the ConfigMap in the storage trait can cause the pod to update

### ISSUE THREAD

**Issue by ZhongsJie** [kubevela/kubevela#4161]
**Is your feature request related to a problem? Please describe.**

Currently, when using VelaUX or CLI, it is simply just updating the data field of the configMap in the `storage`. e.g.

```yaml
        - type: storage
          properties:
            configMap:
              - name: zsj-cm-1
                mountToEnv: 
                  envName: cmEnvKey01
                  configMapKey: cmKey01
                data:
                  cmKey01: cmValue01
```
->
```yaml
        - type: storage
          properties:
            configMap:
              - name: zsj-cm-1
                mountToEnv: 
                  envName: cmEnvKey01
                  configMapKey: cmKey01
                data:
                  cmKey01: cmValue02
```
Will not cause pod updates, resulting in inability to mount to the latest env data.

**Describe the solution you'd like**

Add extra label to `spec.template`

**Describe alternatives you've considered**

**Additional context**

**Comment by barnettZQG** [comment]
If you use the webservice component type, you could set the addRevisionLabel is true:

```
parameter:
  image: xxx
  addRevisionLabel: true
  ...
traits:
  ...
```

**Comment by ZhongsJie96** [comment]
> If you use the webservice component type, you could set the addRevisionLabel is true:
> 
> ```
> parameter:
>   image: xxx
>   addRevisionLabel: true
>   ...
> traits:
>   ...
> ```
> 
> This field means the revision label will be added to the underlying pods, so, if you change the trait configuration, the revision will change, and the pod will be rebuilt.

After adding this parameter. When I change the data of `storage` trait and apply it, the label  `app.oam.dev/revision`  does not change. 
` app.oam.dev/revision: zsj-comp-1-v1`

**Comment by wangyikewxgm** [comment]
What's the vela's version?

**Comment by ZhongsJie96** [comment]
> What's the vela's version?

CLI Version: master
Core Version: 1.4.1
GitRevision: git-b3ef120f
GolangVersion: go1.17.7

**Comment by barnettZQG** [comment]
With this issue, we should rethink the version controller mechanism. After investigation, only by changing the component 
parameter, the component revision number will change. 

In this case, you only change the storage trait(Configmap), then the Configmap object will be changed. If we mount the Configmap to the pod as a volume, the pod will be remounted. But, if mount to env, the pod does not rebuild.  

Here we could have two solutions:

1. All traits should cause the component revision change, and we inject the revision number into the Pod template by default.
2. Only specific traits should cause the component revision change. such as match the `podDisruptive=true`.

**Comment by barnettZQG** [comment]
BTW, This issue related to #4143

**Comment by wonderflow** [comment]
fixed by https://github.com/kubevela/kubevela/pull/4570 , we can define the storage trait to be:

```
apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  name: storage-pre-dispatch
spec:

  stage: PreDispatch

  schematic:
    cue:
      template: |
        ...
```

We need to add **`  stage: PreDispatch`** field, and open the feature gate `MultiStageComponentApply`.
