### ISSUE TITLE
Patch doesn't behave as expected

### ISSUE THREAD

**Issue by rgaoistheone** [kubevela/kubevela#4164]
**Describe the bug**
Recently we are playing around with vela patch features and found that some misbehaviors.

**To Reproduce**
lets say we have a virtualservice like this
```
apiVersion: networking.istio.io/v1beta1
  kind: VirtualService
    name: demo-vs
    namespace: demo
  spec:
    gateways:
    - mesh
    - istio-system/default-gateway
    hosts:
    - demo.com
    - demo
    http:
    - name: http-route-a
      route:
      - destination:
          host: demo
          subset: version-a
    - name: http-route-b
      route:
      - destination:
          host: demo
          subset: version-b
```
And we define a patch wf like 
```
	doPatch: op.#Apply & {
		value:   patchObj.value
		patch: {
			// +patchKey=name
			spec: http:[{
				name: "http-route-c"
				route:[{
					destination:{
						host: "demo"
						subset: "version-c"
					}
				}]
			},...]
		}
}
```
**Expected behavior**
So the expected behaviour should be the `http-route-c` added to http[0] , but the result is that the element is appened to the list.

And also I didn't find any referrence for the json patch , something like 
```
{"op": "replace", "path": "/spec/template/spec/containers/0/env/0/name", "value": "FOO"}
```

**Screenshots**

**KubeVela Version**

CLI Version: v1.4.1
Core Version: 1.4.1
GitRevision: git-ea0508a
GolangVersion: go1.17.10

**Cluster information**

virtual-kubelet-cn-shanghai-e   Ready    agent   313d   v1.20.11-aliyun.1
**Additional context**
