### ISSUE TITLE
[Feature] add multiple domain supports for gateway trait

### ISSUE THREAD

**Issue by haozileung** [kubevela/kubevela#4169]
**Is your feature request related to a problem? Please describe.**
In our company, we build an online order center for multiple brand of company products.
We use different domain to id brand info in our system, it's some kind of SaaS application.
When deploy with default gateway trait, multiple domain cannot be config in one gateway trait.
We can add multiple gateway trait, but it's better not to repeat that.

**Describe the solution you'd like**
```
traits:
  - type: gateway
    properties:
      secretName: some-tls-secret
      domains:
        - brand1.example.com
        - brand2.example.com
        - xxx.example.com
        - ...
      http:
        "/": 8080
```

**Describe alternatives you've considered**
We already deploy our app with helm charts, and those config is working.

**Additional context**
Our TLS certs is a wildcard certs (*.example.com)
