### ISSUE TITLE
Trait中执行Http请求解析Json响应失败

### ISSUE THREAD

**Issue by wonderflow** [kubevela/kubevela#4175]
### Discussed in https://github.com/kubevela/kubevela/discussions/4173

<div type='discussions-op-text'>

<sup>Originally posted by **Echo-Van** June 14, 2022</sup>
验证官方文档提供的自定义运维特征里执行-http-request（https://kubevela.io/zh/docs/platform-engineers/traits/advanced#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%BF%90%E7%BB%B4%E7%89%B9%E5%BE%81%E9%87%8C%E6%89%A7%E8%A1%8C-http-request）。

验证发现，Trait里面的http请求正常返回，但是当返回内容中token的value为null时，dry-run就会报错。Trait定义如下：

```
authservice: {
  type: "trait"
  annotations: {}
  description: "auth-service"
  attributes: {
    podDisruptive: false
    appliesToWorkloads: ["*"]
  }
}
template: {

  parameter: {
    serviceURL: string
  }

  processing: {
    output: {
      token?: string
    }
    // The target server will return a JSON data with `token` as key.
    http: {
      method: *"GET" | string
      url:    parameter.serviceURL
    }
  }

  patch: {
    if processing.output.token != null {
       data: token: processing.output.token
    }
  }
}
```

验证的demo：
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: test-demo
spec:
  components:
    - name: express-server
      type: webservice
      properties:
        image: crccheck/hello-world
        port: 8000
      traits:
        - type: authservice
          properties:
            serviceURL: https://www.fastmock.site/mock/681f554b30a153a31adac0602d7692f7/kubevela/token
```

demo会调用在线的mock接口，接口返回内容：
```
{
  "token": null
}
```

报错信息如下：
```
[root@VM-0-7-centos auth]# vela dry-run -f demo.yaml 
Error: validate application: demo.yaml by dry-run: admission webhook "validating.core.oam.dev.v1beta1.applications" denied the request: field "schematic": Invalid value error encountered, cannot evaluate trait "authservice": invalid patch trait authservice into workload: compile patch file: reference "processing" not found. 
```

当mock接口返回内容中token的值为字符串时，dry-run正常。这个是看起来是json解析null的问题，有什么解决办法吗？
</div>
