### ISSUE TITLE
[Feature] Search useful addon version automatically.

### ISSUE THREAD

**Issue by wangyikewxgm** [kubevela/kubevela#4181]
**Is your feature request related to a problem? Please describe.**

Since when enable an addon, if not set version flag will enable the latest version of addon. But if the system version cannot meet the requirement will generate an error. This is bad user experience, os propose we can search the useful addon version automatically when the  latest version cannot meet version constraint.

**Describe the solution you'd like**

1. First, we cannot download every version of addon iteratively. This is too heavy, we must record the version constraint in `index.yaml`.
2. Check every addon version in descending order until find a matched version.
3. Tell user find a proper version :xxx, install it [Y/N]. User should make the decision whether install it.
4. Only do this search when latest version cannot meet version constraint and not set the `--version` flag.

**Describe alternatives you've considered**

**Additional context**

**Comment by wonderflow** [comment]
Good proposal, let me add more details for this issue：

1. we can use the "annotation" field of the `index.yaml` to store the verison and dependency info. https://github.com/helm/helm/blob/main/pkg/repo/index.go#L92
2. we should recommand like this:

One user has a vela core with version "v1.3.0" which the "velaux"(v1.4.0) is the latest addon. When user install addon like this:

```
vela addon enable velaux
```

The the cli should search all velaux versions and prompt:

```
The latest version of velaux is v1.4.0, it requires vela-core to be upgraded to v1.4.0+.
Would you like to install velaux(v1.3.6) which is the latest version that suits current vela core. [Y/n]?
```

**Comment by Hanmengnan** [comment]
I will try to advance this issue, please assign the issue to me.

@wonderflow

**Comment by Hanmengnan** [comment]
The original code logic is: get the latest version of the addon when `version` is not specified, and get the corresponding version when `version` is specified.
Therefore, the version verification logic can be designed as:
- Verify whether the current addon version meets the system version requirements according to the obtained specified version. There are two system version requirements: Vela core version, K8s version
- If meet the requirements and continue to perform the next task.
- If the requirements are not met, obtain the highest version that meets the requirements.
    - If can get the addon version that meets the requirements and ask the user whether to deploy with this version.
        - If the user agrees to deploy using the prompt version, deploy it.
        - If the user disagrees, exit.
    - Unable to get the addon version that meets the requirements. An error message is returned.


And about the "annotation" field of the index.yaml to store the verison and dependency info, an example of "annotation" file is :
```yaml
annotations:
  fluxcd/1.0.0/vela: 1.2.0
  fluxcd/1.0.0/k8s: 19.0.0
  fluxcd/2.0.0/vela: 1.4.0
  fluxcd/2.0.0/k8s: 20.0.0
```
each line is `<addonName>/<addonVersion>/<vela/k8s>: <required version>`

**Comment by wonderflow** [comment]
The general proposal for install process LGTM. But for the annotations, every addon version will have its own annotations, I propose to be like:

```
apiVersion: v1
entries:
  fluxcd:
  - apiVersion: v2
    appVersion: 1.16.0
    description: A Helm chart for Kubernetes
    name: fluxcd
    type: application
    urls:
    - fluxcd-1.0.0.tgz
    version: 1.0.0
    annotations:
       system: "vela>=1.3.0; kubernetes>=1.10.0"
  - apiVersion: v2
    appVersion: 1.16.0
    description: A Helm chart for Kubernetes
    name: fluxcd
    type: application
    urls:
    - fluxcd-1.1.0.tgz
    version: 1.1.0
    annotations:
       system: "vela>=1.4.0; kubernetes>=1.20.0"
generated: "2022-06-15T13:17:04.733573+08:00"
```
