### ISSUE TITLE
[Feature]  Proposal about the Pipeline

### ISSUE THREAD

**Issue by barnettZQG** [kubevela/kubevela#4183]
## In what area(s)?

/area core/workflow

### What is a Pipeline?

The role of the pipeline is to drive multiple applications to continuous delivery in multiple environments. One pipeline consists of multiple stages, One stage is running one workflow.

### What is different with Workflow

Workflows are designed to describe a single, deterministic process, such as publishing Application A to a test environment via a rolling upgrade, publishing the application B to production by canary rollout, or executing a CI build process. The pipeline is an orderly organization of multiple workflows into a process.

## Why?

In the past, the workflow spec was nested in the application, when the application has changed, the workflow will be executed. We recommend that continuously published microservice be used as an independent application. Therefore, if we only have Workflow, we cannot cover the scenario of arranging multiple services to be published in multiple environments. In addition, if we perform the grayscale release of a complete microservice as long-term behavior, Workflow should undertake a release phase, and after completion, it will reach the final state of the application in this phase. At this time, Pipeline orchestrates and organizes the complete long-term release process. It is not affected by changes to the application description.

## API and Spec

```yaml
apiVersion: core.oam.dev/v1beta1
kind: Pipeline
metadata:
  name: string
  namespace: string
spec:
  stages:
  - name:         string       # Stage name
    workflow?:    string       # +optional, Specify the workflow
    application?: string       # +optional, Specify the application
    suspend:      bool         # Default is true, which means suspending the pipeline before this stage.
    context?:     {...}        # +optional, Specify the workflow context values, the workflow step could read it.
```

Or:

```yaml
apiVersion: core.oam.dev/v1beta1
kind: Pipeline
metadata:
  name: string
  namespace: string
spec:
  stages:
  - name:         string      # Stage name
    workflow?:                # +optional, Specify the workflow.
      namespace?: string      # +optional, Default is the namespace of pipeline.       
      name:       string
    application?:             # +optional, Specify the application.
      namespace?: string
      name:       string
    suspend:      bool        # Default is true, which means suspending the pipeline before this stage.
    context?:     {...}       # +optional, Specify the workflow context values, the workflow step could read it.
``` 

The pipeline controller will generate a WorkflowRun resource for every stage.

## Example

* Publishing to multiple environments.

```yaml
apiVersion: core.oam.dev/v1beta1
kind: Pipeline
metadata:
  name: multiple-publish
spec:
  stages:
   - name: publish2test            
     workflow: rolling-upgrade        
     application: 
        name: example-app
        namespace: test-env
     suspend: false
   - name: publish2prod
     workflow: canary-rollout        
     application: 
         name: example-app
         namespace: prod-env
     suspend: true
```

* CI and CD

```yaml
apiVersion: core.oam.dev/v1beta1
kind: Pipeline
metadata:
  name: ci-cd-example
spec:
  stages:
   - name: build            
     workflow: build-image
     context:
        component:   # For example the build-image workflow support building multiple component images.
            source: xxx
            image: xxx
   - name: publish2test
     workflow: rolling-upgrade
     application?: example-app
     suspend: false
     context:
        component:
            image: xxx

```

* multiple microservices

```yaml
apiVersion: core.oam.dev/v1beta1
kind: Pipeline
metadata:
  name: multiple-publish
spec:
  stages:
   - name: publish-user-service      
     workflow: rolling-upgrade        
     application: user-service
     suspend: false
   - name: publish-auth-service  
     workflow: rolling-upgrade        
     application: auth-service
     suspend: false
```
