### ISSUE TITLE
[Feature] vela def should support generate trait definition without CUE schematic

### ISSUE THREAD

**Issue by wonderflow** [kubevela/kubevela#4184]
**Is your feature request related to a problem? Please describe.**

We have a special usage that if we define a trait without any CUE schematic, users can embed the whole spec information into the trait properties. **If we use vela def, we can't generate this kind of trait.**

A trait in KubeVela can be defined by simply reference a existing Kubernetes API resource.
```
apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  name: ingress
spec:
  definitionRef:
    name: ingresses.networking.k8s.io
```
Let's attach this trait to a component instance in Application:
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: testapp
spec:
  components:
    - name: express-server
      type: webservice
      properties:
        cmd:
          - node
          - server.js
        image: oamdev/testapp:v1
        port: 8080
      traits:
        - type: ingress
          properties:
            rules:
            - http:
                paths:
                - path: /testpath
                  pathType: Prefix
                  backend:
                    service:
                      name: test
                      port:
                        number: 80
```
Note that in this case, all fields in the referenced resource's spec will be exposed to end user and no metadata (e.g. annotations etc) are allowed to be set trait properties. Hence this approach is normally used when you want to bring your own CRD and controller as a trait, and it dose not rely on annotations etc as tuning knobs.

**Describe the solution you'd like**

we should support use vela def and generate the empty trait with only definitionRef specifid.

**Describe alternatives you've considered**

**Additional context**
