### ISSUE TITLE
[Feature] Proposal about stopping the application

### ISSUE THREAD

**Issue by barnettZQG** [kubevela/kubevela#4192]
## In what area(s)?

/area api/lifecycle

## What?

In application lifecycle management, a very important operation is stopping the application. From the knowledge of most developers, stopping the application releases the computing resources occupied by the application, and the application service no longer runs, but the persistent data should not be lost, and the application can be restored after restarting. In KubeVela, applications are generalized, including stateless services, stateful services, cloud services, etc., so the seemingly simple operation of stopping the application becomes a challenge.

## Why?

Why do we need this operation? For example the following scenarios:

1. Application only provides services at a fixed time, and releases resources at other times;
2. Application running blocking requires a traditional restart;
3. Application currently idle and needs to release resources;

## How to?

We first need to be clear about the technical meaning of stopping the application. To keep all data and restore the application, we should only adjust the number of instances of all components under the application to 0, and other resources should be completely reserved. The application includes multiple components of different types, including normal workload components, non-workload components, and cloud service components. This solution mainly realizes the adjustment of the number of instances of workload components.

We cannot directly request the cluster to delete instances or modify the parameters of workload type resources such as Deployment to adjust the number of instances, because KubeVela's state maintenance mechanism will restore the configuration. We need to change the instance of all components to 0 by modifying the configuration of the application and doing special publishing.

So, we can provide a stopping the application workflow configuration, such as:

```bash
workflow:
  steps:
  - type: read-resource-tracker
    ...
  - type: scaler
    parameter:
       replicas: 0 
  - type: deploy
    ...
```

* read-resource-tracker: Read the latest resource tracker, we do not need to render again.
* scaler: filter all workload resources in the resource tracker, and scaler the replicas.
* deploy: publish the resources to all clusters.

**Comment by barnettZQG** [comment]
BTW, This proposal is also a solution to manual scaler application.

**Comment by chwetion** [comment]
we do stop app through workflow, but manual scaling will use trait.
this can preserves the number of instances of the app before stopping the app.
workflow as follow:
```yaml
apiVersion: core.oam.dev/v1beta1
kind: WorkflowStepDefinition
metadata:
  name: hc.pause-application
  namespace: vela-system
spec:
  schematic:
    cue:
      template: |
        import "vela/op"

        parameter: {
          componentName: string
        }

        load: op.#Load & {}

        apply: op.#ApplyComponent & {
          value: load.value[parameter.componentName]
          patch: {
            // +patchStrategy=retainKeys
            workload: spec: replicas: 0
          }
        }
```
