### ISSUE TITLE
traits env/annotations conflict, invalid patch trait env into workload: field "env" not allowed in closed struct

### ISSUE THREAD

**Issue by yucw01** [kubevela/kubevela#4203]
**Describe the bug**

```
About:

  Name:      	failed-env                   
  Namespace: 	default                      
  Created at:	2022-06-20 13:13:01 +0800 CST
  Status:    	runningWorkflow              

Workflow:

  mode: StepByStep
  finished: false
  Suspend: false
  Terminated: false
  Steps
  - id:c2xqtrhdte
    name:deploy-default
    type:deploy
    phase:failed 
    message:step deploy: step deploy: run step(provider=oam,do=components-apply): Found 1 errors. [(failed to apply component local-default-0: GenerateComponentManifest: evaluate template trait=env app=failed-env: invalid patch trait env into workload: result check err: spec.template.spec.containers.0._params: field "env" not allowed in closed struct)]

Services:


```

**To Reproduce**

**Expected behavior**

**Screenshots**

```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: failed-env
spec:
  components:
  - name: failed-env
    type: webservice
    properties:
      ports:
      - name: http
        port: 8080
        expose: true
      image: busybox:1.34
      imagePullPolicy: IfNotPresent
      env:
      - name: TZ
        value: Asia/Shanghai
    traits:
    - type: annotations #################### conflict trait env
      properties:
        app.kubernetes.io/tier: bff
    - type: resource
      properties:
        requests:
          cpu: 0.1
          memory: 256Mi
        limits:
          cpu: 1
          memory: 960Mi
  policies:
  - name: topology-default
    type: topology
    properties:
      clusters: ["local"]
      namespace: default
  - name: override-default
    type: override
    properties:
      components:
      - type: webservice
        properties:
        traits:
        - type: scaler
          properties:
            replicas: 1
        - type: container-image
          properties:
            image: busybox:1.35
            imagePullPolicy: IfNotPresent
        - type: env #################### conflict trait annotations
          properties:
            env:
              PARAMS: "trait env failed"
  workflow:
    steps:
    - name: deploy-default
      type: deploy
      properties:
        policies: ["topology-default", "override-default"]

```

**KubeVela Version**

```
CLI Version: v1.3.6
Core Version: 1.3.6
GitRevision: git-54477ea
GolangVersion: go1.17.10

```

**Cluster information**

**Additional context**
