### ISSUE TITLE
[Feature] provide defualt namespace for dry-run

### ISSUE THREAD

**Issue by wonderflow** [kubevela/kubevela#4219]
**Is your feature request related to a problem? Please describe.**

The example apps usually don't have namespace like:
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: first-vela-app
spec:
  components:
    - name: express-server
      type: webservice
      properties:
        image: oamdev/hello-world
        port: 8000
      traits:
        - type: gateway
          properties:
            domain: testsvc.example.com
            myann: myann
            http:
              "/": 8000
```

But it reports an error that we don't have namespace.
```
$ vela dry-run -f myapp.yaml
Error: validate application: myapp.yaml by dry-run: an empty namespace may not be set during creation
```

It shouldn't be an error， just add default namespace for the dry-run result.

**Describe the solution you'd like**

add `default` namespace for the dry-run result.

**Describe alternatives you've considered**

**Additional context**
