### ISSUE TITLE
the components  in the application create  different deployment name in the different k8s cluster or in the different  namespace in the same k8s cluster

### ISSUE THREAD

**Issue by huangyanhong** [kubevela/kubevela#4220]
**Describe the bug**

the components  in the application create  the same deployment name in the different k8s cluster or in the different  namespace the same k8s cluster

**To Reproduce**

```apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: demo
  namespace: default
spec:
  components:
    - name: demod1456164520727810788
      properties:
        exposeType: ClusterIP
        image: nginx:latest
        imagePullPolicy: IfNotPresent
      traits:
        - properties:
            replicas: 1
          type: scaler
        - properties:
            app: demo
            branch: test-1
            deploymentID: d1456164520727810788
            env: test
          type: labels
      type: webservice
  policies:
    - name: default
      properties:
        clusters:
          - local
        namespace: demo
      type: topology
    - name: infra-test2
      properties:
        clusters:
          - infra-test2
        namespace: demo
      type: topology
    - name: deploy-ha
      type: override
      properties:
        components:
          - type: webservice
            name: demod14561645207
            traits:
              - type: scaler
                properties:
                  replicas: 2
  workflow:
    steps:
      - name: check-nginx
        type: depends-on-app
        properties:
          name: nginx-prod
          namespace: default
      - name: check-object
        type: depends-on-app
        properties:
          name: k8s
          namespace: infra-test2
      - name: default
        properties:
          policies: ["default"]
        type: deploy
      - name: infra-test2
        properties:
          policies: ["infra-test2", "deploy-ha"]
        type: deploy
```

**Expected behavior**

**Screenshots**

**KubeVela Version**
1.4.2

**Cluster information**

1.20.11
**Additional context**

**Comment by wonderflow** [comment]
you can update the webservice definition, add a `random` field in parameter and add it in the output:

```
import (
	"strconv"
)

webservice: {
	type:  "component"
...

}

template: {

....

	output: {
		apiVersion: "apps/v1"
		kind:       "Deployment"

                metadata: name: context.name+"\(parameter.randomNum)"

		spec: {
			selector: matchLabels: "app.oam.dev/component": context.name
...

	parameter: {

                 randomNum: *"" | string

		// +usage=Specify the labels in the workload
		labels?: [string]: string


.....
	}
}

```

Then you can use it like:

```
kind: Application
metadata:
  name: demo
  namespace: default
spec:
  components:
    - name: demo
      properties:
        exposeType: ClusterIP
        image: nginx:latest
        imagePullPolicy: IfNotPresent
      traits:
        - properties:
            replicas: 1
          type: scaler
        - properties:
            app: demo
            branch: test-1
            deploymentID: d1456164520727810788
            env: test
          type: labels
      type: webservice
  policies:
    - name: default
      properties:
        clusters:
          - local
        namespace: demo
      type: topology
    - name: infra-test2
      properties:
        clusters:
          - infra-test2
        namespace: demo
      type: topology
    - name: deploy-ha
      type: override
      properties:
        components:
          - type: webservice
            name: demo
            properties:
               random: d14561645207
            traits:
              - type: scaler
                properties:
                  replicas: 2
  workflow:
    steps:
      - name: check-nginx
        type: depends-on-app
        properties:
          name: nginx-prod
          namespace: default
      - name: check-object
        type: depends-on-app
        properties:
          name: k8s
          namespace: infra-test2
      - name: default
        properties:
          policies: ["default"]
        type: deploy
      - name: infra-test2
        properties:
          policies: ["infra-test2", "deploy-ha"]
        type: deploy
```
