### ISSUE TITLE
[Feature] Support WorkflowRun to separate workflow execution from the application

### ISSUE THREAD

**Issue by FogDong** [kubevela/kubevela#4223]
**Is your feature request related to a problem? Please describe.**

Our Workflow is now bonded with the Application, which means if you want to execute another version of the workflow, you have to either edit the original Application or create a new one. And Application's garbage collection will recycle all the resources if you edit the original Application.

That's the reason we need WorkflowRun to separate workflow execution from the application. Note that we also want this `WorkflowRun` to be simple to reduce the pressure of controller reconciles.

## Case 1: Use WorkflowRun directly

If you only want to run a simple workflow, you can specify the steps in `workflowRun` directly, notice that you can either use  workflowTemplate or define steps in workflowSpec like:

```yaml
apiVersion: core.oam.dev/v1beta1
kind: WorkflowRun
metadata:
  name: run-example
  namespace: default
spec:
  # you can either use  workflowTemplate or define steps in workflowSpec
  workflowTemplate: my-workflow
  parameter:
    - name: my-parameter-1
      value: my-value
  workflowSpec:
    mode:
      steps: StepByStep
      subSteps: DAG
    steps:
      - name: step1
        type: a
      - name: step2-sub
        type: step-group
        subSteps:
          - name: sub
            type: a
status:
  ...
```

WorkflowRun won't have any revisions, if it's not generated from an Application, it will get definitions from the cluster directly.

Note: If the user wants to modify a step during the execution of the WorkflowRun, and the step is executing or has been executed, the ValidatingWebhook will deny the user's modification.

### Proposal 1: Application generates WorkflowRun automatically for its execution

![image](https://user-images.githubusercontent.com/15977536/175236330-ff0e950f-5987-48e2-b08f-6d086873b2b2.png)

For the application, it can generate a WorkflowRun for its execution, the only difference is that this WorkflowRun will get the metadata resources from Application Revision. 

The YAML is like:

```yaml
apiVersion: core.oam.dev/v1beta1
kind: WorkflowRun
metadata:
  name: run-from-application
  namespace: default
  ownerReferences:
    - apiVersion: core.oam.dev/v1beta1
      kind: ApplicationRevision
      name: my-app
status:
  generatedFrom: my-app
  ...
```

If the WorkflowRun is generated from an Application, its lifecycle should be the same as the Application Revision. Also, notice that if the v1 WorkflowRun is still executing, and at the same time the Application is updated, then a v2 WorkflowRun is created and the v1 WorkflowRun is terminated because of the update.

Note: If the WorkflowRun is generated from an Application, then we shouldn't allow users modification for the WorkflowRun.

### Proposal 2: Application uses the execution of workflow as a lib in its controller

The application only wants to use the execution logic of workflow, in fact, there's no need to generate a WorkflowRun CR from the Application. Instead, we can use the execution logic as a lib in the application controller, so that there will be no WorkflowRun resources if you're just using Application.

Related issue: oam-dev/spec#461

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by barnettZQG** [comment]
We need to clearly define the difference and connection between Workflow and WorkflowRun.

**Comment by FogDong** [comment]
> We need to clearly define the difference and connection between Workflow and WorkflowRun.

`Workflow` is only a template, `WorkflowRun` is an execution. If we want to execute a `Workflow`, a `WorkflowRun` will be generated based on the `Workflow` with its steps.

**Comment by barnettZQG** [comment]
Maybe we do not need more fields in WorkflowRun, such as:

```
apiVersion: core.oam.dev/v1beta1
kind: WorkflowRun
metadata:
  name: run-example
  namespace: default
spec:
   workflow: xxx
status:
   phase: Initing | Running | Pause | Terminated | Finished
   steps:
   - name: step1
      status: xxx
      ...
```

After the WorkflowRun resource is created, the controller read the step definition from the workflow or application and saves it to status. Then execute all steps and no longer accept changes in the workflow definition.

**Comment by FogDong** [comment]
> Maybe we do not need more fields in WorkflowRun, such as:
> 
> ```
> apiVersion: core.oam.dev/v1beta1
> kind: WorkflowRun
> metadata:
>   name: run-example
>   namespace: default
> spec:
>    workflow: xxx // Mutually exclusive with `application`
>    application: xxx  // Mutually exclusive with `workflow`
> status:
>    phase: Initing | Running | Pause | Terminated | Finished
>    steps:
>    - name: step1
>       status: xxx
>       ...
> ```
> 
> After the WorkflowRun resource is created, the controller read the step definition from the workflow or application and saves it to status. Then execute all steps and no longer accept changes in the workflow definition.

In this way, we can not run a `WorkflowRun` without Workflow or Application.

In my opinion, `WorkflowRun` can have the field `steps`, and if it's generated from Application or Workflow, its steps should come the source data.

**Comment by wonderflow** [comment]
https://github.com/oam-dev/spec/issues/461 ping @dhiguero , let's discuss here.

**Comment by FogDong** [comment]
For the WorkflowRun that is generated from applications or workflows, it can have `ownerReference`, so that we can get the data from the source, but still, references in spec are redundant.

**Comment by dhiguero** [comment]
Hi all, for me it is still a bit confusing, so I think we should try clarify what will be the use cases for both the current `Application.spec.workflow` and the newer `WorkflowRun`, and how those entity will coexist in the future.

Based on this:

> Workflow is only a template, WorkflowRun is an execution. If we want to execute a Workflow, a WorkflowRun will be generated based on the Workflow with its steps.

I have the following questions:

* **Q1**: If the user changes the `WorkflowRun` (assuming this is possible) that has participated in the deployment of an application, what would be the effect? It seems that the default case will still be reapplying the steps and potentially garbage collecting the previous application entities. One option would be to add a new property to specify the workflow update policy (which could also be used in the `WorkflowRun` if necessary):

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: app-example
spec:
...
  workflow:
    updatePolicy: Reapply | Patch | ...
    steps:
    ...
``` 

* **Q2** With this approach it seems that the user can either write their application workflow either embedded in `Application.spec.workflow` or use `Application.spec.workflow.ref` and reference to a `WorkflowRun`. Is this correct? If the approach is to move `Application.spec.workflow` to a `Workflow` entity, I think the previous lifecycle issues will still happen.
* **Q3** Where is the status of `WorkflowRun` going to be stored? We are currently taking status information from `Application.status.workflow`, will this mean that there are now two workflow statuses that need to be merged? I would try to minimize the entities that are needed to compute user-facing statuses.
* **Q4** With respect to some of the proposed scenarios (e.g., Vertical Scale Workflow) I foresee some issues with trying to use a workflow as a kind of update template. For example, if the intended use is to scale the components of an application changing the replication to Y, the `Application` spec should also be updated to reflect the new revision (as the user checking the apps or the UI should also be aware of the new changes), which could trigger the application garbage collector as described before. If not, the reconciling methods will likely fail or enter in a loop between the workflow and application controllers modifying the definition at the same time.
* **Q5** What will be the lifecycle of `WorkflowRun`?

With regards with a previous Workflow proposal https://github.com/oam-dev/spec/issues/461 I think some elements could help this discussion. To give a brief summary, the idea was to create a top-level `Workflow` entity that does not depend on an `Application`, and which is composed of a list of task as the current `Application.spec.workflow`. Bear in mind, that `Application.spec.workflow` did not exist at the time of the proposal. The only difference here will be to have other steps that would be able to deploy complete applications, and interact with those. The main difference with the current approach is that the proposed workflow can orchestrate different applications, while the current one is always linked with an application.

**Comment by FogDong** [comment]
Hi @dhiguero 

To make things clear, this `WorkflowRun` is the underlying executor for `Application` so that we can separate all the workflow codes in the application controller into a new workflow controller. And users can use the Application in the old way, the only difference of it is that a `WorkflowRun` CR will be automatically created after the Application is created or updated just like Application Revision.

<img width="1161" alt="image" src="https://user-images.githubusercontent.com/15977536/175038815-fa9bfb4f-6e83-4695-a181-7a6509094dcf.png">


> Q1: If the user changes the WorkflowRun (assuming this is possible) that has participated in the deployment of an application, what would be the effect? It seems that the default case will still be reapplying the steps and potentially garbage collecting the previous application entities.

Users can not change a WorkflowRun that is generated from the Application, we should have a validating webhook to avoid it.

> Q2 With this approach it seems that the user can either write their application workflow either embedded in Application.spec.workflow or use Application.spec.workflow.ref and reference to a WorkflowRun.

Right now users can specify the workflow in `Application.spec.workflow` or `Application.spec.workflow.ref`. For me, I don't think that we should have some `ref` fields in WorkflowRun which will make things more confused. IMO, the `WorkflowRun` that is generated from an Application should have some `ownerReference` that links to the ApplicationRevision so that we can get all the steps info from it.

> Q3 Where is the status of WorkflowRun going to be stored? 

The status of WorkflowRun is stored in WorkflowRun CR. If the WorkflowRun is generated from an Application, the in the status of the Application, we should also store the status of the workflow like before.

> Q4

Can you provide some examples of this question? 

> Q5 What will be the lifecycle of WorkflowRun?

There are two cases:

1. If the WorkflowRun is generated from an Application, its lifecycle should be the same as the Application Revision. Also, notice that if the `v1 WorkflowRun` is still executing, and at the same time the Application is updated, then a `v2 WorkflowRun` is created and the `v1 WorkflowRun` is terminated because of the update.
2. If the WorkflowRun is applied with steps in its spec, that is to say, the WorkflowRun has no components, traits, policies, etc, then this WorkflowRun has its own lifecycle, it's just an IaC-based WorkflowRun without GC nor revisions.

**Comment by ZhongsJie96** [comment]
IMO, I am more in favor of generating `WorkflowRun` from applications to reduce break change. What I'm more confused about is that the `WorkflowRun` exists independently of the application and just moves `Application.spec.workflow` to a `WorkflowRun`, how to solve the problem that was first raised.

> Our Workflow is now bonded with the Application, which means if you want to execute another version of the workflow, you have to either edit the original Application or create a new one.

If a validating webhook is introduced to avoid modifying the `WorkflowRun`, it will also result in the need to modify the original application to execute another version of the workflow. The benefit is only when there is no need to write an application in an IaC-based scenario and it will be converted to a new `WorkflowRun`. Whether this behavior It can be done based on `Application`.

**Comment by FogDong** [comment]
Hi @ZhongsJie96 

There are two cases when we use WorkflowRun

1. Use the WorkflowRun independently without Applications like:
```yaml
apiVersion: core.oam.dev/v1beta1
kind: WorkflowRun
metadata:
  name: run-example
  namespace: default
spec:
  run:
    steps:
      ...
```

2. Applications use the WorklfowRun for execution, the WorklfowRun is generated from Application automatically like:
```yaml
apiVersion: core.oam.dev/v1beta1
kind: WorkflowRun
metadata:
  name: run-from-application
  namespace: default
  ownerReferences:
  - apiVersion: core.oam.dev/v1beta1
    controller: true
    kind: Application
    name: my-app
```


If the users want to use the Application, then they can use the Application like before. But if they don't want to use the Application's components, traits and policies, they can use the `WorkflowRun` as an IaC-based workflow for execution.

**Comment by FogDong** [comment]
FYI, I have updated the description of this issue to try to make things clear.

**Comment by FogDong** [comment]
Thanks for the reply @dhiguero 

For the first question, if the application set the replica to 3 and then users create a `WorkflowRun` to set the replica to 5, notice that `WorkflowRun` will only execute **once** while `Application` will try to keep the resource status consistent with its spec, so after a while, `Application` will re-set the replica to 3.

For the confusing part, `Workflow` and `WorkflowRun`.

We already have this `Workflow` CRD, and it's a template, you can reference it in your `Application.` If you define the `Workflow`, it will not be executed automatically since it's only a template.

Will it be clear if we define the `WorkflowRun` like:

```yaml
apiVersion: core.oam.dev/v1beta1
kind: WorkflowRun
metadata:
  name: run-example
  namespace: default
spec:
  # you can either use from or define steps in run
  from:
    template: my-workflow
    parameter:
      - name: my-parameter-1
        value: my-value
  run:
    mode:
      steps: StepByStep
      subSteps: DAG
    steps:
      - name: step1
        type: a
      - name: step2-sub
        type: step-group
        subSteps:
          - name: sub
            type: a
status:
  ...
```

**Comment by wonderflow** [comment]
I need to add some details from my point of view.  @FogDong 

There're actually two scenarios:

1. Application generated workflow as the real execution engine for Workflow. 
2. Run Workflow independently.

## Application generated workflow

For the application generated case, the general idea of using owenerReference is to reuse spec from apprevision, the idea is fine but the spec is not good enough. Here's my reason:

1. The ownerReference shouldn't be abused. The ownerReference in K8s generally represent some other object owns this one.
    - 1) it don't mean there's only one owner. What if there're two or more ownerReference.
    - 2) the ownerReference can't and shouldn't represent the hidden logic that the controller will use the spec from owner.
2. users can be confused cause they usually focus on spec while ignore metadata.
3. different spec source loading ways are not consistent, in your design, there're three ways to load the workflow spec, they are：
   - 1) ownerReference
   - 2) use `run.steps` to define directly
   - 3) use `from: ` to load from outside workflow.
 
I propose the spec should be like:
```
apiVersion: core.oam.dev/v1beta1
kind: WorkflowRun
metadata:
  name: run-from-application
  namespace: default
spec:
  fromApplication: my-app
status:
  ...
```

## Run Workflow independently

1. Define spec in workflowrun

It's confusing on the field name `run`, in my view, you're trying to define workflow spec directly in the `WorkflowRun`, why don't point out it is the spec by:

```
apiVersion: core.oam.dev/v1beta1
kind: WorkflowRun
metadata:
  name: run-example
  namespace: default
spec:
  workflowSpec:
    steps:
      - name: step1
        type: a
      - name: step2-sub
        type: step-group
        subSteps:
          - name: sub
            type: a
status:
  ...
```

2. Ref a workflow from outside

```
apiVersion: core.oam.dev/v1beta1
kind: WorkflowRun
metadata:
  name: run-example
  namespace: default
spec:
  # you can either use from or define steps in run
  fromWorkflow: my-workflow
```

This can be consistent with the one from ownerReference.

3. Other fields should be outside, they're common for both ways of reference and define directly.


The running mode and parameters:

```
apiVersion: core.oam.dev/v1beta1
kind: WorkflowRun
metadata:
  name: run-example
  namespace: default
spec:
  mode:
    steps: StepByStep
    subSteps: DAG
  parameters:
     ...
  fromWorkflow: <>
  workflowSpec:
     ...
status:
  ...

```

Besides, there're still some features not included but importand:

1. Since workflow is indepently, can I ref a workflow in workflowstep?
2. Can I use more than one workflow in workflowRun? 
3. How can I use workflowRun to deploy multiple applications? What's the spec like? 

Please refer to some existing projects such as tekton or argo workflow for the spec design, we should make it easy-to-use and powerful.

**Comment by FogDong** [comment]
Thanks for the addition @wonderflow 

## Application generated workflow

In this part, I still think that adding `fromApplication` in `WorkflowRun.spec` is not a good way to clarify the connection between Application and WorkflowRun.

If we add `fromApplication` in `WorkflowRun.spec`, it will make the user feel that he can change this field. The other way is to add `generatedFrom` in `WorkflowRun.status` like:

```yaml
apiVersion: core.oam.dev/v1beta1
kind: WorkflowRun
metadata:
  name: run-example
  namespace: default
status:
  generatedFrom: my-app
  ...
```

## Run Workflow independently

I agree that `workflowSpec` is a better description and we can make this `WorkflowRun` like:

apiVersion: core.oam.dev/v1beta1
kind: WorkflowRun
metadata:
  name: run-example
  namespace: default
spec:
  # you can either use  workflowTemplate or define steps in workflowSpec
  workflowTemplate: my-workflow
  parameter:
    - name: my-parameter-1
      value: my-value
  workflowSpec:
    mode:
      steps: StepByStep
      subSteps: DAG
    steps:
      - name: step1
        type: a
      - name: step2-sub
        type: step-group
        subSteps:
          - name: sub
            type: a
status:
  ...

## Other important but not mentioned yet

I think we should minimize the scope of `WorkflowRun`, if we want to orchestrate multiple workflows in one CR, the object should be like `Pipeline` or something else.

**Comment by wonderflow** [comment]
> I think we should minimize the scope of WorkflowRun, if we want to orchestrate multiple workflows in one CR, the object should be like Pipeline or something else.

I don't agree adding too much concept just because we're not thinking the future for design.

**Comment by wonderflow** [comment]
```
apiVersion: core.oam.dev/v1beta1
kind: WorkflowRun
metadata:
  name: run-example
  namespace: default
status:
  generatedFrom: my-app
  ...
```

Looks good for me.

For the "Run Workflow independently" part, the only different is do we separate the `mode` outside. I think it should be in outside from the spec.
