### ISSUE TITLE
bugs caused by cluster distribution policy modification

### ISSUE THREAD

**Issue by zxbyoyoyo** [kubevela/kubevela#4244]
**Describe the bug**

**To Reproduce**
1. register the cluster, using the same kubeconfig
```
 vela cluster join k8s_demo.config --name cluster01
 vela cluster join k8s_demo.config --name cluster02
```
2. apply a demo, dispatch to cluster01
```
cat <<EOF | kubectl apply -f -
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: first-vela-app
  namespace: default
spec:
  components:
  - name: first-vela-app
    properties:
      exposeType: ClusterIP
      image: nginx
    traits:
    - properties:
        replicas: 1
      type: scaler
    type: webservice
  policies:
  - name: env-bindings-default
    properties:
      envs:
      - name: default
        patch: {}
        placement:
          clusterSelector:
            name: cluster01
          namespaceSelector:
            name: default
    type: env-binding
  workflow:
    steps:
    - name: default
      properties:
        env: default
        policy: env-bindings-default
      type: deploy2env
EOF

```
4. update the demo, dispatch to cluster02
```
at <<EOF | kubectl apply -f -
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: first-vela-app
  namespace: default
spec:
  components:
  - name: first-vela-app
    properties:
      exposeType: ClusterIP
      image: nginx
    traits:
    - properties:
        replicas: 1
      type: scaler
    type: webservice
  policies:
  - name: env-bindings-default
    properties:
      envs:
      - name: default
        patch: {}
        placement:
          clusterSelector:
            name: cluster02
          namespaceSelector:
            name: default
    type: env-binding
  workflow:
    steps:
    - name: default
      properties:
        env: default
        policy: env-bindings-default
      type: deploy2env
EOF
```
3. in target cluster, apps are constantly being launched and destroyed
![image](https://user-images.githubusercontent.com/20168048/175448655-8aa8060d-c4fb-4062-aeed-470d38555341.png)

**Expected behavior**

  the content of the application template has not changed, only the clusterId in the policy has changed, but in fact the corresponding target cluster is the same, so the application should not be updated or destroyed

**Screenshots**

**KubeVela Version**

  CLI Version: v1.4.2
  Core Version: 1.4.2
  GitRevision: git-eb9ddaa
  GolangVersion: go1.17.11

**Cluster information**
  v1.20.8

**Additional context**
