### ISSUE TITLE
The webservice component definition would fail in repeated volume conditions

### ISSUE THREAD

**Issue by jingliming** [kubevela/kubevela#4273]
**Describe the bug**

**To Reproduce**
1. The YAML files of Component/Trait I used.
webservice component
3. The YAML file of Application I applied.
```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: nginx01
  namespace: mingyuan 
spec:
  components:
  - name: nginx01-dockerhub
    properties:
      image: docker.io/library/nginx:1.22.0
      port: 80
      volumeMounts:
        pvc: 
        - name: oam-pvc-1
          mountPath: /tmp/a
          claimName: nginx-dockerhub-pvc
        - name: oam-pvc-2
          mountPath: /tmp/b
          claimName: nginx-dockerhub-pvc
    traits:
    - properties:
        rolloutBatches:
        - replicas: 1
        targetSize: 1
      type: rollout
    type: webservice
```
5. Other operations I have done.
pv
```yml
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
    pv.kubernetes.io/provisioned-by: local-volume-provisioner-bizworks-console011160135243.na63-908ec031-aa91-4f3f-826b-a191953ece70
  name: nginx-pv-01
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 40Gi
  local:
    fsType: ext4
    path: /mnt/fast-disks/vol4
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - bizworks-console011160135243.na63
  persistentVolumeReclaimPolicy: Delete
  storageClassName: fast-disks
  volumeMode: Filesystem
```
pvc 
```yml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  name: nginx-dockerhub-pvc
  namespace: mingyuan
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
  volumeName: nginx-pv-01
```
6. See error
```
Events:
  Type     Reason       Age    From               Message
  ----     ------       ----   ----               -------
  Normal   Scheduled    3m11s  default-scheduler  Successfully assigned mingyuan/nginx01-dockerhub-v2-66fd858fd4-tlddl to bizworks-console011160135243.na63
  Warning  FailedMount  68s    kubelet            Unable to attach or mount volumes: unmounted volumes=[oam-pvc-1], unattached volumes=[oam-pvc-1 oam-pvc-2 default-token-g2s6b]: timed out waiting for the condition
```

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/9865050/176131969-61ca9483-4b32-4790-b9f5-c5bb9999d4a6.png)

**KubeVela Version**
1.2.5

**Cluster information**

1.18.8
**Additional context**
