### ISSUE TITLE
Goroutines leak if the server don't close the connections

### ISSUE THREAD

**Issue by phantomnat** [kubevela/kubevela#4294]
**Describe the bug**

goroutines keep increasing when doing a get request in workflows

**To Reproduce**

- Start server that don't close the connection (infinity read, write and idle timeout)
- Create the WorkflowStep.
- Create some Applications and leave it running.
- Request to metric endpoint to see the number of goroutines
    ```bash
    kubectl port-forward kubevela-vela-core-<hash> 8080:8080
    curl -s 127.0.0.1:8080/metrics|grep -E 'threads|routine'
    ```

    the result after let it running for a while and then delete all the applications
    ```bash
    # HELP go_goroutines Number of goroutines that currently exist.
    # TYPE go_goroutines gauge
    go_goroutines 12100
    ```
    same number after 5 minutes passed
    ```
    go_goroutines 12100
    ```

- Goroutines went back to normal after restart the server.
    ```
    go_goroutines 194
    ```

WorkflowStep
```cue
import (
	"vela/op"
)

"wait-for": {
	annotations: {}
	attributes: {}
	description: ""
	labels: {}
	type: "workflow-step"
}

template: {
	waitFor: op.#Steps & {
		// get an environment status
		getStatus: op.#HTTPGet & {
			url: "http://fiber.default.svc.cluster.local:3000"
		} @step(1)

		result: getStatus.response.body

		// Wait until the status is `completed`
		wait: op.#ConditionalWait & {
			continue: result == "keep-looping"
			message:  "response: \(result)"
		} @step(2)
	}
}

```
Application 
```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: wait-1
spec:
  components: [ ]
  workflow:
    steps:
      - name: simple-wait
        type: wait-for
```

gofiber server
```go
package main

import (
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/logger"
)

func main() {
	app := fiber.New()
	app.Use(logger.New())

	app.Get("/", func(c *fiber.Ctx) error {
		return c.SendString("not-ok")
	})

	app.Listen(":3000")
}
```
or 
```
kubectl run fiber --image=phantomnat/hello-go-fiber:latest
kubectl expose pod fiber --port=3000
```

**Expected behavior**

Number of goroutines should be stable or not keep increasing

**Screenshots**

**KubeVela Version**

v1.4.3

**Cluster information**

KinD version v1.19.7

**Additional context**

**Comment by wonderflow** [comment]
Thanks for report, we're investigating:

1. create the missing service for fiber image:

```
kubectl create svc clusterip fiber --tcp=3000:3000
```

2. The workflow report the following errors, seems not connected

```
 message: 'step waitFor: step getStatus: run step(provider=http,do=do): Get "http://fiber.default:3000":
        context deadline exceeded (Client.Timeout exceeded while awaiting headers)'
```

**Comment by wonderflow** [comment]
The service should be:
```
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-07-01T06:15:55Z"
  labels:
    app: fiber
  name: fiber
  namespace: default
  resourceVersion: "7024963"
  uid: 5b3ba528-96bd-447d-abc4-0ba28af0f0f2
spec:
  clusterIP: 10.43.44.225
  clusterIPs:
  - 10.43.44.225
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 80-3000
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    run: fiber
  sessionAffinity: None
  type: ClusterIP
```

And the workflow runs in my env.

**Comment by wonderflow** [comment]
I didn't reprodue, the gorutine is always 231.

**Comment by phantomnat** [comment]
Not sure why there is the error about timeout.

I think the workflow should be in running forever.
```
    steps:
    - firstExecuteTime: "2022-07-01T06:37:20Z"
      id: h4rq4kqmga
      lastExecuteTime: "2022-07-01T06:37:26Z"
      message: 'response: not-ok'
      name: simple-wait
      phase: running
      reason: Wait
      type: wait-for
```
