### ISSUE TITLE
mutil cluster with override, workflow `deploy` trigged if yaml not changed

### ISSUE THREAD

**Issue by yucw01** [kubevela/kubevela#4316]
**Describe the bug**

**To Reproduce**

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: foo-app
  namespace: examples
spec:
  components:
    - name: nginx
      type: webservice
      properties:
        image: nginx:1.20
  policies:
    - name: topology-dev
      type: topology
      properties:
        clusters: ["local"]
        namespace: dev
    - name: topology-test
      type: topology
      properties:
        clusters: ["local"]
        namespace: test
    - name: override-dev
      type: override
      properties:
        components:
        - type: webservice
          properties:
          traits:
          - type: scaler
            properties:
              replicas: 1
          - type: container-image
            properties:
              image: nginx:1.20
              imagePullPolicy: IfNotPresent
    - name: override-test
      type: override
      properties:
        components:
        - type: webservice
          properties:
          traits:
          - type: scaler
            properties:
              replicas: 2
          - type: container-image
            properties:
              image: nginx:1.21       ### <----------------- env "test" ugrade image version to 1.21
              imagePullPolicy: IfNotPresent
  workflow:
    steps:
      - type: deploy                  ### <----------------- env "dev" yaml not changed, but trigger this. should skip ??
        name: deploy-dev    
        properties:
          policies: ["topology-dev", "override-dev"]
      - name: dingtalk-deploy-dev     
        type: notification
        properties:
          dingding:
            url:
              secretRef:
                name: secret-dingtalk
                key: url
            message:
              msgtype: markdown
              markdown:
                title: "deploy success"
                text: "deploy success, env=dev,service=foo-app"
      - type: deploy
        name: deploy-test
        properties:
          policies: ["topology-test", "override-test"]
      - name: dingtalk-deploy-test
        type: notification
        properties:
          dingding:
            url:
              secretRef:
                name: secret-dingtalk
                key: url
            message:
              msgtype: markdown
              markdown:
                title: "deploy success"
                text: "deploy success, env=test,service=foo-app" 

```

**Expected behavior**

skip ??

**Screenshots**

**KubeVela Version**

```
CLI Version: v1.4.5
Core Version: 1.4.5
GitRevision: git-15bea4f
GolangVersion: go1.17.11
```

**Cluster information**

**Additional context**
