### ISSUE TITLE
Installation fails on Ubuntu 20.04

### ISSUE THREAD

**Issue by bxiiiiii** [kubevela/kubevela#4317]
**Describe the bug**

Installation fails on Ubuntu 20.04
**To Reproduce**

I am using the Installation from the documentation until using **sudo velad install**

**Screenshots**

![2022-07-04 15-04-39 的屏幕截图](https://user-images.githubusercontent.com/75570810/177100971-652ef647-f773-4891-8f57-845952ae2d61.png)

**Comment by FogDong** [comment]
cc @chivalryq

**Comment by bxiiiiii** [comment]
What more information is needed?

**Comment by bxiiiiii** [comment]
Error from server (NotFound): deployments.apps "kubevela-vela-core" not found

**Comment by chivalryq** [comment]
Oh, sorry, installation fails at "pre-install" stage. 

Try get jobs at pre-install stage:

```shell
kubectl get job -A
```

```shell
kubectl get job kubevela-vela-core-cluster-gateway-tls-secret-create -o yaml
```

**Comment by bxiiiiii** [comment]
![2022-07-04 15-46-03 的屏幕截图](https://user-images.githubusercontent.com/75570810/177106991-b1c0ac67-203f-482e-be33-e003c824de45.png)

**Comment by chivalryq** [comment]
> ![2022-07-04 15-39-22 的屏幕截图](https://user-images.githubusercontent.com/75570810/177106027-d8538c3c-9e3b-4798-b07e-b9c8574966d7.png)

Actually you can try 
- `velad uninstall` and `velad install` again to see if it is reproducable.
or 
- `vela install --version=1.4.5`

**Comment by chivalryq** [comment]
> ![2022-07-04 15-46-03 的屏幕截图](https://user-images.githubusercontent.com/75570810/177106991-b1c0ac67-203f-482e-be33-e003c824de45.png)

try `kubectl get job -n vela-system -o yaml kubevela-vela-core-admission-create`

**Comment by bxiiiiii** [comment]
> > ![2022-07-04 15-39-22 的屏幕截图](https://user-images.githubusercontent.com/75570810/177106027-d8538c3c-9e3b-4798-b07e-b9c8574966d7.png)
> 
> 其实你可以试试
> 
> * `velad uninstall`并`velad install`再次查看它是否可重现。
>   或者
> * `vela install --version=1.4.5`

still fails

**Comment by bxiiiiii** [comment]
> > ![2022-07-04 15-46-03 的屏幕截图](https://user-images.githubusercontent.com/75570810/177106991-b1c0ac67-203f-482e-be33-e003c824de45.png)
> 
> 尝试`kubectl get job -n vela-system -o yaml kubevela-vela-core-admission-create`
![2022-07-04 16-28-29 的屏幕截图](https://user-images.githubusercontent.com/75570810/177115238-c2924b10-9ade-4ee7-85fe-469aab5246ff.png)

**Comment by chivalryq** [comment]
Sorry but you didn't show all the infomation of `kubectl get job`, could you paste all as text?

**Comment by bxiiiiii** [comment]
> 抱歉，您没有显示 的​​所有信息`kubectl get job`，您可以将所有信息都粘贴为文本吗？@bxiiiiii

No resources found in default namespace.

**Comment by bxiiiiii** [comment]
when using kubectl get job -A
> NAMESPACE     NAME                                  COMPLETIONS   DURATION   AGE
kube-system            helm-install-traefik-crd              0/1           33m        33m
kube-system   helm-install-traefik                  0/1           33m        33m
vela-system   kubevela-vela-core-admission-create   0/1           33m        33m

**Comment by bxiiiiii** [comment]
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  creationTimestamp: "2022-07-04T08:10:37Z"
  labels:
    app: vela-core-admission-create
    app.kubernetes.io/instance: kubevela
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vela-core
    app.kubernetes.io/version: v1.4.3
    helm.sh/chart: vela-core-v1.4.3
  name: kubevela-vela-core-admission-create
  namespace: vela-system
  resourceVersion: "600"
  uid: c1ed86a7-757a-4632-8484-72cdac16c968
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: c1ed86a7-757a-4632-8484-72cdac16c968
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vela-core-admission-create
        app.kubernetes.io/instance: kubevela
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: vela-core
        app.kubernetes.io/version: v1.4.3
        controller-uid: c1ed86a7-757a-4632-8484-72cdac16c968
        helm.sh/chart: vela-core-v1.4.3
        job-name: kubevela-vela-core-admission-create
      name: kubevela-vela-core-admission-create
    spec:
      containers:
      - args:
        - create
        - --host=vela-core-webhook,vela-core-webhook.vela-system.svc
        - --namespace=vela-system
        - --secret-name=kubevela-vela-core-admission
        - --key-name=tls.key
        - --cert-name=tls.crt
        image: oamdev/kube-webhook-certgen:v2.4.1
        imagePullPolicy: IfNotPresent
        name: create
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext:
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 2000
      serviceAccount: kubevela-vela-core-admission
      serviceAccountName: kubevela-vela-core-admission
      terminationGracePeriodSeconds: 30
status:
  active: 1
  startTime: "2022-07-04T08:10:37Z"

**Comment by chivalryq** [comment]
What about `kubectl describe job -n vela-system kubevela-vela-core-admission-create`?

**Comment by bxiiiiii** [comment]
> kubectl describe job -n vela-system kubevela-vela-core-admission-create

Name:           kubevela-vela-core-admission-create
Namespace:      vela-system
Selector:       controller-uid=c1ed86a7-757a-4632-8484-72cdac16c968
Labels:         app=vela-core-admission-create
                app.kubernetes.io/instance=kubevela
                app.kubernetes.io/managed-by=Helm
                app.kubernetes.io/name=vela-core
                app.kubernetes.io/version=v1.4.3
                helm.sh/chart=vela-core-v1.4.3
Annotations:    helm.sh/hook: pre-install,pre-upgrade
                helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
Parallelism:    1
Completions:    1
Start Time:     Mon, 04 Jul 2022 16:10:37 +0800
Pods Statuses:  1 Running / 0 Succeeded / 0 Failed
Pod Template:
  Labels:           app=vela-core-admission-create
                    app.kubernetes.io/instance=kubevela
                    app.kubernetes.io/managed-by=Helm
                    app.kubernetes.io/name=vela-core
                    app.kubernetes.io/version=v1.4.3
                    controller-uid=c1ed86a7-757a-4632-8484-72cdac16c968
                    helm.sh/chart=vela-core-v1.4.3
                    job-name=kubevela-vela-core-admission-create
  Service Account:  kubevela-vela-core-admission
  Containers:
   create:
    Image:      oamdev/kube-webhook-certgen:v2.4.1
    Port:       <none>
    Host Port:  <none>
    Args:
      create
      --host=vela-core-webhook,vela-core-webhook.vela-system.svc
      --namespace=vela-system
      --secret-name=kubevela-vela-core-admission
      --key-name=tls.key
      --cert-name=tls.crt
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Events:           <none>

**Comment by chivalryq** [comment]
The pod is running, check the pod status: 
```shell
kubectl get pod -n vela-system
```
and
```shell
kubectl get pod -n vela-system kubevela-vela-core-admission-create-xxxxx -oyaml
kubectl describe pod -n vela-system kubevela-vela-core-admission-create-xxxxx
```

Also a tip: GitHub support Markdown syntax, try wrap code like 

\``` yaml
yaml here
\```

**Comment by bxiiiiii** [comment]
> The pod is running, check the pod status:
> 
> ```shell
> kubectl get pod -n vela-system
> ```
> 
> and
> 
> ```shell
> kubectl get pod -n vela-system kubevela-vela-core-admission-create-xxxxx -oyaml
> kubectl describe pod -n vela-system kubevela-vela-core-admission-create-xxxxx
> ```
> 
> Also a tip: GitHub support Markdown syntax, try wrap code like
> 
> ``` yaml yaml here ```

kubectl get pod -n vela-system
``` yaml
NAME                                        READY   STATUS    RESTARTS   AGE
kubevela-vela-core-admission-create-s644k   0/1     Pending   0          82m
```
kubectl get pod -n vela-system kubevela-vela-core-admission-create-s644k -oyaml
``` yaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2022-07-04T08:10:37Z"
  generateName: kubevela-vela-core-admission-create-
  labels:
    app: vela-core-admission-create
    app.kubernetes.io/instance: kubevela
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vela-core
    app.kubernetes.io/version: v1.4.3
    controller-uid: c1ed86a7-757a-4632-8484-72cdac16c968
    helm.sh/chart: vela-core-v1.4.3
    job-name: kubevela-vela-core-admission-create
  name: kubevela-vela-core-admission-create-s644k
  namespace: vela-system
  ownerReferences:
  - apiVersion: batch/v1
    blockOwnerDeletion: true
    controller: true
    kind: Job
    name: kubevela-vela-core-admission-create
    uid: c1ed86a7-757a-4632-8484-72cdac16c968
  resourceVersion: "599"
  uid: b1dff55e-2c3f-41e0-959e-7ffcf5525801
spec:
  containers:
  - args:
    - create
    - --host=vela-core-webhook,vela-core-webhook.vela-system.svc
    - --namespace=vela-system
    - --secret-name=kubevela-vela-core-admission
    - --key-name=tls.key
    - --cert-name=tls.crt
    image: oamdev/kube-webhook-certgen:v2.4.1
    imagePullPolicy: IfNotPresent
    name: create
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-pctzl
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: OnFailure
  schedulerName: default-scheduler
  securityContext:
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 2000
  serviceAccount: kubevela-vela-core-admission
  serviceAccountName: kubevela-vela-core-admission
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-pctzl
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-07-04T08:10:37Z"
    message: '0/1 nodes are available: 1 node(s) had taint {node.kubernetes.io/disk-pressure:
      }, that the pod didn''t tolerate.'
    reason: Unschedulable
    status: "False"
    type: PodScheduled
  phase: Pending
  qosClass: BestEffort
```
kubectl describe pod -n vela-system kubevela-vela-core-admission-create-s644k
``` yaml
Name:           kubevela-vela-core-admission-create-s644k
Namespace:      vela-system
Priority:       0
Node:           <none>
Labels:         app=vela-core-admission-create
                app.kubernetes.io/instance=kubevela
                app.kubernetes.io/managed-by=Helm
                app.kubernetes.io/name=vela-core
                app.kubernetes.io/version=v1.4.3
                controller-uid=c1ed86a7-757a-4632-8484-72cdac16c968
                helm.sh/chart=vela-core-v1.4.3
                job-name=kubevela-vela-core-admission-create
Annotations:    <none>
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  Job/kubevela-vela-core-admission-create
Containers:
  create:
    Image:      oamdev/kube-webhook-certgen:v2.4.1
    Port:       <none>
    Host Port:  <none>
    Args:
      create
      --host=vela-core-webhook,vela-core-webhook.vela-system.svc
      --namespace=vela-system
      --secret-name=kubevela-vela-core-admission
      --key-name=tls.key
      --cert-name=tls.crt
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-pctzl (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  kube-api-access-pctzl:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  88m   default-scheduler  0/1 nodes are available: 1 node(s) had taint {node.kubernetes.io/disk-pressure: }, that the pod didn't tolerate.
```
