### ISSUE TITLE
ref-objects component parameter invalid field cause validating webhook failed or application failed

### ISSUE THREAD

**Issue by jiangshantao-dbg** [kubevela/kubevela#4318]
**Describe the bug**
when use ref-objects, the invalid field of the parameter cue cause webhook or application deploy failed. 

**To Reproduce**
1. application yaml file (vela.yaml) i use:
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: ref-objects-example
  namespace: default
spec:
  components:
    - name: configmap-copy
      type: ref-objects
      properties:
        objects:
          - resource: configmap
            name: new
            namespace: dev-test
```
2. `kubectl apply -f vela.yaml` with the error:
```
E0704 05:53:57.037740       1 instance.go:80] "failed to have the workload/trait unstructured" err="apiVersion: incomplete value (string) (and 1 more errors)" Definition=<
	apiVersion: string
	kind:       string
	resource:   "configmap"
 >
```
3. add `apiVersion and kind field`,
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: ref-objects-example
  namespace: default
spec:
  components:
    - name: configmap-copy
      type: ref-objects
      properties:
        objects:
          - resource: configmap
            name: new
            namespace: dev-test
            apiVersion: v1
            kind: configmap
```
4. still have error:
```
E0701 09:14:43.041793       1 instance.go:80] "failed to have the workload/trait unstructured" err="metadata.name: incomplete value (string)" Definition=<
  name:       "new"
  apiVersion: "v1"
  kind:       "ConfigMap"
  metadata: {
    name: string
    ...
  }
  namespace: "dev-test"
  resource:  "configmap"
 >
E0701 09:14:43.041959       1 task.go:238] "do steps" err="step apply: run step(provider=oam,do=component-apply): GenerateComponentManifest: evaluate base template component=configmap-copy app=ref-objects-example: failed to have the workload/trait unstructured: metadata.name: incomplete value (string)" application="default/ref-objects-example" controller="application" resource_version="708753618" generation=4 publish_version="v1.4.3" workflow_version="ref-objects-example-v2:d776d3fb9706466" step_name="configmap-copy" step_type="apply-component" spanID="i-fvploap9.workflow.t4i8catdjy"
```
**Expected behavior**

ref-objects should be worked with resource and name field.

**Screenshots**

**KubeVela Version**
```
CLI Version: v1.4.3
Core Version: 1.4.3
GitRevision: git-5e3ab73
GolangVersion: go1.17.11
```

**Cluster information**
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

```
**Additional context**
