### ISSUE TITLE
[Feature] support edge application delivery

### ISSUE THREAD

**Issue by huiwq1990** [kubevela/kubevela#4326]
**Is your feature request related to a problem? Please describe.**

[openyurt application delivery proposal](https://github.com/huiwq1990/openyurt/blob/feat-app-delivery/docs/proposals/20220611-openyurt-application-delivery.md)

[openyurt application delivery proposal chinese version](https://github.com/huiwq1990/openyurt/blob/feat-app-delivery/docs/proposals/20220611-openyurt-application-delivery-cn.md)

**Describe the solution you'd like**

[use oam deploy edge applicaton chinese version](https://github.com/huiwq1990/openyurt/blob/feat-app-delivery/docs/proposals/20220611-openyurt-application-delivery-oam.md)

**Describe alternatives you've considered**

**Additional context**

- all information could be found in https://github.com/openyurtio/openyurt/pull/879
- the proposal has disscus with openyurt community members

**Comment by FogDong** [comment]
It would be nice if you can comment on the community meeting agenda issue here kubevela/community#34 so that you can share your proposal and we can discuss this in the community meeting.

**Comment by huiwq1990** [comment]
> It would be nice if you can comment on the community meeting agenda issue here [kubevela/community#34](https://github.com/kubevela/community/issues/34) so that you can share your proposal and we can discuss this in the community meeting.

We are happly to attend the meeting.

**Comment by wonderflow** [comment]
Typo: subnet -> subset

**Comment by huiwq1990** [comment]
@wonderflow  I think it works fine for deploy helm to a specific nodepool. If we want to deploy helm to all nodepools, did we should write override policy for all nodepools?

**Comment by chivalryq** [comment]
Here is another solution with trait. There is one trait for webservice (will introduce trait for helm later) if you want to deploy them to two node pool.  
```cue
annotations: {
	type: "trait"
	annotations: {}
}
template: {
	// +patchStrategy=jsonMergePatch
	patch: {
		metadata: {
			annotations: {
				nodeSelectorLabel: "apps.openyurt.io/nodepool"
				nodeSelectorLabel: [context.replicaKey]
			}
		}
		if context.output.spec != _|_ && context.output.spec.template != _|_ {
			spec: template: metadata: annotations: {
				nodeSelectorLabel: "apps.openyurt.io/nodepool"
				nodeSelectorLabel: [context.replicaKey]
			}
		}
	}
	parameter:  null
}
```

Note that It needed a replication policy in Application. Replication policy do two things:
1. It will replicate a component to two with different suffix. 
2. Replication policy will assign different `context.replica-key` when component rendered into K8s manifest (Deployment for example).  Then traitDefinition can use `context.replicaKey` to patch the manifest.

The render and dispatch process is shown below.
![image](https://user-images.githubusercontent.com/47812250/180148365-d3e96b9b-9b8b-4582-baf9-b2d0792c9038.png)

As for helm type component, it's the same process. The difference is traitDefinition will patch HelmRelease's value field. There is an example TraitDefinition to patch helm values:

```cue
annotations: {
	type: "trait"
	annotations: {}
	attributes: {
		podDisruptive: true
		appliesToWorkloads: ["helm"]
	}

}
template: {
	// +patchStrategy=jsonMergePatch
	patchOutputs: {
		release: {
			if spec.values != _|_ {
				spec: values: {
					nodeSelectorLabel: "apps.openyurt.io/nodepool"
					nodeSelectorLabel: [context.replicaKey]
				}
			}
		}
	}
	parameter: null
}
```

-----

There are also another patch method came up by @wangyikewxgm. Use `PostRender` [feature](https://fluxcd.io/docs/components/helm/api/#helm.toolkit.fluxcd.io/v2beta1.PostRenderer). The benefits is there is no need for expose specific argument in `Values.yaml` in helm chart. It'll be more convenient to deploy regular helm chart to edge.

**Comment by wonderflow** [comment]
1. normal apply without replication

```
piVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: first-vela-app2
spec:
  components:
    - name: redis
      type: helm
      properties:
        repoType: "helm"
        url: "https://charts.bitnami.com/bitnami"
        chart: "redis"
        version: "16.8.5"
```

2. Deploy with replication policy
```
piVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: first-vela-app2
spec:
  components:
    - name: redis
      type: helm
      properties:
        repoType: "helm"
        url: "https://charts.bitnami.com/bitnami"
        chart: "redis"
        version: "16.8.5"
      traits:
      - type: yurt-annoation-replication
        
  policies:
    - name: replication
      type: replication
      properties:
        keys: ["beijing","hangzhou"]
```
