### ISSUE TITLE
Missing ownerReference information in created resources by the kubevela operator

### ISSUE THREAD

**Issue by tommy1199** [kubevela/kubevela#4359]
**Describe the bug**

Kubernetes has the concept of ownership of resources (see [here](https://kubernetes.io/docs/concepts/overview/working-with-objects/owners-dependents/)). It is meant to avoid interfering of objects that do not belong to a controller, e.g. it can happen that based on the label selector two deployments think they own a ReplicaSet and start to modify it. To avoid that to controllers think they own the ReplicaSet a special field is set by the controller which created the ReplicaSet.

Kubevela acts here as an owner of several resources, but is not setting an ownerReference. This should be fixed to follow the standard way how operators and controllers work in Kubernetes

**To Reproduce**

Apply the following app definition 

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: app
spec:
  components:
  - name: app
    type: webservice
    properties:
      image: traefik/whoami:v1.8.1
      port: 80
    traits:
    - properties:
        domain: app.127.0.0.1.nip.io
        http:
          /: 80
      type: gateway
    - properties:
        cpuPercent: 80
        max: 5
        min: 2
      type: cpuscaler
```

kubevela creates several resources like deployment, service, hpa and ingress but none of the resources has an ownerReference.

```
kubectl get deployment app -o jsonpath='{.metadata.ownerReferences}'
kubectl get service app -o jsonpath='{.metadata.ownerReferences}'
kubectl get ingress app -o jsonpath='{.metadata.ownerReferences}'
kubectl get hpa app -o jsonpath='{.metadata.ownerReferences}'
```

Kubevela also creates an applicationrevision and sets the ownerReference correctly.

```
kubectl get applicationrevisions.core.oam.dev app-v1 -ojsonpath='{.metadata.ownerReferences}' | yq -P '.'
- apiVersion: core.oam.dev/v1beta1
  controller: true
  kind: Application
  name: app
  uid: fef924af-6825-41e2-a1aa-5ed765e51e60
```

**Expected behavior**
Kubevela shall set the same ownerReferences to all directly created resources as it does for the applicationsrevisions and shall update it if the Application uid changes.

It shall ignore all transitively created resources (e.g. replicasets which are created by the deployment controller and not kubevela)

The same shall happen for all created resources from other traits or properties (like secrets or configmap)

**KubeVela Version**

Controller Version: 1.4.1
CLI Version: 1.4.5

**Cluster information**
Kubernetes Version: 1.24.1

**Additional context**
See [Kubernetes documentation](https://kubernetes.io/docs/concepts/overview/working-with-objects/owners-dependents/) for more details
