### ISSUE TITLE
[Feature] Allow work together with multiple policies of the same type.

### ISSUE THREAD

**Issue by barnettZQG** [kubevela/kubevela#4389]
**Is your feature request related to a problem? Please describe.**

We can define some common scenario policies in advance, such as:

```yaml
kind: Policy
apiVersion: core.oam.dev/v1alpha1
metadata:
  name: allow-change-replicas
  namespace: default
spec:
   type: apply-once
   properties: 
     rules:
      - enable: true
        rules:
        - selector:
            resourceTypes:
            - Deployment
            - StatefulSet
            - Job
          strategy:
            path:
            - spec.replicas
```

This policy means allowing the replicas of the workloads(Deployment, StatefulSet, Job) configuration to drift.

```yaml
kind: Policy
apiVersion: core.oam.dev/v1alpha1
metadata:
  name: allow-change-labels
  namespace: default
spec:
   type: apply-once
   properties: 
     rules:
      - enable: true
        rules:
        - selector:
            resourceTypes:
            - Deployment
          strategy:
            path:
            - spec.template.metadata.labels
```
This policy means allowing the labels of the pod template(Deployment) configuration to drift.

Then, we could create an application to reference two policies.

```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: game-2048
  namespace: default
spec:
  components:
  - name: game-2048
    properties:
      cpu: "0.2"
      exposeType: ClusterIP
      image: evilroot/docker-2048
      imagePullPolicy: IfNotPresent
      memory: 128Mi
      ports:
      - expose: true
        port: 80
        protocol: TCP
    type: webservice
 policies:
  - name: default
    properties:
      clusters:
      - local
      namespace: default
    type: topology
  workflow:
    steps:
    - name: default
      properties:
        policies:
        - default
        -  allow-change-labels
        -  allow-change-replicas
      type: deploy
status: {}
```

Unfortunately, the `allow-change-replicas` can not work. For one application, the same type of policy only one could take effect.

**Describe the solution you'd like**

Allow work together with multiple policies of the same type.
