### ISSUE TITLE
ref-objects component don't dispatch updates to managedCluster when ref-objects modified in hubCluster

### ISSUE THREAD

**Issue by jiangshantao-dbg** [kubevela/kubevela#4418]
**Describe the bug**
i use ref-objects component in my application, ref-object is created and modified in hub cluster and then dispatch to managed clusters. when application first applied, everything is ok. but when i modified the ref-object in hub cluster, i want this modification should be dispatch to managed cluster as expected, it doesn't work.

**To Reproduce**
- the first apply in hub cluster
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: first-vela-app-pre
  namespace: dev-test
spec:
  components:
  - type: webservice
    name: first-vela-app-pre
    properties:
      image: nginx
  - type: ref-objects
    name: configmap
    properties:
      objects:
        - resource: configmap
          name: first-vela-app-pre
          namespace: default
          cluster: local
  - name: topology-local
    properties:
      clusters:
      - local
    type: topology
  - name: topology-other
    properties:
      clusters:
      - other
    type: topology
  workflow:
    steps:
    - name: deploy-cluster
      properties:
        policies:
        - topology-cluster
      type: deploy
    - name: manual-approval
      type: suspend
    - name: deploy-other
      properties:
        policies:
        - topology-other
      type: deploy
---
apiVersion: v1
kind: ConfigMap
metadata:
  name:  first-vela-app-pre
  namespace: default
data:
  key1: value1
```
- modified configmap in hub cluster
```
apiVersion: v1
kind: ConfigMap
metadata:
  name:  first-vela-app-pre
  namespace: default
data:
  key2: value2
```

**Expected behavior**
when ref-objects is modified, this modification should be dispatch to managed cluster defined in application without to modify application and trigger dispatching.

**Screenshots**

**KubeVela Version**
```
CLI Version: v1.5.0-alpha.3
Core Version: 1.5.0-alpha.3
GitRevision: git-a8d5403
GolangVersion: go1.17.11
```
**Cluster information**
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
**Additional context**

**Comment by wonderflow** [comment]
You need to update the application after the configmap modified to trigger the deploy happen.

You can change the annotation:

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: first-vela-app-pre
  namespace: dev-test
  annotations:
     app.oam.dev/publishVersion: "v1"
spec:
  components:
  - type: webservice
    name: first-vela-app-pre
    properties:
      image: nginx
  - type: ref-objects
    name: configmap
    properties:
      objects:
        - resource: configmap
          name: first-vela-app-pre
          namespace: default
          cluster: local
  - name: topology-local
    properties:
      clusters:
      - local
    type: topology
  - name: topology-other
    properties:
      clusters:
      - other
    type: topology
  workflow:
    steps:
    - name: deploy-cluster
      properties:
        policies:
        - topology-cluster
      type: deploy
    - name: manual-approval
      type: suspend
    - name: deploy-other
      properties:
        policies:
        - topology-other
      type: deploy
```
