### ISSUE TITLE
cross namespace definitions reference

### ISSUE THREAD

**Issue by diego-milhomes** [kubevela/kubevela#4427]
**Describe the bug**

Following the spec, I tried to use cross namespace definitions reference. [Spec](https://github.com/oam-dev/spec/blob/master/7.application.md#component)

_Optionally a namespaced component may be referenced as "namespace/component_name"_

**To Reproduce**

1. The YAML files of Component/Trait I used.
```
apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  annotations:
    definition.oam.dev/description: Add labels on K8s pod for your workload which follows the pod spec in path 'spec.template'.
  labels:
    custom.definition.oam.dev/ui-hidden: "true"
  name: labels-one
  namespace: def-one
spec:
  appliesToWorkloads:
    - "*"
  podDisruptive: true
  schematic:
    cue:
      template: |
        // def-one +patchStrategy=jsonMergePatch
        patch: {
        	metadata: labels: {
        		for k, v in parameter {
        			"\(k)": v
        		}
        	}
        	if context.output.spec != _|_ && context.output.spec.template != _|_ {
        		spec: template: metadata: labels: {
        			for k, v in parameter {
        				"\(k)": v
        			}
        		}
        	}
        }
        parameter: [string]: string | null
```
3. The YAML file of Application I applied.
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: example-app-with-trait
  namespace: default
  annotations:
    app.oam.dev/revision-only: "true"
spec:
  components:
    - name: testsvc-with-trait
      type: "webservice"
      properties:
        addRevisionLabel: true
        image: nginx
        port: 80
      traits:
        # the `labels` trait will add/delete label key/value pair to the
        # labels of the workload and the template inside the spec of the workload (if exists)
        # 1. if original labels contains the key, value will be overridden
        # 2. if original labels do not contain the key, value will be added
        # 3. if original labels contains the key and the value is null, the key will be removed
        - type: "def-one/labels-one"
          properties:
            added-label-key: added-label-def-one
            label-key: modified-label-def-one
            to-delete-label-key: null

```
4. Create app without trait created, result in this error:

```
❯ kubectl apply -f app-test-external-with-trait.yaml
Error from server: error when creating "app-test-external-with-trait.yaml": admission webhook "validating.core.oam.dev.v1beta1.applications" denied the request: field "spec": Invalid value error encountered, component(testsvc-with-trait) parse trait(def-one/labels-one): trait definition of def-one/labels-one not found.
```
5. Create app with trait created, result in this success:

```
application.core.oam.dev/example-app-with-trait created
```
6. But app revision rendered the trait:

```
traitDefinitions:
    labels-one:
      apiVersion: core.oam.dev/v1beta1
      kind: TraitDefinition
      metadata:
        annotations:
          definition.oam.dev/description: Add labels on K8s pod for your workload
            which follows the pod spec in path 'spec.template'.
          kubectl.kubernetes.io/last-applied-configuration: |
            {"apiVersion":"core.oam.dev/v1beta1","kind":"TraitDefinition","metadata":{"annotations":{"definition.oam.dev/description":"Add labels on K8s pod for your workload which follows the pod spec in path 'spec.template'."},"labels":{"custom.definition.oam.dev/ui-hidden":"true"},"name":"labels-one","namespace":"def-one"},"spec":{"appliesToWorkloads":["*"],"podDisruptive":true,"schematic":{"cue":{"template":"// def-one +patchStrategy=jsonMergePatch\npatch: {\n\tmetadata: labels: {\n\t\tfor k, v in parameter {\n\t\t\t\"\\(k)\": v\n\t\t}\n\t}\n\tif context.output.spec != _|_ \u0026\u0026 context.output.spec.template != _|_ {\n\t\tspec: template: metadata: labels: {\n\t\t\tfor k, v in parameter {\n\t\t\t\t\"\\(k)\": v\n\t\t\t}\n\t\t}\n\t}\n}\nparameter: [string]: string | null\n"}}}}
        labels:
          custom.definition.oam.dev/ui-hidden: "true"
        name: labels-one
        namespace: def-one
      spec:
        appliesToWorkloads:
        - '*'
        definitionRef:
          name: ""
        podDisruptive: true
        schematic:
          cue:
            template: "// def-one +patchStrategy=jsonMergePatch\npatch: {\n\tmetadata:
              labels: {\n\t\tfor k, v in parameter {\n\t\t\t\"\\(k)\": v\n\t\t}\n\t}\n\tif
              context.output.spec != _|_ && context.output.spec.template != _|_ {\n\t\tspec:
              template: metadata: labels: {\n\t\t\tfor k, v in parameter {\n\t\t\t\t\"\\(k)\":
              v\n\t\t\t}\n\t\t}\n\t}\n}\nparameter: [string]: string | null\n"
      status: {}
```

6. The workflow show the following error:
```
message: 'step apply: run step(provider=oam,do=component-apply): ParseWorkload:
        component(testsvc-with-trait) parse trait(def-one/labels-one): TraitDefinition
        [def-one/labels-one] not found in app revision example-app-with-trait-v1'
```

**Expected behavior**

Application has deployed and health.

**Screenshots**

**KubeVela Version**

1.4.5, 1.4.8 and 1.5.0-beta.1

**Cluster information**

1.21 and 1.22

**Additional context**
