### ISSUE TITLE
Canary Rollout on helm chart error

### ISSUE THREAD

**Issue by clcc2019** [kubevela/kubevela#4519]
![image](https://user-images.githubusercontent.com/46099295/182268669-6952ceb9-893b-47e8-aceb-00bd0178b075.png)

All pods are updated directly and cannot achieve the expected effect

vela-core v1.5.0-beta4
fluxcd 2.0

**Comment by wonderflow** [comment]
Can you describe the application here?

**Comment by clcc2019** [comment]
> Can you describe the application here?
![image](https://user-images.githubusercontent.com/46099295/182269957-b1e5e111-2d01-47d4-916b-9845f40a8b67.png)
```yaml
cat <<EOF | vela up -f -
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: nginx
  annotations:
    app.oam.dev/publishVersion: v1
spec:
  components:
  - name: web
    type: helm
    properties:
      repoType: oss
      secretRef: bucket-secret
      url: oss-cn-xxx.aliyuncs.com
      chart: ./charts/xxx.tgz
      values:
        image:
          pullPolicy: "Always"
          repository: "ssssssnginx"
          tag: "v1"
        serviceports:
        - name: "http"
          port: 80
          protocol: "TCP"
          targetPort: "http"
        replicaCount: 5
        ports:
          enabled: true
          port:
          - containerPort: 80
            name: "http"
            protocol: "TCP"
        ingress:
          annotations:
            meta.helm.sh/release-name: web
            meta.helm.sh/release-namespace: default
            nginx.ingress.kubernetes.io/ssl-redirect: "false"
            nginx.org/compute-full-forwarded-for: "true"
            nginx.org/forwarded-for-header: X-Forwarded-For
            nginx.org/use-forwarded-headers: "true"
          hosts:
          - "bigdata-test11.dd.com"
          path:
          - "/"
          servicePort: "http"
          tls: {}
      oss:
        bucketName: starship-charts
      version: 17.0.5
    traits:
    - type: kruise-rollout
      properties:
        canary:
          steps:
          - weight: 20
          - weight: 90
          trafficRoutings:
          - type: nginx
  - name: bucket-secret
    type: raw
    properties:
      apiVersion: v1
      stringData:
        accesskey:  
        secretkey:  
      kind: Secret
      metadata:
        name: bucket-secret
      type: opaque
EOF
```
