### ISSUE TITLE
[Feature] deploy step supports Input/Output Variables

### ISSUE THREAD

**Issue by kferrone** [kubevela/kubevela#4658]
**Describe the bug**

If your components use input output steps, then those will not resolve if you use the deploy workflow step. 

**To Reproduce**

Try this one out:

```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: foo-tester
  namespace: default
spec:
  components: 
  - type: helm
    name: nginx-test
    inputs:
    - from: items
      parameterKey: properties.values.items
    properties:
      targetNamespace: default
      chart: nginx
      url: https://charts.bitnami.com/bitnami
      version: "12.0.0"
      values:
        replicas: 12
  - type: k8s-objects
    name: some-things
    outputs:
    - name: items
      valueFrom: output.data["items"]
    properties:
      objects:
      - apiVersion: v1
        kind: ConfigMap 
        metadata:
          name: some-things-around
        data:
          items: egss,pizza,cactus
          through: the door
          replicas: "1"
  workflow:
    steps:
    - name: upit 
      type: deploy
      properties: 
        policies: []
        
```

**Expected behavior**

The values key should ultimately have the items value. 

**Screenshots**

**KubeVela Version**

1.5

**Cluster information**

1.22 eks

**Additional context**

If you apply the components one by one with `apply-component` then the input/output is resolved.
