### ISSUE TITLE
The application can not render resources without the clusters in the topology.

### ISSUE THREAD

**Issue by barnettZQG** [kubevela/kubevela#4671]
**Describe the bug**

The application can not render resources without the clusters in the topology.

**To Reproduce**

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: nginx
  namespace: e2e-test
spec:
  components:
    - name: nginx
      properties:
        image: nginx
      traits:
        - properties:
            replicas: 2
          type: scaler
      type: webservice
  policies:
    - name: topology
      properties:
        namespace: e2e-test
      type: topology
  workflow:
    steps:
      - name: deploy-e2e
        properties:
          auto: true
          ignoreTerraformComponent: true
          parallelism: 5
          policies:
            - topology
        type: deploy
```
```
bash-5.1# vela status nginx -n e2e-test
About:

  Name:         nginx                        
  Namespace:    e2e-test                     
  Created at:   2022-08-31 08:18:29 +0000 UTC
  Status:       running                      

Workflow:

  mode: StepByStep
  finished: true
  Suspend: false
  Terminated: false
  Steps
  - id: qluprgrykq
    name: deploy-e2e
    type: deploy
    phase: succeeded 
    message: 

bash-5.1# vela status nginx -n e2e-test --pod
CLUSTER COMPONENT       POD NAME        NAMESPACE       PHASE   CREATE TIME     REVISION        HOST
bash-5.1# vela status nginx -n e2e-test --tree
CLUSTER       NAMESPACE     RESOURCE  STATUS 
```

**Expected behavior**

This application should be deployed to the e2e-test namespace in hub cluster.

**KubeVela Version**

1.5.3
