### ISSUE TITLE
kubevela upgrade from 1.4.x->1.5.x, the workflow rerun, but if from 1.5.1 to 1.5.4 not 

### ISSUE THREAD

**Issue by yuchu01** [kubevela/kubevela#4725]
**Describe the bug**

Upgrade version from 1.4.x -> 1.5.x trigger workflow rerun , 1.5.1 to 1.5.4 not .

This bug still in 1.2.x -> 1.3.x, etc. Keep  the `MINOR version`  different .

**To Reproduce**

1. add `notification` , such as:
```
  workflow:
    steps:
    - name: deploy-dev
      type: deploy
      properties:
        policies: ["topology-dev", "override-dev"]
    - name: dingtalk-message-dev
      type: notification
      properties:
        dingding:
          url:
            secretRef:
              name: secret-dingtalk
              key: url
          message:
            msgtype: markdown
            markdown:
              title: "xxxx"
              text: "some message"
```

2. keep application workflow **running**

3. upgrade kubevela version, from 1.4.x -> 1.5.x , the `MINOR version` need different , will trigger notification

**Expected behavior**

not rerun **workflow** if upgrade kubevela version.

**Screenshots**

**KubeVela Version**

1.x.x version

**Cluster information**

**Additional context**
