### ISSUE TITLE
The apply-once strategy has inconsistent behavior in the state maintenance phase and the republishing phase

### ISSUE THREAD

**Issue by zxbyoyoyo** [kubevela/kubevela#4757]
**Describe the bug**

The apply-once strategy will only take effect during the state maintenance phase

**To Reproduce**
1. I deployed this example first, scaler.replicas is set to  1, and the number of copies of the underlying Deployment is 1.
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: apply-once-app
spec:
  components:
    - name: hello-world
      type: webservice
      properties:
        image: oamdev/hello-world
      traits:
        - type: scaler
          properties:
            replicas: 1
  policies:
    - name: apply-once
      type: apply-once
      properties:
        enable: true
        rules:
        - strategy:
            path:
            - spec.replicas
          selector:
            resourceTypes:
            - Deployment

```

2. Then I manually or through HPA changed the number of copies of the underlying Deployment to 4 --- this 4 is the number of drift copies I want to configure, and I don't want it to be managed by KubevelaController

3. Then I modified this example yaml, scaler.replicas was changed to 3, then I expected the rendered Deployment to be 4, and the result used 3

**Expected behavior**

**Screenshots**

**KubeVela Version**

**Cluster information**

**Additional context**

**Comment by wonderflow** [comment]
Yes, the apply-once now has ambiguity, we need add more on the strategy, such as:

```
    - name: apply-once
      type: apply-once
      properties:
        enable: true
        rules:
        - strategy:
            affect: onCreate | onUpdate          
            path:
            - spec.replicas
          selector:
            resourceTypes:
            - Deployment

```
