### ISSUE TITLE
[Feature]  Proposal of supporting to add context info when render application.

### ISSUE THREAD

**Issue by wangyikewxgm** [kubevela/kubevela#4791]
**Is your feature request related to a problem? Please describe.**

Senarior:

Assume that I'm a cluster operator, and I had installed a Loki server in my cluster.  I want make a traitDefinition to help  users to sink  the application log to  the loki server without caring about what the loki endopint is. Because the loki server was installed by me, users don't know neither. User just create  an application like this:

```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: my-biz
spec:
  components:
    - name:  biz-workload
      type: webservice
      properties:
        image: nginx
        port: 80
     traits:
       ### user needn't config the loki endpoint
       type: collect-log-file
       path: /xxx/app.log
```

Currently, we have supported many `context` infos when render application, so I propose to  support cluster operator can add info in `context`. 

**Describe the solution you'd like**

*Potential solution*

When render an application, app controller can read `user set render context` from a configMap. So I can set the loki endpoint in the configMap as `runtime.loki.endpoint=<public-ip>`.

Then I can define the  traitDefinition 's parameter like this:

```cue
parameter: {
    path: string
    lokiEndpoint?: *context.loki.endpoint | string
}

```

**Describe alternatives you've considered**

**Additional context**
