### ISSUE TITLE
[Feature]Add a new patch strategy annotation that can Ignore some values while overriding or merging values

### ISSUE THREAD

**Issue by tangoliu** [kubevela/kubevela#4804]
**Is your feature request related to a problem? Please describe.**
In the actual production environment, the platform may have its own system environment variables, which are usually used for other management platforms, such as the log platform. However, these environment variables are transparent to users, so users do not know that these environment variables exist. As a result, users may use environment variables with the same name as the platform when configuring environment variables, which may lead to platform failure.
If a patch policy is added, some environment variables can be ignored when merging or overwriting. Even if the user has configured the same environment variables, the platform environment variables will not be overwritten, which can solve the problem in this scenario.

**Describe the solution you'd like**
such as
```
myenv: {  
  type: "trait"  
  annotations: {}  
  labels: {  
    "ui-hidden": "true"  
  }  
  attributes: appliesToWorkloads: ["*"]  
}  
template: {  
  patch: {  
    spec: template: spec: {  
              // +patchKey=name  
              containers: [{  
                name: context.name  
                // +patchStrategy=retainKeys
                // e.g. +patchIgnore=AA,BB
                env: [  
                  for k, v in parameter.env {  
                    name: k  
                    value: v  
                  },  
                ]  
    }]  
  }  
}
  
  parameter: {  
    env: [string]: string  
  }  
}
```
Use the above myenv trait in application:
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: webservice-app
spec:
  components:
    - name: express-server
      type: webservice
      properties:
        image: crccheck/hello-world
        env:
          - name: OLD
            value: old
          - name: AA
            value: old2
      traits:
        - type: myenv
          properties:
            env:
              NEW: new
              AA: xx
```
Before using the myenv patch trait, the env in the application is like:
```
spec:
  containers:
  - env:
    - name: OLD
      value: old
    - name: AA
      value: old2
```
After using the myenv patch trait, the env in the application is like:
```
spec:
  containers:
  - env:
    - name: OLD
      value: old
    - name: AA
      value: old2
    - name: NEW
      value: new
```
Similarly, for +patchStrategy=replace, add the same policy(e.g. +patchIgnore=AA,BB).
Before using the myenv patch trait, the env in the application is like:
```
spec:
  containers:
  - env:
    - name: OLD
      value: old
    - name: AA
      value: old2
```
After using the myenv patch trait, the env in the application is like:
```
spec:
  containers:
  - env:
    - name: AA
      value: old2
    - name: NEW
      value: new
```
