### ISSUE TITLE
Can't query workflow execution records of Application with PublishVersion annotation 

### ISSUE THREAD

**Issue by aoreki** [kubevela/kubevela#4816]
**Describe the bug**
When annotation `app.oam.dev/publishVersion: xx` is added to Application,I can't query application workflow execution records using kubevela HTTP API. Thus can't use API to resume or rollback workflow record. Not sure if this a feature or a bug.

**To Reproduce**
nginx-app.yaml
```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: nginx-app
  namespace: default
  annotations:
    app.oam.dev/publishVersion: 1.22
spec:
  components:
    - name: nginx
      type: webservice
      properties:
        image: nginx:1.22
      traits:
        - type: expose
          properties:
            port: [80]
  workflow:
    steps:
    - name: apply
      type: apply-component
      properties:
        component: nginx
    - name: suspend
      type: suspend
```

```bash
$ vela up -f nginx-app.yaml
Application default/nginx-app applied.
$ vela port-forward -n vela-system addon-velaux -c apiserver 8000:8000
trying to connect the remote endpoint svc/apiserver 8000:8000 ..Forwarding from 127.0.0.1:8000 -> 8000
Forwarding from [::1]:8000 -> 8000
Forward successfully! Opening browser ...
$ curl http://127.0.0.1:8000/api/v1/applications/nginx-app/workflows/syc-nginx-app/records -H 'Authorization: Bearer <token>'
{
 "records": [],
 "total": 0
}
```
Then delete app
```bash
$ vela delete nginx-app
```
Remove the publish annotation
```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: nginx-app
  namespace: default
spec:
  components:
    - name: nginx
      type: webservice
      properties:
        image: nginx:1.22
      traits:
        - type: expose
          properties:
            port: [80]
  workflow:
    steps:
    - name: apply
      type: apply-component
      properties:
        component: nginx
    - name: suspend
      type: suspend
```

```bash
$ vela up -f nginx-app.yaml
Application default/nginx-app applied.
$ curl http://127.0.0.1:8000/api/v1/applications/nginx-app/workflows/syc-nginx-app/records -H 'Authorization: Bearer <token>'
{
 "records": [
  {
   "name": "nginx-app-v1-5ad7601dcca7d5e9",
   "namespace": "default",
   "workflowName": "syc-nginx-app",
   "workflowAlias": "syc-nginx-app",
   "applicationRevision": "nginx-app-v1",
   "startTime": "0001-01-01T00:00:00Z",
   "status": "running",
   "steps": [
    {
     "id": "",
     "name": "apply",
     "alias": "",
     "type": "apply-component",
     "phase": "succeeded",
     "firstExecuteTime": "2022-09-30T07:50:50Z",
     "lastExecuteTime": "2022-09-30T07:50:53Z"
    },
    {
     "id": "",
     "name": "suspend",
     "alias": "",
     "type": "suspend",
     "phase": "running",
     "firstExecuteTime": "2022-09-30T07:50:53Z",
     "lastExecuteTime": "2022-09-30T07:50:53Z"
    }
   ]
  }
 ],
 "total": 1
}
```
But can't use this record to rollback, only can resume.
```bash
$ curl http://127.0.0.1:8000/api/v1/applications/nginx-app/workflows/syc-nginx-app/records/nginx-app-v1-5ad7601dcca7d5e9/rollback -H 'Authorization: Bearer <token>'
{
 "BusinessCode": 10017,
 "Message": "application not have ready revision"
}
```

**Expected behavior**
Show workflow execution records correctly. With publishversion annotation, I can rollback Application with cli. But I want to rollback with API

**Screenshots**

**KubeVela Version**
```bash
$ vela version
CLI Version: v1.5.6
Core Version: 1.5.6
GitRevision: git-4c525f8
GolangVersion: go1.17.13
```

**Cluster information**
```bash
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.11-aliyun.1", GitCommit:"88d5e8b", GitTreeState:"", BuildDate:"2021-10-25T13:55:31Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.3-aliyun.1", GitCommit:"937757761d3c1db7080f179102b437c26c521ecd", GitTreeState:"clean", BuildDate:"2022-05-26T12:38:52Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
