### ISSUE TITLE
[Feature]对GitOps应用来说，如果url,pullInterval,git.branch这三个参数的值相同，希望共用同一个gitRepo CR

### ISSUE THREAD

**Issue by miyoosan** [kubevela/kubevela#4820]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/25057968/193416235-1b44bcbe-8ff4-4ea8-a7c2-8964b874ea3e.png)

如上图所示，我有56个GitOps应用(参考`https://kubevela.net/zh/docs/end-user/gitops/fluxcd`)，都是监听同一个git仓库(url)，监听频次(pullInterval)与仓库分支(git.branch)完全一样，只是目录(path)不一样。

统计了一下，频次设为1分钟的时候，平均要10分钟才能走完一次reconcilation。意味着推送完镜像后，一直到自动分发应用，这过程至少要花费10分钟时间。后面如果创建更多应用，这个时间只会线性增长，而不可能减少，非常糟糕。

如果频次都设为5秒(期望值)，对git仓库服务器来说，并发压力会比较大(10个并发数左右吧)，flux-system的几个pod也要承受这种并发数，要想维持服务正常运转，请求资源得加x倍。

那么，对于这56个应用来说，能否只创建一个监听(gitRepo CR)，做一次拉取，而不是创建56个监听，去拉取56遍呢？

这样的话， 因为只有一个监听，那我就可以大胆地把频次设为5秒，而不用担心并发数，reconcilation的总时间也会降到1分钟以内，甚至是十几秒，大大提高了响应速度，支持应用的秒级部署是非常轻松的事情。

**Describe alternatives you've considered**

**Additional context**

**Comment by chengleqi** [comment]
情况应该是这样的，官方的[FluxCD插件](https://github.com/kubevela/catalog/tree/master/addons/fluxcd)提供了[Kustomize](https://github.com/kubevela/catalog/blob/master/addons/fluxcd/definitions/kustomize.cue)的ComponentDefinition，当你创建一个Kustomize应用时，会生成对应FluxCD的一个[Repository](https://github.com/kubevela/catalog/blob/9196c149d24ed4644efeec363dcc9b7915d47841/addons/fluxcd/definitions/kustomize.cue#L40)和一个[Kustomization](https://github.com/kubevela/catalog/blob/9196c149d24ed4644efeec363dcc9b7915d47841/addons/fluxcd/definitions/kustomize.cue#L11)，这两个FluxCD资源通过`context.name`关联，所以你有几个Kustomize就有几个Repository，而且Helm也是这样的，这种组合抽象容易使用一点，但是缺少了FluxCD原本的灵活。

我感觉感觉官方的插件可以这样改进一下：

- 把kustomize和helm的[source](https://github.com/kubevela/catalog/blob/9196c149d24ed4644efeec363dcc9b7915d47841/addons/fluxcd/definitions/kustomize.cue#L41)的输出作为可选的
- 暴露[source name](https://github.com/kubevela/catalog/blob/9196c149d24ed4644efeec363dcc9b7915d47841/addons/fluxcd/definitions/kustomize.cue#L27)，让用户可以选择源
- 添加源的ComponentDefinetion

我觉得这个场景还是挺常见的，我可以先尝试着搞一搞
@wonderflow @barnettZQG @FogDong @wangyikewxgm

**Comment by oeular** [comment]
You can assign the issue to yourself by commenting "/assign"

**Comment by miyoosan** [comment]
> 我感觉感觉官方的插件可以这样改进一下：
> 
> * 把kustomize和helm的[source](https://github.com/kubevela/catalog/blob/9196c149d24ed4644efeec363dcc9b7915d47841/addons/fluxcd/definitions/kustomize.cue#L41)的输出作为可选的
> * 暴露[source name](https://github.com/kubevela/catalog/blob/9196c149d24ed4644efeec363dcc9b7915d47841/addons/fluxcd/definitions/kustomize.cue#L27)，让用户可以选择源
> * 添加源的ComponentDefinetion
> 

@chengleqi  解法很nice！期待您的改进~ 谢谢~

**Comment by chivalryq** [comment]
@chengleqi Nice idea! You can add new parameters like `sourceName`. when this parameter is not empty, skip  outputting the Source resource. So that you can keep the backward compatibility.

**Comment by wonderflow** [comment]
> 情况应该是这样的，官方的[FluxCD插件](https://github.com/kubevela/catalog/tree/master/addons/fluxcd)提供了[Kustomize](https://github.com/kubevela/catalog/blob/master/addons/fluxcd/definitions/kustomize.cue)的ComponentDefinition，当你创建一个Kustomize应用时，会生成对应FluxCD的一个[Repository](https://github.com/kubevela/catalog/blob/9196c149d24ed4644efeec363dcc9b7915d47841/addons/fluxcd/definitions/kustomize.cue#L40)和一个[Kustomization](https://github.com/kubevela/catalog/blob/9196c149d24ed4644efeec363dcc9b7915d47841/addons/fluxcd/definitions/kustomize.cue#L11)，这两个FluxCD资源通过`context.name`关联，所以你有几个Kustomize就有几个Repository，而且Helm也是这样的，这种组合抽象容易使用一点，但是缺少了FluxCD原本的灵活。
> 
> 我感觉感觉官方的插件可以这样改进一下：
> 
> * 把kustomize和helm的[source](https://github.com/kubevela/catalog/blob/9196c149d24ed4644efeec363dcc9b7915d47841/addons/fluxcd/definitions/kustomize.cue#L41)的输出作为可选的
> * 暴露[source name](https://github.com/kubevela/catalog/blob/9196c149d24ed4644efeec363dcc9b7915d47841/addons/fluxcd/definitions/kustomize.cue#L27)，让用户可以选择源
> * 添加源的ComponentDefinetion
> 
> 我觉得这个场景还是挺常见的，我可以先尝试着搞一搞 @wonderflow @barnettZQG @FogDong @wangyikewxgm

This solution could work, please keep the backward compatibility and make it simple in default case.

**Comment by miyoosan** [comment]
@chengleqi 我看了一下提交的代码，有点没太看懂。该怎么使用sourceName呢？是按我设想的那样吗？

我举个例子：
现在有A、B、C三个应用，它们打算共用一个git respository，先部署A，再部署B、C。
在我的认知里，B与C里面，肯定要使用sourceName的，值为A的名称。假设A的yaml如下：

```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: fluxcd-app-a
  namespace: default
spec:
  components:
  - name: fluxcd-app-a
    type: kustomize
    properties:
      repoType: git
      url: http://gitlab:80/sre/k8s-vela-config.git
      secretRef: git-secret
      pullInterval: 1m
      git:
        branch: master
      path: ./test/apps/default/app-a
```
那么，B的yaml应该长这样：

```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: fluxcd-app-b
  namespace: default
spec:
  components:
  - name: fluxcd-app-b
    type: kustomize
    properties:
      sourceName: fluxcd-app-a
      repoType: git
      url: http://gitlab:80/sre/k8s-vela-config.git
      secretRef: git-secret
      pullInterval: 1m
      git:
        branch: master
      path: ./test/apps/default/app-b
```
C的跟B类似，只是把yaml里的 fluxcd-app-b改成了 fluxcd-app-c，这里就不贴出来了。

这样使用sourceName的方式是否正确？

假设B跟C还在running，A应用如果被执行删除，是直接删除失败吗？还是会把A删除了，并保留fluxcd-app-a这个git repository？

**Comment by chengleqi** [comment]
这个sourceName是指A创建出来的GitRepository的名称，并且B直接可以是这样的：
```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: fluxcd-app-b
  namespace: default
spec:
  components:
  - name: fluxcd-app-b
    type: kustomize
    properties:
      sourceName: fluxcd-app-a
      repoType: git
      pullInterval: 1m
      path: ./test/apps/default/app-b
```
`url`、`git.branch`、`secretRef`其实是可以省略的，因为这些信息已经包含在fluxcd-app-a的GitRepository里了。

我想如果要删除A应用，应该会成功删除掉GitRepository和Kustomization，但是B和C应用会找不到GitRepository，会在下次的Reconcile中报错。

**Comment by wonderflow** [comment]
这么看这种场景准确的用法应该是使用 shared-resource policy，把  source 作为单独的组件创建，并设置为 shared-resource。

https://kubevela.net/docs/end-user/policies/shared-resource

**Comment by miyoosan** [comment]
@chengleqi 好的，谢谢~ 了解了！直接删除比较干净，需要再创建一个新的也可以，短暂的错误应该不怎么影响业务。

**Comment by chengleqi** [comment]
> 这么看这种场景准确的用法应该是使用 shared-resource policy，把 source 作为单独的组件创建，并设置为 shared-resource。
> 
> https://kubevela.net/docs/end-user/policies/shared-resource

嗯嗯 我看下 我也准备创建source的ComponentDefinition，选择生成GitRepository、HelmRepository、OCIRepository和Bucket中的其中一种。

**Comment by miyoosan** [comment]
> 这么看这种场景准确的用法应该是使用 shared-resource policy，把 source 作为单独的组件创建，并设置为 shared-resource。
> 
> https://kubevela.net/docs/end-user/policies/shared-resource
> 
> > 我想如果要删除A应用，应该会成功删除掉GitRepository和Kustomization，但是B和C应用会找不到GitRepository，会在下次的Reconcile中报错。
> 
> 如果不介意这一点， @chengleqi 的写法OK，但是我们也应该支持 shared-resource 的做法

使用shared-resource的话，只有删除最后一个应用才会把git repository删除?  还是说，一经创建，它就是独立的了，应用删除与否，跟它没有关系？

**Comment by wonderflow** [comment]
@miyoosan 细节可以看下文档，是最后一个app删除才会删除shared-resource

**Comment by miyoosan** [comment]
> 

嗯嗯，刚刚看完了，明白，谢谢！

**Comment by miyoosan** [comment]
> @chengleqi 我看了一下提交的代码，有点没太看懂。该怎么使用sourceName呢？是按我设想的那样吗？
> 
> 我举个例子： 现在有A、B、C三个应用，它们打算共用一个git respository，先部署A，再部署B、C。 在我的认知里，B与C里面，肯定要使用sourceName的，值为A的名称。假设A的yaml如下：
> 
> ```yaml
> apiVersion: core.oam.dev/v1beta1
> kind: Application
> metadata:
>   name: fluxcd-app-a
>   namespace: default
> spec:
>   components:
>   - name: fluxcd-app-a
>     type: kustomize
>     properties:
>       repoType: git
>       url: http://gitlab:80/sre/k8s-vela-config.git
>       secretRef: git-secret
>       pullInterval: 1m
>       git:
>         branch: master
>       path: ./test/apps/default/app-a
> ```
> 
> 那么，B的yaml应该长这样：
> 
> ```yaml
> apiVersion: core.oam.dev/v1beta1
> kind: Application
> metadata:
>   name: fluxcd-app-b
>   namespace: default
> spec:
>   components:
>   - name: fluxcd-app-b
>     type: kustomize
>     properties:
>       sourceName: fluxcd-app-a
>       repoType: git
>       url: http://gitlab:80/sre/k8s-vela-config.git
>       secretRef: git-secret
>       pullInterval: 1m
>       git:
>         branch: master
>       path: ./test/apps/default/app-b
> ```
> 
> C的跟B类似，只是把yaml里的 app-b改成了app-c，这里就不贴出来了。
> 
> 这样使用sourceName的方式是否正确？
> 
> 假设B跟C还在running，A应用如果被执行删除，是直接删除失败吗？还是会把A删除了，并保留fluxcd-app-a这个git repository？

@chengleqi 我还有个疑问，A是在default命名空间创建的，C是在demo命名空间创建的，C能使用A的gitRepository吗？我的业务场景想跨命名空间共用同一个gitRepository。

**Comment by chengleqi** [comment]
这个应该不能，默认创建在一个名称空间了。不过以后要是有source的ComponentDefinition，你就直接可以把GitRepository创建在demo名称空间了，而不用使用A附带创建出来的GitRepository。

**Comment by miyoosan** [comment]
> 这个应该不能，默认创建在一个名称空间里了。不过以后要是有source的ComponentDefinition，你就直接可以把GitRepository创建在demo名称空间了，而不用使用A附带创建出来的GitRepository。

了解。单独创建source的话，path参数也是必须的吧？让它指向一个永远不会更新的目录，是否是比较好的做法? 只有业务应用里的path，才需要指向应用对应的目录。source作为公用资源，空转就好了。

**Comment by chengleqi** [comment]
这个Path参数是[Kustomization](https://github.com/fluxcd/kustomize-controller/blob/ce46ec8f78922f39cd22b92cb3194d7a077a324c/api/v1beta2/kustomization_types.go#L77)的，创建GitRepository的source是不需要path的。

一个GitRepository应该只负责维护一个gitrepo的内容，比如branch等，path这种参数应该是应用层面的比如Kustomization和HelmRelease。所以可以引用同一个GitRepository但设置不同的path来创建两个不同的Kustomization或者HelmRelease。

**Comment by miyoosan** [comment]
@chengleqi  啊，是我想差了，抱歉！那这样就比较好了！

btw，对于已经存在的应用D来说，如果给它加上resourceName，值为fluxcd-app-a，然后apply。那么D原来的GitRepository是会被自动删除吧？应用D的path下面有1个业务应用在running，我担心的是，该业务应用是否会受影响？

**Comment by chengleqi** [comment]
原来的应用D的GitRepository虽然不被引用了，但是不会被自动删除会一直存在，可以手动删除掉这个GitRepository。
不会影响业务，因为D会引用到新的source，D应用中的Kustomization可以从你设置的sourceName对应的GitRepository那里获得Artifacts。

**Comment by miyoosan** [comment]
> 原来的应用D的GitRepository虽然不被引用了，但是不会被自动删除会一直存在，可以手动删除掉这个GitRepository。 不会影响业务，因为D会引用到新的source，D应用中的Kustomization可以从你设置的sourceName对应的GitRepository那里获得Artifacts。

好的，非常nice!

我总结一下，你看看对不对：

1. GitRepository有两种创建方式：

    (1) 依据相应的ComponentDefinition手动创建。 
    (2) 创建Component类型为kustomize的Application时，指定repoType为git。

2. 可通过sourceName来引用相同Namespace下已有的GitRepository。

3. 对于kustomize的Application来说，升级fluxcd addon版本后，使用sourceName引用其它GitRepository不影响path关联的应用，但它原有的GitRepository不会被自动删除，需要手动清理。（当然，前提条件是这2个GitRepository的url与branch保持一致）

4. 删除任何一个GitRepository之前，最好先确认有哪些Application引用了它，避免造成不好的影响。

**Comment by chengleqi** [comment]
> > 原来的应用D的GitRepository虽然不被引用了，但是不会被自动删除会一直存在，可以手动删除掉这个GitRepository。 不会影响业务，因为D会引用到新的source，D应用中的Kustomization可以从你设置的sourceName对应的GitRepository那里获得Artifacts。
> 
> 好的，非常nice!
> 
> 我总结一下，你看看对不对：
> 
> 1. GitRepository有两种创建方式：
>    (1) 依据相应的ComponentDefinition手动创建。
>    (2) 创建Component类型为kustomize的Application时，指定repoType为git。
> 2. 可通过sourceName来引用相同Namespace下已有的GitRepository。
> 3. 对于kustomize的Application来说，升级fluxcd addon版本后，使用sourceName引用其它GitRepository不影响path关联的应用，但它原有的GitRepository不会被自动删除，需要手动清理。（当然，前提条件是这2个GitRepository的url与branch保持一致）
> 4. 删除任何一个GitRepository之前，最好先确认有哪些Application引用了它，避免造成不好的影响。

我觉得没问题

**Comment by miyoosan** [comment]
@chengleqi 你好，我还有个疑问，vela暴露的pullInterval参数，是[GitRepository](https://github.com/chengleqi/kubevela-catalog/blob/f75ab6242ed398481b21e6d03a10dfa413ed7bfe/addons/fluxcd/definitions/kustomize.cue#L19)、[ImageRepository](https://github.com/chengleqi/kubevela-catalog/blob/f75ab6242ed398481b21e6d03a10dfa413ed7bfe/addons/fluxcd/definitions/kustomize.cue#L91)、[ImageUpdateAutomation](https://github.com/chengleqi/kubevela-catalog/blob/f75ab6242ed398481b21e6d03a10dfa413ed7bfe/addons/fluxcd/definitions/kustomize.cue#L122)共用的，那现在怎么分开指定监听间隔？

GitRepository与ImageUpdateAutomation的间隔应该是同一个吧？

假如我希望是GitRepository间隔20s, ImageRepository间隔1m，这个issue的解法能满足吗？

**Comment by miyoosan** [comment]
@chengleqi 谢谢~  那就好，我怕共用Interval的时候，interval设小了ImageRepository会消息多到积压得爆炸，毕竟有多少个应用就有多少个ImageRepository，这个好像还不能跟GitRepository一样复用。 这种优化类的issue不是很着急，你按你的节奏来

**Comment by VobileLiuZhiwu** [comment]
@chengleqi 催个更，大佬最近有空搞这个了么？

**Comment by miyoosan** [comment]
@chengleqi 催个更，大佬最近有空搞这个么？

**Comment by chengleqi** [comment]
> @chengleqi 催个更，大佬最近有空搞这个么？

我今晚就搞搞👌

**Comment by miyoosan** [comment]
> > @chengleqi 催个更，大佬最近有空搞这个么？
> 
> 我今晚就搞搞👌

哇，秒回！感谢大佬，期待~！！

**Comment by VobileLiuZhiwu** [comment]
> 这个sourceName是指A创建出来的GitRepository的名称，并且B直接可以是这样的：
> 
> ```yaml
> apiVersion: core.oam.dev/v1beta1
> kind: Application
> metadata:
>   name: fluxcd-app-b
>   namespace: default
> spec:
>   components:
>   - name: fluxcd-app-b
>     type: kustomize
>     properties:
>       sourceName: fluxcd-app-a
>       repoType: git
>       pullInterval: 1m
>       path: ./test/apps/default/app-b
> ```
> 
> `url`、`git.branch`、`secretRef`其实是可以省略的，因为这些信息已经包含在fluxcd-app-a的GitRepository里了。
> 
> 我想如果要删除A应用，应该会成功删除掉GitRepository和Kustomization，但是B和C应用会找不到GitRepository，会在下次的Reconcile中报错。

@chengleqi  大佬，我vela-core升级到1.6.4了，fluxcd升级到了2.1.8，用这种方式的话，推送新镜像 后，现在一直没有更新fluxcd-app-b(在我的例子里，是fluxcd-keyword-push-test)对应的应用，不知道是怎么回事，除了一个调谐错误，没有任何其他错误信息与报错状态。
```yaml
$ kubectl describe app fluxcd-keyword-push-test  -n mediawise
Name:         fluxcd-keyword-push-test
Namespace:    mediawise
Labels:       <none>
Annotations:  oam.dev/kubevela-version: v1.5.5
API Version:  core.oam.dev/v1beta1
Kind:         Application
Metadata:
  Creation Timestamp:  2022-10-18T08:39:14Z
  Finalizers:
    app.oam.dev/resource-tracker-finalizer
  Generation:  6
  Managed Fields:
    API Version:  core.oam.dev/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:components:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2022-10-18T08:39:14Z
    API Version:  core.oam.dev/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:oam.dev/kubevela-version:
        f:finalizers:
          .:
          v:"app.oam.dev/resource-tracker-finalizer":
    Manager:      kubevela
    Operation:    Update
    Time:         2022-10-18T08:39:14Z
    API Version:  core.oam.dev/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:appliedResources:
        f:conditions:
        f:latestRevision:
          .:
          f:name:
          f:revision:
          f:revisionHash:
        f:observedGeneration:
        f:services:
        f:status:
        f:workflow:
          .:
          f:appRevision:
          f:contextBackend:
            .:
            f:apiVersion:
            f:kind:
            f:name:
            f:namespace:
            f:uid:
          f:endTime:
          f:finished:
          f:message:
          f:mode:
          f:startTime:
          f:status:
          f:steps:
          f:suspend:
          f:terminated:
    Manager:         kubevela
    Operation:       Update
    Subresource:     status
    Time:            2022-12-13T03:20:45Z
  Resource Version:  1091781303
  UID:               aa0f1f9e-984b-4d67-8ab8-2410af4131da
Spec:
  Components:
    Name:  fluxcd-keyword-push-test
    Properties:
      Git:
        Branch:  master
      Image Repository:
        Commit Message:  Image: {{range .Updated.Images}}{{println .}}{{end}}
        Filter Tags:
          Extract:  $ts
          Pattern:  ^dev-[a-f0-9]+-(?P<ts>[0-9]+)
        Image:      xxxx.aliyuncs.com/keyword-push
        Interval:   1m
        Policy:
          Numerical:
            Order:    asc
        Secret Ref:   image-secret
      Path:           ./test/apps/mediawise/keyword-push
      Pull Interval:  10s
      Repo Type:      git
      Secret Ref:     git-secret
      Source Name:    fluxcd-mediawise-test
    Type:             kustomize
Status:
  Applied Resources:
    API Version:  kustomize.toolkit.fluxcd.io/v1beta2
    Creator:      workflow
    Kind:         Kustomization
    Name:         fluxcd-keyword-push-test
    Namespace:    mediawise
    API Version:  image.toolkit.fluxcd.io/v1beta1
    Creator:      workflow
    Kind:         ImageRepository
    Name:         fluxcd-keyword-push-test
    Namespace:    mediawise
    API Version:  image.toolkit.fluxcd.io/v1beta1
    Creator:      workflow
    Kind:         ImagePolicy
    Name:         fluxcd-keyword-push-test
    Namespace:    mediawise
    API Version:  image.toolkit.fluxcd.io/v1beta1
    Creator:      workflow
    Kind:         ImageUpdateAutomation
    Name:         fluxcd-keyword-push-test
    Namespace:    mediawise
  Conditions:
    Last Transition Time:  2022-10-18T08:39:14Z
    Reason:                Available
    Status:                True
    Type:                  Parsed
    Last Transition Time:  2022-10-18T08:39:14Z
    Reason:                Available
    Status:                True
    Type:                  Revision
    Last Transition Time:  2022-10-18T08:39:14Z
    Reason:                Available
    Status:                True
    Type:                  Policy
    Last Transition Time:  2022-10-18T08:39:14Z
    Reason:                Available
    Status:                True
    Type:                  Render
    Last Transition Time:  2022-12-13T05:04:55Z
    Reason:                Available
    Status:                True
    Type:                  Workflow
    Last Transition Time:  2022-12-13T05:05:03Z
    Reason:                ReconcileSuccess
    Status:                True
    Type:                  Ready
    Last Transition Time:  2022-12-13T05:05:03Z
    Message:               failed to sweep resourcetrackers to be deleted: Operation cannot be fulfilled on resourcetrackers.core.oam.dev "fluxcd-keyword-push-test-v5-mediawise": StorageError: invalid object, Code: 4, Key: /c3dc8334499df41229c696dc90429151c/core.oam.dev/resourcetrackers/fluxcd-keyword-push-test-v5-mediawise, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: e3ee729b-94e9-423a-afa0-f1fd4742f2ae, UID in object meta: 
    Reason:                ReconcileError
    Status:                False
    Type:                  Synced
  Latest Revision:
    Name:               fluxcd-keyword-push-test-v4
    Revision:           4
    Revision Hash:      fc3060d39c5816d9
  Observed Generation:  6
  Services:
    Healthy:    true
    Name:       fluxcd-keyword-push-test
    Namespace:  mediawise
    Workload Definition:
      API Version:  
      Kind:         
  Status:           running
  Workflow:
    App Revision:  fluxcd-keyword-push-test-v4
    Context Backend:
      API Version:  v1
      Kind:         ConfigMap
      Name:         workflow-fluxcd-keyword-push-test-context
      Namespace:    mediawise
      UID:          50d74e8d-9da3-4ced-9daf-f93ca4d304dd
    End Time:       2022-12-13T05:04:55Z
    Finished:       true
    Message:        Succeeded
    Mode:           DAG-DAG
    Start Time:     2022-12-13T05:04:55Z
    Status:         succeeded
    Steps:
      First Execute Time:  2022-12-13T05:04:55Z
      Id:                  81w7czceh3
      Last Execute Time:   2022-12-13T05:04:55Z
      Name:                fluxcd-keyword-push-test
      Phase:               succeeded
      Type:                apply-component
    Suspend:               false
    Terminated:            false
Events:
  Type    Reason  Age                   From         Message
  ----    ------  ----                  ----         -------
  Normal  Parsed  98s (x73 over 3h54m)  Application  Parsed successfully
```
另外一点，git.branch不能被省略的，否则apply时会报错。repoType，secretRef，url，pullInterval这四个是可以省略的。pullInterval默认是5m。

**Comment by miyoosan** [comment]
> 这个sourceName是指A创建出来的GitRepository的名称，并且B直接可以是这样的：
> 
> ```yaml
> apiVersion: core.oam.dev/v1beta1
> kind: Application
> metadata:
>   name: fluxcd-app-b
>   namespace: default
> spec:
>   components:
>   - name: fluxcd-app-b
>     type: kustomize
>     properties:
>       sourceName: fluxcd-app-a
>       repoType: git
>       pullInterval: 1m
>       path: ./test/apps/default/app-b
> ```
> 
> `url`、`git.branch`、`secretRef`其实是可以省略的，因为这些信息已经包含在fluxcd-app-a的GitRepository里了。
> 
> 我想如果要删除A应用，应该会成功删除掉GitRepository和Kustomization，但是B和C应用会找不到GitRepository，会在下次的Reconcile中报错。

@chengleqi  大佬，我vela-core升级到1.6.4了，fluxcd升级到了2.1.8，用这种方式的话，推送新镜像 后，现在一直没有更新fluxcd-app-b(在我的例子里，是fluxcd-keyword-push-test)对应的应用，不知道是怎么回事，除了一个调谐错误，没有任何其他错误信息与报错状态。
```yaml
$ kubectl describe app fluxcd-keyword-push-test  -n mediawise
Name:         fluxcd-keyword-push-test
Namespace:    mediawise
Labels:       <none>
Annotations:  oam.dev/kubevela-version: v1.5.5
API Version:  core.oam.dev/v1beta1
Kind:         Application
Metadata:
  Creation Timestamp:  2022-10-18T08:39:14Z
  Finalizers:
    app.oam.dev/resource-tracker-finalizer
  Generation:  6
  Managed Fields:
    API Version:  core.oam.dev/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:components:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2022-10-18T08:39:14Z
    API Version:  core.oam.dev/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:oam.dev/kubevela-version:
        f:finalizers:
          .:
          v:"app.oam.dev/resource-tracker-finalizer":
    Manager:      kubevela
    Operation:    Update
    Time:         2022-10-18T08:39:14Z
    API Version:  core.oam.dev/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:appliedResources:
        f:conditions:
        f:latestRevision:
          .:
          f:name:
          f:revision:
          f:revisionHash:
        f:observedGeneration:
        f:services:
        f:status:
        f:workflow:
          .:
          f:appRevision:
          f:contextBackend:
            .:
            f:apiVersion:
            f:kind:
            f:name:
            f:namespace:
            f:uid:
          f:endTime:
          f:finished:
          f:message:
          f:mode:
          f:startTime:
          f:status:
          f:steps:
          f:suspend:
          f:terminated:
    Manager:         kubevela
    Operation:       Update
    Subresource:     status
    Time:            2022-12-13T03:20:45Z
  Resource Version:  1091781303
  UID:               aa0f1f9e-984b-4d67-8ab8-2410af4131da
Spec:
  Components:
    Name:  fluxcd-keyword-push-test
    Properties:
      Git:
        Branch:  master
      Image Repository:
        Commit Message:  Image: {{range .Updated.Images}}{{println .}}{{end}}
        Filter Tags:
          Extract:  $ts
          Pattern:  ^dev-[a-f0-9]+-(?P<ts>[0-9]+)
        Image:      xxxx.aliyuncs.com/keyword-push
        Interval:   1m
        Policy:
          Numerical:
            Order:    asc
        Secret Ref:   image-secret
      Path:           ./test/apps/mediawise/keyword-push
      Pull Interval:  10s
      Repo Type:      git
      Secret Ref:     git-secret
      Source Name:    fluxcd-mediawise-test
    Type:             kustomize
Status:
  Applied Resources:
    API Version:  kustomize.toolkit.fluxcd.io/v1beta2
    Creator:      workflow
    Kind:         Kustomization
    Name:         fluxcd-keyword-push-test
    Namespace:    mediawise
    API Version:  image.toolkit.fluxcd.io/v1beta1
    Creator:      workflow
    Kind:         ImageRepository
    Name:         fluxcd-keyword-push-test
    Namespace:    mediawise
    API Version:  image.toolkit.fluxcd.io/v1beta1
    Creator:      workflow
    Kind:         ImagePolicy
    Name:         fluxcd-keyword-push-test
    Namespace:    mediawise
    API Version:  image.toolkit.fluxcd.io/v1beta1
    Creator:      workflow
    Kind:         ImageUpdateAutomation
    Name:         fluxcd-keyword-push-test
    Namespace:    mediawise
  Conditions:
    Last Transition Time:  2022-10-18T08:39:14Z
    Reason:                Available
    Status:                True
    Type:                  Parsed
    Last Transition Time:  2022-10-18T08:39:14Z
    Reason:                Available
    Status:                True
    Type:                  Revision
    Last Transition Time:  2022-10-18T08:39:14Z
    Reason:                Available
    Status:                True
    Type:                  Policy
    Last Transition Time:  2022-10-18T08:39:14Z
    Reason:                Available
    Status:                True
    Type:                  Render
    Last Transition Time:  2022-12-13T05:04:55Z
    Reason:                Available
    Status:                True
    Type:                  Workflow
    Last Transition Time:  2022-12-13T05:05:03Z
    Reason:                ReconcileSuccess
    Status:                True
    Type:                  Ready
    Last Transition Time:  2022-12-13T05:05:03Z
    Message:               failed to sweep resourcetrackers to be deleted: Operation cannot be fulfilled on resourcetrackers.core.oam.dev "fluxcd-keyword-push-test-v5-mediawise": StorageError: invalid object, Code: 4, Key: /c3dc8334499df41229c696dc90429151c/core.oam.dev/resourcetrackers/fluxcd-keyword-push-test-v5-mediawise, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: e3ee729b-94e9-423a-afa0-f1fd4742f2ae, UID in object meta: 
    Reason:                ReconcileError
    Status:                False
    Type:                  Synced
  Latest Revision:
    Name:               fluxcd-keyword-push-test-v4
    Revision:           4
    Revision Hash:      fc3060d39c5816d9
  Observed Generation:  6
  Services:
    Healthy:    true
    Name:       fluxcd-keyword-push-test
    Namespace:  mediawise
    Workload Definition:
      API Version:  
      Kind:         
  Status:           running
  Workflow:
    App Revision:  fluxcd-keyword-push-test-v4
    Context Backend:
      API Version:  v1
      Kind:         ConfigMap
      Name:         workflow-fluxcd-keyword-push-test-context
      Namespace:    mediawise
      UID:          50d74e8d-9da3-4ced-9daf-f93ca4d304dd
    End Time:       2022-12-13T05:04:55Z
    Finished:       true
    Message:        Succeeded
    Mode:           DAG-DAG
    Start Time:     2022-12-13T05:04:55Z
    Status:         succeeded
    Steps:
      First Execute Time:  2022-12-13T05:04:55Z
      Id:                  81w7czceh3
      Last Execute Time:   2022-12-13T05:04:55Z
      Name:                fluxcd-keyword-push-test
      Phase:               succeeded
      Type:                apply-component
    Suspend:               false
    Terminated:            false
Events:
  Type    Reason  Age                   From         Message
  ----    ------  ----                  ----         -------
  Normal  Parsed  98s (x73 over 3h54m)  Application  Parsed successfully
```
另外一点，git.branch不能被省略的，否则apply时会报错。repoType，secretRef，url，pullInterval这四个是可以省略的。pullInterval默认是5m。
