### ISSUE TITLE
Lark notification workflow is not working

### ISSUE THREAD

**Issue by cloorc** [kubevela/kubevela#4844]
Lark notification workflow is not working

**To Reproduce**
1. Add notification workflow to application with values:

```yaml
lark:
  url:
    value: >-
      https://open.feishu.cn/open-apis/bot/v2/hook/<token>
  message:
    content: >-
      {"text":"Success with detail at https://private.domain.com/applications/message/config"}
    msg_type: text
```

Lark got nothing after previous step done.

**Expected behavior**
Lark will got a message after the deployment step.

**Screenshots**

![image](https://user-images.githubusercontent.com/13597105/194876960-17f84936-0a1f-437f-b4c2-c21749c5fa77.png)

**KubeVela Version**

v1.5.0-d007fc3
API Server Version: v1.5.0
API Server GitCommit: git-e29b1af

**Cluster information**

[root@master3 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

**Additional context**

Is there any way to check the workflow logs?
