### ISSUE TITLE
[Bug] For a `Cron-Task` component, cannot get its Pod.

### ISSUE THREAD

**Issue by Hanmengnan** [kubevela/kubevela#4914]
**Describe the bug**

we can't get Pods generated by a `Cron-Task` component, if `labels` parameter isn't added.

**To Reproduce**

I use the YAML to run an application:

```YAML
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: cron-curl
spec:
  components:
    - name: mytask
      type: cron-task
      properties:
        image: perl
        count: 10
        cmd: ["curl",  "http://8.210.141.47:30922/"]
        schedule: "*/1 * * * *"
```
But I can't get the pod generated by it.

<img width="978" alt="image" src="https://user-images.githubusercontent.com/30918851/197667529-495c2ab3-b159-4aaa-a674-89c9c0c2d91c.png">

**Expected behavior**

**Screenshots**

**KubeVela Version**

**Cluster information**

**Additional context**
