### ISSUE TITLE
[Bug] Health check bypass owner check

### ISSUE THREAD

**Issue by Somefive** [kubevela/kubevela#4948]
**Describe the bug**

When using `deploy` workflow step to dispatch resources, it will
1. do health check for all components to deploy
2. for unhealthy component, execute applyComponent
3. do health check again

For second step, if the resource to create already exists, it will fail due to the incorrect management. This can prevent application from intruding resources created by other system/people.

In the case target resource exists and not managed by the current application (or sharable), the second step will always fail. 

However, the healthCheck in the first step will try to find out if the target resource exists and match the requirements defined in the `healthPolicy`. To this point, the logic is divided into two parts:
1. For resources that are defined with name in templates, like `k8s-objects`, the search for the target resource will be directly located. Then the resource will be found and health check passed. **THIS IS INCORRECT.** Because the target resource now is not manageable by the application.
2. For resources that are not defined with name in templates, like `webservice`, the search for the target resource will use `List` with `labelSelector` and pick out the resource dispatched by the current application. **THIS IS CORRECT BUT NOT EFFICIENT.** The labelSelector ensures that only resources managed by the application can be found, but we actually know these no-named resources use the name of the component by default, so `List` is not actually needed.

For *p1*, the health check is bypassed and second step (dispatch resource) is skipped, and the `deploy` step will succeeded, this is not a rigorous behaviour, but has no side-effect by far as we know. (The StateKeep/GC process will find that this resource is not owned by the current application so it will not touch it. Errors will be thrown in the StateKeep.)

For *p2*, the `deploy` step will treat the component as unhealthy (since it cannot find the resource that not uses the correct owner label), and repeatedly execute step 2 until max retry time reached.

**To Reproduce**

Let's say we have namespace `o11y-system` and deployment `nginx` in the default namespace already.

The first application will succeeded, which is incorrect.
```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: ns
spec:
  components:
    - type: k8s-objects
      name: ns
      properties:
        objects:
          - apiVersion: v1
            kind: Namespace
            metadata:
              name: o11y-system
  workflow:
    steps:
      - type: deploy
        name: deploy
        properties:
          policies: []
```

The second application will fail, and is correct.
```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: nginx
spec:
  components:
    - type: webservice
      name: nginx
      properties:
        image: nginx
  workflow:
    steps:
      - type: deploy
        name: deploy
        properties:
          policies: []
```

NOTICE THAT this incorrect behaviour actually allows users to let application work together with some existing resources that are not managed by them. This "feature" is made possible due to this bug, we should seek for better implementation.

**Expected behavior**

**Screenshots**

**KubeVela Version**

**Cluster information**

**Additional context**
