### ISSUE TITLE
Multi-Protocol in same port under component's define may duplicate.

### ISSUE THREAD

**Issue by fly3366** [kubevela/kubevela#4986]
**Describe the bug**
If set same port with diff protocol will make yaml parse error.

**To Reproduce**
![image](https://user-images.githubusercontent.com/38378045/199500038-3c3d5ad1-5058-4d58-9446-47c597d174b4.png)

**Expected behavior**
1. set component's port with same port but different protocol.
2. do deploy, fluxcd(gitpos context) will throw error.

**KubeVela Version**
1.5.8

**Cluster information**
1.24 k3s

**Comment by Somefive** [comment]
You are using `webservice` component, is it right? I think it is caused by the duplicated name rendering. Could you try to add explicit name to these two port? Like 
```yaml
ports:
  - port: 9000
    protocol: tcp
    expose: true
    name: tcp-9000
  - port: 9000
    protocol: udp
    expose: true
    name: udp-9000
```
