### ISSUE TITLE
can not connect aliyun oss,head invalid

### ISSUE THREAD

**Issue by 13567436138** [kubevela/kubevela#5024]
**Describe the bug**

can not connect aliyun oss
**To Reproduce**

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: helm
spec:
  components:
    - name: nginx
      type: helm
      properties:
        url: oss-cn-hangzhou.aliyuncs.com
        chart: nginx
        repoType: oss
        oss:
          bucketName: fluxcd
          region: 华东1
        secretRef: aliyun-bucket
```

```
[root@node01 helm]# kubectl get buckets.source.toolkit.fluxcd.io -n prod nginx 
NAME    ENDPOINT                       AGE   READY   STATUS
nginx   oss-cn-hangzhou.aliyuncs.com   15s   False   failed to confirm existence of 'fluxcd' bucket: Head "https://oss-cn-hangzhou.aliyuncs.com/fluxcd/": net/http: invalid header field value "AWS4-HMAC-SHA256 Credential=LTAIgaugfV2CGDca\n/20221108/华东1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=e19269ea841d18629ec1055549e15f1c3941f8768b5f5a903368ebf94f105007" for key Authorization
```
**Expected behavior**

no error
**Screenshots**

**KubeVela Version**

**Cluster information**

1.21.0
**Additional context**

**Comment by chivalryq** [comment]
Seems like you didn't configure the authentication secret right.

**Comment by wangyikewxgm** [comment]
It's look like the fluxcd controller cannot fetch your bucket with the ak/sk. Not the bug of kubevela

**Comment by 13567436138** [comment]
> Seems like you didn't configure the authentication secret right.

how to config：
```
apiVersion: v1
kind: Secret
metadata:
  name: aliyun-bucket
type: Opaque
data:
  accesskey: xxx
  secretkey: xxxx
```

**Comment by chivalryq** [comment]
> > Seems like you didn't configure the authentication secret right.
> 
> 
> 
> how to config：
> 
> ```
> 
> apiVersion: v1
> 
> kind: Secret
> 
> metadata:
> 
>   name: aliyun-bucket
> 
> type: Opaque
> 
> data:
> 
>   accesskey: xxx
> 
>   secretkey: xxxx
> 
> ```

have you checked the related documents about the format？

**Comment by 13567436138** [comment]
yes ,format is wright,according the doc.
```
apiVersion: v1
kind: Secret
metadata:
  name: minio-bucket-secret
  namespace: default
type: Opaque
stringData:
  accesskey: <access key>
  secretkey: <secret key>
```

**Comment by chivalryq** [comment]
Have you encode ak and sk using base64?

**Comment by 13567436138** [comment]
问题貌似有进展，base64有特殊要求，echo 必须加 -n,现在报
```
Events:
  Type     Reason                 Age                  From               Message
  ----     ------                 ----                 ----               -------
  Warning  BucketOperationFailed  26s (x9 over 6m49s)  source-controller  bucket 'fluxcd' not found
```

**Comment by 13567436138** [comment]
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: kustomize
spec:
  components:
    - name: podinfo
      type: kustomize
      properties:
        url: fluxcd.oss-cn-hangzhou.aliyuncs.com
        path: ./apps/staging
        repoType: oss
        pullInterval: 1m
        timeout: 5m
        oss:
          provider: generic
          bucketName: fluxcd
          region: oss-cn-hangzhou
        secretRef: aliyun-bucket
```

域名也改了，加了子域名
