### ISSUE TITLE
[Bug] Failed to get detail policy for application

### ISSUE THREAD

**Issue by nuclearwu** [kubevela/kubevela#5040]
**Describe the bug**

Failed to get detail policy for application, and reports "unexpected end of JSON input" error

**To Reproduce**

1、`vela up -f first-vela-app.yaml`
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: first-vela-app
  labels: 
    app.kubernetes.io/name: nginx
    app.kubernetes.io/version: v1
spec:
  components:
    - name: express-server
      type: webservice
      properties:
        image: oamdev/hello-world
        exposeType: NodePort
        ports:
         - port: 8000
           expose: true
      traits:
        - type: scaler
          properties:
            replicas: 1
  policies:
    - name: target-default
      type: topology
      properties:
        # local 集群即 Kubevela 所在的集群
        clusters: ["local"]
        namespace: "default"
    - name: target-prod
      type: topology
      properties:
        clusters: ["local"]
        # 此命名空间需要在应用部署前完成创建
        namespace: "prod"
    - name: deploy-ha
      type: override
      properties:
        components:
          - type: webservice
            traits:
              - type: scaler
                properties:
                  replicas: 2
  workflow:
    steps:
      - name: deploy2default
        type: deploy
        properties:
          policies: ["target-default"]
      - name: manual-approval
        type: suspend
      - name: deploy2prod
        type: deploy
        properties:
          policies: ["target-prod", "deploy-ha"]
```
2、get detail policy
![image](https://user-images.githubusercontent.com/37976659/200986905-da350f0a-2b1a-4e08-8330-19fc477e5cd2.png)

**Expected behavior**

**Screenshots**

**KubeVela Version**
1.6.0

**Cluster information**

1.21.5

**Additional context**
