### ISSUE TITLE
自定义policy中的outputs没有被渲染出来

### ISSUE THREAD

**Issue by LomotHo** [kubevela/kubevela#5047]
**Describe the bug**

自定义policy中的outputs没有被渲染出来

**To Reproduce**

自定义的 policy:

```
"traffic-route-test": {
	alias: ""
	annotations: {}
	attributes: {}
	description: "traffic route, include DestinationRule and VirtualService"
	labels: {}
	type: "policy"
}

template: {
	parameter: {
		version: [...string]
		rules: [...{
			name:         string
			matchHeader?: string
			route: [...{
				host?:   string
				weight:  int
				version: string
			}]
			timeout?: string
		}]
	}

	output: {
		apiVersion: "networking.istio.io/v1alpha3"
		kind:       "DestinationRule"
		metadata: name: context.name
		spec: {
			host: context.appName
			subsets: [
				for _, v in parameter.version {
					name: v
					labels: version: v
				},
			]
			trafficPolicy: tls: mode: "DISABLE"
		}
	}

	outputs: virtualservice: {
		apiVersion: "networking.istio.io/v1alpha3"
		kind:       "VirtualService"
		spec: {
			hosts: [context.appName]
			http: [
				for rule in parameter.rules {
					name: rule.name
					if rule.matchHeader != _|_ {
						match: [{
							headers: baggage: exact: rule.matchHeader
						}]
					}
					route: [
						for _, r in rule.route {
							destination: {
								host:   context.appName
								subset: r.version
							}
							weight: r.weight
						},
					]
					if rule.timeout != _|_ {
						timeout: rule.timeout
					}
				},
			]
		}
	}
}
```

yaml:

```yaml
  policies:
    - name: kitex-server-route
      type: traffic-route-test
      properties:
        version: ["v1", "v2"]
        rules:
          - name: test
            matchHeader: "env=test"
            route: 
              - version: v1
                weight: 100
            timeout:  0.5s
          - name: prod
            matchHeader: "env=prod"
            route: 
              - version: v2
                weight: 100
            timeout:  0.5s
```

vela dry-run 之后只渲染出了output中的 `DestinationRule`, 没有渲染出outputs中的 VirtualService, 但是如果把这个policy改成component就可以正常渲染出outputs

文档中提到policy支持outputs, 所以认为是bug
>规则要和 component 定义保持一致，必须制定 output，outputs 可用于多个对象，格式如下:
>```
>output: {
>    <full template data>
>}
>outputs: <unique-name>: 
>  <full template data>
>```

**KubeVela Version**
1.6.0

**Cluster information**
1.20.6
