### ISSUE TITLE
cpuscaler traits documentation example is incorrect

### ISSUE THREAD

**Issue by dginzbourg** [kubevela/kubevela#5060]
The example of cpuscaler shows cpuPercent attribute [cpuscaler](https://kubevela.io/docs/end-user/traits/references#cpuscaler) while the spec defines cpuUtil. 

**To Reproduce**

This's the definition in example:
```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: website
spec:
  components:
    - name: frontend
      type: webservice
      properties:
        image: nginx
      traits:
        - type: cpuscaler
          properties:
            min: 1
            max: 10
            cpuPercent: 60
```
**Expected behavior**

```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: website
spec:
  components:
    - name: frontend
      type: webservice
      properties:
        image: nginx
      traits:
        - type: cpuscaler
          properties:
            min: 1
            max: 10
            cpuUtil: 60
```

**Screenshots**

**KubeVela Version**
Documentation version 1.5

**Cluster information**

**Additional context**
