### ISSUE TITLE
[Bug] deploy-cloud-resource workflow step not work

### ISSUE THREAD

**Issue by chivalryq** [kubevela/kubevela#5084]
**Describe the bug**

In VelaUX, we generate application with cloud-resource like:
```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: regular-check-oss
spec:
  components:
    - name: sample-oss
      type: alibaba-oss
      properties:
        bucket: deploy-cloud-resource-check
        acl: private
  policies:
    - name: env-bindings-default
      type: env-binding
      properties:
        envs:
          - name: default
            patch:
              components:
                - name: test2222
                  properties:
                    providerRef:
                      name: default
                    writeConnectionSecretToRef:
                      name: test2222-default
                      namespace: default
            placement:
              clusterSelector:
                name: local
              namespaceSelector:
                name: default
  workflow:
    steps:
      - name: default-cloud-resource
        properties:
          env: default
          policy: env-bindings-default
        type: deploy-cloud-resource
```

In `deploy-cloud-resource` step, it will fail:

```text

│   steps:
│     - firstExecuteTime: "2022-11-17T16:01:36Z"
│       id: osz1ftdtuw
│       lastExecuteTime: "2022-11-17T16:02:20Z"
│       message: 'run step(provider=kube,do=apply): Found 1 errors. [(cannot apply ApplyOption:
│         Secret default/test2222-default-default exists but not managed by any application
│         now)]'
│       name: default-cloud-resource
│       phase: failed
│       reason: FailedAfterRetries
│       type: deploy-cloud-resource


**Screenshots**
<!--
If applicable, add screenshots to help explain your problem.
-->

**KubeVela Version**
```shell
$ vela version
CLI Version: v1.6.0
Core Version: 1.6.1
GitRevision: git-4b4e4f8
GolangVersion: go1.19.2
```

**Cluster information**

VelaD / v1.21.10+k3s1
**Additional context**
