### ISSUE TITLE
多集群资源分发“集群”级别的资源提示资源不存在

### ISSUE THREAD

**Issue by wxuedong** [kubevela/kubevela#5105]
k8s version   1.20.8
vela version  v1.6.0

应用yaml实现：

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: priorityclass
  namespace: vela-system
spec:
  components:
    - name: sync-priorityclass
      type: ref-objects
      properties:
        objects:
          - resource: priorityclass
            name: high-priority-apps
  policies:
    - name: topology-non-prod-clusters
      type: topology
      properties:
        clusterLabelSelector:
          env: non-prod
```

错误提示：

```
Message:             run step(provider=multicluster,do=deploy): failed to select objects from referred objects in revision storage: failed to load ref object PriorityClass vela-system/high-priority-apps: PriorityClass.scheduling.k8s.io "high-priority-apps" not found

```

实际上vela所在的集群是存在 资源是 PriorityClass.scheduling.k8s.io  名字是 high-priority-apps

```
$ k get PriorityClass.scheduling.k8s.io high-priority-apps
NAME                 VALUE     GLOBAL-DEFAULT   AGE
high-priority-apps   2000000   false            24m

```

没有单独设置--ref-objects-available-scope 参数。
