### ISSUE TITLE
Multiple initialization containers are not supported in traits

### ISSUE THREAD

**Issue by huaxk** [kubevela/kubevela#5110]
When I configure multiple initialization containers in traits, I get an error:

```
error: cannot update object: admission webhook "validating.core.oam.dev.v1beta1.applications" denied the request: field "schematic": Invalid value error encountered, cannot evaluate trait "init-container": invalid patch trait init-container into workload: result check err: spec.template.spec.initContainers.0.name: conflicting values "init-busybox-2" and "init-busybox".
```

it is not supported multiple initialization containers in traits.

The YAML files of Component/Trait I used.

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: busybox
spec:
  components:
    - name: busybox
      type: webservice
      properties:
        image: busybox
        cmd: ["sleep", "86400"]
      traits:
        - type: init-container
          properties:
            name: init-busybox
            image: busybox
            cmd: ["sh", "-c"]
            args:
              - |
                echo hello > /data/hello.text
            mountName: "init-data"
            initMountPath: /data
            appMountPath: /data-initialized
        - type: init-container
          properties:
            name: init-busybox-2
            image: busybox
            cmd: ["sh", "-c"]
            args:
              - |
                echo hello > /data/hello2.text
            mountName: "init-data-2"
            initMountPath: /data
            appMountPath: /data-initialized-2
```

**KubeVela Version**
```
CLI Version: v1.6.0
Core Version: 1.6.0
GitRevision: git-4b4e4f8
GolangVersion: go1.19.2
```

**Comment by wonderflow** [comment]
yes, it's not supported, why don't put them in the same trait? Or, you can customize the trait by editing the cue definition.

**Comment by wonderflow** [comment]
There's a easy work around for this feature, just modify this trait:

https://github.com/kubevela/kubevela/blob/master/vela-templates/definitions/internal/trait/init-container.cue

For example, rename it as `init-container-new`:

```
"init-container-new": {
	type: "trait"
	annotations: {}
	description: "add an init container and use shared volume with pod"
	attributes: {
		podDisruptive: true
		appliesToWorkloads: ["deployments.apps", "statefulsets.apps", "daemonsets.apps", "jobs.batch"]
	}
}
template: {
   ...
}
```

Then apply this trait:

```
vela def apply init-container-new.cue
```

Then you'll be able to use in application like:

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: busybox
spec:
  components:
    - name: busybox
      type: webservice
      properties:
        image: busybox
        cmd: ["sleep", "86400"]
      traits:
        - type: init-container
          properties:
            name: init-busybox
            image: busybox
            cmd: ["sh", "-c"]
            args:
              - |
                echo hello > /data/hello.text
            mountName: "init-data"
            initMountPath: /data
            appMountPath: /data-initialized
        - type: init-container-new
          properties:
            name: init-busybox-2
            image: busybox
            cmd: ["sh", "-c"]
            args:
              - |
                echo hello > /data/hello2.text
            mountName: "init-data-2"
            initMountPath: /data
            appMountPath: /data-initialized-2
```
