### ISSUE TITLE
多集群交付应用然后删除application PHASE一直处于deleting

### ISSUE THREAD

**Issue by wxuedong** [kubevela/kubevela#5191]
vela veriosn  1.6.2

手动删除应用后application一直存在 且PHASE 是deleting
 ```
$ k get application.core.oam.dev  | grep deleting
multi-cluster-addon-fluxcd                    flux-system-namespace   raw           deleting         true               3h39m
 ```

应用定义：

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: multi-cluster-addon-fluxcd
  namespace: control-system
spec:
  components: 
    - name: flux-system-namespace 
      type: raw
      properties:
        ----
        ----
  policies:
  - name: topology-vela-clusters
    type: topology
    properties:
    - name: topology-clusters
      type: topology
      properties:
        clusterLabelSelector:
           xxx:xxx

```
