### ISSUE TITLE
vela-cli workflow step definition logs are not available

### ISSUE THREAD

**Issue by jamesdobson** [kubevela/kubevela#5247]
**Describe the bug**
When using the `vela-cli` workflow step, the logs are not available.
The root cause is a missing label on the pod, will submit a PR shortly.

**To Reproduce**
1. Use VelaUX UI to create a new pipeline with steps like:
```yaml
- name: prepare
  type: print-message-in-status
  outputs:
    - name: arguments
      valueFrom: |
        ["vela", "exec", "some-application", "-n", "some-namespace", "--", "/bin/ps"]

- name: run-ps
  type: vela-cli
  inputs:
    - from: arguments
      parameterKey: command
```
2. Run the pipeline and look at the output of the `run-ps` step.
3. No log appears and an error banner *may* appear: "no pod found"
4. You can also run `vela workflow logs some-workflowrun`, select the `run-ps` step, and get the output `Error: no pod found`.

**Expected behavior**
You should see the output of the command and there should be no error.

**KubeVela Version**
v1.6.5 and vela-workflow addon v0.3.6.
The problem also happens with the `vela-cli` in the latest `kubevela` master branch (where `vela-cli` is now defined in the `kubevela` repo)

**Cluster information**
- kind cluster with `kindest/node:v1.22.15`
