### ISSUE TITLE
[Bug] parameter type is conflict with Component webserice and Trait resource

### ISSUE THREAD

**Issue by StevenLeiZhang** [kubevela/kubevela#5569]
**Describe the bug**

1. `cpu` in https://kubevela.net/zh/docs/end-user/components/references#webservice is String
2. but it is Number in https://kubevela.net/zh/docs/end-user/traits/references#requests-resource
3. when you set cpu in Component 0.3 and then set 2 with Trait , vela raises one error

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: website
spec:
  components:
    - name: busy
      type: webservice
      properties:
        image: busybox
        ports:
          - port: 8080
            expose: true
        cpu: "0.1"
      traits:
        - type: resource
          properties:
            cpu: 0.25
            memory: "200Mi"

```

```
Error from server: error when creating "application-with-resource2.yaml": admission webhook "validating.core.oam.dev.v1beta1.applications" denied the request: field "schematic": Invalid value error encountered, cannot evaluate trait "resource": invalid patch trait resource into workload: result check err: spec.template.spec.containers.0.resources.limits.cpu: conflicting values "0.1" and 0.25 (mismatched types string and float). 
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**KubeVela Version**

**Cluster information**

**Additional context**

**Comment by StevenLeiZhang** [comment]
Which type is right? string or number?

**Comment by StevenLeiZhang** [comment]
I also tried such case
1. change cpu type to be string in trait resource 
```
resource: {
	type: "trait"
	annotations: {}
	description: "Add resource requests and limits on K8s pod for your workload which follows the pod spec in path 'spec.template.'"
	attributes: {
		podDisruptive: true
		appliesToWorkloads: ["deployments.apps", "statefulsets.apps", "daemonsets.apps", "jobs.batch"]
	}
}
template: {
	patch: spec: template: spec: containers: [...{
		resources: {
			if parameter.cpu != _|_ && parameter.memory != _|_ && parameter.requests == _|_ && parameter.limits == _|_ {
				// +patchStrategy=retainKeys
				requests: {
					cpu:    parameter.cpu
					memory: parameter.memory
				}
				// +patchStrategy=retainKeys
				limits: {
					cpu:    parameter.cpu
					memory: parameter.memory
				}
			}

			if parameter.requests != _|_ {
				// +patchStrategy=retainKeys
				requests: {
					cpu:    parameter.requests.cpu
					memory: parameter.requests.memory
				}
			}
			if parameter.limits != _|_ {
				// +patchStrategy=retainKeys
				limits: {
					cpu:    parameter.limits.cpu
					memory: parameter.limits.memory
				}
			}
		}
	}]

	parameter: {
		// +usage=Specify the amount of cpu for requests and limits
		cpu?: *1 | number
		// +usage=Specify the amount of memory for requests and limits
		memory?: *"2048Mi" | =~"^([1-9][0-9]{0,63})(E|P|T|G|M|K|Ei|Pi|Ti|Gi|Mi|Ki)$"
		// +usage=Specify the resources in requests
		requests?: {
			// +usage=Specify the amount of cpu for requests
			//     cpu: *1 | number | string
			cpu: string
			// +usage=Specify the amount of memory for requests
			memory: *"2048Mi" | =~"^([1-9][0-9]{0,63})(E|P|T|G|M|K|Ei|Pi|Ti|Gi|Mi|Ki)$"
		}
		// +usage=Specify the resources in limits
		limits?: {
			// +usage=Specify the amount of cpu for limits
			//     cpu: *1 | number | string
			cpu: string
			// +usage=Specify the amount of memory for limits
			memory: *"2048Mi" | =~"^([1-9][0-9]{0,63})(E|P|T|G|M|K|Ei|Pi|Ti|Gi|Mi|Ki)$"
		}
	}
}

```

2. apply this Application with cpu: "1" in Trait

```

apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: website
spec:
  components:
    - name: busy
      type: webservice
      properties:
        image: busybox
        ports:
          - port: 8080
            expose: true
        cpu: "0.1"
      traits:
        - type: resource
          properties:
            requests:
              cpu: "1"
              memory: "200Mi"

```

but vela still raises error
```
Error from server: error when creating "application-with-resource2.yaml": admission webhook "validating.core.oam.dev.v1beta1.applications" denied the request: field "schematic": Invalid value error encountered, cannot evaluate trait "resource": invalid patch trait resource into workload: result check err: spec.template.spec.containers.0.resources.requests.cpu: conflicting values "1" and "0.1". 

```
