### ISSUE TITLE
[Feature] ImmutableAfterDeploy

### ISSUE THREAD

**Issue by talhazengin** [kubevela/kubevela#5594]
We have a spec field in our CRD definition it corresponds to the real resource's name. It is a unique field. We don't expect to be another duplicate with the same resource name. To ensure that we added a validation webhook. This field is immutable also. There is no way to change this field with CRD edit. Our webhook provides immutability and uniqueness checks. This field is also corresponds to our CRD's metada.name field. That means if this field changes then whole CRD recreated in deployments. 

When it comes to Kubevela UI side we couldn't give immutability to this field. If we add the setting `immutable: true` from UI definitions, then there is no way to create a new one because it is completely not editable. I think we need a setting like `ImmutableAfterDeploy` this way we can enter a new record and it will be immutable after the deployment.

**Comment by Somefive** [comment]
Great suggestion. Actually, in KubeVela we have faced similar problems for native resources before, like PersistentVolumeClaim. Some types of the resources are designed to be immutable and can only be recreated.

BTW, in your case, could the metadata fields like labels or annotations be edited for the CRD object and only fields in the spec cannot be edited?

**Comment by Somefive** [comment]
> In our case, our CRD's some spec fields are mutable and some other spec fields are immutable. One of them which i mention in the first message is also immutable and part of the CRD's metadata.name. Also we can change labels or annotations yes.

Okay, I see. That's quite complex. I think in the future KubeVela could support to recreate some specific type of objects but it could be hard to configure such behaviour in fields level. Is that okay for you to recreate such type of objects no matter what fields changes?

**Comment by talhazengin** [comment]
Hi again, sorry for confusing but, it is hard to explain also. Actually, the problem is recreating. We are using a custom trait's outputs section. And we are producing N units CRDs with this outputs section. When we deploy, Kubevela decides which CRD to create or which CRD to delete by looking at their metada.name. So if the CRD's one of the field is also unique by design and if we use this field in the part of metadata.name, and if we change this field, Kubevela will understand that CRD is removed and will be deleted in deployment. But we don't want to mutate this field because it is very error prone. Normally inside kubernetes we guarantee that this field can not change. Any change action will be blocked by validation webhook. But kubevela does not try to change it, but it recreates it because of the above situations. That is very error prone for us. I hope it was a little more descriptive.

**Comment by talhazengin** [comment]
Hi @Somefive, is there any news about this?

**Comment by Somefive** [comment]
Sorry for the late response. If I'm understanding it correctly, you would like to add advanced fine-grained control for the "update" operation of your CRD resource. For example let's say we have
```yaml
apiVerison: example/v1
kind: Example
metadata:
  name: sample-1
spec:
  mutableField: x
  immutableField: y
```

If we want to update it to
```yaml
apiVerison: example/v1
kind: Example
metadata:
  name: sample-1
spec:
  mutableField: z
  immutableField: y
```

This is ok now. But if we want to update it to

```yaml
apiVerison: example/v1
kind: Example
metadata:
  name: sample-1
spec:
  mutableField: x
  immutableField: z
```

It will fail as the change `.spec.immutableField` is rejected by the CRD's validation webhook.

The solution you are using now is to use 

```yaml
apiVerison: example/v1
kind: Example
metadata:
  name: sample-1-y
spec:
  mutableField: x
  immutableField: y
```

and the change to `.spec.immutableField` will mean KubeVela creates another resource and delete the old one.
```yaml
apiVerison: example/v1
kind: Example
metadata:
  name: sample-1-z
spec:
  mutableField: x
  immutableField: z
```

It works now in KubeVela. But you would prefer to still use the name `sample-1` and **recreate** this object when `.spec.immutableField` changes.

Did I understand it correctly?

**Comment by talhazengin** [comment]
```yaml
apiVerison: example/v1
kind: Example
metadata:
  name: sample-1-y
spec:
  mutableField: x
  immutableField: y
```

Yes we don't want to accept changes for `.spec.immutableField` because this change creates a new CRD as you said. We don't want this. But we also need to create a new CRD in the first time by giving a new value to `.spec.immutableField`. If we mark this `.spec.immutableField` with "immutable: true" from the UI definitions, we can't enter a new value, so we can't create a new CRD. I think we need something else, like `ImmutableAfterDeploy` but i am not sure. Thanks for a good explanation. My explanation was terrible sorry.
