### ISSUE TITLE
this apply-once config will fallback after 5m

### ISSUE THREAD

**Issue by 13567436138** [kubevela/kubevela#5606]
**Describe the bug**

policy/apply-once/policy-apply-once-rules-selector-oamTypes.yaml

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: apply-once
spec:
  components:
    - name: nginx
      type: webservice
      properties:
        image: nginx
      traits:
        - type: scaler
          properties:
            replicas: 1
  policies:
    - name: apply-once
      type: apply-once
      properties:
        enable: true
        rules:
        - strategy:
            path: ["spec.replicas"]
          selector:
            oamTypes:
            - COMPONENT
```

```
kubectl set image -n prod deploy nginx nginx=nginx:1.14
[root@easzlab apply-once]# kubectl get deploy nginx -n prod -o yaml |grep "image: nginx:1.14"
```

##### 
**To Reproduce**

**Expected behavior**

**Screenshots**

**KubeVela Version**
1.6.5

**Cluster information**

**Additional context**
