### ISSUE TITLE
this apply-once config will fallback

### ISSUE THREAD

**Issue by 13567436138** [kubevela/kubevela#5607]
**Describe the bug**

policy/apply-once/policy-apply-once-rules-selector-oamTypes-TRAIT.yaml

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: apply-once
spec:
  components:
    - name: nginx
      type: webservice
      properties:
        image: nginx
      traits:
        - type: scaler
          properties:
            replicas: 1
  policies:
    - name: apply-once
      type: apply-once
      properties:
        enable: true
        rules:
        - strategy:
            path: ["spec.replicas"]
          selector:
            oamTypes:
            - TRAIT
```

```
 kubectl scale deploy nginx -n prod --replicas=3
 
 [root@easzlab apply-once]# kubectl get pod -n prod  -w
NAME                     READY   STATUS    RESTARTS   AGE
nginx-86bf946668-bw56b   1/1     Running   0          5m22s
nginx-86bf946668-gdbw5   1/1     Running   0          5m22s
nginx-86bf946668-p65rn   1/1     Running   0          6m7s
```

[root@easzlab ~]#  kubectl get pod -n prod  -w
NAME                     READY   STATUS    RESTARTS   AGE
nginx-86bf946668-66c2x   1/1     Running   0          28s
nginx-86bf946668-7p98q   1/1     Running   0          28s
nginx-86bf946668-c8n5r   1/1     Running   0          55s
nginx-86bf946668-c8n5r   1/1     Terminating   0          5m12s
nginx-86bf946668-7p98q   1/1     Terminating   0          4m45s
nginx-86bf946668-7p98q   0/1     Terminating   0          4m46s
nginx-86bf946668-7p98q   0/1     Terminating   0          4m46s
nginx-86bf946668-7p98q   0/1     Terminating   0          4m46s
nginx-86bf946668-c8n5r   0/1     Terminating   0          5m13s
nginx-86bf946668-c8n5r   0/1     Terminating   0          5m13s
nginx-86bf946668-c8n5r   0/1     Terminating   0          5m13s
**To Reproduce**

**Expected behavior**

**Screenshots**

**KubeVela Version**1.6.5

**Cluster information**

**Additional context**
