### ISSUE TITLE
this apply-once will fallback

### ISSUE THREAD

**Issue by 13567436138** [kubevela/kubevela#5608]
**Describe the bug**

policy/apply-once/policy-apply-once-rules-selector-traitTypes.yaml

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: apply-once
spec:
  components:
    - name: nginx
      type: webservice
      properties:
        image: nginx
      traits:
        - type: scaler
          properties:
            replicas: 1
  policies:
    - name: apply-once
      type: apply-once
      properties:
        enable: true
        rules:
        - strategy:
            path: ["spec.replicas"]
          selector:
            traitTypes:
            - scaler
```

```
 kubectl scale deploy nginx -n prod --replicas=3
 
 [root@easzlab apply-once]# kubectl get pod -n prod  -w
NAME                     READY   STATUS    RESTARTS   AGE
nginx-86bf946668-bw56b   1/1     Running   0          5m22s
nginx-86bf946668-gdbw5   1/1     Running   0          5m22s
nginx-86bf946668-p65rn   1/1     Running   0          6m7s
```

#### 
**To Reproduce**

**Expected behavior**

**Screenshots**

**KubeVela Version**

**Cluster information**

**Additional context**
