### ISSUE TITLE
I apply a policy , garbage-collect,In my understand the selected resource will not be garbaged,but in fact it is cleand

### ISSUE THREAD

**Issue by 13567436138** [kubevela/kubevela#5609]
**Describe the bug**

policy/garbage-collect/gc-rules-selector-componentNames.yaml

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: garbage
spec:
  components:
    - name: nginx
      type: webservice
      properties:
        image: nginx
        port: 80
      traits:
        - type: expose
          properties:
            port: [80]
  policies:
    - name: garbage-collect
      type: garbage-collect
      properties:
        rules:
          - selector:
              componentNames:
                - nginx
            strategy: onAppDelete
```

```
vela up -f gc-rules-selector-componentNames.yaml

vela delete garbage

[root@easzlab ~]# vela delete garbage
Do you want to delete the application garbage from namespace prod (y/n)y
app "garbage" deleted from namespace "prod"


[root@easzlab ~]# kubectl get svc -n prod
No resources found in prod namespace.
[root@easzlab ~]#  kubectl get pod -n prod  
No resources found in prod namespace.
```
when I delete the resource the svc and deploy are both cleaned.but I set nginx deploy in garbage-collect will not cleaned.
我是不是理解错了

**To Reproduce**

**Expected behavior**

**Screenshots**

**KubeVela Version**

**Cluster information**

**Additional context**
