### ISSUE TITLE
(cannot create Deployment (nginx) in read-only mode)

### ISSUE THREAD

**Issue by 13567436138** [kubevela/kubevela#5612]
**Describe the bug**

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: readonly
spec:
  components:
    - name: nginx
      type: webservice
      properties:
        image: nginx
      traits:
        - type: scaler
          properties:
            replicas: 1
  policies:
    - type: read-only
      name: read-only
      properties:
        rules:
          - selector:
              componentNames:
              - nginx
```
apply the yaml got message: 'run step(provider=oam,do=component-apply): Dispatch: pre-dispatch
        dryrun failed: Found 1 errors. [(cannot create Deployment (nginx) in read-only
        mode)]'

**To Reproduce**

**Expected behavior**

**Screenshots**

**KubeVela Version**
1.7.4

**Cluster information**

**Additional context**
