### ISSUE TITLE
missing required field "workload" in dev.oam.core.v1beta1.ComponentDefinition.spec

### ISSUE THREAD

**Issue by 13567436138** [kubevela/kubevela#5613]
**Describe the bug**

```
apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  annotations:
    definition.oam.dev/description: Webservice, but can be replicated
  name: replica-webservice
  namespace: vela-system
spec:
  schematic:
    cue:
      template: |
        output: {
            apiVersion: "apps/v1"
            kind:       "Deployment"
            metadata: {
                if context.replicaKey != _|_ {
                    name: context.name + "-" + context.replicaKey
                }
                if context.replicaKey == _|_ {
                    name: context.name
                }
            }
            spec: {
                selector: matchLabels: {
                    "app.oam.dev/component": context.name
                    if context.replicaKey != _|_ {
                        "app.oam.dev/replicaKey": context.replicaKey
                    }
                }

                template: {
                    metadata: {
                        labels: {
                            if parameter.labels != _|_ {
                                parameter.labels
                            }
                            if parameter.addRevisionLabel {
                                "app.oam.dev/revision": context.revision
                            }
                            "app.oam.dev/name":      context.appName
                            "app.oam.dev/component": context.name
                            if context.replicaKey != _|_ {
                                "app.oam.dev/replicaKey": context.replicaKey
                            }

                        }
                        if parameter.annotations != _|_ {
                            annotations: parameter.annotations
                        }
                    }
                }
            }
        }
        outputs: {
            if len(exposePorts) != 0 {
                webserviceExpose: {
                    apiVersion: "v1"
                    kind:       "Service"
                    metadata: {
                        if context.replicaKey != _|_ {
                            name: context.name + "-" + context.replicaKey
                        }
                        if context.replicaKey == _|_ {
                            name: context.name
                        }
                    }
                    spec: {
                        selector: {
                            "app.oam.dev/component": context.name
                            if context.replicaKey != _|_ {
                                "app.oam.dev/replicaKey": context.replicaKey
                            }
                        }
                        ports: exposePorts
                        type:  parameter.exposeType
                    }
                }
            }
        }
```

the yaml is from doc https://kubevela.io/zh/docs/end-user/policies/references
apply got 

[root@localhost replication]# kubectl apply -f cd-replica-webservice.yaml -n vela-system
error: error validating "cd-replica-webservice.yaml": error validating data: ValidationError(ComponentDefinition.spec): missing required field "workload" in dev.oam.core.v1beta1.ComponentDefinition.spec; if you choose to ignore these errors, turn validation off with --validate=false

**To Reproduce**

**Expected behavior**

**Screenshots**

**KubeVela Version**
1.7.4

**Cluster information**

1.23.1
**Additional context**

**Comment by Somefive** [comment]
Great catch! Thanks for the report.

**Comment by 13567436138** [comment]
[root@localhost replication]# vela up -f app-replication.yaml
Applying an application in vela K8s object format...
I0305 22:57:07.034074  135642 apply.go:121] "creating object" name="replication" resource="core.oam.dev/v1beta1, Kind=Application"
error: cannot create object: admission webhook "validating.core.oam.dev.v1beta1.applications" denied the request: field "schematic": Invalid value error encountered, cannot create the validation process context of app=replication in namespace=prod: evaluate base template app=replication in namespace=prod: invalid cue template of workload nginx after merge parameter and context: outputs: reference "exposePorts" not found (and 1 more errors).

**Comment by 13567436138** [comment]
@Somefive can you reopen ,it still has problem when I apply the app
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: replication
spec:
  components:
    - name: nginx
      type: replica-webservice
      properties:
        image: nginx
        ports:
          - port: 80
            expose: true
  policies:
    - name: comp-to-replicate
      type: override
      properties:
        selector: [ "hello-rep" ]
    - name: target-default
      type: topology
      properties:
        clusters: [ "local" ]
    - name: replication-default
      type: replication
      properties:
        keys: ["beijing","hangzhou"]
        selector: ["hello-rep"]
  workflow:
    steps:
      - name: deploy-with-rep
        type: deploy
        properties:
          policies: ["comp-to-replicate","target-default","replication-default"]
```
