### ISSUE TITLE
readonly policy problem oamTypes problem,it seams this kind of selector has problem in many poliicys,did I configured wrong

### ISSUE THREAD

**Issue by 13567436138** [kubevela/kubevela#5620]
**Describe the bug**

**To Reproduce**

apply the nginx deployment
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app.oam.dev/component: nginx
  template:
    metadata:
      labels:
        app.oam.dev/component: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
```

then apply application
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: readonly
spec:
  components:
    - name: nginx
      type: webservice
      properties:
        image: nginx
      traits:
        - type: scaler
          properties:
            replicas: 1
        - type: expose
          properties:
            port: [80]
  policies:
    - type: read-only
      name: read-only
      properties:
        rules:
          - selector:
              oamTypes:
              - COMPONENT
```

      message: 'run step(provider=oam,do=component-apply): Dispatch: pre-dispatch
        dryrun failed: Found 1 errors. [(cannot apply ApplyOption: Deployment prod/nginx
        exists but not managed by any application now)]'
**Expected behavior**

**Screenshots**

**KubeVela Version**

1.7.4

**Cluster information**
1.23.1

**Additional context**
