### ISSUE TITLE
garbage-collect select component strategy never in the first case trait will not cleaned,in the second case trait will cleaned

### ISSUE THREAD

**Issue by 13567436138** [kubevela/kubevela#5624]
**Describe the bug**

**To Reproduce**

policy/garbage-collect/gc-rules-selector-componentNames.yaml

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: garbage
spec:
  components:
    - name: nginx
      type: webservice
      properties:
        image: nginx
        port: 80
      traits:
        - type: expose
          properties:
            port: [80]
  policies:
    - name: garbage-collect
      type: garbage-collect
      properties:
        rules:
          - selector:
              componentNames:
                - nginx
            strategy: never
```

```
vela up -f gc-rules-selector-componentNames.yaml

vela delete garbage

component下面的trait也不会被删除

[root@localhost garbage-collect]# kubectl get pod -n prod
NAME                     READY   STATUS    RESTARTS   AGE
nginx-7d9549d6f7-dhmxl   1/1     Running   0          8s
[root@localhost garbage-collect]# kubectl get svc -n prod
NAME    TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
nginx   ClusterIP   10.68.241.123   <none>        80/TCP    13s
[root@localhost garbage-collect]# vela delete garbage
Are you sure to delete the application prod/garbage (y/n)y
Start deleting appplication prod/garbage
Delete appplication prod/garbage succeeded
[root@localhost garbage-collect]# kubectl get pod -n prod
NAME                     READY   STATUS    RESTARTS   AGE
nginx-7d9549d6f7-dhmxl   1/1     Running   0          28s
[root@localhost garbage-collect]# kubectl get svc -n prod
NAME    TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
nginx   ClusterIP   10.68.241.123   <none>        80/TCP    30s

[root@localhost garbage-collect]# vela list
APP     COMPONENT       TYPE    TRAITS  PHASE   HEALTHY STATUS  CREATED-TIME
```

#### componentTypes

policy/garbage-collect/gc-rules-selector-componentTypes.yaml

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: garbage
spec:
  components:
    - name: nginx
      type: webservice
      properties:
        image: nginx
        port: 80
      traits:
        - type: expose
          properties:
            port: [80]
  policies:
    - name: garbage-collect
      type: garbage-collect
      properties:
        rules:
          - selector:
              componentTypes:
                - webservice
            strategy: never
```

```
vela up -f gc-rules-selector-componentTypes.yaml

vela delete garbage

[root@localhost garbage-collect]# kubectl get pod -n prod
NAME                     READY   STATUS              RESTARTS   AGE
nginx-7d9549d6f7-5hw5x   0/1     ContainerCreating   0          4s
[root@localhost garbage-collect]# kubectl get svc -n prod
NAME    TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)   AGE
nginx   ClusterIP   10.68.244.14   <none>        80/TCP    9s
[root@localhost garbage-collect]# vela delete garbage
Are you sure to delete the application prod/garbage (y/n)y
Start deleting appplication prod/garbage
Delete appplication prod/garbage succeeded
[root@localhost garbage-collect]# kubectl get pod -n prod
NAME                     READY   STATUS    RESTARTS   AGE
nginx-7d9549d6f7-5hw5x   1/1     Running   0          24s
[root@localhost garbage-collect]# kubectl get svc -n prod
No resources found in prod namespace.
```

**Expected behavior**

**Screenshots**

**KubeVela Version**

1.7.4
**Cluster information**

1.23.1
**Additional context**
