### ISSUE TITLE
no component-level GC when workflow failed

### ISSUE THREAD

**Issue by zxbyoyoyo** [kubevela/kubevela#5637]
**Describe the bug**

If there are multiple components under one application, if the distribution operations do not affect each other, the GC operations should also not affect each other

**To Reproduce**

1. apply app yaml

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: first-vela-app
spec:
  components:
    - name: express-server01
      type: webservice
      properties:
        image: crccheck/hello-world
        port: 8000
      traits:
        - type: ingress-1-20
          properties:
            domain: testsvc.example.com
            http:
              "/": 8000

    - name: express-server02
      type: webservice
      properties:
        image: crccheck/hello-world
        port: 8000
      traits:
        - type: ingress-1-20
          properties:
            domain: testsvc.example.com
            http:
              "/": 8000

    - name: express-server03
      type: webservice
      properties:
        image: crccheck/hello-world
        port: 8000
      traits:
        - type: ingress-1-20
          properties:
            domain: testsvc.example.
            http:
              "/": 8000
```

2. get deployment , express-server01 and express-server02 should be running

3. update app yaml,remove express-server01 component

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: first-vela-app
spec:
  components:
    - name: express-server02
      type: webservice
      properties:
        image: crccheck/hello-world
        port: 8000
      traits:
        - type: ingress-1-20
          properties:
            domain: testsvc.example.com
            http:
              "/": 8000

    - name: express-server03
      type: webservice
      properties:
        image: crccheck/hello-world
        port: 8000
      traits:
        - type: ingress-1-20
          properties:
            domain: testsvc.example.
            http:
              "/": 8000
```
          
4. get deployment , express-server01 and express-server02 still running, not garbage collected

**Expected behavior**

**Screenshots**

**KubeVela Version**

**Cluster information**

**Additional context**

**Comment by wonderflow** [comment]
It seems caused by the `express-server03` component is not running successfully. When the workflow failed, the legacy resources won't be deleted.

And yes, we may consider health check and garbage collection to be component level, so that when one component failed, it won't affect other components.

But I think it's a tricky use case, when you deploy the first application that you can already find the app is not health as the 3rd component is failed, why don't fix this error before update a new one? @zxbyoyoyo

**Comment by zxbyoyoyo** [comment]
> It seems caused by the `express-server03` component is not running successfully. When the workflow failed, the legacy resources won't be deleted.
> 
> And yes, we may consider health check and garbage collection to be component level, so that when one component failed, it won't affect other components.
> 
> But I think it's a tricky use case, when you deploy the first application that you can already find the app is not health as the 3rd component is failed, why don't fix this error before update a new one? @zxbyoyoyo

our pass platform is designed to allow a component to fail, but other components can iterate and update normally, without failing because of a component exception

**Comment by Somefive** [comment]
We can add extension fields for the `garbage-collect` policy and allow application to set which component to gc manually.

```yaml
policies:
- type: garbage-collect
  properties:
    components: ["comp-1", "comp-2"]
```

That will let the application only run GC on components `comp-1` and `comp-2`.

**Comment by zxbyoyoyo** [comment]
> We can add extension fields for the `garbage-collect` policy and allow application to set which component to gc manually.
> 
> ```yaml
> policies:
> - type: garbage-collect
>   properties:
>     components: ["comp-1", "comp-2"]
> ```
> 
> That will let the application only run GC on components `comp-1` and `comp-2`.

@wonderflow after discussing with @Somefive , we found that our requirement is to be able to execute GC when the workflow fails, currently it is only when the workflow succeeds, so we intend to add gcWhenWorkflowFailed field, if is set , execute gc when the workflow fails

demo:
```
  policies:
    - name: gc-when-workflowfailed
      type: garbage-collect
      properties:
        gcWhenWorkflowFailed: true
```
