### ISSUE TITLE
can not change workflowrun apply-app namespace

### ISSUE THREAD

**Issue by 13567436138** [kubevela/kubevela#5639]
**Describe the bug**

```
[root@localhost apply-app]# kubectl apply -f aa-ref-namespace.yaml -n prod
workflowrun.core.oam.dev/apply-app created
configmap/my-app unchanged
[root@localhost apply-app]# kubectl get pod -n prod
No resources found in prod namespace.
[root@localhost apply-app]# kubectl get pod 
```

```
apiVersion: core.oam.dev/v1alpha1
kind: WorkflowRun
metadata:
  name: apply-app
  annotations:
    workflowrun.oam.dev/debug: "true"
spec:
  workflowSpec:
    steps:
      - name: apply-app
        type: apply-app
        properties:
          ref:
            name: my-app
            namespace: prod
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-app
  namespace: prod
data:
  application: |
    apiVersion: core.oam.dev/v1beta1
    kind: Application
    metadata:
      name: nginx
    spec:
      components:
        - name: nginx
          type: webservice
          properties:
            image: nginx
            ports:
              - port: 80
```

even apply the yaml to prod namespace the application is create in default namespace
**To Reproduce**

**Expected behavior**

**Screenshots**

**KubeVela Version**

**Cluster information**

**Additional context**
