### ISSUE TITLE
can not use build-image-push

### ISSUE THREAD

**Issue by 13567436138** [kubevela/kubevela#5643]
**Describe the bug**

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: build-push-image
spec:
  components:
  - name: my-web
    type: webservice
    properties:
      image: registry.cn-hangzhou.aliyuncs.com/hxpdocker/build-push-image:v1
      ports:
        - port: 80
          expose: true
  workflow:
    steps:
    - name: create-image-secret
      type: export2secret
      properties:
        secretName: image-secret
        kind: docker-registry
        dockerRegistry:
          username: 195446040@qq.com
          password: xxx
    - name: build-push
      type: build-push-image
      properties:
        kanikoExecutor: registry.cn-hangzhou.aliyuncs.com/hxpdocker/kaniko-executor:v1.9.1
        context:
          git: gitee.com/hxpgit/build-push-image.git
          branch: master
        image: registry.cn-hangzhou.aliyuncs.com/hxpdocker/build-push-image:v1
        dockerfile: ./Dockerfile
        credentials:
          image:
            name: image-secret
        buildArgs:
        - BUILDKIT_INLINE_CACHE=1
        platform: linux/amd64
        verbosity: true
    - name: apply-comp
      type: apply-component
      properties:
        component: my-web
```

apply this got 

```
      lastExecuteTime: "2023-03-09T07:52:25Z"
      message: "#do:       \"apply\"\n#provider: \"kube\"\n\n// +usage=The cluster
        to use\ncluster: *\"\" | string\n// +usage=The resource to apply\nvalue: {\n\tapiVersion:
        \"v1\"\n\tkind:       \"Pod\"\n\tmetadata: {\n\t\tname:      \"build-push-image-n3difdfdtz-kaniko\"\n\t\tnamespace:
        \"prod\"\n\t}\n\tspec: {\n\t\tcontainers: [{\n\t\t\targs: [\"--dockerfile=./Dockerfile\",
        _|_, \"--destination=registry.cn-hangzhou.aliyuncs.com/hxpdocker/build-push-image:v1\",
        \"--verbosity=true\", \"--customPlatform=linux/amd64\", \"--build-arg=BUILDKIT_INLINE_CACHE=1\"]\n\t\t\timage:
        \"registry.cn-hangzhou.aliyuncs.com/hxpdocker/kaniko-executor:v1.9.1\"\n\t\t\tvolumeMounts:
        [{\n\t\t\t\tmountPath: \"/kaniko/.docker/\"\n\t\t\t\tname:      \"image-secret\"\n\t\t\t}]\n\t\t\tname:
        \"kaniko\"\n\t\t}]\n\t\tvolumes: [{\n\t\t\tname: \"image-secret\"\n\t\t\tsecret:
        {\n\t\t\t\tdefaultMode: 420\n\t\t\t\titems: [{\n\t\t\t\t\tkey:  *\".dockerconfigjson\"
        | string\n\t\t\t\t\tpath: \"config.json\"\n\t\t\t\t}]\n\t\t\t\tsecretName:
        \"image-secret\"\n\t\t\t}\n\t\t}]\n\t\trestartPolicy: \"Never\"\n\t}\n}\n//
        +usage=The patcher that will be applied to the resource, you can define the
        strategy of list merge through comments. Reference doc here: https://kubevela.io/docs/platform-engineers/traits/patch-trait#patch-in-workflow-step\npatch?:
        {\n\t...\n}\n(bottom kind)"
      name: build-push
```
**To Reproduce**

**Expected behavior**

**Screenshots**

**KubeVela Version**

**Cluster information**

**Additional context**
