### ISSUE TITLE
workflow clean-jobs error

### ISSUE THREAD

**Issue by 13567436138** [kubevela/kubevela#5653]
**Describe the bug**

**To Reproduce**

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: clean-jobs
spec:
  components:
  - name: nginx
    type: webservice
    properties:
      image: nginx
    traits:
      - type: expose
        properties:
          port: 
          - 80
  workflow:
    steps:
    - name: clean-cli-jobs
      type: clean-jobs
      properties:
        labelSelector:
          enable-addon.oam.dev: addon
```

got error:
      message: 'run step(provider=kube,do=delete): cue: marshal error: cleanJobs.value.metadata.namespace:
        cannot convert incomplete value "|((string){ \"default\" }, (string){ \"prod\"
        }, (string){ string })" to JSON'

**Expected behavior**

**Screenshots**

**KubeVela Version**

1.7.4
**Cluster information**

**Additional context**
