### ISSUE TITLE
workflow create-config no cm was created,no pod svc was created

### ISSUE THREAD

**Issue by 13567436138** [kubevela/kubevela#5654]
**Describe the bug**

**To Reproduce**

```
kind: Application
apiVersion: core.oam.dev/v1beta1
metadata:
  name: create-config
spec:
  components: 
    - type: webservice
      name: nginx
      properties:
        image: nginx
        imagePullPolicy: IfNotPresent
      traits:
        - type: expose
          properties:
            port: [80]
  workflow:
    steps:
    - name: write-config
      type: create-config
      properties:
        name: test
        config: 
          key1: value1
          key2: 2
          key3: true
          key4: 
            key5: value5
```

```
[root@localhost ~]# kubectl get pod -n prod
No resources found in prod namespace.
[root@localhost ~]# kubectl get pod -n prod
No resources found in prod namespace.
[root@localhost ~]# kubectl get svc -n prod
No resources found in prod namespace.
[root@localhost ~]# kubectl get cm -n prod
NAME                                DATA   AGE
kube-root-ca.crt                    1      6d2h
workflow-build-push-image-context   1      2d2h
workflow-create-config-context      1      3m36s
```
**Expected behavior**

**Screenshots**

**KubeVela Version**

**Cluster information**

**Additional context**

**Comment by barnettZQG** [comment]
@13567436138 The config save as Secret and not ConfigMap. Unfortunately, your use case doesn't have the deploy step, so, the component resource is not deployed.

**Comment by wonderflow** [comment]
Please try this: 

```
kind: Application
apiVersion: core.oam.dev/v1beta1
metadata:
  name: create-config
spec:
  components: 
    - type: webservice
      name: nginx
      properties:
        image: nginx
        imagePullPolicy: IfNotPresent
      traits:
        - type: expose
          properties:
            port: [80]
  workflow:
    steps:
    - name: write-config
      type: create-config
      properties:
        name: test
        config: 
          key1: value1
          key2: 2
          key3: true
          key4: 
            key5: value5
    - name: deploy-my-component
      type: deploy
      properties:
        policies: []
```

**Comment by wonderflow** [comment]
But after run the above application twice, I found a new issue:

```
   steps:
    - firstExecuteTime: "2023-03-13T11:21:28Z"
      id: som2tt8641
      lastExecuteTime: "2023-03-13T11:21:43Z"
      message: 'run step(provider=config,do=create): the secret type of the config
        can not be change'
      name: write-config
      phase: failed
      reason: Execute
      type: create-config
```

It seems the `create-config` step can't be run twice. \cc @barnettZQG @FogDong

**Comment by barnettZQG** [comment]
@wonderflow Yeah, I also found it. Maybe the empty config template leads to this issue. It needs to further analyze.

**Comment by Mcduller** [comment]
> @wonderflow Yeah, I also found it. Maybe the empty config template leads to this issue. It needs to further analyze.

yes, the empty config template leads this issue. after first time to create the secret, the secret type is Qpaque, then create the same secret use empty config template again, the secret type is empty, and the error occurred。

**Comment by sambeet99** [comment]
Any improvement here ? I am also facing same issue.
I have a component and policy and need to create a configmap.
I first deployed component and then configmap. Policy automatically applied. Application running but configmap not getting created.

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: swagger

---
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: swagger-application
  namespace: swagger
spec:
  components:
  - name: restapi-documentaion
    type: swagger
  policies:
    - name: swagger-sa
      type: serviceaccount
      properties:
        name: swagger-sa
    - name: swagger-sa
      type: userrole
      properties:
        name: swagger-sa
        apigroups:
        - ""
        - extensions
        - apps
        resources:
        - configmaps
        - pods
        - services
        - endpoints
        - secrets
        verbs:
        - get
        - list
        - watch
    - name: swagger-sa
      type: userrolebinding
      properties:
        name: swagger-sa
        rbname: "swagger-sa"
        rbsubjects:
          "ServiceAccount": swagger-sa
  workflow:
    steps:
    - name: apply-component
      type: apply-component
      properties:
        component: restapi-documentaion
    - name: write-config
      type: create-config
      properties:
        name: swaggerui-2
        namespace: swagger
        config:
          key1: value1
          key2: 2
          key3: true
          key4:
            key5: value5
```
