### ISSUE TITLE
vela ls -A isn't well format

### ISSUE THREAD

**Issue by howieyuen** [kubevela/kubevela#5662]
**Describe the bug**

`vela ls -A` is not well format.

**To Reproduce**

run `vela up` twice, with different application yaml of course, each app's name should be long and short.

**Expected behavior**

a well format table.

**Screenshots**

![image](https://user-images.githubusercontent.com/23924124/224653562-39d708fe-66d1-46b4-b1b1-835881551722.png)

after I do `vela delete`, well format:

![image](https://user-images.githubusercontent.com/23924124/224654348-de20820a-7c22-49b6-bcf7-2f704b561340.png)

**KubeVela Version**

```yaml
CLI Version: 1.6.6
Core Version: 1.6.6
GitRevision: b24b52b65129e25bfdeb87026a500e0b50541a64
GolangVersion: go1.19.4
```
**Cluster information**

```yaml
serverVersion:
  buildDate: "2022-01-25T21:19:12Z"
  compiler: gc
  gitCommit: 816c97ab8cff8a1c72eccca1026f7820e93e0d25
  gitTreeState: clean
  gitVersion: v1.23.3
  goVersion: go1.17.6
  major: "1"
  minor: "23"
  platform: linux/amd64
```

**Additional context**
