### ISSUE TITLE
[Feature] deploy workflow-step should support not filling properties

### ISSUE THREAD

**Issue by Somefive** [kubevela/kubevela#5670]
**Is your feature request related to a problem? Please describe.**

When there is no explicit policy to use, application workflow should support `deploy` workflow-step without properties.

**Describe the solution you'd like**

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: create-config
  namespace: default
spec:
  components:
  - name: nginx
    properties:
      image: nginx
      imagePullPolicy: IfNotPresent
    traits:
    - properties:
        port:
        - 80
      type: expose
    type: webservice
  workflow:
    steps:
    - name: write-config
      properties:
        config:
          key1: value1
          key2: 2
          key3: true
          key4:
            key5: value5
        name: test
      type: create-config
    - name: deploy-my-component
      type: deploy
```

It reports error:

```
    - firstExecuteTime: "2023-03-13T11:15:50Z"
      id: y6elrnvs43
      lastExecuteTime: "2023-03-13T11:15:50Z"
      name: write-config
      phase: succeeded
      type: create-config
    - firstExecuteTime: "2023-03-13T11:15:50Z"
      id: 4uuotv2ze2
      lastExecuteTime: "2023-03-13T11:16:42Z"
      message: 'run step(provider=multicluster,do=deploy): cue: marshal error: deploy.policies:
        cannot reference optional field: policies'
      name: deploy-my-component
      phase: failed
      reason: FailedAfterRetries
      type: deploy
    suspend: false
    terminated: true
```

The expected behavior is to run successfully without error.

**Describe alternatives you've considered**

**Additional context**
