### ISSUE TITLE
workflow delete-config can not delete secret created by create-config

### ISSUE THREAD

**Issue by 13567436138** [kubevela/kubevela#5674]
**Describe the bug**

**To Reproduce**

```
kind: Application
apiVersion: core.oam.dev/v1beta1
metadata:
  name: delete-config
spec:
  components: 
    - type: webservice
      name: nginx
      properties:
        image: nginx
        imagePullPolicy: IfNotPresent
      traits:
        - type: expose
          properties:
            port: [80]
  workflow:
    steps:
    - name: write-config
      type: create-config
      properties:
        name: test
        config: 
          key1: value1
          key2: 2
          key3: true
          key4: 
            key5: value5
    - name: delete-config
      type: delete-config
      properties:
        name: test
```
```
[root@localhost ~]# kubectl get secret -n prod
NAME                  TYPE                                  DATA   AGE
default-token-z8xcp   kubernetes.io/service-account-token   3      8d
test                  Opaque                                1      5s
```
secret is not deleted
**Expected behavior**

**Screenshots**

**KubeVela Version**
1.7.4

**Cluster information**

**Additional context**
