### ISSUE TITLE
workflow export-service has no cm or secret created

### ISSUE THREAD

**Issue by 13567436138** [kubevela/kubevela#5675]
**Describe the bug**

**To Reproduce**

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: export-service
spec:
  components:
    - type: webservice
      name: nginx
      properties:
        image: nginx
        imagePullPolicy: IfNotPresent
      traits:
        - type: expose
          properties:
            port: [80]
            type: LoadBalancer
  policies:
    - type: topology
      name: local
      properties:
        clusters: ["local"]
  workflow:
    steps:
      - type: deploy
        name: deploy
        properties:
          policies: ["local"]
      - type: collect-service-endpoints
        name: collect-service-endpoints
        outputs:
          - name: host
            valueFrom: value.endpoint.host
      - type: export-service
        name: export-service
        properties:
          name: nginx
        inputs:
          - from: host
            parameterKey: ip
```
```
[root@localhost ~]# kubectl get svc -n prod
NAME    TYPE           CLUSTER-IP    EXTERNAL-IP   PORT(S)        AGE
nginx   LoadBalancer   10.68.7.128   <pending>     80:30098/TCP   3m22s
[root@localhost ~]# kubectl get secret -n prod
NAME                  TYPE                                  DATA   AGE
default-token-z8xcp   kubernetes.io/service-account-token   3      8d
[root@localhost ~]# kubectl get cm -n prod
NAME                              DATA   AGE
kube-root-ca.crt                  1      8d
workflow-export-service-context   1      3m28s
[root@localhost ~]# kubectl get cm 
NAME                 DATA   AGE
istio-ca-root-cert   1      287d
kube-root-ca.crt     1      287d
[root@localhost ~]# kubectl get secret 
NAME                  TYPE                                  DATA   AGE
default-token-rzkpb   kubernetes.io/service-account-token   3      287d
```

**Expected behavior**

**Screenshots**

**KubeVela Version**

1.7.4
**Cluster information**

**Additional context**
