### ISSUE TITLE
second apply-app step not executed

### ISSUE THREAD

**Issue by 13567436138** [kubevela/kubevela#5686]
**Describe the bug**

**To Reproduce**

```
apiVersion: core.oam.dev/v1alpha1
kind: WorkflowRun
metadata:
  name: read-app
  annotations:
    workflowrun.oam.dev/debug: "true"
spec:
  workflowSpec:
    steps:
      - name: check-app-exist
        type: read-app
        properties:
          name: webservice-app
      - name: apply-app1
        type: apply-app
        if: status["check-app-exist"].message == "Application not found"
        properties:
          data:
            apiVersion: core.oam.dev/v1beta1
            kind: Application
            metadata:
              name: webservice-app
              namespace: prod
            spec:
              components:
                - name: nginx
                  type: webservice
                  properties:
                    image: nginx
                    ports:
                      - port: 80
      - name: suspend
        type: suspend
        timeout: 10s
      - name: apply-app2
        type: apply-app
        properties:
          ref:
            name: my-app
            key: application
            type: configMap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-app
data:
  application: |
    apiVersion: core.oam.dev/v1beta1
    kind: Application
    metadata:
      name: webservice-app2
      namespace: prod
    spec:
      components:
        - name: nginx2
          type: webservice
          properties:
            image: nginx
            ports:
              - port: 80
        
```
```
[root@localhost ~]# kubectl get pod -n prod -w
NAME                    READY   STATUS              RESTARTS   AGE
nginx-d76966689-brscn   0/1     ContainerCreating   0          13s
nginx-d76966689-brscn   1/1     Running             0          17s

```
I0316 02:59:30.068689       1 workflowrun_controller.go:158] "Workflow return state=Failed" workflowrun="prod/read-app" spanID="i-bbolu9m7"
**Expected behavior**

**Screenshots**

**KubeVela Version**

**Cluster information**

**Additional context**
