### ISSUE TITLE
message: run step(provider=config,do=read): unexpected end of JSON input

### ISSUE THREAD

**Issue by 13567436138** [kubevela/kubevela#5687]
**Describe the bug**

**To Reproduce**

workflow/read-config/rc-name.yaml

```
kind: Application
apiVersion: core.oam.dev/v1beta1
metadata:
  name: read-config
spec:
  components: []
  workflow:
    steps:
    - name: read-config
      type: read-config
      properties:
        name: test
      outputs:
      - fromKey: config
        name: read-config
```

```
kubectl create secret generic test -n prod --from-literal config=bb

vela up -f rc-name.yaml
```

```
[root@localhost read-config]# vela status read-config
About:

  Name:         read-config                  
  Namespace:    prod                         
  Created at:   2023-03-15 20:36:29 -0700 PDT
  Status:       runningWorkflow              

Workflow:

  mode: StepByStep-DAG
  finished: false
  Suspend: false
  Terminated: false
  Steps
  - id: i45jdwjjma
    name: read-config
    type: read-config
    phase: failed 
    message: run step(provider=config,do=read): unexpected end of JSON input
```
**Expected behavior**

**Screenshots**

**KubeVela Version**

**Cluster information**

**Additional context**
