### ISSUE TITLE
step-group webservice component configured port did not create svc

### ISSUE THREAD

**Issue by 13567436138** [kubevela/kubevela#5700]
**Describe the bug**

**To Reproduce**

workflow/step-group/sg-demo.yaml

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: step-group
spec:
  components:
    - name: nginx
      type: webservice
      properties:
        image: nginx
        port: 80
    - name: nginx2
      type: webservice
      properties:
        image: nginx
        port: 80

  workflow:
    steps:
      - name: step
        type: step-group
        subSteps:
          - name: apply-sub-step1
            type: apply-component
            properties:
              component: nginx
          - name: apply-sub-step2
            type: apply-component
            properties:
              component: nginx2
```

```
vela up -f sg-demo.yaml
```

```
[root@localhost step-group]# vela status step-group
About:

  Name:         step-group                   
  Namespace:    prod                         
  Created at:   2023-03-18 00:04:31 -0700 PDT
  Status:       running                      

Workflow:

  mode: StepByStep-DAG
  finished: true
  Suspend: false
  Terminated: false
  Steps
  - id: rxacdeqp42
    name: step
    type: step-group
    phase: succeeded 
    - id: 8tqlcl1kdq
      name: apply-sub-step1
      type: apply-component
      phase: succeeded 
    - id: znz2zim4o4
      name: apply-sub-step2
      type: apply-component
      phase: succeeded 

Services:

  - Name: nginx  
    Cluster: local  Namespace: prod
    Type: webservice
    Healthy Ready:1/1
    No trait applied

  - Name: nginx2  
    Cluster: local  Namespace: prod
    Type: webservice
    Healthy Ready:1/1
    No trait applied
```

```
[root@localhost ~]# kubectl get pod -n prod
NAME                      READY   STATUS    RESTARTS   AGE
nginx-5b58cdc7d6-bg9z5    1/1     Running   0          2m
nginx2-658649d65b-zr5gv   1/1     Running   0          119s
[root@localhost ~]# kubectl get svc -n prod
No resources found in prod namespace.
```

**Expected behavior**

**Screenshots**

**KubeVela Version**

1.7.4

**Cluster information**

**Additional context**
