### ISSUE TITLE
Format error loses all patch annotations without error

### ISSUE THREAD

**Issue by paulsdt** [kubevela/kubevela#5749]
**Describe the bug**
If defining a patching trait to add annotations, incorrectly processing an int annotation value results in all annotations being lost, without any error being displayed.

**To Reproduce**

Trait definition:

```
mytrait: {
    description: ""
    labels: {}
    type: "trait"
    alias: ""
    annotations: {}
    labels: {}
    attributes: {
        appliesToWorkloads: ["deployments.apps"]
        podDisruptive: true
    }
}

template: {
        patch: {
               metadata: annotations: {
                       "myattr1": parameter.myattr1
                       "myattr2": parameter.myattr2
                       "myattr3": parameter.myattr3
               }
        }

        parameter: {
                myattr1: string
                myattr2: int
                myattr3: string
        }
}
```

Application:

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: myapp
spec:
  components:
  - name: myapp
    type: webservice
    properties:
      image: oamdev/hello-world
    traits:
    - name: anot
      type: mytrait
      properties:
        myattr1: foo
        myattr2: 7
        myattr3: bar
```

Perform a vela dry-run, output is (note no annotations on deployment):
```
---
# Application(myapp) -- Component(myapp)
---

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app.oam.dev/appRevision: ""
    app.oam.dev/component: myapp
    app.oam.dev/name: myapp
    app.oam.dev/namespace: default
    app.oam.dev/resourceType: WORKLOAD
    workload.oam.dev/type: webservice
  name: myapp
  namespace: default
spec:
  selector:
    matchLabels:
      app.oam.dev/component: myapp
  template:
    metadata:
      labels:
        app.oam.dev/component: myapp
        app.oam.dev/name: myapp
    spec:
      containers:
      - image: oamdev/hello-world
        name: myapp

---
```
Fixing the myattr2 line in the trait definition to read:

```
                       "myattr2": "\(parameter.myattr2)"
```

The dry-run output becomes (note deployment now has all annotations):

```
---
# Application(myapp) -- Component(myapp)
---

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    myattr1: foo
    myattr2: "7"
    myattr3: bar
  labels:
    app.oam.dev/appRevision: ""
    app.oam.dev/component: myapp
    app.oam.dev/name: myapp
    app.oam.dev/namespace: default
    app.oam.dev/resourceType: WORKLOAD
    workload.oam.dev/type: webservice
  name: myapp
  namespace: default
spec:
  selector:
    matchLabels:
      app.oam.dev/component: myapp
  template:
    metadata:
      labels:
        app.oam.dev/component: myapp
        app.oam.dev/name: myapp
    spec:
      containers:
      - image: oamdev/hello-world
        name: myapp

---
```

**Expected behavior**

An error should be presented, or if this is not possible, only the problem annotation dropped, not all.

**KubeVela Version**

CLI Version: 1.7.6.

**Additional context**

Discussed [on slack channel](https://cloud-native.slack.com/archives/C01BLQ3HTJA/p1679482746697269), @wonderflow asked for a bug to be raised.
