### ISSUE TITLE
component name generated by vela adopt should be lowercase without dot

### ISSUE THREAD

**Issue by wonderflow** [kubevela/kubevela#5771]
**Is your feature request related to a problem? Please describe.**

I've deployed a replication controller object:

```
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app.oam.dev/adopt: native
    app.oam.dev/component: mysql-replica-controller
    app.oam.dev/name: mysql
    app.oam.dev/namespace: default
    name: mysql
  name: mysql
  namespace: default
spec:
  replicas: 1
  selector:
    name: mysql
  template:
    metadata:
      labels:
        name: mysql
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: nacos_devtest
        - name: MYSQL_USER
          value: nacos
        - name: MYSQL_PASSWORD
          value: nacos
        image: mysql:8.0.19
        imagePullPolicy: IfNotPresent
        name: mysql
        ports:
        - containerPort: 3306
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-data
      volumes:
      - hostPath:
          path: /var/lib/mysql
          type: ""
        name: mysql-data
```

After adoption by, it generate application like below, when I want to add a trait, it reports error because the name used in trait is the component name which should follow the K8s name format:

```
        DNS-1035 label must consist of lower case alphanumeric characters or ''-'',
        start with an alphabetic character, and end with an alphanumeric character
```

The YAML like below:

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  labels:
    app.oam.dev/adopt: native
  name: mysql
  namespace: default
spec:
  components:
  - name: mysql.ReplicationController
    properties:
      objects:
      - apiVersion: v1
        kind: ReplicationController
        metadata:
          name: mysql
    traits:
    - properties:
        ports:
        - nodePort: 3306
          port: 3306
        type: NodePort
      type: expose
    type: k8s-objects
  policies:
  - name: take-over
    properties:
      rules:
      - selector:
          componentNames:
          - mysql.ReplicationController
    type: take-over
```

![image](https://user-images.githubusercontent.com/2173670/228472658-8e479696-4b40-41fc-b243-59c6272c53d6.png)

```
      message: 'run step(provider=oam,do=component-apply): Dispatch: pre-dispatch
        dryrun failed: Found 1 errors. [(cannot create object: Service "mysql.ReplicationController"
        is invalid: metadata.name: Invalid value: "mysql.ReplicationController": a
        DNS-1035 label must consist of lower case alphanumeric characters or ''-'',
        start with an alphabetic character, and end with an alphanumeric character
        (e.g. ''my-name'',  or ''abc-123'', regex used for validation is ''[a-z]([-a-z0-9]*[a-z0-9])?''))]'
```

**Describe the solution you'd like**

I hope the component name can be lower case automatically.

It seems we just need to change [this line](https://github.com/kubevela/kubevela/blob/master/references/cli/adopt-templates/default.cue#L129) to use something like "strings.ToLowerCase" to cover this string result.

I'm not sure if there's a real "strings.ToLowerCase"  exists.

**Describe alternatives you've considered**

**Additional context**
