### ISSUE TITLE
[Feature] make an openTelemetry operator addon

### ISSUE THREAD

**Issue by wangyikewxgm** [kubevela/kubevela#5774]
**Is your feature request related to a problem? Please describe.**

[OpenTelemetry](https://github.com/open-telemetry/opentelemetry-operator) operator can implement traces in your application without any code changes. Therefore, I suggest creating an OpenTelemetry operator addon.

**Describe the solution you'd like**

1. Install OT operator by addon.
2. Define a traitDefinition to inject OT sidecar to workload.

**Describe alternatives you've considered**

**Additional context**

**Comment by wangyikewxgm** [comment]
@MdSahil-oss Are you interested in doing this?

**Comment by MdSahil-oss** [comment]
@wangyikewxgm I created a traitDefinition `opentelemetry-sidecar-collector` to inject OT sidecar to workload, But there is a problem that sidecar container `otc-container` doesn't get created for the application which defines `trait` like shown below: 
```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: otel-sample
spec:
  components:
    - type: "k8s-objects"
      name: "otel-pod"
      properties:
        objects:
          - apiVersion: v1
            kind: Pod
            metadata:
              name: myapp
              annotations:
                sidecar.opentelemetry.io/inject: "true"
            spec:
              containers:
                - name: myapp
                  image: jaegertracing/vertx-create-span:operator-e2e-tests
                  ports:
                    - containerPort: 8080
                      protocol: TCP
      traits:
        - type: opentelemetry-sidecar-collector
          name: otel-container
          properties:
            config: |
              receivers:
                jaeger:
                  protocols:
                    thrift_compact:
              processors:

              exporters:
                logging:

              service:
                pipelines:
                  traces:
                    receivers: [jaeger]
                    processors: []
                    exporters: [logging]

```
When above YAML is applied to the cluster then the Pod `myapp` will get created first after that trait resources will be executed so the pod `myapp` will have no impact of the trait resources, All the pods (or resources) which will be executed later on, will have impact of trait resouces and `otel-container` will be created in their pods, So I think we should have `ComponentDefination` of otel-collector instead of `traitDefination`.
