### ISSUE TITLE
Adding support for ApplicationConfiguration similar to Rudr

### ISSUE THREAD

**Issue by nitagarwal** [kubevela/kubevela#5876]
**Is your feature request related to a problem? Please describe.**
The Kubevela require developer to declare a high level OAM application spec. It restrict any abstraction which common infrastructure team can provide or developers to define application as composition of multiple components defined in different spec files. 

The Rudr support a ApplicationConfiguration spec, which is similar to Application spec but let developers reference components defined in their own spec: https://github.com/oam-dev/rudr/blob/master/docs/concepts/application-configuration.md 

**Describe the solution you'd like**
I would like to add a new OAM spec like https://github.com/oam-dev/rudr/blob/master/docs/concepts/application-configuration.md

**Comment by Somefive** [comment]
ApplicationConfiguration is a legacy design for version before 1.0. Currently, KubeVela does not have a plan for a Component outside application. I'm curious what is the case that you need external Component? For reuse or sharing?

**Comment by Pacman99** [comment]
This feature would be nice for when you have components that are long and you want to re-use them between staging and production manifests for the same application.

**Comment by Somefive** [comment]
> This feature would be nice for when you have components that are long and you want to re-use them between staging and production manifests for the same application.

I see. Do you use one application to handle both staging and production cases? If so, you only need to write component once and use the "override" policy and "deploy" workflow-step to handle the single component multi-destination deploy.

**Comment by Somefive** [comment]
> How would I do this if I wanted the staging application to deploy to a separate namespace from the production application? Because the override policy is unable to change the name or namespace of an application.

The `topology` policy could.

```
policies:
- type: topology
  name: namespace-x
  properties:
    clusters: ["local"] // this means this topology points to the hub control plane cluster, you can change it to other
    namespace: x // this means all namespaced resources will be delivered to this namespace
```
