### ISSUE TITLE
Application failed when vela adopt multi-cluster resource by read-only.

### ISSUE THREAD

**Issue by caiqi1111** [kubevela/kubevela#5970]
**Describe the bug**

I use `vela adopt deployment/cq-mem/caiqi/cq deployment/local/caiqi1/nginx-deployment -n caiqi-test --apply --app-name test-multi` to read-only multi-cluster resource, the application is created, but status is failed. Vela cli is from latest master-branch code.

This is application.yaml:

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  creationTimestamp: null       
  labels:
    app.oam.dev/adopt: native   
  name: test-multi
  namespace: caiqi-test
spec:
  components:
  - name: deployment-cq
    properties:
      objects:
      - apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: cq
          namespace: caiqi
        spec:
          progressDeadlineSeconds: 600
          replicas: 2
          revisionHistoryLimit: 10
          selector:
            matchLabels:
              kind: deployment
              workload: cq
          strategy:
            rollingUpdate:
              maxSurge: 25%
              maxUnavailable: 25%
            type: RollingUpdate
          template:
            metadata:
              creationTimestamp: null
              labels:
                kind: deployment
                workload: cq
            spec:
              containers:
              - image: cis-hub-huadong-4.cmecloud.cn/kubesphere/nginx:latest
                imagePullPolicy: IfNotPresent
                name: cq
                resources:
                  limits:
                    cpu: 500m
                    memory: 512Mi
                  requests:
                    cpu: 500m
                    memory: 512Mi
                terminationMessagePath: /dev/termination-log
                terminationMessagePolicy: File
              dnsConfig:
                options:
                - name: single-request-reopen
                - name: timeout
                  value: "2"
                - name: ndots
                  value: "5"
              dnsPolicy: ClusterFirst
              restartPolicy: Always
              schedulerName: default-scheduler
              securityContext: {}
              terminationGracePeriodSeconds: 30
              topologySpreadConstraints:
              - labelSelector:
                  matchLabels:
                    workload: cq
                maxSkew: 1
                topologyKey: kubernetes.io/hostname
                whenUnsatisfiable: ScheduleAnyway
    type: k8s-objects
  - name: deployment-nginx-deployment
    properties:
      objects:
      - apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: nginx-deployment
          namespace: caiqi1
        spec:
          progressDeadlineSeconds: 600
          replicas: 3
          revisionHistoryLimit: 10
          selector:
            matchLabels:
              app: nginx
          strategy:
            rollingUpdate:
              maxSurge: 25%
              maxUnavailable: 25%
            type: RollingUpdate
          template:
            metadata:
              creationTimestamp: null
              labels:
                app: nginx
            spec:
              containers:
              - image: nginx
                imagePullPolicy: Always
                name: nginx
                ports:
                - containerPort: 80
                  protocol: TCP
                resources: {}
                terminationMessagePath: /dev/termination-log
                terminationMessagePolicy: File
              dnsPolicy: ClusterFirst
              restartPolicy: Always
              schedulerName: default-scheduler
              securityContext: {}
              terminationGracePeriodSeconds: 30
    type: k8s-objects
  policies:
  - name: read-only
    properties:
      rules:
      - selector:
          componentNames:
          - deployment-cq
          - deployment-nginx-deployment
    type: read-only
  workflow: {}
status: {}
```

the error is：
<img width="517" alt="1683625704392_69950F1B-1128-4022-BA2C-072CE986C776" src="https://github.com/kubevela/kubevela/assets/107997570/234e5e0e-4503-4711-810b-086d968a4b02">

**To Reproduce**

**Expected behavior**

**Screenshots**

**KubeVela Version**

**Cluster information**

**Additional context**
