### ISSUE TITLE
[Feature] Extend topology policy for overriding application labels/ annotations 

### ISSUE THREAD

**Issue by nitagarwal** [kubevela/kubevela#6001]
**Is your feature request related to a problem? Please describe.**
We plan to use OAM + kubevela to generate set of CRDs/K8s manifests for different environments.  The CRDs and K8s resources names/ properties require environmentType to drive uniqueness and discoverability. 
To achieve that we plan to attach some application specific metadata (envType, name ) in the labels/ annotations.
So, consider the following OAM : 
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: mygolangservicemultienv
  namespace: mygolangservice
  labels:
    environment: development #Type of environment, For ex: development, staging, prod
  annotations:
    path: "some/local/path"
spec:
  components:
    - name: mygolangservicemultienv
      type: webservice
      properties:
        image: mygolangservice
      traits:
        - type: managed-ingress
  policies:
    - name: target-development
      type: topology
      properties:
        clusters: ["common"]
        labels: 
          environment: development
    - name: target-staging
      type: topology
      properties:
        clusters: ["common"]
        labels: 
          environment: staging  
  workflow:
    steps:
      - name: development
        type: deploy
        properties:
          policies: ["target-development"]
      - name: manual-approval
        type: suspend
      - name: staging
        type: deploy
        properties:
          policies: ["target-staging"]
```

It generated two different environments : development and staging
The servicename and managed ingress dns address for development env should be:  mygolangservicemultienv-development, mygolangservicemultienv-development.cloud.tech,  

and for staging should be : mygolangservicemultienv-staging, mygolangservicemultienv-staging.cloud.tech

**Describe the solution you'd like**
We would like to extend the topology policy to override the labels and annotations. 

**Describe alternatives you've considered**
1. Use namespace to scope the generated CRDs :  It is not entirely possible, because our organization shares namespace because permissions are whitelisted by namespace. 
2. Create your policy definition : It will not work, as we would like to change the context of the application. A new policy definition can only patch certain properties to few components. 
3. Expose labels as properties in components and pass labels directly to components by  override policy: This solution is not scalable as for every component definition we need to expose labels fields. And often our application may require multiple components sharing same context. So, it will require lot of same label context being repeated.

**Comment by nitagarwal** [comment]
Thanks, agreed it may work. My third alternative is exactly this approach. I am hesitant for this approach as our application may have multiple components and we would like to avoid repetition. And want that environment specific context is available by default.

**Comment by Somefive** [comment]
> Thanks, agreed it may work. My third alternative is exactly this approach. I am hesitant for this approach as our application may have multiple components and we would like to avoid repetition. And want that environment specific context is available by default.

Well, as for the "environment" there is a long history debating how this should be designed and implemented. One of the critical thing is that different people have different opinion for the "environment" and it is hard to reach a consensus. Therefore, in the core controller of KubeVela, we discard the design of environment and leave it for upper layer, like VelaUX or other platforms.

If you are worrying about the repetition of attaching labels to resources from multiple components, one of the good thing is that the "override" policy can decorate all components if you do not write the name or type of the component. Like
```yaml
  components:
    - name: mygolangservicemultienv-1
      type: webservice
      properties:
        image: mygolangservice
      traits:
        - type: managed-ingress
    - name: mygolangservicemultienv-2
      type: webservice
      properties:
        image: mygolangservice
      traits:
        - type: managed-ingress
  policies:
    - name: override-deployment
      type: override
      properties:
        components:
          - traits:
              - type: labels
                properties:
                  environment: development
```
Or you can use wildcard like "name: mygolangservicemultienv-*" to select components for modifying.
