### ISSUE TITLE
enable terraform provider for alibabacloudstack error

### ISSUE THREAD

**Issue by junfsir** [kubevela/kubevela#6085]
**Describe the bug**
启用terraform的阿里专有云provider报错

**To Reproduce**
按照[文档](https://kubevela.io/zh/docs/platform-engineers/addon/terraform)中的描述启用阿里专有云的terraform provider，hack/addons/terraform/terraform-provider-scaffold/metadata.yaml的配置如下
```
cloudProperties:
  - name: ALIBABACLOUDSTACK_ACCESS_KEY
    secretKey: access_key
  - name: ALIBABACLOUDSTACK_SECRET_KEY
    secretKey: secret_key
  - name: ALIBABACLOUDSTACK_REGION
    isRegion: true
  - name: INSECURE
    secretKey: insecure
  - name: RESOURCE_GROUP_SET_NAME
    secretKey: resource_group_set_name
  - name: DOMAIN
    secretKey: domain
  - name: PROTOCOL
    secretKey: protocol
```

**Screenshots**
![image](https://github.com/kubevela/kubevela/assets/16758455/218e790f-4e9b-4f12-8150-817155f70606)
![image](https://github.com/kubevela/kubevela/assets/16758455/f457c197-830e-4488-b539-142b3b29849e)

**KubeVela Version**
CLI Version: 1.8.2
Core Version: 1.8.2
GitRevision: git-360f69be
GolangVersion: go1.19.9
