### ISSUE TITLE
[Bug] Velaux fail to sync workflow record with conflict entity primarykey

### ISSUE THREAD

**Issue by basuotian** [kubevela/kubevela#6102]
**Describe the bug**

We have two application in different namespace with the same name, like:
- `default/first-vela-app`
- `new-default/first-vela-app`

Both applications are applied by kubectl, and veluax can not render workflow page:
<img width="955" alt="image" src="https://github.com/kubevela/kubevela/assets/93654253/66358160-7723-4ca1-bebf-789556a2edcd">

The reason is that the workflowRecord name do not have namespace/envName info
https://github.com/kubevela/velaux/blob/1c7641efa0e0d8522d817c669209954bd066064f/pkg/server/domain/model/workflow.go#L158C1-L161

So the second app will be conflict in sync workflowRecord from cr to datastore

**To Reproduce**

Apply the follow application

application 1
```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: first-vela-app
  namespace: default
spec:
  components:
  - name: first-vela-app-nginx
    properties:
      image: nginx
    type: webservice
  policies:
  - name: default
    properties:
      clusters:
      - local
      namespace: default
    type: topology
  workflow:
    mode:
      steps: StepByStep
      subSteps: DAG
    steps:
    - meta:
        alias: Deploy To default
      name: default
      properties:
        policies:
        - default
      type: deploy
```

application 2
```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: first-vela-app
  namespace: new-default
spec:
  components:
  - name: first-vela-app-nginx
    properties:
      image: nginx
    type: webservice
  policies:
  - name: default
    properties:
      clusters:
      - local
      namespace: new-default
    type: topology
  workflow:
    mode:
      steps: StepByStep
      subSteps: DAG
    steps:
    - meta:
        alias: Deploy To default
      name: default
      properties:
        policies:
        - default
      type: deploy
```

**Expected behavior**

**Screenshots**

**KubeVela Version**
vela-core:v1.6.7 / 1.8.1
velaux: 1.8.0

**Cluster information**

**Additional context**

Simply change the `WorkflowRecord.PrimaryKey()` to concat namespace will cause some problems: 
- the existing applications created by Velaux will not be able to get workflow record because of the datastore key changed, it has to be recreated 
- the existing applications created by Cli will left legacy entity in datastore

do we have any other better solutions?
