### ISSUE TITLE
vela build-in op op.#Patch does not support patch the whole "spec" field

### ISSUE THREAD

**Issue by TomQunChaoA** [kubevela/kubevela#6119]
**Describe the bug**

When I Write my customized workflow step, I found the op.#Patch with `// +patchStrategy=replace` can't patch the whole spec field, It produced 

**To Reproduce**

1. apply workflow step

```cue
import (
	"vela/op"
	"encoding/json"
)
"workflow-patch-demo": {
	alias: ""
	annotations: {}
	attributes: {}
	description: ""
	labels: {}
	type: "workflow-step"
}

template: {
	parameter:{
		componentName:string
	}
	comps:op.#Load&{}
	compSpec:op.#RenderComponent&{
		value:comps.value[parameter.componentName]
	}
	workloadGvk:{
		kind:compSpec.output.kind
		apiVersion:compSpec.output.apiVersion
		metadata:{
			name:compSpec.output.metadata.name
			namespace:compSpec.output.metadata.namespace
		}
	}
	specLog:op.#Log&{
		data:"[component spec]:"+json.Marshal(compSpec.output.spec)+"\n"
	}
	patch:op.#Patch&{
		value:workloadGvk
		patch:{
			// +patchStrategy=replace
			spec:compSpec.output.spec
		}
	}
}
```

2. apply workload
```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: example
spec:
  components:
    - name: webservice-test
      type: webservice
      properties:
        image: busybox
        cmd: ["/bin/sh", "-c", "sleep 100d"]
        env:
          - name: VERSION
            value: "version-1"
      traits:
        - type: scaler
          properties:
            replicas: 5
  policies:
    - type: apply-once
      name: apply-once
      properties:
        enable: true
    - name: target-xm
      type: topology
      properties:
        clusters: ["local"]
        namespace: "xm"
```

result:

```sh
❯ vela status example
About:

  Name:         example                      
  Namespace:    xm                           
  Created at:   2023-06-14 09:20:47 +0800 CST
  Status:       running                      

Workflow:

  mode: DAG-DAG
  finished: true
  Suspend: false
  Terminated: false
  Steps
  - id: edkzrknj1b
    name: deploy-target-xm
    type: deploy
    phase: succeeded 

Services:

  - Name: webservice-test  
    Cluster: local  Namespace: xm
    Type: webservice
    Healthy Ready:5/5
    Traits:
      ✅ scaler
```

3. apply another workflow

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: example
spec:
  components:
    - name: webservice-test
      type: webservice
      properties:
        image: busybox
        cmd: ["/bin/sh", "-c", "sleep 100d"]
        env:
          - name: VERSION
            value: "version-2"
      traits:
        - type: scaler
          properties:
            replicas: 5
  policies:
    - type: apply-once
      name: apply-once
      properties:
        enable: true
    - name: target-xm
      type: topology
      properties:
        clusters: ["local"]
        namespace: "xm"
  workflow:
    steps:
    - name: patch1
      type: workflow-patch-demo
      properties:
        componentName: "webservice-test"
```

the only difference is the env VERSION's value and the workflow steps

result:

```sh
❯ vela status example
About:

  Name:         example                      
  Namespace:    xm                           
  Created at:   2023-06-14 09:20:47 +0800 CST
  Status:       runningWorkflow              

Workflow:

  mode: StepByStep-DAG
  finished: false
  Suspend: false
  Terminated: false
  Steps
  - id: 9eyn7kexdt
    name: patch1
    type: workflow-patch-demo
    phase: failed 
    message: run step(provider=kube,do=patch): result check err: spec.template.spec.containers.0.env.0.value: conflicting values "version-2" and "version-1"

Services:

  - Name: webservice-test  
    Cluster: local  Namespace: xm
    Type: webservice
    Healthy Ready:5/5
    Traits:
      ✅ scaler
```

**Expected behavior**

replace the whole spec field

**Extra Information**

I also tried `// +patchStrategy=retainKeys`，It can replace the whole spec, though 2nd deployment's spec is 

```yaml
# ...
        env:
          - name: VERSIONX
            value: "version-2"
# ...
```

(There is only one env in the deployment, and name is VERSIONX, value is `version-2`)

and the result is

```
❯ k exec webservice-test-7cb67d6777-6dsbq -- env | grep ver
VERSIONX=version-2
```

So the `retainKeys` performs like `replace`

**KubeVela Version**

```
❯ vela version
CLI Version: 1.8.2
Core Version: 1.8.2
GitRevision: git-360f69be
GolangVersion: go1.19.9
```
