### ISSUE TITLE
kubevela 1.8.2 cannot run canary-demo

### ISSUE THREAD

**Issue by cyxinda** [kubevela/kubevela#6161]
**Describe the bug**
when I run canary-demo of kubeVela offical document ,the document web url :https://www.bookstack.cn/read/kubevela-1.8-zh/723a1378bc12fd77.md ,some error happened.
```yaml
[root@xy-5-server14 canary]# cat v1.yaml 
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: canary-demo
  namespace: canary
  annotations:
    app.oam.dev/publishVersion: v1
spec:
  components:
  - name: canary-demo
    type: helm
    properties:
      repoType: "helm"
      url: "https://wangyikewxgm.github.io/my-charts/"
      chart: "canary-demo"
      version: "1.0.0"
    traits:
    - type: kruise-rollout
      properties:
        canary:
          # The first batch of Canary releases 20% Pods, and 20% traffic imported to the new version, require manual confirmation before subsequent releases are completed
          steps:
          - weight: 20
          # The second batch of Canary releases 90% Pods, and 90% traffic imported to the new version.
          - weight: 90
          trafficRoutings:
          - type: ingress
```

I start up the application:
```bash
[root@xy-5-server14 canary]# vela up -f v1.yaml 
Applying an application in vela K8s object format...
I0627 14:27:17.357818   21058 apply.go:121] "creating object" name="canary-demo" resource="core.oam.dev/v1beta1, Kind=Application"
✅ App has been deployed 🚀🚀🚀
    Port forward: vela port-forward canary-demo -n canary
             SSH: vela exec canary-demo -n canary
         Logging: vela logs canary-demo -n canary
      App status: vela status canary-demo -n canary
        Endpoint: vela status canary-demo -n canary --endpoint
Application canary/canary-demo applied. 
```
Some error happend:
```bash
[root@xy-5-server14 canary]# vela status canary-demo -n canary
About:

  Name:         canary-demo                  
  Namespace:    canary                       
  Created at:   2023-06-27 14:27:17 +0800 CST
  Status:       workflowFailed               

Workflow:

  mode: DAG-DAG
  finished: true
  Suspend: false
  Terminated: true
  Steps
  - id: 4vb9iyar1c
    name: canary-demo
    type: apply-component
    phase: failed 
    message: run step(provider=oam,do=component-apply): Dispatch: pre-dispatch dryrun failed: Found 1 errors. [(cannot create object: admission webhook "vrollout.kb.io" denied the request: Spec.ObjectRef.WorkloadRef: Invalid value: v1alpha1.WorkloadRef{APIVersion:"helm.toolkit.fluxcd.io/v2beta1", Kind:"HelmRelease", Name:"canary-demo"}: WorkloadRef kind is not supported)]
```
 
**Expected behavior**
the canary demo can run corrently.

**KubeVela Version**
```bash
[root@xy-5-server14 canary]# vela version
CLI Version: 1.8.2
Core Version: 1.8.2
GitRevision: git-360f69be
GolangVersion: go1.19.9
```
the fluxcd version is 2.3.3 .
**Cluster information**
```bash 
[root@xy-5-server14 canary]# kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.10", GitCommit:"5c1d2d4295f9b4eb12bfbf6429fdf989f2ca8a02", GitTreeState:"clean", BuildDate:"2023-01-18T19:13:52Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
```
