### ISSUE TITLE
traitdefinition with stage=PostDispatch is being applied at component creation time instead of post health state. 

### ISSUE THREAD

**Issue by scheuk** [kubevela/kubevela#6163]
**Describe the bug**
With a trait definition with the stage stage attribute "PostDispatch" is being applied during creating of it's component.  

Error when applying the application:
```
About:

  Name:      	helloworld
  Namespace: 	default
  Created at:	2023-06-27 12:56:12 -0400 EDT
  Status:    	runningWorkflow

Workflow:

  mode: DAG-DAG
  finished: false
  Suspend: false
  Terminated: false
  Steps
  - id: e8s3bvcy3l
    name: helloworld
    type: apply-component
    phase: failed
    message: run step(provider=oam,do=component-apply): GenerateComponentManifest: evaluate trait=poxyConfig template for component=helloworld app=helloworld: failed to have the workload/trait unstructured: outputs.poxyConfig.spec.forProvider.vars.2.value: undefined field: status (and 15 more errors)
```
This is due to the status trait in the component object not being available until the controller reconciles. 

**To Reproduce**
component:
```
"gcp-cloudrun-service": {
	type:        "component"
	description: "GCP CloudRun V2Service"
	attributes: { 
		workload: {
			type: "autodetects.core.oam.dev"
		}

		status: {
			customStatus: #"""
				ready: {
					url: *"Not Ready" | string
				} & {
					if context.output.status.atProvider.status[0].url != _|_ {
							url: context.output.status.atProvider.status[0].url
					}
				}
				message: "App URL: \(ready.url)"
			"""#
			healthPolicy: #"""
				isHealth: len(context.output.status.atProvider.status) != 0 && context.output.status.atProvider.status[0].conditions[0].status=="True"
				"""#
		}
	}
}

template: {
	output: {
		apiVersion: "cloudrun.gcp.upbound.io/v1beta1"
		kind:       "Service"
		metadata: labels: {
			"foobar.com/name": context.name
		}
		spec: {
			forProvider: {
				location: "us-central1"
				template: [{
					spec: [{
						containers: [{
							image: parameter.image
						}]
					}]
				}]
				traffic: [{
					latestRevision: true
					percent: 100
				}]
			}
			providerConfigRef: {
				name: parameter.providerConfigName
			}
		}
	}

	parameter: {
		// +usage=The container Image to deploy
		image: string
		// +usage=The ProviderConfig name
		providerConfigName: *"gcp" | string
	}
}
```
trait definition
```
apigateway: {
	alias: ""
	annotations: {

	}
	attributes: {
		appliesToWorkloads: ["gcp-cloudrun-service"]
		stage: "PostDispatch"
	}
	description: "Make a Cloud Run service availible through the apigateway"
	type: "trait"
}

template: {
	parameter: {
		// +usage=Path to map on the apigee gateway
		path: string
		// +usage=Proxy template to use
		template: *"basicReverseProxy" | string
		apigee_project_id: *"prj-sche-apigee-f2ad" | string
	}
	outputs: {
		poxyConfig: {
			apiVersion: "tf.upbound.io/v1beta1"
			kind:       "Workspace"
			metadata: labels: {
				"foobar.com/name": context.name
			}
			spec: {
				forProvider: {
					module: "github.com/username/repo.git"
					source: "Remote"
					vars: [{
						key:   "component_name"
						value: context.name
					}, {
						key:   "base_path"
						value: parameter.path
					}, {
						key:   "cloudrun_url"
						value: context.output.status.atProvider.status[0].url
					}, {
						key:   "apigee_project_id"
						value: parameter.apigee_project_id
					}, {
						key:   "proxy_template"
						value: parameter.template
					}]
				}
				providerConfigRef: name: "gcp-wi"
			}
		}
		ServiceIAMMember: {
			apiVersion: "cloudrun.gcp.upbound.io/v1beta1"
			kind:       "ServiceIAMMember"
			metadata: labels: {
				"foobar.com/name": context.name
			}
			spec: {
				forProvider: {
					location: "us-central1"
					member: "serviceAccount:sa-apigee-invoker@" + parameter.apigee_project_id + ".iam.gserviceaccount.com"
					role: "roles/run.invoker"
					serviceSelector:
						matchLabels: 
							"foobar.com/name": context.name
				}
				providerConfigRef: {
					name: context.output.spec.providerConfigRef.name
				}
			}
		}
	}
}


```
Application definition:
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: helloworld
spec:
  components:
    - name: helloworld
      type: gcp-cloudrun-service
      properties:
        image: us-docker.pkg.dev/cloudrun/container/hello
        providerConfigName: google-project-id
      traits:
        - type: apigateway
          properties: 
            path: /
```

**Expected behavior**
I expect the trait ouputs{} would be rendered and applied after the the component becomes `Healthy`

**KubeVela Version**
1.9.1

**Cluster information**
GKE autopilot v1.25.8-gke.1000

**Additional context**
This works if I move the trait definition to a component and setup a dependency between the two components like this:
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: helloworld
spec:
  components:
    - name: helloworld
      type: gcp-cloudrun-service
      properties:
        image: us-docker.pkg.dev/cloudrun/container/hello
        providerConfigName: prj-sche-cloudrun-f417
      outputs:
        - name: component
          valueFrom: output.metadata.name
        - name: cloudRunUrl
          valueFrom: output.status.atProvider.status[0].url
        - name: cloudRunProjectID
          valueFrom: output.spec.providerConfigRef.name
    - name: helloworld-proxy
      type: apigeeproxy
      inputs:
        - from: component
          parameterKey: properties.component
        - from: cloudRunUrl
          parameterKey: properties.cloudrun_url
        - from: cloudRunProjectID
          parameterKey: properties.cloudrun_project_id
      properties: 
        path: /
      dependsOn: 
        - helloworld

```
