### ISSUE TITLE
[Feature] KubeVela adopt Cluster Inventory API from k8s-sig for multi-cluster  

### ISSUE THREAD

**Issue by wonderflow** [kubevela/kubevela#6205]
**Is your feature request related to a problem? Please describe.**

The community is discussing a unified [Cluster Inventory API](https://docs.google.com/document/d/1sUWbe81BTclQ4Uax3flnCoKtEWngH-JA9MyCqljJCBM/edit?pli=1) for cluser registry info. 

The spec likes below:

```
apiVersion: multicluster.x-k8s.io/v1alpha1
kind: ClusterInventory
metadata:
 name: some-cluster
spec:
 accessObjectRefs: # optional object points to the resource that declares how to access the cluster
 - group: someGroup
   resource: someResource
   name: someName
   namespace: someNamespace
   type: KUBECONFIG
 taints:
   - key: key1
     value: value1
     effect: NoSchedule
     addTime: xxx
 healthinessProbe:
   heartbeatIntervalSeconds: 60
status:
 version:
   kubernetes: 1.26.1
 resources: # total resources of a cluster
   capacity:
     cpu: 12
     memory: 12Gi
   allocatable:
     cpu: 10
     memory: 16Gi
 properties:
   - name: clusterset.k8s.io
     value: some-clusterset
 conditions:
   - type: Healthy
     status: True
     lastTransitionTime: "2023-05-08T07:58:55Z"
     message: ""
```

It‘s similar to our [virtual-cluster object](https://github.com/oam-dev/cluster-gateway/blob/master/pkg/apis/cluster/v1alpha1/virtualcluster_types.go#L68) implemented in [cluster-gateway](https://github.com/oam-dev/cluster-gateway).

When the community has a unified api, KubeVela can migrate to that unified API and benefit from that. We can easily connect with different clusters registered from different multi-cluster projects such as OCM, karmada, clusternet and fleetmanager. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
