### ISSUE TITLE
Helm Chart can't depency on another one

### ISSUE THREAD

**Issue by cyxinda** [kubevela/kubevela#6225]
**Describe the bug**
my vela yaml as follow:
```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
  name: depends
spec:
  components:
    - name: mysql
      properties:
        chart: mysql
        repoType: helm
        retries: 3
        secretRef: harbor-helm
        url: https://registry.knowdee.com/chartrepo/knowdee
      type: helm
    - name: app
      properties:
        chart: app
        repoType: helm
        retries: 3
        secretRef: harbor-helm
        url: https://registry.knowdee.com/chartrepo/knowdee
      type: helm
      dependsOn:
      - mysql
```
Then I start up the yaml :
```bash
[root@xy-5-server14 workflow]# vela up -f depence.yaml 
error: File format is illegal, only support vela appfile format or OAM Application object yaml: error converting YAML to JSON: yaml: line 3: mapping values are not allowed in this context
```
I don't know why the helm chart can't been support. Or the other problem ?
I have seen that in the vela document [https://kubevela.net/docs/end-user/workflow/component-dependency-parameter](https://kubevela.net/docs/end-user/workflow/component-dependency-parameter).
![1111](https://github.com/kubevela/kubevela/assets/7237898/5760a28b-6ed5-43c2-ba48-d99fcd26a5d1)

My kubeVela version is 1.9.3 .
