### ISSUE TITLE
Can the read-object workflow-step correctly read and decode secrets of type Opaque? 

### ISSUE THREAD

**Issue by flysqrlboy** [kubevela/kubevela#6231]
When using kubevela to apply Terraform cloud resources, the returned values are saved in the secret specified by **`writeConnectionSecretToRef`**.
**My question is**: when using the read-object step in a workflow to read the values from this secret, can outputs and inputs properly decode secrets of type Opaque?
The following YAML is an example of applying two cloud resources. The second resource needs to retrieve the returned value id from the first resource, which is saved in a secret.

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: xxxx
spec:
  components:
    - name: abc 
      type: alibaba-abc
      properties:
        is_internal: true
        providerRef:
          name: abc-provider
          namespace: default
        writeConnectionSecretToRef:
          name: output-abc
    - name: hello
      type: alibaba-zzzz
      properties:
        providerRef:
          name: abc-provider
          namespace: default
        writeConnectionSecretToRef:
          name: output-zzz
  workflow:
    steps:
      - name: deploy-abc
        type: apply-component
        properties:
          component: abc
      - name: read-output-abc
        type: read-object
        dependsOn:
          - deploy-abc
        outputs:
          - name: id-of-output-abc
            valueFrom: output.value.data.id
        properties:
          apiVersion: v1
          kind: Secret
          name: output-abc
          cluster: local
      - name: deploy-hello
        type: apply-component
        dependsOn:
          - read-output-abc
        properties:
          component: hello
        inputs:
          - from: id-of-output-abc
            parameterKey: properties.id
```
**KubeVela Version**
CLI Version: 1.8.2
Core Version: 1.8.2
GitRevision: git-360f69be
GolangVersion: go1.19.9

**Cluster information**

**Additional context**

**Comment by FogDong** [comment]
You can checkout this example:

```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: read-secret
  namespace: default
spec:
  components: []
  workflow:
    steps:
      - name: apply-secret
        type: apply-object
        properties:
          value:
            apiVersion: v1
            kind: Secret
            metadata:
              name: my-secret
            stringData:
              hello: world
      - name: read-secret
        type: read-object
        properties:
          apiVersion: v1
          kind: Secret
          name: my-secret
        outputs:
          - name: hello-secret-raw
            valueFrom: output.value.data["hello"]
          - name: hello-secret-decode
            valueFrom: |
              import "encoding/base64"
              base64.Decode(null, output.value.data["hello"])
          - name: secret-name
            valueFrom: output.value.metadata.name
      - name: apply-cm
        type: apply-object
        inputs:
          - from: hello-secret-raw
            parameterKey: value.data.raw
          - from: hello-secret-decode
            parameterKey: value.data.decode
          - from: secret-name
            parameterKey: value.metadata.name
        properties:
          value:
            apiVersion: v1
            kind: ConfigMap
            metadata:
              name: placehoder
            data:
              additional: hi
```
