### ISSUE TITLE
kubeVela cannot auto trigger gitops with my-git-repository

### ISSUE THREAD

**Issue by cyxinda** [kubevela/kubevela#6233]
**Describe the bug**
I run the demo by the kubevela document [https://kubevela.net/zh/docs/end-user/gitops/fluxcd](https://kubevela.net/zh/docs/end-user/gitops/fluxcd).
I change the repo url only like this:
```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: infra-gitops
spec:
  components:
  - name: database-config
    type: kustomize
    properties:
      repoType: git
      # 将此处替换成你需要监听的 git 配置仓库地址
      url: https://github.com/cyxinda/gitops.git
      # 如果是私有仓库，还需要关联 git secret
      # secretRef: git-secret
      # 自动拉取配置的时间间隔，由于基础设施的变动性较小，此处设置为十分钟
      pullInterval: 1m
      git:
        # 监听变动的分支
        branch: infra
      # 监听变动的路径，指向仓库中 infrastructure 目录下的文件
      path: ./infrastructure
```
The only difference with the official document is the url address,as follow:
![1111](https://github.com/kubevela/kubevela/assets/7237898/3faa3cf6-a7e7-478e-9289-037b1659e020)

I start up the infra-gitops above and there are no actions about gitops.
![2222](https://github.com/kubevela/kubevela/assets/7237898/ae7e3c72-be3e-47b3-9f57-8d54d52b2861)

If I change the gitrepo url to `https://github.com/FogDong/KubeVela-GitOps-Infra-Demo` ,it  triggers the gitops process correctly.
![3333](https://github.com/kubevela/kubevela/assets/7237898/9dfbd7cc-b17d-4fe3-a9d6-543c5343185c)

During the whole journey, I can't see any log whether kubeVela  pulled /compare the  yaml statement on the git repository and reconciliation .It  is not a good experience to use kubeVela gitOps.

 

**KubeVela Version**
1.9.3

**Cluster information**
1.24.10
