### ISSUE TITLE
Kubevela not updating Kubernetes objects

### ISSUE THREAD

**Issue by ce0la** [kubevela/kubevela#6249]
**Describe the bug**

The bug observed is in two parts:
**Part one:**
Changes done to a helm chart for postgres in my Github repo reflects in the kubevela application (`/Application/my_env/my_app` auto sync is active i.e. label: `app.oam.dev/source-of-truth=from-k8s-resource`), but does not get deployed to my Kubernetes cluster (`/local/postgresql/my_env/my_app`). Using the deploy button in Kubevela to propagate the change works just the first time. Currently, no further updates can be done to the postgres pods even when the Deploy button is hit again. 

TL;DR: Updates made to the Git repo helm chart always show up in the kubevela application, but does not get deployed to the cluster.

**Part two:**
The pods did not get automatically rescheduled after hitting deploy the first time (from Part one above) and I had to delete the pods before they got rescheduled with the new changes.

**To Reproduce**

1. Setup a GitHub repo and make a helm chart with the template below in it:
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: run-database
  namespace: run-staging
  annotations:
    app.oam.dev/publishVersion: {{ .Chart.AppVersion }}
    "helm.sh/resource-policy": keep
spec:
  components:
    - type: "postgres-cluster"
      name: run-database
      properties:
        replicas: 3
        volume:
          size: "500Gi"
        resources:
          requests:
            cpu: "4000m"
            memory: "16Gi"
          limits:
            cpu: "4000m"
            memory: "24Gi"
        postgresql:
          parameters:
            max_connections: "1000"
            superuser_reserved_connections: "5"
            huge_pages: "try"
            max_wal_size: "6GB"
            max_locks_per_transaction: "256"
            max_pred_locks_per_transaction: "256"
            shared_buffers: "2GB"
            wal_buffers: "256MB"
            work_mem: "32MB"
            maintenance_work_mem: "512MB"
        ports:
          - expose: true
            port: 5432
            protocol: TCP
        preparedDatabases:
          {{- range $index, $network := .Values.networks }}
          sync_{{ $network }}:
            defaultUsers: true

          {{- end }}
      traits:
        - type: annotations
          properties:
            "helm.sh/resource-policy": keep
```
2.  Deploy it as a Kubevela application with autosync active i.e. label: `app.oam.dev/source-of-truth=from-k8s-resource` should be present on it.
3. Update the memory and cpu requests/limits in the template from step 1 above. 
**Expected behavior**

The Postgres database cluster should get deployed and its pods automatically rescheduled with the new memory and cpu requests/limits specification.

**KubeVela Version**
```
CLI Version: UNKNOWN
Core Version: 1.8.0
GitRevision: UNKNOWN
GolangVersion: go1.19.6
```

**Cluster information**

AWS EKS
Kubernetes version 1.23
