### ISSUE TITLE
Can't share terraform resource between Applications

### ISSUE THREAD

**Issue by imzhangsiwei** [kubevela/kubevela#6260]
**Describe the bug**

**Background:**
Two applications intend to utilize the same Terraform resource, like a VPC. If one application is removed, the VPC it uses should not be deleted, because another application is still utilizing this VPC.
I attempted to use the **shared-resources** policy, but it didn't work.

**To Reproduce**

I used the following two applications,  when app1 deploying seccessfully, the vpc1 will be created。And then, app2 is also successfully deployed, using vpc1 instead of creating a new VPC. So ，the two applications use the same vpc（vpc1）。

-  Application1

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: app1
spec:
  components:
    - name: vpc1
      type: alibaba-vpc
      properties:
        vpc_cidr: 172.16.0.0/12
        vpc_name: myvpc_xxxx
        providerRef:
          name: terraform-alibaba-provider-auth
        writeConnectionSecretToRef:
          name: outputs-vpc1
        backend:
          backendType: kubernetes
          kubernetes:
            secret_suffix: 'myvpc'
            namespace: 'default'
  policies:
    - name: shared-resource
      type: shared-resource
      properties:
        rules:
          - selector:
              componentTypes: ["alibaba-vpc"]
```

- Application2

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: app2
spec:
  components:
    - name: vpc2
      type: alibaba-vpc
      properties:
        vpc_cidr: 172.16.0.0/12
        vpc_name: myvpc_xxxx
        providerRef:
          name: terraform-alibaba-provider-auth
        writeConnectionSecretToRef:
          name: outputs-vpc2
        backend:
          backendType: kubernetes
          kubernetes:
            secret_suffix: 'myvpc'
            namespace: 'default'
  policies:
    - name: shared-resource
      type: shared-resource
      properties:
        rules:
          - selector:
              componentTypes: ["alibaba-vpc"]
```

But，when I delete the app1，the vpc1 is also deleted！

I understand that part of the reason is because the Configuration resources `(configurations.terraform.core.oam.dev)` generated by the component with type "alibaba-vpc" directly use the component's name. Due to the uniqueness of component names, these two Configuration resources have different names, making them distinct resources. As a result, sharing cannot be achieved.

So, any advice on how to share Terraform resources would be greatly appreciated and helpful to me. Thank you!

**Expected behavior**

**Screenshots**

**KubeVela Version**

CLI Version: 1.8.0
Core Version: 1.8.0
GitRevision: git-fcd721ff
GolangVersion: go1.19.8

**Cluster information**

**Additional context**
