### ISSUE TITLE
Suggestion: When deleting an application that includes Terraform-type components, if deleteResource is specified as false, the corresponding tfstate secret should not be deleted.

### ISSUE THREAD

**Issue by imzhangsiwei** [kubevela/kubevela#6339]
**Describe the bug**

**Background**
Two applications, such as application1 and application2, intend to utilize the same Terraform resource, like a VPC. If one application is removed, the VPC it uses should not be deleted, because another application is still utilizing this VPC.

I took some time to investigate, and I found that terraform-type components do have a field called **deleteResource**. When I set deleteResource to **false**, the cloud resources(in this case, VPC) are indeed retained when deleting the application(such as application1).

But when I redeploy application1 or application2 with the same configuration, I expect that this application will continue to use the undeleted cloud resources (in this case, the VPC). Unfortunately, what happens is that this redeployment creates a new VPC.

After doing some debugging, I've discovered that when deleteResource is set to false, even though it doesn't delete the cloud resources, it still deletes the k8s secret that stores the Terraform tfstate. Once this secret is deleted, KubeVela can no longer obtain the status information of remote cloud resources. This results in the creation of new cloud resources instead of reusing existing ones when redeploying the same application.

It may make sense to add the following check for this use case: if deleteResource is set to false, then do not delete the tfstate in k8s or s3.

I can submit a pull request If this check sounds reasonable.  @chivalryq @FogDong 

**To Reproduce**

I used the following two applications, when app1 is deployed successfully, the vpc1 will be created. And then, app2 is also successfully deployed, using vpc1 instead of creating a new VPC. Because they use the same backend . So the two applications use the same vpc（vpc1）。

1. deploy application1 and application2

- application1
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: app1
spec:
  components:
    - name: vpc1
      type: alibaba-vpc
      properties:
        vpc_cidr: 172.16.0.0/12
        vpc_name: myvpc_xxxx
        providerRef:
          name: terraform-alibaba-provider-auth
        writeConnectionSecretToRef:
          name: outputs-vpc1
       deleteResource: false
        backend:
          backendType: kubernetes
          kubernetes:
            secret_suffix: 'myvpc'
            namespace: 'default'
```

- application2

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: app2
spec:
  components:
    - name: vpc2
      type: alibaba-vpc
      properties:
        vpc_cidr: 172.16.0.0/12
        vpc_name: myvpc_xxxx
        providerRef:
          name: terraform-alibaba-provider-auth
        writeConnectionSecretToRef:
          name: outputs-vpc2
        deleteResource: false
        backend:
          backendType: kubernetes
          kubernetes:
            secret_suffix: 'myvpc'
            namespace: 'default'
```
2. delete application1 (the vpc will be retained )
3. redeploy application1 or application2 (but create a new vpc unexpectedly)

**Expected behavior**

**Screenshots**

**KubeVela Version**
Core Version: 1.8.0, master

**Terraform Controller Version**

**Version**: v0.7.2, master

**Cluster information**

**Additional context**

**Comment by FogDong** [comment]
Have you tried the GC policy for Application to never GC the component?
https://github.com/kubevela/kubevela/blob/master/docs/examples/app-with-policy/gc-policy/persist-resources.md#componentnames
https://kubevela.io/docs/end-user/policies/gc/#persist-partial-resources

**Comment by imzhangsiwei** [comment]
> Have you tried the GC policy for Application to never GC the component? https://github.com/kubevela/kubevela/blob/master/docs/examples/app-with-policy/gc-policy/persist-resources.md#componentnames https://kubevela.io/docs/end-user/policies/gc/#persist-partial-resources

I had previously tried the GC policy. While **strategy=never** can indeed retain cloud resources after deleting an application, it led to issues when redeploying the same application with the same configuration, which is a common scenario. It would fail with an error indicating the existence of a Configuration resource with the same name, and this Configuration resource was not managed by any application at that time. This is unacceptable.

The error messages are as follows:

```
Workflow:

  mode: DAG-DAG
  finished: false
  Suspend: false
  Terminated: false
  Steps
  - id: g5mwo18iuq
    name: vpc7
    type: apply-component
    phase: failed
    message: run step(provider=oam,do=component-apply): Dispatch: pre-dispatch dryrun failed: Found 1 errors. [(cannot apply ApplyOption: Configuration default/vpc7 exists but not managed by any application now)]
```

**Comment by chivalryq** [comment]
Try compose application with take-over policy: https://kubevela.io/docs/end-user/policies/resource-adoption/#takeover-policy

**Comment by imzhangsiwei** [comment]
> Try compose application with take-over policy: https://kubevela.io/docs/end-user/policies/resource-adoption/#takeover-policy

The Take-over policy does indeed allow for the re-management of configuration resources. But to use Take-over successfully, configuration resources must exist beforehand. If they don't exist, attempting to use Take-over can result in errors. This requires users to determine whether a configuration exists before deploying an application.

My point is that this practice can be overly complex.  We should offer a more user-friendly way of using it.

**Comment by chivalryq** [comment]
>  If they don't exist, attempting to use Take-over can result in errors.

What error is that? If take-over a non-existing resource, it will just apply the resource If I remember it right. 

Here's an example

```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: take-over
spec:
  components:
    - name: nginx-take-over
      type: k8s-objects
      properties:
        objects:
          - apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: nginx
            spec:
              selector:
                matchLabels:
                  app: nginx
              template:
                metadata:
                  labels:
                    app: nginx
                spec:
                  containers:
                  - name: nginx
                    image: nginx:1.14.2
                    ports:
                    - containerPort: 80 
      traits:
        - type: scaler
          properties:
            replicas: 1
  policies:
    - type: take-over
      name: take-over
      properties:
        rules:
          - selector:
              resourceTypes: ["Deployment"]
```

**Comment by imzhangsiwei** [comment]
> > If they don't exist, attempting to use Take-over can result in errors.
> 
> What error is that? If take-over a non-existing resource, it will just apply the resource If I remember it right.
> 
> Here's an example
> 
> ```yaml
> apiVersion: core.oam.dev/v1beta1
> kind: Application
> metadata:
>   name: take-over
> spec:
>   components:
>     - name: nginx-take-over
>       type: k8s-objects
>       properties:
>         objects:
>           - apiVersion: apps/v1
>             kind: Deployment
>             metadata:
>               name: nginx
>             spec:
>               selector:
>                 matchLabels:
>                   app: nginx
>               template:
>                 metadata:
>                   labels:
>                     app: nginx
>                 spec:
>                   containers:
>                   - name: nginx
>                     image: nginx:1.14.2
>                     ports:
>                     - containerPort: 80 
>       traits:
>         - type: scaler
>           properties:
>             replicas: 1
>   policies:
>     - type: take-over
>       name: take-over
>       properties:
>         rules:
>           - selector:
>               resourceTypes: ["Deployment"]
> ```

You are right. There is no error when taking over a non-existent resource, I just made some mistakes in my previous attempts.
And this is my yaml, it's work : 

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: app1
spec:
  components:
    - name: vpc1
      type: alibaba-vpc
      properties:
        vpc_cidr: 172.16.0.0/12
        vpc_name: myvpc_xxxx
        providerRef:
          name: terraform-alibaba-provider-auth
        writeConnectionSecretToRef:
          name: outputs-vpc1
        backend:
          backendType: kubernetes
          kubernetes:
            secret_suffix: 'myvpc'
            namespace: 'default'
  policies:
    - name: garbage-collect
      type: garbage-collect
      properties:
        rules:
          - selector:
              componentTypes: ["alibaba-vpc"]
            strategy: never
    - name: take-over
      type: take-over
      properties:
        rules:
          - selector:
              resourceTypes: ["Configuration"]
```
