### ISSUE TITLE
The distributed-config for helm repository was automatically deleted for no reason.

### ISSUE THREAD

**Issue by knowdee** [kubevela/kubevela#6383]
**Describe the bug**
I use gitops to deploy some application.
I found that the distributed secret for the helm repository will be deleted after about 24 hours.
I distribute the config by the command `vela config distribute knowdee-charts -t $namespace`.
The secret`knowdee-charts` is the secret  for the helm repository of https://registry.knowdee.com/chartrepo/charts.
My listener is as fallow:
```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name:  elasticsearch-listener
  namespace: midware
spec:
  components:
    - name: elasticsearch-secret
      type: k8s-objects
      properties:
        objects:
        - apiVersion: v1
          kind: Secret
          metadata:
            name: elasticsearch-secret
          type: kubernetes.io/basic-auth
          stringData:
            username: root
            password: xxxxx
    - name: elasticsearch-listener
      type: kustomize
      #type: webservice
      properties:
        repoType: git
        # 将此处替换成你需要监听的 git 配置仓库地址
        url:  https://repository.knowdee.com/midware/elasticsearch.git
        # 如果是私有仓库，还需要关联 git secret
        secretRef: elasticsearch-secret
        # 自动拉取配置的时间间隔，由于基础设施的变动性较小，此处设置为十分钟
        pullInterval: 1m
        git:
          # 监听变动的分支
          branch: main
        # 监听变动的路径，指向仓库中 infrastructure 目录下的文件
        path: ./environments
  workflow:
    steps:
      - name: deploy-elasticsearch-secret
        type: apply-component
        properties:
          component: elasticsearch-secret
      - name: deploy-elasticsearch-listener
        type: apply-component
        properties:
          component: elasticsearch-listener
        dependsOn:
          - deploy-elasticsearch-secret

```
My Application yaml is :
```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: elasticsearch
  namespace: examples ## 这个需要跟前面初始化的env保持一致
spec:
  components:
    - name: elasticsearch
      type: helm
      properties:
        chart: eck-stack
        version: 0.7.0 # 部署的版本
        repoType: helm
        retries: 3
        secretRef: knowdee-charts # 下载helm chart的密码配置（secret）
        url: https://registry.knowdee.com/chartrepo/charts
        values:
          eck-elasticsearch:
            host: ela333.knowdee.com
```
I deploy the application normally .And like this:
![截图 2023-10-26 18-00-33](https://github.com/kubevela/kubevela/assets/139095591/92700a0e-f131-4449-9c78-adb8d7e417c9)
All of the things is normally .
But after about 24 hours ,the secret `knowdee-charts` will be deleted for unknown reasons.
It is like this:
![截图 2023-10-26 18-03-39](https://github.com/kubevela/kubevela/assets/139095591/c438331e-f42c-4a80-8498-9e8f1d5ddec8)
I don't know why this case will happen .I think it's a bug ?

**Expected behavior**
the secret `knowdee-charts` will not be automatically deleted.
 

**KubeVela Version**
```bash
[root@midware-0 /]# vela version
CLI Version: 1.9.6
Core Version: 1.9.6
GitRevision: git-9c57c098
GolangVersion: go1.19.12
```

**Cluster information**
 kubernetes version :v1.24.16
