### ISSUE TITLE
[Feature] Support user defined context in vela core

### ISSUE THREAD

**Issue by oanasc** [kubevela/kubevela#6391]
**Is your feature request related to a problem? Please describe.**

Looking for a way to inject additional parameters in the `context` because those are available throughout an application template would simplify greatly the deployment process.

How we intend to deploy: 
- Will use CI triggers
- The CI has it's own environment variables that will be able to pass in the context without having to know too much of how or where they are used in the templates. It is generic and therefore doesn't have to change, changing is painful because it means we got to release new versions of a client side tool which can be used in hundreds of repos.
- `vela up` to deploy
- The cue templates can simply use the custom context variables and update anything that's changed
It means we can integrate vela with the ci without too much layers in between, or so I hope (still early days running vela in a POC).

**Describe the solution you'd like**
Vela core support for custom context similar to how is implemented on [WorflowRun](https://kubevela.io/docs/end-user/pipeline/workflowrun/#custom-context-data) 

**Describe alternatives you've considered**
Perhaps use a similar concept with configmaps, some discussion [here](https://github.com/kubevela/kubevela/discussions/6384#discussioncomment-7435555)

**Additional context**

**Comment by FogDong** [comment]
So for an application with context, it will be like:
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: test
  namespace: default
spec:
  components:
  - name: express-server
    type: webservice
    properties:
      image: oamdev/hello-world
      ports:
        - port: 8000
  workflow:
    context:
       myName: "my-comp"
    steps:
      - name: apply-comp
        type: apply-component
        properties:
          component: express-server
```

And if in the definition we have cue template like: 
```
name: context.myName
```

Then when the application is deployed, the name will be `my-comp`.

I'd like to discuss more about where we should put this context field. If we put the context in parallel with the component it will make more sense. However, this will also change the model of OAM so we'll probably need more discussion.

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: test
  namespace: default
spec:
  components:
  - name: express-server
    type: webservice
    properties:
      image: oamdev/hello-world
      ports:
        - port: 8000
  context:
    myName: "my-comp"
  workflow:
    steps:
      - name: apply-comp
        type: apply-component
        properties:
          component: express-server
```

**Comment by testinfected** [comment]
We need something similar to pass additional runtime information to the workflow steps. It is possible in standalone workflow runs but not in Applications, which is a shame, since we cannot refer to existing workflow templates which expect context parameters.

It would be a great addition if we could define runtime context information for the workflow steps, the same way we can do it with workflow runs.

Thanks

**Comment by FogDong** [comment]
Hi @testinfected 
According to your description, the capability you want is to use the `context` in workflow steps but not trait and component, right?
If so, we can add the `context` field inside the workflow but not the whole application like:
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: test
  namespace: default
spec:
  components:
  - name: express-server
    type: webservice
    properties:
      image: oamdev/hello-world
      ports:
        - port: 8000
  workflow:
    context:
       myName: "my-comp"
    steps:
      - name: apply-comp
        type: apply-component
        properties:
          component: express-server
```

**Comment by testinfected** [comment]
Hi @FogDong yes this is correct. 

One use case is using an external workflow template. It's possible to add context parameters in workflow runs, but not applications. 

Thanks

**Comment by FogDong** [comment]
I think it's a valuable feature for Application and I'm good with supporting it.
If other maintainers also like this idea then I'll start working on this.
cc @wonderflow @StevenLeiZhang

**Comment by oanasc** [comment]
For us would be beneficial to be able to use the user context in the applications and traits like in your first [example](https://github.com/kubevela/kubevela/issues/6391#issuecomment-1804050004) 
If you add it just to workflow steps will is still be available to use in the application cue templates?

**Comment by FogDong** [comment]
> For us would be beneficial to be able to use the user context in the applications and traits like in your first [example](https://github.com/kubevela/kubevela/issues/6391#issuecomment-1804050004) If you add it just to workflow steps will is still be available to use in the application cue templates?

If we want this context to be used in the whole Application, then we may need to re-struct the Application template to add `context` field, which might influence the OAM model and need more discussion.

**Comment by oanasc** [comment]
Having it at a application OAM level would work

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: test
  namespace: default
spec:
  components:
  - name: express-server
    type: webservice
    properties:
      image: oamdev/hello-world
      ports:
        - port: 8000
  context:
    myName: "my-comp"
  workflow:
    steps:
      - name: apply-comp
        type: apply-component
        properties:
          component: express-server
```
