### ISSUE TITLE
vela built-in trait "startup-probe" bug

### ISSUE THREAD

**Issue by codeReaper2001** [kubevela/kubevela#6393]
**Describe the bug**

startup-probe这个运维特征的cue文件编写有bug：出现了未出现的变量，当使用startup-probe运维特征且使用tcpSocket字段时会报错：
![image](https://github.com/kubevela/kubevela/assets/74849229/f2d38640-45f3-4218-9527-678c2859e092)

**To Reproduce**

trait使用：
```yaml
    traits:
    - type: startup-probe
      properties:
        initialDelaySeconds: 5
        periodSeconds: 10
        tcpSocket:
          port: "18004"
```

运行命令：
vela dry-run -f app.yaml > app_raw.yaml

运行结果：
Error: validate application: access_test.yaml by dry-run: admission webhook "validating.core.oam.dev.v1beta1.applications" denied the request: field "schematic": Invalid value error encountered, cannot evaluate trait "startup-probe": invalid template of trait startup-probe after merge with parameter and context: patch.spec.template.spec.containers.0._params.tcpSocket: undefined field: grtcpSocketpc (and 32 more errors). 

**Expected behavior**

正常生成k8s资源文件

**Screenshots**

**KubeVela Version**

1.9.6

**Cluster information**

1.25.11

**Additional context**
