### ISSUE TITLE
MultiCluster components deployment stuck on waiting for dependents

### ISSUE THREAD

**Issue by javijvj** [kubevela/kubevela#6410]
**Describe the bug**

When I create an application with two components which each one expect to be deployed on different clusters. The `dependsOn` and `inputs and outputs` cause to the workflow to be stuck on `<component> is waiting dependents`

**To Reproduce**

1. The YAML file of Application I applied.
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: example-app
  namespace: default
spec:
  components:
    - name: hello-world-server
      type: webservice
      outputs:
        - name: message
          valueFrom: output.status.conditions[0].message
      properties:
        image: oamdev/hello-world
        port: 8000
      traits:
        - type: scaler
          properties:
            replicas: 1
    - name: configmap
      type: raw
      inputs:
        - from: message
          parameterKey: data.msg
      dependsOn:
      - hello-world-server
      properties:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: deployment-msg
  policies:
    - name: debug
      type: debug
    - name: cluster1
      properties:
        clusters: [ "local"]
      type: topology
    - name: cluster2
      properties:
        clusters: [ "cluster-2"]
      type: topology
    - name: override-cm
      properties:
        selector:
        - configmap
      type: override
    - name: override-info
      properties:
        selector:
        - hello-world-server
      type: override
  workflow:
    steps:
    - name: deploy-info
      type: deploy
      properties:
        policies: [debug, override-info, cluster1]
    - name: deploy-cm
      type: deploy
      properties:
        policies: [debug,  override-cm, cluster2]
```
2. Error:
```

  Name:         example-app                  
  Namespace:    default                      
  Created at:   2023-11-27 17:11:42 -0400 AST
  Status:       runningWorkflow              

Workflow:

  mode: StepByStep-DAG
  finished: false
  Suspend: false
  Terminated: false
  Steps
  - id: m6fgp5uzgb
    name: deploy-info
    type: deploy
    phase: succeeded 
  - id: ccraanyv93
    name: deploy-cm
    type: deploy
    phase: running 
    message: local///configmap is waiting dependents

Services:

  - Name: hello-world-server  
    Cluster: local  Namespace: default
    Type: webservice
    Healthy Ready:1/1
    Traits:
      ✅ scaler
```

**Expected behavior**

- All components should be deployed
- The configmap `deployment-msg` should exists only on cluster2 and it should have as data the status condition message of the first component.

**Error**
The `deploy-cm` step stuck on running for hours and never finish
![image](https://github.com/kubevela/kubevela/assets/90943990/14fff4de-366c-4f2b-9188-797d05a7de34)

**KubeVela Version**

```CLI Version: 1.9.7
Core Version: 1.9.7
GitRevision: git-b036624e
GolangVersion: go1.19.13```

**Cluster information**
```
clientVersion:
  buildDate: "2019-12-07T21:20:10Z"
  compiler: gc
  gitCommit: 70132b0f130acc0bed193d9ba59dd186f0e634cf
  gitTreeState: clean
  gitVersion: v1.17.0
  goVersion: go1.13.4
  major: "1"
  minor: "17"
  platform: darwin/amd64
serverVersion:
  buildDate: "2023-10-20T23:22:38Z"
  compiler: gc
  gitCommit: 9587e521d190ecb7ce201993ceea41955ed4a556
  gitTreeState: clean
  gitVersion: v1.25.15-eks-4f4795d
  goVersion: go1.20.10
  major: "1"
  minor: 25+
  platform: linux/amd64
```

**Additional context**
Im goal of this it to be able to deploy a component in a cluster, get some values after the resource is deployed and the send those values as input on the second component that will be deployed in other cluster.
