### ISSUE TITLE
after enabling sharding, the application cannot be updated normally.

### ISSUE THREAD

**Issue by zxbyoyoyo** [kubevela/kubevela#6433]
**Describe the bug**

**To Reproduce**
1. make a test application
```
cat <<EOF | kubectl apply -f -
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: app-normal
spec:
  components:
    - name: comp-normal
      type: webservice
      properties:
        image: nginx
  policies:
    - name: topology
      type: topology
      properties:
        clusters: ["local"]
EOF
```
2. switch on Controller sharding
```
vela install  -v 1.9.5 --set sharding.enabled=true
vela addon enable vela-core-shard-manager nShards=2
```
3. update the test application
```
cat <<EOF | kubectl apply -f -
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: app-normal
spec:
  components:
    - name: comp-normal
      type: webservice
      properties:
        image: nginx
  policies:
    - name: topology
      type: topology
      properties:
        clusters: ["local"]
EOF
```
What happens: When the application mutating webhook updates, if it finds that the application does not have a shard-id, it will assign one randomly. But it doesn't add the shard-id to the related apprev and rt resources. Because of this, the slave controller will report that it can't find the apprevision resource when it is processing the application.

How to solve: We can try to adjust the application mutating webhook logic to make it also add a shard-id to the application, apprev, rt and other related resources. But in the test, we found that the master controller will get the apprev, rt data from the cache (at this point, there is no apprev, rt data in the cache. Once the sharding is activated, the master controller will only cache resources with the shard-id: master label).

**Expected behavior**

**Screenshots**

![image](https://github.com/kubevela/kubevela/assets/20168048/2e314ecd-bfce-4885-a661-7a97db16ff25)

**KubeVela Version**
v 1.9.5

**Cluster information**

**Additional context**
