### ISSUE TITLE
[Feature] Support for ephemeral environment deployments

### ISSUE THREAD

**Issue by oanasc** [kubevela/kubevela#6458]
**Is your feature request related to a problem? Please describe.**

From every git branch we deploy an ephemeral environment in our develop k8s cluster. The application name and components require an additional suffix appended in the name in order to deploy several versions of the same application with a unique name and not clash with one another.
 

**Describe the solution you'd like**

1. A possible solution could involve allowing a new variable `nameSuffix` in the metadata which if present will be automatically appended to all the component, traits, workflows, policy names and to the context.name and context.appName

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: webwithsa
  nameSuffix: mybranch
  namespace: vela-dev
spec:{}
```

2. Another option is to implement the same nameSuffix but instead of auto appending it to the component, trait, policy, workflow names to allow for templating in the application.yaml so we can 
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: webwithsa
  nameSuffix: mybranch
  namespace: vela-dev
spec:
  components:
    - name: component1 context.mybranch
      type: webservice
      properties:
        image: oamdev/hello-world
        ports:
          - port: 8001
            expose: true
```

**Describe alternatives you've considered**
I tested the sub app model where a app yaml is defined as a component, and although that could work it creates an additional application that is confusing for end users

**Additional context**
