### ISSUE TITLE
Passing data from component to trait

### ISSUE THREAD

**Issue by raphdom** [kubevela/kubevela#6484]
**Describe the bug**
I am using kubevela to wrap my Crossplane Compositions in order to give a better experience to the developers to define Applications. But I have many dependencies inside the compositions.
I need to read a component status parameter from the trait, after the component has been created:

**To Reproduce**
```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: restapi
  namespace: playground-dev
spec:
  components:
    - name: restapi
      type: aws-apigateway-restapi
      traits:
        - type: aws-restapi-method
          properties:
            name: process-request
            component: processing-request-lambda
```

```cue
"aws-apigateway-restapi": {
    attributes: workload: definition: {
        apiVersion: "aws.example.eu/v1alpha1"
        kind:       "AwsApiGatewayRestApiClaim"
    }
    description: "ApiGateway RestAPI Using Crossplane"
    type: "component"
}

template: {
    import ("strings")
    output: {
        spec: {
            name: context.name
	    project: strings.Split(context.namespace,"-")[0]
	    environment: strings.Split(context.namespace,"-")[1]
        }
        apiVersion: "aws.example.eu/v1alpha1"
	kind:       "AwsApiGatewayRestApiClaim"
    }
}
```

This crossplane composition has an output value from the status of the provider, it is the rootResourceId

```yaml
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.rootResourceId
          toFieldPath: spec.rootResourceId
```

I need to inject this in the trait to create the method in AWS

```cue
"aws-restapi-method": {
	attributes: {
		appliesToWorkloads: ["aws-apigateway-restapi"]
	}
	description: "RestAPI Method"
	type: "trait"
}

template: {
  outputs: method: {
    apiVersion: "aws.example.eu/v1alpha1"
    kind:       "AwsApiGatewayRestApiMethodClaim"
    spec: {
      name: context.name
      project: context.output.spec.project
      environment: context.output.spec.environment
      restApiName: context.output.spec.name
      lambdaFunctionName: parameter.component
      rootResourceId: context.output.rootResourceId <-- HERE IS NOT WORKING
    }
  }
  parameter: {
    component: string
  }
}
```
