### ISSUE TITLE
[Feature] Allow specifying cloud credentials for Crossplane integration via a secret

### ISSUE THREAD

**Issue by shashankram** [kubevela/kubevela#6488]
As per https://kubevela.io/docs/next/end-user/components/cloud-services/provision-cloud-resources-by-crossplane/, the AWS access credentials are inlined in the spec:
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: aws
  namespace: vela-system
spec:
  components:
    - name: aws
      type: crossplane-aws
      properties:
        name: aws
        AWS_ACCESS_KEY_ID: xxx
        AWS_SECRET_ACCESS_KEY: yyy
```

This is not usable since the credentials are exposed in plaintext on the resource spec. At the very least, this should be specified via a k8s secret on which RBAC can be enforced.
