### ISSUE TITLE
Components are not updated if under a garbage-collector policy strategy: never

### ISSUE THREAD

**Issue by fboismenu** [kubevela/kubevela#6591]
**Describe the bug**
Having an application with a component which is the target of a Policy `garbage-collector` with a strategy never,
this component updates are silently ignored.

**To Reproduce**

1. Deploy such kind of application:

```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: my-operator
spec:
  components:
    - name: crds
      type: k8s-objects
      properties:
        objects:
          - apiVersion: v1
            kind: ConfigMap
            metadata:
              name: my-map
            data:
              beurre: "yes"
  policies:
    - name: pas de pitie pour les croissants
      type: garbage-collect
      properties:
        rules:
          - selector:
              componentNames:
                - crds
            strategy: never
```

2. wait for the deployment to be completed and verify content of the ConfigMap
3. update the configMap by adding some data to it, e.g. 
```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: my-operator
spec:
  components:
    - name: crds
      type: k8s-objects
      properties:
        objects:
          - apiVersion: v1
            kind: ConfigMap
            metadata:
              name: my-map
            data:
              beurre: "yes"
              chocolate: "yes" # <- this was added 
  policies:
    - name: pas de pitie pour les croissants
      type: garbage-collect
      properties:
        rules:
          - selector:
              componentNames:
                - crds
            strategy: never
```
 4. `vela up` again with updated Application
 5. wait for workflow to complete
 6. k get cm my-map -o yaml will return exactly the same content than in step 2.

**Expected behavior**

I should be able to successfully update my component with a policy garbage-collect strategy: never on it

**KubeVela Version**

v1.9.9

**Cluster information**

Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:15:38Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by PushparajShetty** [comment]
Hi @fboismenu
The never strategy in the garbage-collector policy works as expected — it prevents the component from being updated by the application. 

If you want the component to be updated by the application and still persist after deleting the application, use `strategy: onAppUpdate `(default) with `propagation: orphan` as shown below.
```

apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: my-operator
spec:
  components:
    - name: crds
      type: k8s-objects
      properties:
        objects:
          - apiVersion: v1
            kind: ConfigMap
            metadata:
              name: my-map
            data:
             a: b
  policies:
    - name: pas de pitie pour les croissants
      type: garbage-collect
      properties:
        rules:
          - selector:
              componentNames:
                - crds
            propagation: orphan

```

This behavior had issues in earlier versions but works fine in KubeVela v1.10.2. 
Hope this solves your issue. Thanks 

cc @VibhorChinda
