### ISSUE TITLE
wrong ports in Kubernetes manifests with Application daemon type

### ISSUE THREAD

**Issue by ks-tool** [kubevela/kubevela#6604]
**Describe the bug**
When i deploy daemon app with port definitions i get wrong containerPort value in DaemonSet and targetPort in Service

**To Reproduce**
```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: gw-nginx
spec:
  components:
    - name: nginx
      type: daemon
      properties:
        image: nginx:alpine
        ports:
          - port: 80
            name: http
            expose: true
            containerPort: 8080
```
```yaml
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  ...
spec:
  ...
    spec:
      containers:
      - image: nginx:alpine
        name: nginx
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  ...
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  ...
```

**Expected behavior**
```yaml
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  ...
spec:
  ...
    spec:
      containers:
      - image: nginx:alpine
        name: nginx
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  ...
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  ...
```

**KubeVela Version**
v1.9.11
