### ISSUE TITLE
自定义trait无法使用Http请求

### ISSUE THREAD

**Issue by regend** [kubevela/kubevela#6607]
**Describe the bug**
https://kubevela.net/zh/docs/platform-engineers/traits/customize-trait#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%BF%90%E7%BB%B4%E7%89%B9%E5%BE%81%E9%87%8C%E6%89%A7%E8%A1%8C-http-request  参考这个文章里的内容编写了一个自定义trait,内容如下

```cue
"auth-service": {
    type: "trait"
}

template: {
    parameter: {
        serviceURL: string
    }

    processing: {
        output: {
            token?: string
        }
        // The target server will return a JSON data with `token` as key.
        http: {
            method: *"GET" | string
            url:    parameter.serviceURL
            request: {
                body?: bytes
                header: {}
                trailer: {}
            }
        }
    }

    patch: {
          spec: template: spec: serviceAccountName: processing
    }
}
``` 

app内容如下
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: first-vela-app
spec:
  components:
    - name: express-server
      type: webservice
      properties:
        image: oamdev/hello-world
      traits:
        # - type: gpu-render
        #   properties:
        #     containerName: express-server
        #     method: POST
        - type: auth-service
          properties:
            serviceURL: http://localhost:8080/api/v1/render/demo
``` 
**To Reproduce**

执行vela def apply d.cue; vela dry-run -f app.yaml报错:
Error: validate application: app.yaml by dry-run: admission webhook "validating.core.oam.dev.v1beta1.applications" denied the request: field "schematic": Invalid value error encountered, cannot evaluate trait "auth-service": invalid process of trait auth-service: fail to exec http task, invalid character 'p' after top-level value. 
**Expected behavior**
运行成功并渲染出yaml

**KubeVela Version**
CLI Version: 1.8.2
Core Version: 1.8.2
GitRevision: git-360f69be
GolangVersion: go1.19.9
