### ISSUE TITLE
Component and trait healthchecks are not run after initial deploy

### ISSUE THREAD

**Issue by mkls6** [kubevela/kubevela#6639]
**Describe the bug**
As of now, it seems that it works like this:

- Deployment process runs in a workflow step
- During the process healthchecks are run to evaluate if the step succeeded or not
- When it's finished, healthchecks are actually not run anymore. So we end up with an infinitely 'Healthy' app.

**To Reproduce**
Consider this Application example:
```yaml
---
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: first-vela-app
  namespace: vela-system
spec:
  components:
    - name: express-server
      type: webservice
      properties:
        image: oamdev/hello-world
        ports:
          - port: 8000
            expose: true
        replicas: 3
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          periodSeconds: 5
          failureThreshold: 3
          initialDelaySeconds: 60
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          periodSeconds: 5
          successThreshold: 2
          initialDelaySeconds: 30
      traits:
        - type: scaler
          properties:
            replicas: 3
  policies:
    - name: target-default
      type: topology
      properties:
        clusters: ["local"]
        namespace: "default"
  workflow:
    steps:
      - name: deploy2default
        type: deploy
        properties:
          policies: ["target-default"]
```
At first it gets successfully deployed, vela status shows `Healthy Ready:3/3`, then eventually all pods go into CrashLoop. Application controller after some time reconciles the app at the moment when everything is down, but vela status still shows `Healthy Ready:3/3`.

**Expected behavior**
Application and component health state updates according to the actual status the moment of reconciliation.

**Screenshots**
```
~ $ kubectl get pods
NAME                              READY   STATUS    RESTARTS      AGE
express-server-5f7f69579d-5gshm   0/1     Running   5 (31s ago)   5m32s
express-server-5f7f69579d-7nj4q   0/1     Running   5 (31s ago)   5m32s
express-server-5f7f69579d-bkq7c   0/1     Running   5 (31s ago)   5m32s
~ $ vela status first-vela-app -n vela-system
About:

  Name:         first-vela-app
  Namespace:    vela-system
  Created at:   2024-10-14 11:54:21 +0500 +05
  Status:       running

Workflow:

  mode: StepByStep-DAG
  finished: true
  Suspend: false
  Terminated: false
  Steps
  - id: wbxjnznjze
    name: deploy2default
    type: deploy
    phase: succeeded

Services:

  - Name: express-server
    Cluster: local  Namespace: default
    Type: webservice
    Healthy Ready:3/3
    Traits:
      ✅ scaler
```

**KubeVela Version**
```
~ $ vela version
CLI Version: 1.9.13
Core Version: 1.9.13
GitRevision: git-d56da069
GolangVersion: go1.19.13
```

**Cluster information**
Tested with 1.25.16
