### ISSUE TITLE
Error when adding an external EKS cluster in KubeVela

### ISSUE THREAD

**Issue by danylos-profisea** [kubevela/kubevela#6658]
**Describe the bug**
Hello, dear KubeVela community!
I ran into a problem adding an external EKS cluster to KubeVela.

I have intentions to manage some amount of external clusters via KubeVela service. I've created couple clusters for this --> installed kubevela inside the one of them --> generated the kubeconfig to another one --> tried to join inside the cluster with kubevela --> got an error.

**To Reproduce**
1. Create two EKS clusters

The hub cluster, inside which we will install the kubevela:
```
eksctl create cluster --name cluster-a --region us-east-1
```
and external cluster, which we would try to add to the kubevela:
```
eksctl create cluster --name cluster-b --region us-east-1
```

2. Install the kubevela into the cluster-a
```
helm repo add kubevela https://kubevela.github.io/charts
helm repo update
helm install --create-namespace -n vela-system kubevela kubevela/vela-core --wait
```

3. Generate kubeconfig for cluster-b joining
```
aws eks update-kubeconfig --name cluster-b --region us-east-1 --kubeconfig ./kube.config
```

4. Join external cluster to kubevela
```
vela cluster join ./kube.config --yes
```

5. See error
```
Error: failed to ensure vela-system namespace installed in cluster test: failed to check if namespace vela-system exists: namespaces "vela-system" is forbidden: User "system:anonymous" cannot get resource "namespaces" in API group "" in the namespace "vela-system"
```

**Expected behavior**
Successful cluster joining into kubevela.

**KubeVela Version**
1.10.0-alpha.1

**Cluster information**
- Kubernetes Version: 1.31

**Additional context**
the example of generated kube.config:
```
clusters:
- cluster:
    certificate-authority-data: <certificate-authority-data>
    server: <server>
  name: cluster-b
contexts:
- context:
    cluster: cluster-b
    user: cluster-b
  name: cluster-b
current-context: cluster-b
kind: Config
preferences: {}
users:
- name: cluster-b
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-east-1
      - eks
      - get-token
      - --cluster-name
      - cluster-b
      - --output
      - json
      command: aws
```

I checked kubeconfig manually using `kubectl` - everything works correctly. The command was:
```
kubectl --kubeconfig=kube.config get namespaces
```

I would be grateful for help in solving this problem or for tips on how to properly use `vela cluster join` with external EKS clusters.

**Comment by Chaitanyareddy0702** [comment]
Hi @Danylo Profisea,  

To use a ServiceAccount token instead of the system's anonymous user, replace the `exec` field in the `users` section of your Kubeconfig with a `token` field.  

### Steps:  
1. Run the following AWS command to generate the token:  
   ```sh
   aws --region us-west-2 eks get-token --cluster-name <eks-cluster-name>
   ```
2. The output will include a `token` inside the `status` field:
   ```json
   {
       "kind": "ExecCredential",
       "apiVersion": "client.authentication.k8s.io/v1beta1",
       "spec": {},
       "status": {
           "expirationTimestamp": "2025-03-07T06:58:38Z",
           "token": "<token for connecting to the EKS cluster>"
       }
   }
   ```
3. Update your Kubeconfig file by replacing the `exec` section with the `token`:
   ```yaml
   apiVersion: v1
   clusters:
   - cluster:
       server: <api-server>
       certificate-authority-data: <certificate-authority-data>
     name: cluster-b
   contexts:
   - context:
       cluster: cluster-b
       user: cluster-b
       namespace: default
     name: cluster-b
   current-context: cluster-b
   kind: Config
   preferences: {}
   users:
   - name: cluster-b
     user:
       token: "<token-generated by running the AWS command>"
   ```
This should allow KubeVela to authenticate correctly using the ServiceAccount token. Let us know if you encounter any issues!
