### ISSUE TITLE
Kubernetes Namespace Deletion Issue - Stale GroupVersion Discovery: cluster.core.oam.dev/v1alpha1

### ISSUE THREAD

**Issue by akorade** [kubevela/kubevela#6688]
**Describe the bug**
While attempting to delete a namespace, the following error is encountered:
```yaml
- type: NamespaceDeletionDiscoveryFailure
  status: 'True'
  lastTransitionTime: '2025-02-10T14:40:13Z'
  reason: DiscoveryFailed
  message: >-
    Discovery failed for some groups, 1 failing: unable to retrieve the
    complete list of server APIs: cluster.core.oam.dev/v1alpha1: stale
    GroupVersion discovery: cluster.core.oam.dev/v1alpha1
- type: NamespaceDeletionContentFailure
  status: 'False'
  lastTransitionTime: '2025-02-10T14:40:14Z'
  reason: ContentDeleted
  message: All content successfully deleted, may be waiting on finalization
```

**To Reproduce**
1. Install ArgoCD on the cluster with the ArgoCD Vela plugin 
plugin.yaml
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: vela-plugin-cm
  namespace: argocd
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: oam
    spec:
      version: v1.0
      init:
        command: ["vela", "version"]
      generate:
        command: ["bash"]
        args:
          - -c
          - |
            kustomize build . --load-restrictor LoadRestrictionsNone > app.yaml
            vela dry-run -f app.yaml -n $ARGOCD_APP_NAMESPACE
```

ArgoCD RepoServer Patch
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      initContainers:
        - name: kubevela
          image: nginx:1.21.6
          command:
            - bash
            - "-c"
            - |
              #!/usr/bin/env bash
              set -eo pipefail
              curl -fsSl https://kubevela.io/script/install.sh | bash -s 1.9.7
              cd /usr/local/bin
              curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash

              apt-get update
              apt-get install -y wget

              VERSION=v4.33.3
              BINARY=yq_linux_386
              wget https://github.com/mikefarah/yq/releases/download/${VERSION}/${BINARY} -O /usr/local/bin/yq
              chmod +x /usr/local/bin/yq
          env:
            - name: VELA_INSTALL_DIR
              value: /custom-tools
          resources:
            requests:
              cpu: 250m
              memory: 500Mi
            limits:
              cpu: 500m
              memory: 1024Mi
          volumeMounts:
            - name: custom-tools
              mountPath: /custom-tools
            - name: custom-cli
              mountPath: /usr/local/bin
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      containers:
        - name: vela
          image: nginx
          securityContext:
            runAsNonRoot: true
            runAsUser: 999
            runAsGroup: 999
          command:
            - /var/run/argocd/argocd-cmp-server
          env:
            - name: KUBECONFIG
              value: /kubeconfig
          resources: {}
          volumeMounts:
            - name: var-files
              mountPath: /var/run/argocd
            - name: plugins
              mountPath: /home/argocd/cmp-server/plugins
            - name: vela-plugin-cm
              mountPath: /home/argocd/cmp-server/config/plugin.yaml
              subPath: plugin.yaml
            - name: custom-tools
              mountPath: /usr/local/bin/vela
              subPath: vela
            - name: custom-cli
              mountPath: /usr/local/bin
            - name: vela-cli-dir
              mountPath: /.vela
            - name: kubeconfig-volumn
              mountPath: /kubeconfig
              subPath: kubeconfig
              readOnly: true
      volumes:
        - emptyDir: {}
          name: custom-tools
        - emptyDir: {}
          name: custom-cli
        - emptyDir: {}
          name: var-files
        - emptyDir: {}
          name: vela-cli-dir
        - emptyDir: {}
          name: plugins
        - configMap:
            name: vela-plugin-cm
          name: vela-plugin-cm
        - secret:
            secretName: kubeconfig
          name: kubeconfig-volumn
```
2. Install Vela-Core as an ArgoCD App on the cluster along with the definitions
3. Install a OAM based sample app on ArgoCD with the registered ArgoCD OAM plugin to parse the manifest files. 
    Note: I am using custom OAM definitions for namespace (component) and deployment (component) to define an app.  
4. Update the OAM App by changing the namespace. 
5. Wait for ArgoCD to reconcile the new changes.

The namespace is stuck in Terminating state as described in Issue Summary.

**Expected behavior**
Namespace should be deleted successfully. 

**Screenshots**

**KubeVela Version**

1. Vela CLI version: 1.9.7
2. Vela Core Chart Version: 0.1.0
    Image Versions: 
   -  cluster-gateway: v1.9.0
   - kube-webhook-certgen: v2.4.2
   - vela-core: v1.9.11

**Cluster information**
Kubernetes Version : 1.30.7

**Additional context**
1. Manually setting the namespace finalizer to null
```bash
kubectl get namespace "[NAMESPACE_NAME]" -o json \
  | tr -d "\n" | sed "s/\"finalizers\": \[[^]]\+\]/\"finalizers\": []/" \
  | kubectl replace --raw /api/v1/namespaces/[NAMESPACE_NAME]/finalize -f -
```
2. Another work around we tried was to delete the v1alpha1 (Workflow and Policy) OAM CRDs and the namespace gets deleted successfully.
