### ISSUE TITLE
Bug Report: In-Use Definition Revision Deleted Upon Exceeding Revision Limit

### ISSUE THREAD

**Issue by vishal210893** [kubevela/kubevela#6689]
## Describe the Bug
We have identified an issue in KubeVela where an in-use definition revision is deleted when the revision limit is reached. The revision limit is configured via the container argument `--definition-revision-limit=2`. This behavior leads to the removal of a revision that is actively used by an application, causing unexpected errors.

## Steps to Reproduce

1. **Create Multiple Revisions** <a id="create-multiple-revisions"></a><br>
    1. Apply the following `ComponentDefinition` manifest.<br>
    2. Modify the `data.test` value to a different value and apply the manifest **three times** to generate three distinct revisions.

    ```yaml
    apiVersion: core.oam.dev/v1beta1
    kind: ComponentDefinition
    metadata:
      name: configmap-component
    spec:
      workload:
        definition:
          apiVersion: v1
          kind: ConfigMap
      schematic:
        cue:
          template: |
            parameter: {
              firstkey: string
              secondkey: string
            }
            output: {
              apiVersion: "v1"
              kind:       "ConfigMap"
              metadata: {
                name: context.name
              }
              data: {
                firstkey: parameter.firstkey
                secondkey: parameter.secondkey
                test: "6"
              }
            }
    ```

2. **Verify Revisions** <a id="verify-revisions"></a><br>
    1. Run the following command to list the definition revisions:
       ```bash
       kubectl get DefinitionRevision
       ```  
    2. **Expected output**:
       ```
       NAME                     REVISION   HASH               TYPE
       configmap-component-v1   1          d3f08a1e86217a2a   Component
       configmap-component-v2   2          a773a862c7501cbd   Component
       configmap-component-v3   3          c2cd55aec8c4516e   Component
       ```

3. **Deploy an Application Using an Older Revision** <a id="deploy-an-application-using-an-older-revision"></a><br>
    1. Apply the following `Application` manifest, which explicitly uses revision 1 of the definition:
       ```yaml
       apiVersion: core.oam.dev/v1beta1
       kind: Application
       metadata:
         name: configmap-workflow-app
       spec:
         components:
           - name: defrevlimitcheck
             type: configmap-component@v1
             properties:
               firstkey: "first1"
               secondkey: "second"
       ```

4. **Trigger Revision Pruning** <a id="trigger-revision-pruning"></a><br>
    1. Reapply the `ComponentDefinition` from [step 1](#create-multiple-revisions). Since the revision limit has been reached, the system will delete revision 1 and create a new revision (revision 4).
    2. Run the command again to check revisions:
       ```bash
       kubectl get DefinitionRevision
       ```
    3. **Expected updated output**:
       ```
       NAME                     REVISION   HASH               TYPE
       configmap-component-v2   2          d3f08a1e86617a2a   Component
       configmap-component-v3   3          a773a862c5601cbd   Component
       configmap-component-v4   4          c2cd55ae6jc4516e   Component
       ```
    4. Revision 1 has been deleted, which is in use by the application created in [step 3](#deploy-an-application-using-an-older-revision).

5. **Observe the Error** <a id="observe-the-error"></a><br>
    1. Creating or updating any other application that references the deleted revision will show the following error:

       ```plaintext
       Error from server: error when applying patch:
       {"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"core.oam.dev/v1beta1\",\"kind\":\"Application\",\"metadata\":{\"annotations\":{},\"name\":\"configmap-workflow-app\",\"namespace\":\"default\"},\"spec\":{\"components\":[{\"name\":\"defrevlimitcheck\",\"properties\":{\"firstkey\":\"first1\",\"secondkey\":\"second\"},\"type\":\"configmap-component@v1\"}]}}\n"}},"spec":{"components":[{"name":"defrevlimitcheck","properties":{"firstkey":"first1","secondkey":"second"},"type":"configmap-component@v1"}]}}
       to:
       Resource: "core.oam.dev/v1beta1, Resource=applications", GroupVersionKind: "core.oam.dev/v1beta1, Kind=Application"
       Name: "configmap-workflow-app", Namespace: "default"
       for: "application.yaml": error when patching "application.yaml": admission webhook "validating.core.oam.dev.v1beta1.applications" denied the request: field "spec": Invalid value error encountered, failed to parseComponents: fetch component/policy type of defrevlimitcheck: load template from component definition [configmap-component@v1] : WorkloadDefinition.core.oam.dev "configmap-component@v1" not found.
       ```

## Expected Behavior
An in-use definition revision (for example, revision 1) should be protected from deletion even when the revision limit is exceeded. The system should ensure that active revisions remain available to prevent disruptions in the applications that depend on them.

## KubeVela Version
- **KubeVela Versions Tested:** v1.9.13 and v1.10.0

## Cluster information
Tested on a K3d Kubernetes cluster
- **Client Version:** v1.31.2
- **Kustomize Version:** v5.4.2
- **Server Version:** v1.30.4+k3s1
