### ISSUE TITLE
When specifying orphan propagation for garbage collect policy for a component it still deletes the workload associated with the component.

### ISSUE THREAD

**Issue by shivin** [kubevela/kubevela#6703]
**Describe the bug**

When specifying orphan propagation for garbage collect policy for a component it still deletes the workload associated with the component.

**To Reproduce**

1. Apply below Application:

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: my-operator
spec:
  components:
    - name: crds
      type: k8s-objects
      properties:
        objects:
          - apiVersion: v1
            kind: ConfigMap
            metadata:
              name: my-map
            data:
             a: b
  policies:
    - name: pas de pitie pour les croissants
      type: garbage-collect
      properties:
        rules:
          - selector:
              componentNames:
                - crds
            propagation: orphan

```
2. Delete the application. Observed that Application and the configmap created by the component gets deleted.

**Expected behavior**
The expectation is that ConfigMap created by the component should not be deleted because garbage-collect policy applied on the component has propagation set to orphan.

**Screenshots**

**KubeVela Version**

CLI Version: 1.10.1
Core Version: 1.10.1

**Cluster information**

Client Version: v1.31.2
Kustomize Version: v5.4.2
Server Version: v1.30.4+k3s1

**Additional context**
