### ISSUE TITLE
KubeVela task component should support a one-time run to completion functionality

### ISSUE THREAD

**Issue by shivin** [kubevela/kubevela#6732]
**Describe the bug**

In KubeVela, we have a task component that creates a Kubernetes Job internally. However, when we modify properties of the task, the KubeVela controller attempts to update the existing job, which fails since updating a Job is not allowed in Kubernetes. The purpose of the Task component is to trigger a one-time run to completion. Therefore, whenever an application containing this component is deployed, we always want a new job to be triggered, even if no changes have been made to the spec.
**To Reproduce**

1. Apply the below application containing task component
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: app-worker
spec:
  components:
    - name: mytask
      type: task
      properties:
        image: ubuntu:22.04
        count: 3
        cmd: [ "sleep", "30" ]
```

2. Modify the above Application by changing count from 3 to 2 in properties. This does not create a new Job and KubeVela controller throws below errors in the log:
`E0320 05:31:44.026520       1 task.go:252] "do steps" err="run step(provider=oam,do=component-apply): Dispatch: pre-dispatch dryrun failed: Found 1 errors. [(cannot patch object: Job.batch \"mytask\" is invalid: spec.completions: Invalid value: 2: field is immutable)]" application="default/app-worker" controller="application" resource_version="184063" generation=2 publish_version="" step_name="mytask" step_type="builtin-apply-component" spanID="i-p4uqyb4z.execute application workflow.ixwymmovkh"`
**Expected behavior**

We expect new Job to be created and no errors in KubeVela controller.
**Screenshots**

**KubeVela Version**

CLI Version: 1.10.1
Core Version: 1.10.2
GitRevision: git-711c9f00
GolangVersion: go1.22.11

**Cluster information**
Client Version: v1.31.2
Kustomize Version: v5.4.2
Server Version: v1.30.4+k3s1

**Additional context**
