### ISSUE TITLE
Regression in workflow outputs with decode function from v1.9.11 to v1.10.x

### ISSUE THREAD

**Issue by oanasc** [kubevela/kubevela#6734]
During upgrade testing from v1.9.11 to v1.10.0 and 1.10.2, I see a regression where workflows that use a read-object step to decode a secret value no longer work. Specifically, when using the base64.Decode function, the output returns null. This functionality worked correctly in v1.9.11.

Use the following step configuration:
```
     -  name: stepname
        type: read-object
        outputs:
          - name: mypassword
            valueFrom: |-
              import "encoding/base64"
              base64.Decode(null, output.value.data["password"])
        properties:
          apiVersion: v1
          kind: Secret
          name: mysecret
          namespace: namespacename
```
Additional Information:

* Using a hardcoded value with the base64.Decode function works correctly, indicating the issue is not with the decode function or syntax.
* Directly accessing the secret value without decoding works fine, as shown below:

```
valueFrom: output.value.data["password"]
```
