### ISSUE TITLE
podsecuritycontext Trait Definition: localhostProfile Attribute Should Be Optional in seccompProfile and appArmorProfile for Type RuntimeDefault

### ISSUE THREAD

**Issue by glaxman** [kubevela/kubevela#6772]
**Describe the bug**
The localhostProfile attribute is currently required or improperly validated when the type field is set to RuntimeDefault in both seccompProfile and appArmorProfile. According to expected behavior, localhostProfile should be optional and ignored when type is RuntimeDefault, as the runtime’s default profile does not require a custom local profile.

**To Reproduce**

1. Apply the following application yaml:

```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: podtato-head
  namespace: default
spec:
  components:
    - name: podtato-head-frontend
      type: webservice
      properties:
        image: ghcr.io/podtato-head/podtato-server:v0.3.1
        ports:
          - port: 8080
            expose: true
        cpu: "0.1"
        memory: "32Mi"
      traits:
        - type: podsecuritycontext
          properties:
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
```

**Error:**

 Message:             function call error for : GenerateComponentManifest: evaluate base template component=podtatohead-frontend app=podtato-head: failed to have the workload/trait unstructured: spec.template.spec.securityContext.seccompProfile.localhostProfile: incomplete value string (value: cue/format: unsupported node type <nil>)

**Expected behavior**
When type: RuntimeDefault is specified:

The localhostProfile field should be optional.

If provided, it should be ignored or validated as unused.

No error or validation failure should occur due to presence or absence of localhostProfile.

**KubeVela Version** :  v1.10.2

CLI Version: 1.9.13
Core Version: 1.10.2
GitRevision: git-d56da069
GolangVersion: go1.19.13
**Cluster information**
