### ISSUE TITLE
Component / Trait Validation Webhooks still use legacy cue compiler

### ISSUE THREAD

**Issue by briankane** [kubevela/kubevela#6786]
**Describe the bug**
The ValidateCueTemplate function currently compiles CUE using cuecontext.New().CompileString(...), which bypasses the CueX DefaultCompiler. This results in inconsistent validation behavior between Components/Traits and other template-based resources like Policies.

**To Reproduce**
Apply a Package:
```
apiVersion: cue.oam.dev/v1alpha1
kind: Package
metadata:
  name: atmos-common-types
  namespace: vela-system
spec:
  path: "bug/example"
  templates:
    example.cue: |
      package example

      #ToUpper: {
        input: string
        output: string
        output: strings.ToUpper(input)
      }
```

Create a component that utilises it: 
```
import "bug/example"

"bug-example": {
    attributes: workload: definition: {
        apiVersion: "v1"
        kind:       "ConfigMap"
    }
    type: "component"
}

template: {
    test: example.#ToUpper & {
      input: "hello, world"
    }

    output: {
        apiVersion: "v1"
        kind:       "ConfigMap"
        data: {
            result: test.output
        }
    }
}
```

Try to apply:
```
vela def apply path/to/example.cue
```

The webhook will fail with error:
```
Error: failed to create new definition in kubernetes: admission webhook "validating.core.oam-dev.v1beta1.componentdefinitions" denied the request: builtin package "example/bug" undefined
```

**Expected behavior**
The validation webhooks should match the behaviour in the component and trait templating and use the CueX compiler.

**KubeVela Version**
CLI Version: 1.10.3
Core Version: 1.10.3

**Cluster information**
N/A

**Additional context**
This validation behavior was introduced as part of earlier changes I contributed, during which I wasn’t running with the full webhook setup in my environment. At the time, the issue wasn’t apparent because the missing validation pipeline masked the gap.

I can pick this up to fix it but filing it in the meantime.
