### ISSUE TITLE
[Bug] - If a kubevela application is created with a reference to definition with specifying the version, kubevela uses the last applied version of the definition(instead of the latest semver of the definition)

### ISSUE THREAD

**Issue by rohank2002** [kubevela/kubevela#6795]
**Describe the bug**
The Kubevela [documentation](https://kubevela.io/docs/next/end-user/definition-version-control/) suggests that if the definition version is not specified, kubevela uses the latest semver available for definition. This is not the current behavior, kubevela uses last applied version instead. 

**To Reproduce**
Please follow the steps in the below order to reproduce the issue:
Create a component definition with version 2.5.0

```
apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  name: configmap-component
  namespace: vela-system
spec:
  version: 2.5.0 # Specify the component version using Semantic Versioning
  schematic:
    cue:
      template: |
        output: {
            apiVersion: "v1"
            kind:       "ConfigMap"
            metadata: {
                name:      "comptest250"
            }
            data: {
            version: "2.5.0"
            }
        }

  workload:
    definition:
      apiVersion: v1
      kind: ConfigMap
```

Create a component definition with version 1.2.6
```
apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  name: configmap-component
  namespace: vela-system
spec:
  version: 1.2.6 # Specify the component version using Semantic Versioning
  schematic:
    cue:
      template: |
        output: {
            apiVersion: "v1"
            kind:       "ConfigMap"
            metadata: {
                name:      "comptest1"
            }
            data: {
            version: "1.2.6"
            }
        }

  workload:
    definition:
      apiVersion: v1
      kind: ConfigMap
```

Create an application without the reference to any version:
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: test-app
  namespace: default
  annotations:
    app.oam.dev/autoUpdate: "true" # Enable automatic upgrades
spec:
  components:
    - name: test-configmap
      type: configmap-component # Should use v2.5.0 as that is the latest available version
```
Kubevela assigns the component definition version as 1.2.6 and the configmap comptest1 is created.

**Expected behavior**
Kubevela should use the latest available version of the definition, i.e. v2.5.0

**KubeVela Version**

v1.10.2

**Cluster information**
k3d cluster
Kubernetes version: v1.31.5+k3s1
