### ISSUE TITLE
Request WorkflowStep Not Working

### ISSUE THREAD

**Issue by briankane** [kubevela/kubevela#6800]
**Describe the bug**
The `request` WorkflowStep doesn't appear to be working correctly and give back error

```
 function call error for req: cue: marshal error: req.$returns.response.body: cannot convert incomplete value "string" to JSON
```

**To Reproduce**
Create this simple app:
```
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: test-request
  namespace: default
spec:
  components: []
  workflow:
    steps:
      - type: request
        name: make-request
        properties:
          url: https://jsonplaceholder.typicode.com/todos/1
        outputs:
          - name: response
            valueFrom: |
              import "encoding/json"
              json.Marshal(response)
      - type: apply-object
        name: output-map
        properties:
          value:
            apiVersion: v1
            kind: ConfigMap
            metadata:
                name: request-output
        inputs:
          - from: response
            parameterKey: data["aField"]
```

Get the status of the app:
`vela status test-request -n default`

The following will be returned with the error present:
```
About:

  Name:         test-request                 
  Namespace:    bkane                        
  Created at:   2025-06-07 14:23:35 +0100 IST
  Status:       runningWorkflow              

Workflow:

  mode: StepByStep-DAG
  finished: false
  Suspend: false
  Terminated: false
  Steps
  - id: xskq52r16h
    name: make-request
    type: request
    phase: failed 
    message: function call error for req: cue: marshal error: req.$returns.response.body: cannot convert incomplete value "string" to JSON (value: #do:       "do"
#provider: "http"
$params: {
        method: "GET"
        url:    "https://jsonplaceholder.typicode.com/todos/1"
        request: {
                timeout?: string
                body?:    string
                header?: {}
                trailer?: {}
                ratelimiter?: {
                        limit:  int
                        period: string
                }
        }
        tls_config?: {
                secret:     string
                namespace?: string
        }
}
$returns: response: {
        body: string
        header?: {}
        trailer?: {}
        statusCode: int
})
```

**Expected behavior**
The HTTP request should be made to the dummy endpoint. 
The response from the request should be written to the `request-output` ConfigMap. 

**Screenshots**
N/A

**KubeVela Version**
CLI Version: 1.10.3
Core Version: 1.10.3

**Cluster information**
Client Version: v1.31.2
Kustomize Version: v5.4.2
Server Version: v1.31.2+k3s1

**Additional context**
I noticed the definitions are different between Kubevela and Workflow (standalone):
- https://github.com/kubevela/workflow/blob/main/charts/vela-workflow/templates/definitions/request.yaml
- https://github.com/kubevela/kubevela/blob/master/vela-templates/definitions/internal/workflowstep/request.cue

The Kubevela version is referencing `http` but the request variable is actually `req`
