### ISSUE TITLE
Addon-Operation Default Image - Pods Fail

### ISSUE THREAD

**Issue by briankane** [kubevela/kubevela#6801]
**Describe the bug**
When using the addon-operation with the default image ([oamdev/vela-cli:v1.7.2](https://github.com/kubevela/catalog/blob/master/addons/vela-workflow/definitions/addon-operation.cue#L97C12-L97C34)) the pods always fail. 

Updating it to match the version (10.3 in this case) fixes the issues. 

**To Reproduce**
Deploy this WorkflowRun:
```
apiVersion: core.oam.dev/v1alpha1
kind: WorkflowRun
metadata:
  name: test-addon-operation
  namespace: default
spec:
  context:
    readConfig: true
    mode:
  workflowSpec:
    steps:
      - name: Enable Prism
        type: addon-operation
        properties:
          addonName: vela-prism
```

The workflow run will go into a failure state:
```
kubectl get workflowruns.core.oam.dev test-addon-operation
```

View failing pods:
```
kubectl get pods -n vela-system -l workflow.oam.dev/name=test-addon-operation
```

If you change the application to include an up to date image, the addon installs successfully:
```
apiVersion: core.oam.dev/v1alpha1
kind: WorkflowRun
metadata:
  name: test-addon-operation
  namespace: default
spec:
  context:
    readConfig: true
    mode:
  workflowSpec:
    steps:
      - name: Enable Prism
        type: addon-operation
        properties:
          addonName: vela-prism
          image: "oamdev/vela-cli:v1.10.3"
```

*NOTE*: While the addon installs ok, there is a separate issue with the status reporting in the WorkflowRun. Will open an independent bug for that. 

**Expected behavior**
The addon should install successfully and the `addon-{addonName}` app should be created and succeed. 

**Screenshots**
N/A

**KubeVela Version**
CLI Version: 1.10.3
Core Version: 1.10.3

**Cluster information**
Client Version: v1.31.2

**Additional context**
