### ISSUE TITLE
Unable to pass dynamic values to trait parameters

### ISSUE THREAD

**Issue by meyuviofficial** [kubevela/kubevela#6810]
**Unable to pass any dynamic values to the trait parameter**
I'm trying to create a PV using trait and pass dynamic values to the volume handle which will be known only at the runtime (after the parent component - EFS is deployed). The trait is able to deploy the PV using static values but it is not recognising any dynamic values. 

**To Reproduce**
Create a trait with the below yaml file and try to attach it to a component. While deploying the application, try to pass any values that will be known at the runtime. In my case, the parent component will give me the `filesystemId` in it's status. 

```
"pv-using-trait": {
	alias: "pv-using-trait-v2"
	annotations: {}
	attributes: {
		appliesToWorkloads: []
		conflictsWith: []
		podDisruptive:   false
		workloadRefPath: ""
	}
	description: "deploy pv using trait"
	labels: {}
	type: "trait"
}

template: {
	outputs: persistentVolume: {
		apiVersion: "v1"
		kind:       "PersistentVolume"
		metadata: {
			name: parameter.volumeName
		}
		spec: {
			capacity: {
				storage: "10Gi"
			}
			storageClassName: "efs-csi-infra-sc"
			volumeMode:       "Filesystem"
			accessModes:      ["ReadWriteMany"]
			persistentVolumeReclaimPolicy: "Retain"
			csi: {
				driver:        "efs.csi.aws.com"
				volumeHandle:  "\(parameter.filesystemId)::\(parameter.accessPointId)"
				}
			}
		}
	parameter: {
		volumeName: string | *"atmos-efs-volume"
		filesystemId: string & {
		    if parameter.filesystemId == "" || parameter.filesystemId == null || parameter.filesystemId == _|_ {
		        errorMessage: "filesystemId must be specified"
		    }
		}
		accessPointId: string & {
		    if parameter.accessPointId == "" || parameter.accessPointId == null || parameter.accessPointId == _|_ {
		        errorMessage: "accessPointId must be specified"
		    }
		}
	}
}
```

```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: efs-kubevela-poc
  namespace: ajanta
spec:
  components:
    - name: provision-efs
      type: atmos-efs-v1
      properties:
        name: poc-minimal
        path: /data/poc-minimal
    - name: provision-webservice
      type: webservice
      properties:
        image: busybox:latest
        command:
          ["sh", "-c", "while true; do echo 'Hello from EFS'; sleep 5; done"]
        port: 80
      traits:
        - type: atmos-vol-v2
          properties:
            volumeName: tenant-ajanta-poc-minimal
            accessPointId: (provision-efs.outputs.ap-id)
            filesystemId: (provision-efs.outputs.fs-id)
  workflow:
    steps:
      - name: provision-efs
        type: apply-component
        properties:
          component: provision-efs
        outputs:
          - name: fs-id
            valueFrom: output.status.filesystemId
          - name: ap-id
            valueFrom: output.status.accessPointId
      - name: provision-webservice
        type: apply-component
        properties:
          component: provision-webservice
        dependsOn:
          - provision-efs
```
> I tried to attach in a single component but the kubevela is not waiting for the first component to deploy and fetch it's status. So, I tried this two component approach and still it fails

**Expected behavior**

Kubevela trait should be able to read the status from it's parent component and use the same dynamic value in it's template.  

**Screenshots**

![Image](https://github.com/user-attachments/assets/2c82cb5a-2daa-4df4-a287-a1eacc523a99)

**KubeVela Version**

```
CLI Version: 1.10.3
Core Version: 1.10.2
GitRevision: ef9b6f3cc10a4b6871b5698ca41fea3f6b3bcaec
GolangVersion: go1.24.3
```

**Cluster information**

```
Client Version: v1.31.5
Kustomize Version: v5.4.2
Server Version: v1.31.5+k3s1
```

**Additional context**
I even tried to access it directly inside the cue template but that method also didn't work. Because, these data won't populated at the compile-time and kubevela is not waiting for that. 

```
"atmos-vol-v2": {
	alias: "atmos-efs-volume-v2"
	annotations: {}
	attributes: {
		appliesToWorkloads: []
		conflictsWith: []
		podDisruptive:   false
		workloadRefPath: ""
	}
	description: "deploy pv using trait"
	labels: {}
	type: "trait"
}

template: {
		outputs: persistentVolume: {
		apiVersion: "v1"
		kind:       "PersistentVolume"
		metadata: {
			name: parameter.volumeName
		}
		spec: {
			capacity: {
				storage: "10Gi"
			}
			storageClassName: "efs-csi-infra-sc"
			volumeMode:       "Filesystem"
			accessModes:      ["ReadWriteMany"]
			persistentVolumeReclaimPolicy: "Retain"
			csi: {
				driver:        "efs.csi.aws.com"
				volumeHandle:   context.output.status.filesystemId + "::" + context.output.status.accessPointId
				}
			}
		}

	parameter: {
        // +usage=Name of the volume to be created
		volumeName: string | *"atmos-efs-volume-v2"
	}
}
```

**Comment by meyuviofficial** [comment]
A more simpler example to reproduce the issue. 

# Steps to reproduce

1. Apply the below component definition
```yaml
apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  name: my-pod-component
  namespace: ajanta
spec:
  workload:
    definition:
      apiVersion: v1
      kind: Pod
  schematic:
    cue:
      template: |
        outputs: {
          pod: {
            apiVersion: "v1"
            kind: "Pod"
            metadata: {
              name: parameter.pod.name
              
            }
            spec: {
              containers: [{
                name: "my-container"
                image: "nginx:latest"
              }]
            }
          }
        }
        output: outputs.pod
        parameter: {
          pod: {
            port: int
            image: string
          }
        }
  
```

2. Apply the below trait definition
```yaml
apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  name: echo-pod-info
  namespace: ajanta
spec:
  schematic:
    cue:
      template: |-
        outputs:{

        podWithAnnotation:   {
            apiVersion: "v1"
            kind: "Pod"
            metadata: {
              name: "new"
              annotations: {
                "componentPodStatus": context.outputs.pod.status.phase
              }
            }
            spec: {
              containers: [{
                name: "my-container"
                image: context.outputs.pod.spec.containers[0].image
              }]
            }
            }
            }
```
3. Finally, try to deploy the application manifest 

```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: my-pod-app
  namespace: ajanta
spec:
  components:
  - name: my-pod
    type: my-pod-component
    properties:
      pod:
        name: "my-test-pod"
        port: 80
        image: busybox
    traits:
    - type: echo-pod-info
```

## Current behaviour
It will throw the below error 

![Image](https://github.com/user-attachments/assets/31571402-9f43-4cb7-96f7-a5f6b5bb0bd0)

## Expected behaviour
The trait should wait for the parent component to finish deploy and should be able to read the data that will be available only during the runtime (after applying).

**Comment by briankane** [comment]
At the render time of the trait definition, the component will not have been applied so it is unable to access post apply parameters like `context.outputs.pod.status.phase` 

In the first example, is the usage of workflow outputs in a component valid? I'm not familiar with that usage:
```
traits:
        - type: atmos-vol-v2
          properties:
            volumeName: tenant-ajanta-poc-minimal
            accessPointId: (provision-efs.outputs.ap-id)
            filesystemId: (provision-efs.outputs.fs-id)
```

See https://kubevela.io/docs/end-user/workflow/inputs-outputs/ 

Based on that, I think you need to output the fields from _"Component A"_, then use inputs to provide them to the properties of _"Component B"_. The trait, attached to "B" would then be able to access them from `context.components[context.name]`, I think.
